import type { CaseDef } from '../../types/game-types';
import { BELL_CLUES } from './bell-clues';

// The Ninth Bell. Cathedral Hill: thirty locations from the tower down to the
// water, twenty people who will talk if the diocese does not hear about it,
// and twenty-six documents, most of them written by people who were lying.
//
// The suspects lie. The witnesses do not: every witness line below is written
// from this night and nothing else.
//
// The true night, minute by minute (Friday April 9th, 1948):
//  10:30 PM  Peter Nane leaves the Glasshouse boilers. He tells Lister he has a
//            hole to fill.
//  10:45 PM  Tom Harris lets himself out of the Academy with the porter's gate
//            key and the verger's tower key, meaning to return the tower key.
//  10:50 PM  Nane signs valve key three out at the Water Board in the Canon's
//            name, as he does every month for the Glasshouse water. Miss Coyle
//            knows his hand.
//  11:00 PM  Nane meets Harris on the reservoir path, takes the tower key out of
//            his pocket and tells him to forget it. Harris sees his hands in the
//            lamp and nothing else.
//  11:30 PM  Constance comes to the verger's cottage for the key, as every night.
//            It is not on its hook. She goes up anyway. The tower door is already
//            unlocked, and Nane is on the ringing floor above her.
//  11:40 PM  Quaile opens the Marrow House gate for Beatrix Ayre on the Matron's
//            word. She has a bag.
//  11:45 PM  Rosalind Fay takes car seven out of the depot, unsigned, lights off,
//            and picks Beatrix up at the Marrow House gate for five pounds.
//  11:55 PM  Constance reaches the ringing floor. Nane strikes her from behind.
//            She falls down the stairs with her keys in her hand.
//  11:58 PM  Shale stops the pump house engines to listen, as he does every night.
//  12:00 AM  Nane cuts the rope and rings nine with the cut end, badly. Beatrix
//            stands on the Close Green and counts. Quint, Blake and two boys hear
//            it in the Observatory, and Quint turns the telescope on the tower.
//  12:04 AM  Nane comes down the iron rungs on the outside of the tower, cutting
//            both palms on the rust, and goes toward the reservoir, not the Close.
//            Quint draws him. Beatrix sees him and runs the other way.
//  12:05 AM  The Canon, who has heard nine and knows what Constance was about to
//            find, goes out by the garden door toward the cemetery.
//  12:20 AM  Nane digs up the Canon's tin box in plot forty-four, takes the four
//            hundred pounds, leaves the box, and goes down toward the Water Board.
//  12:25 AM  The Canon reaches plot forty-four, finds the box open and empty,
//            tears his cassock on the railings, and goes home with the box.
//  12:30 AM  It begins to rain. Fay, who left Beatrix on the Green, has run the
//            car down to the reservoir stop and sits on the wall. The Matron goes
//            out to look for Beatrix.
//  12:40 AM  Beatrix takes skiff two from the wall stage and rows for the far
//            side, badly. She loses the oars, then her rosary, and rows with her
//            hands.
//  12:45 AM  The Canon is back at the Rectory, mud to the knee. He puts the
//            cassock in the laundry basket himself and writes to the Dean.
//   1:00 AM  Nane crosses the reservoir wall on the valve walkway with the bag.
//            He drops the tower key on the stones; it rings. Fay sees him. Shale
//            sees him. Quaile closes the Marrow House gate. The Canon's letter
//            reaches the Dean by hand. The Matron comes into the Glasshouse to get
//            warm, with reservoir mud on her shoes.
//   1:10 AM  Nane comes off the walkway at the boathouse. Ferris sees him go
//            along the bank toward the Lamplighter's.
//   1:20 AM  Fay brings car seven back to the depot, wet to the knees.
//   1:30 AM  Nane drinks two rums at the Lamplighter's, wet boots, cut hands, no
//            money, and says he rang it. Beatrix lands skiff two at the boathouse
//            stage and walks up toward the Terraces.
//   2:15 AM  Nane bangs Amsel up, buys the 1939 diocesan report, and tears the
//            plates of the rungs out in the doorway.
//   3:00 AM  Nane returns valve key three to the Water Board and initials it P.N.
//   3:30 AM  Nane comes back to the Glasshouse and sits on the coal with his hands
//            in a rag.
//   4:00 AM  The Matron finds Beatrix on the tea room step, wet to the waist. They
//            argue inside. A glove is left on a chair.
//   4:30 AM  Quaile lets the Matron and Beatrix back in through the gate.
//   5:15 AM  Nane sells his watch to Hobb, outright, for money he can spend.
//   5:30 AM  He buys lint and iodine from Miss Lamb.
//   6:00 AM  The verger finds Constance at the foot of the stairs, and washes them.

const def: CaseDef = {
  id: 'bell',
  title: 'The Ninth Bell',
  subtitle: 'Cathedral Hill · April 1948',
  tagline: 'The bell rang nine times at midnight. By morning the bell-ringer was dead at the foot of her tower.',
  victim: 'Sister Constance Ayre',
  scene: 'tower',
  startHour: 7,
  difficultyHint: 'Everyone on this hill is lying about something.',
  publicTraits: ['build', 'hair'],
  traitPool: ['hand', 'mark', 'vice', 'scent', 'shoe'],

  briefing: `Sister Constance Ayre rang the cathedral bell at midnight for twenty years. Last night it rang nine times instead of twelve, badly. At six in the morning the verger found her dead at the bottom of the tower stairs, hit from behind. The bell rope was cut. Whoever did it climbed down the outside of the tower. Her sister has been locked in Marrow House asylum for nine years. Nine strokes for nine years.`,

  call: {
    from: 'Constable Ned Pardoe', role: 'Hill Division',
    lines: [
      'Inspector. Everyone. I came up the hill at a run. The verger at St. Ordell’s found a nun dead at the bottom of the tower stairs an hour ago.',
      'Sister Constance Ayre. Forty-four. She rang the cathedral bell at midnight every night for twenty years. Twelve strokes, never one more.',
      'Last night the bell rang nine times, not twelve, and badly. Whoever rang it did not know how. By six this morning she was dead on the stairs with the back of her head broken and her keys still in her hand.',
      'She did not fall. Somebody hit her from behind. The bell rope was cut on the ringing floor, and the person who did it did not come down the stairs. There are old iron rungs on the outside of the tower.',
      'Her sister Beatrix has been a patient at Marrow House asylum for nine years, and the gate there was logged open at twenty to midnight. The Canon says the diocese would like discretion.',
      'Note what the Canon wants, and then ignore it. You have two days. Start at the tower, and talk to the verger. He washed the stairs before we got there.',
    ],
  },

  radio: [
    'Hill Division. The diocese has asked for discretion. Note it. Ignore it.',
    'Marrow House asylum logged its gate open at eleven-forty and closed again at one.',
    'The bell rope was cut clean. Whoever went up did not come down the stairs.',
  ],

  terrain: {
    sea: false, river: true, riverSource: 0.18, riverMouth: 0.5,
    lakeAt: 'reservoir', lakeName: 'THE RESERVOIR', parks: 3,
    districts: [
      { text: 'CATHEDRAL HILL', x: 300, y: 10, rot: -3 },
      { text: 'THE CLOSE', x: 560, y: 380, rot: 2 },
      { text: 'THE TERRACES', x: 960, y: 60, rot: 3 },
      { text: 'LOWER ORDELL', x: 230, y: 780, rot: -2 },
      { text: 'THE WATER', x: 900, y: 740, rot: 2 },
    ],
  },

  locations: [
    // ---- Cathedral Hill
    { id: 'tower', name: 'The Bell Tower', type: 'church', x: 470, y: 110, district: 'Cathedral Hill', desc: 'Two hundred and eleven steps, and a bell rope cut clean through.' },
    { id: 'rectory', name: 'The Rectory', type: 'manor', x: 226, y: 158, district: 'Cathedral Hill', desc: 'The Canon’s house. A housekeeper who sees everything and a study where the Canon does his accounts.' },
    { id: 'chapterhouse', name: 'The Chapter House', type: 'library', x: 330, y: 260, district: 'Cathedral Hill', desc: 'Four hundred years of parish records, and an archivist who has read all of them.' },
    { id: 'almshouse', name: 'The Almshouse', type: 'home', x: 170, y: 340, district: 'Cathedral Hill', desc: 'Forty beds, thirty-nine names, and a register nobody trusts.' },
    { id: 'deanery', name: 'Diocesan Office', type: 'office', x: 360, y: 50, district: 'Cathedral Hill', desc: 'The church’s offices. This is where the diocese writes letters asking the police to be discreet.' },
    { id: 'foundry', name: 'Ordell Bell Foundry', type: 'factory', x: 110, y: 70, district: 'Cathedral Hill', desc: 'Cast the bell in 1844. Knows every crack in it since.' },
    // ---- The Close
    { id: 'division', name: 'Hill Division', type: 'police', x: 480, y: 330, district: 'The Close', desc: 'Your police station on the hill. Three constables and a kettle.' },
    { id: 'cottage', name: 'Verger’s Cottage', type: 'home', x: 570, y: 200, district: 'The Close', desc: 'Every key on the hill hangs on a board in the kitchen. One hook is empty.' },
    { id: 'green', name: 'The Close Green', type: 'park', x: 640, y: 270, district: 'The Close', desc: 'Wet grass, a sundial, and a clear view of the tower door.' },
    { id: 'academy', name: 'Ordell Academy', type: 'school', x: 716, y: 140, district: 'The Close', desc: 'Boys in grey uniforms, out of bed, and nobody counting them.' },
    { id: 'sanatorium', name: 'The Academy Sanatorium', type: 'hospital', x: 800, y: 60, district: 'The Close', hidden: true,
      desc: 'A locked ward at the back of the school where sick boys are kept. One boy is in it who is not sick. Nobody outside the school knows the door exists.' },
    { id: 'cemetery', name: 'Ordell Cemetery', type: 'cemetery', x: 322, y: 490, district: 'The Close', desc: 'Fresh earth on plot forty-four. Nobody was buried there this month.' },
    { id: 'dispensary', name: 'Hill Dispensary', type: 'shop', x: 600, y: 430, district: 'The Close', desc: 'The only chemist on the hill, and the only poisons book.' },
    // ---- The Terraces
    { id: 'observ', name: 'The Observatory', type: 'light', x: 898, y: 252, district: 'The Terraces', desc: 'One telescope pointed at the sky. One window pointed at the hill.' },
    { id: 'glasshouse', name: 'The Glasshouse', type: 'market', x: 656, y: 340, district: 'The Terraces', desc: 'Orchids and orange trees under forty tons of glass.' },
    { id: 'asylum', name: 'Marrow House', type: 'hospital', x: 872, y: 450, district: 'The Terraces', desc: 'The gate was logged open at eleven-forty. That is all they will tell you.' },
    { id: 'inn', name: 'The Lamplighter’s Arms', type: 'bar', x: 780, y: 380, district: 'The Terraces', desc: 'The only pub on the hill, and the only place the hill says what it thinks.' },
    { id: 'villa', name: 'The Quint Villa', type: 'manor', x: 1010, y: 150, district: 'The Terraces', desc: 'The astronomer’s house. Every curtain open, every light off.' },
    { id: 'bookshop', name: 'Amsel’s Books', type: 'shop', x: 960, y: 340, district: 'The Terraces', desc: 'Second-hand books, damp, and the only shop that stocks the diocese’s reports.' },
    { id: 'tearooms', name: 'Terrace Tea Rooms', type: 'cafe', x: 1040, y: 430, district: 'The Terraces', desc: 'Where the hill takes its gossip with milk and two sugars.' },
    // ---- Lower Ordell
    { id: 'depot', name: 'The Tram Depot', type: 'tram', x: 164, y: 590, district: 'Lower Ordell', desc: 'The last tram up the hill leaves at eleven. Somebody took one out at a quarter to midnight without signing for it.' },
    { id: 'pawn', name: 'Hobb’s Pawn', type: 'shop', x: 220, y: 470, district: 'Lower Ordell', desc: 'A rosary, a telescope lens, and a watch that has been in and out of this window every year for ten years.' },
    { id: 'mission', name: 'Lower Chapel', type: 'church', x: 290, y: 630, district: 'Lower Ordell', desc: 'The poor parish. Their bell is a handbell, and it rang at midnight too.' },
    { id: 'laundry', name: 'Hill Laundry', type: 'factory', x: 100, y: 710, district: 'Lower Ordell', desc: 'Every sheet and church robe on the hill, washed by nuns who see the stains.' },
    { id: 'tallow', name: 'Tallow Street', type: 'home', x: 380, y: 730, district: 'Lower Ordell', desc: 'The street where the hill’s servants live. They see everything and are asked about nothing.' },
    { id: 'waterboard', name: 'Ordell Water Board', type: 'office', x: 520, y: 610, district: 'Lower Ordell', desc: 'Every gallon that leaves the reservoir is written down here. So is every key to the valves.' },
    // ---- The Water
    { id: 'reservoir', name: 'The Reservoir', type: 'bridge', x: 614, y: 560, district: 'The Water', desc: 'Black water behind a wall, and a walkway nobody is supposed to use.' },
    { id: 'boathouse', name: 'Reservoir Boathouse', type: 'pier', x: 760, y: 520, district: 'The Water', desc: 'Two rowing boats, one missing its oars, and a boatman who keeps count.' },
    { id: 'pumphouse', name: 'The Pump House', type: 'factory', x: 720, y: 670, district: 'The Water', desc: 'The engines run all night, loud enough to cover a bell. Almost.' },
    { id: 'crypt', name: 'The Crypt', type: 'bank', x: 888, y: 630, district: 'The Water', desc: 'Four hundred years of the church’s dead, and its account books.' },
    { id: 'watertower', name: 'Waterworks Tower', type: 'tower', x: 1000, y: 570, district: 'The Water', desc: 'The water tower. From the top you can see the bell tower and the reservoir.' },
  ],
  edges: [
    ['tower', 'rectory'], ['tower', 'deanery'], ['tower', 'cottage'], ['tower', 'chapterhouse'],
    ['rectory', 'almshouse'], ['rectory', 'foundry'], ['rectory', 'chapterhouse'],
    ['deanery', 'foundry'], ['deanery', 'academy'],
    ['chapterhouse', 'division'], ['chapterhouse', 'almshouse'],
    ['almshouse', 'pawn'], ['almshouse', 'depot'],
    ['cottage', 'green'], ['cottage', 'academy'],
    ['green', 'division'], ['green', 'glasshouse'],
    ['academy', 'villa'], ['academy', 'observ'],
    ['academy', 'sanatorium'], ['green', 'sanatorium'],
    ['observ', 'villa'], ['observ', 'glasshouse'], ['observ', 'bookshop'],
    ['villa', 'tearooms'],
    ['bookshop', 'tearooms'], ['bookshop', 'asylum'],
    ['tearooms', 'asylum'], ['tearooms', 'watertower'],
    ['glasshouse', 'inn'], ['glasshouse', 'division'],
    ['inn', 'asylum'], ['inn', 'boathouse'],
    ['division', 'cemetery'], ['division', 'dispensary'],
    ['dispensary', 'reservoir'], ['dispensary', 'inn'],
    ['cemetery', 'pawn'], ['cemetery', 'mission'], ['cemetery', 'waterboard'],
    ['pawn', 'depot'],
    ['depot', 'laundry'], ['depot', 'mission'],
    ['mission', 'tallow'],
    ['laundry', 'tallow'],
    ['tallow', 'waterboard'],
    ['waterboard', 'reservoir'],
    ['reservoir', 'boathouse'], ['reservoir', 'pumphouse'],
    ['boathouse', 'crypt'],
    ['pumphouse', 'crypt'],
    ['asylum', 'crypt'], ['asylum', 'watertower'],
    ['crypt', 'watertower'],
  ],
  start: 'division',

  suspects: [
    { id: 'harris', name: 'Tom Harris', role: 'Third-form boy, Ordell Academy', hidden: true, home: 'sanatorium',
      traits: { build: 'slight', hair: 'fair' },
      blurb: 'Fifteen. Had the tower key on Friday night. Hiding in the school sanatorium with a fever he does not have.',
      motive: 'because Sister Constance had found out about the girl from Marrow House and was going to tell the Canon.',
      bio: 'Fifteen. Third form at the Academy. Borrows the verger’s tower key to meet a girl from Marrow House on the ringing floor. He was on the reservoir path at eleven on Friday with the key in his pocket.',
      alibi: 'In the sanatorium since Saturday morning. He says he was in his bed by half past eleven on Friday. The porter says he came in at half past twelve without the key.',
      secret: 'Peter Nane stopped him on the reservoir path at eleven, took the tower key from him, and told him that if he said a word the girl would be sent somewhere worse than Marrow House. He has not said a word. He saw Nane’s hands in the lamp when he took the key.',
      opinions: { verger: 'Mr. Ill lends me the key. He thinks it is harmless. He is kind, and he is wrong.', canon: 'The Canon caned me in September for being out of bounds. He did not ask where I had been.', matron: 'The Matron lets the girl out on Fridays if I bring her a shilling. I bring her a shilling.', tutor: 'Mr. Blake knows about the key. He said he would not tell as long as I brought it back. I did not bring it back.', astro: 'Dr. Quint lets us look at Saturn. On Friday she sent down for the boys and I did not go. I was on the path.', gardener: 'Nane brings flowers to Marrow House on Sundays. The girl says he stands at the gate for an hour and never goes in.', driver: 'Miss Fay drove past me on the path at a quarter to twelve with the lights off. I ducked.', sister: 'Miss Ayre is the one Nane brings the flowers for. The girl says she never comes to the gate.' },
      topics: [
        { id: 'night', q: 'You had the tower key on Friday.', a: 'He will not look up. I lost it. On the path. I have told Mr. Wick. I lost it.' },
        { id: 'lost', needs: ['brannock.mud', 'verger.boy', 'tutor.boy'], q: 'You did not lose it. Somebody took it from you on the path, and you know who.', a: 'He starts to cry. A man. By the reservoir wall at eleven. He put his hand on my chest and took the key out of my pocket and said if I told anybody the girl would be sent somewhere worse. I have not told anybody. I am telling you.', after: 'night', cost: 1, effect: { type: 'suspectTrait', suspectId: 'harris' } },
        { id: 'hands', q: 'Tell me about the man.', a: 'I could not see his face. The lamp was behind him. I saw his hands when he took the key. He said: forget it, Harris. He knew my name. Everybody on the hill knows my name. That is what a school is.', after: 'lost', cost: 1, effect: { type: 'culpritTrait' } },
        { id: 'girl', q: 'Who is the girl?', a: 'Ellen. From Marrow House. She is not mad. Nobody in there is mad. We meet on the ringing floor because it is the only room on the hill nobody goes into. Sister Constance found us there in January and said nothing to anybody. She just said: be careful on the stairs.' },
      ] },
    { id: 'verger', name: 'Cormac Ill', role: 'The verger',
      traits: { build: 'slight', hair: 'grey' },
      blurb: 'Found the body. Had washed the stairs before we arrived.',
      motive: 'because she had started asking what he does with the tower key at night.',
      bio: 'Fifty-nine. Verger of St. Ordell’s for thirty years. He holds every key on the hill. He found Sister Constance at six and had scrubbed the stairs by seven.',
      alibi: 'Asleep in the verger’s cottage. Nobody can confirm it.',
      secret: 'He lends the tower key to a boy from the Academy who meets a girl from Marrow House up there. The tower key was not on its hook that night because the boy had it.',
      opinions: { canon: 'The Canon is a good man with a bad ledger. I have kept his keys for twenty years. I have never kept his books.', matron: 'The Matron comes to Mass and sits at the back. She looks at the Ayre pew the whole time.', tutor: 'Mr. Blake takes the boys up the tower to see the view. I let him. I should not have.', astro: 'Dr. Quint looks at the tower more than she looks at the sky. She told me so herself.', gardener: 'Nane digs when Grimm is drunk. He dug on Tuesday. Nobody had died on Tuesday.', driver: 'Miss Fay drives the last tram and drives it too fast. Constance would not ride with her. She said a tram was a bell on wheels rung by somebody with no ear.', sister: 'The younger Ayre girl came to the tower door on Wednesday and asked for her sister. I said no. I have thought about that no every hour since.' },
      topics: [
        { id: 'night', q: 'Where were you at midnight?', a: 'In my bed in the cottage. I heard the bell. I counted nine and I thought I had miscounted. I went back to sleep. God forgive me.' },
        { id: 'stairs', q: 'You washed the stairs before we came.', a: 'I did. I found her at six and I could not leave her like that. I know what I did. I would do it again.' },
        { id: 'key', needs: ['item:bell:key-board', 'brannock.night', 'wick.night'], q: 'The tower key was not on its hook.', a: 'He looks at his hands. I lend it out. To a boy from the school. He meets a girl up there. I thought it was harmless. I think about that word now.', after: 'night', cost: 1, effect: { type: 'suspectTrait', suspectId: 'verger' } },
        { id: 'boy', q: 'Which boy?', a: 'Blake’s third form. The thin one. He was to bring the key back by eleven. He did not. He has not come near me since.', after: 'key', cost: 1, effect: { type: 'lead', at: 'academy' } },
        { id: 'constance', q: 'What was Sister Constance like?', a: 'Exact. She rang twelve strokes for twenty years and never one more or less. She counted everything. She had started counting the Canon’s money.' },
      ] },
    { id: 'canon', name: 'Canon Aldritch', role: 'Canon of St. Ordell’s',
      traits: { build: 'broad', hair: 'grey' },
      blurb: 'Says he slept through it. His bedroom window faces the tower.',
      motive: 'because she had asked to see the crypt account books, and the books would have shown the money he took.',
      bio: 'Sixty-four. Canon for twenty years. He runs the crypt restoration fund. Four hundred pounds is missing from it and every withdrawal slip has his signature. Sister Constance asked to see the fund box on Thursday.',
      alibi: 'Asleep in the Rectory. His housekeeper will confirm his light went out at eleven.',
      secret: 'He took the money. Not for himself. For a woman in the city and a child who has his eyes and not his name.',
      opinions: { verger: 'Cormac Ill has kept my keys for thirty years and never once asked what they opened.', matron: 'Matron Crake and I have an understanding about the Ayre girl. I am not proud of it.', tutor: 'Mr. Blake is a good teacher with poor judgement about the hours he keeps.', astro: 'Dr. Quint sees everything from that Observatory. She has never come to confession. I wish she would.', gardener: 'Nane does what he is told and does not ask. That is why I asked him.', driver: 'Miss Fay is a good girl who needs money. Most sins on this hill start there.', sister: 'Beatrix Ayre should never have been put away. I signed the papers. Constance signed them too. We both knew.' },
      topics: [
        { id: 'night', q: 'Where were you at midnight?', a: 'Asleep. Mrs. Tull will tell you my light went out at eleven. I did not hear the bell. I am told it rang nine. I have no idea what that means.' },
        { id: 'fund', needs: ['item:bell:crypt-ledger', 'item:bell:crypt-tin', 'pym.constance'], q: 'Four hundred pounds is missing from the crypt fund. Every slip has your signature.', a: 'He goes very still. Yes. I took it. Constance asked to see the box on Thursday. I said Monday. There was not going to be a Monday.' },
        { id: 'where', q: 'Where did the money go?', a: 'To a woman in the city. And a child. He has my eyes and not my name. I buried the money in a tin box on Tuesday because Constance was coming and I panicked. I am a foolish old man, not a murderer.', after: 'fund', cost: 1, effect: { type: 'suspectTrait', suspectId: 'canon' } },
        { id: 'box', needs: ['item:bell:crypt-tin', 'grimm.night', 'gardener.grave'], q: 'The box is empty now.', a: 'Somebody dug it up on Friday night. Somebody who knew where it was. Only Nane knew where it was. And whoever Nane told.', after: 'where', cost: 1, effect: { type: 'lead', at: 'cemetery' } },
        { id: 'constance', q: 'Tell me about her.', a: 'The best of us. She rang the bell for twenty years and never asked for a thing. Then she asked for the books. She was going to put everything right. On this hill, that is the one thing nobody can afford.' },
      ] },
    { id: 'matron', name: 'Matron Sybil Crake', role: 'Marrow House',
      traits: { build: 'broad', hair: 'grey' },
      blurb: 'Logged the asylum gate open at eleven-forty. Will not say who went through it.',
      motive: 'because Constance had worked out that Beatrix was never ill, and was going to say so.',
      bio: 'Fifty. Matron of Marrow House asylum for eleven years. She keeps one bed for a patient who has never been ill: Beatrix Ayre, Constance’s sister, kept there on the family’s money.',
      alibi: 'In her office at Marrow House all night. The orderly saw her.',
      secret: 'She has kept Beatrix Ayre locked up for nine years knowing there was nothing wrong with her. The Ayre family paid. She stopped asking why long ago.',
      opinions: { verger: 'The verger let my patient up the tower. Then he lets a schoolboy up it. The man will lend anyone a key.', canon: 'The Canon pays the Ayre bill on the family’s behalf. Late. Every quarter.', tutor: 'Mr. Blake brought a boy to my gate on Wednesday. The boy had a letter for Beatrix. I did not take it.', astro: 'Dr. Quint signs for chloral at the dispensary. For sleep, she says. Astronomers do not sleep.', gardener: 'Nane brings the Glasshouse flowers to my wards on Sundays. He stays longer than flowers take.', driver: 'Miss Fay drove one of my patients away at a quarter to midnight. I have not reported it. I should have.', sister: 'Beatrix Ayre is not ill. She has never been ill. I have written her up as ill every month for nine years.' },
      topics: [
        { id: 'night', q: 'Where were you at midnight?', a: 'In my office. Quaile brought me tea at twelve. The gate was open. I logged it open. I did not go through it.' },
        { id: 'gate', needs: ['quaile.night', 'item:bell:depot-sheet', 'driver.who'], q: 'Who went through the gate at eleven-forty?', a: 'She does not answer for a long time. Beatrix. With a bag. I let her go because her sister had told me on Thursday it would stop. I thought that meant she was going home.' },
        { id: 'beatrix', q: 'Is Beatrix Ayre ill?', a: 'No. Never. The family paid for a bed and I gave them one. Constance signed the papers nine years ago. On Thursday she came to unsign them. I told her there was no such thing.', after: 'gate', cost: 1, effect: { type: 'suspectTrait', suspectId: 'matron' } },
        { id: 'bag', needs: ['quaile.night', 'marley.night'], q: 'What was in the bag?', a: 'Her things. And a rosary. And a letter from a schoolmaster that I did not read. She went down the hill toward the tram depot.', after: 'beatrix', cost: 1, effect: { type: 'lead', at: 'depot' } },
      ] },
    { id: 'tutor', name: 'Mr. Ewan Blake', role: 'Master at Ordell Academy',
      traits: { build: 'slight', hair: 'fair' },
      blurb: 'His boys were out of bed. He cannot say where he was.',
      motive: 'because she wrote a letter to the Dean about him. She never posted it, but he did not know that.',
      bio: 'Thirty-four. Teaches the third form at the Academy. Takes boys to the Observatory after lights-out. Sister Constance wrote a letter to the Dean about it. The letter was found in his desk.',
      alibi: 'Marking papers in his rooms at the Academy. Alone.',
      secret: 'He was at the Observatory with two boys and Dr. Quint, looking at Saturn. That is all it was. He knows nobody will believe that is all it was.',
      opinions: { verger: 'The verger lends the tower key to my boys. I have asked him to stop. He says it keeps them out of the pub.', canon: 'The Canon does not like me. He liked Constance. I understand both.', matron: 'Matron Crake would not take a letter from me at her gate. She looked at me like I was the one locked up.', astro: 'Halla Quint shows my boys Saturn on clear nights. That is all it is. Nobody will believe that is all it is.', gardener: 'Nane digs for the Canon. Graves and other things.', driver: 'Miss Fay drives my boys down the hill on Saturdays and back on Sundays and pretends not to know their names.', sister: 'Beatrix Ayre came to the school on Wednesday and gave me a letter for her sister. I gave it to Constance. Constance cried.' },
      topics: [
        { id: 'night', q: 'Where were you at midnight?', a: 'In my rooms, marking papers. Alone. He looks at the floor. That is not true. I was at the Observatory.' },
        { id: 'observatory', q: 'With whom?', a: 'Dr. Quint and two boys. Looking at Saturn. It was clear for ten minutes at midnight. We heard the bell. We counted nine. Quint went to the eyepiece and turned it on the tower.', after: 'night', cost: 1, effect: { type: 'suspectTrait', suspectId: 'tutor' } },
        { id: 'letter', needs: ['item:bell:unposted', 'oakes.constance'], q: 'Constance wrote to the Dean about you. The letter was in your desk.', a: 'She gave it to me. On Thursday. She said, I wrote this and I am not sending it, and I want you to know what I could have done. That is the kind of woman she was.' },
        { id: 'boy', needs: ['wick.night', 'verger.boy', 'brannock.night'], q: 'One of your boys had the tower key.', a: 'Harris. He meets a girl from Marrow House up there. He did not bring the key back on Friday because somebody took it from him on the path. He would not say who. He is fifteen and terrified, and he is hiding in the sanatorium behind the school, where nobody will think to look.', after: 'observatory', cost: 1, effect: { type: 'reveal', locationId: 'sanatorium', suspectId: 'harris' } },
      ] },
    { id: 'astro', name: 'Dr. Halla Quint', role: 'Astronomer',
      traits: { build: 'tall', hair: 'dark' },
      blurb: 'Was awake. Was watching. Refuses to say what.',
      motive: 'because she had seen something through the telescope that she could not unsee.',
      bio: 'Forty-one. Runs the Observatory. At midnight her telescope was not pointed at the sky. Her log says ‘tower’. Twice.',
      alibi: 'At the Observatory all night, observing. Her log shows it.',
      secret: 'She watched somebody climb down the outside of the tower at four minutes past midnight. She drew them in the margin of her log. She has not said who, because she is not sure, and she will not guess at a hanging.',
      opinions: { verger: 'The verger climbs the tower every day and has never once looked up.', canon: 'The Canon’s window faces the tower. His curtains were closed at midnight. They are never closed.', matron: 'The Matron keeps a patient who is not a patient. Constance told me. She told me a lot, at the end.', tutor: 'Ewan Blake was in my dome at midnight with two of his boys. I will say that in court. Nobody will believe it.', gardener: 'The Glasshouse boiler light was on until two. I can see it from here. I cannot tell you who was under it.', driver: 'The tram went up the hill just before midnight with its lights off. I saw it from the dome. Miss Fay was driving.', sister: 'Beatrix Ayre stood on the Close Green at midnight, looking up at the tower. I saw her through the glass. She was counting.' },
      topics: [
        { id: 'night', needs: ['item:bell:tower-view', 'tutor.observatory', 'wick.night'], q: 'Your log says ‘tower’ at midnight. Not the sky.', a: 'The bell rang nine. I turned the telescope. I saw the tower door. Then I saw someone on the outside of the tower, on the iron rungs, coming down.' },
        { id: 'who', q: 'Who?', a: 'I do not know. A figure in dark clothes. I drew what I saw. I will not put a name to a drawing when the name means a rope. Ask me anything else.', after: 'night' },
        { id: 'rungs', q: 'Describe what you saw.', a: 'She takes a breath. Someone who came down fast. Someone who knew the rungs were there. At the bottom they went toward the reservoir, not the Close. They did not look back once.', after: 'who', cost: 1, effect: { type: 'culpritTrait' } },
        { id: 'chloral', needs: ['item:bell:poisons', 'lamb.night'], q: 'You sign for chloral at the dispensary.', a: 'For sleep. I cannot sleep. I have not slept properly since Wednesday, when Constance told me what this hill has been doing to her sister.', cost: 1, effect: { type: 'suspectTrait', suspectId: 'astro' } },
      ] },
    { id: 'gardener', name: 'Peter Nane', role: 'Glasshouse gardener',
      traits: { build: 'tall', hair: 'dark' },
      blurb: 'Glasshouse gardener. Dug grave forty-four. Nobody is buried in it. Takes flowers to Marrow House every Sunday.',
      motive: 'because Constance signed Beatrix into the asylum, and after four years of Sunday visits he had decided Beatrix was his to avenge.',
      bio: 'Twenty-eight. Gardener at the Glasshouse. Digs graves for the parish when the gravedigger is drunk. He dug plot forty-four three days before anyone died.',
      alibi: 'Stoking the Glasshouse boilers until two. Then asleep in the potting shed.',
      secret: 'He took the tower key from the boy on the reservoir path. He was waiting at the top of the stairs when Constance came up. He rang nine for Beatrix, because he thought it was what she wanted, and came down the outside on the rungs.',
      opinions: { verger: 'The verger tells me where to dig. He does not tell me why.', canon: 'The Canon paid me two pounds to dig a hole on Tuesday and asked me not to tell Grimm.', matron: 'The Matron lets me bring flowers on Sundays. I bring them for one patient. She knows which.', tutor: 'Mr. Blake had a boy with him at the Glasshouse on Friday. The boy had been crying.', astro: 'Dr. Quint sends down for orchids for the dome. She says the cold kills them. It does.', driver: 'Rosalind drives me down the hill on Saturdays. She talks about leaving. She never leaves.', sister: 'Beatrix. I have taken her flowers every Sunday for four years. She is not mad. She is angry. There is a difference.' },
      topics: [
        { id: 'night', q: 'Where were you at midnight?', a: 'At the Glasshouse. Stoking. Lister will tell you. I heard the bell. I counted nine. I sat down on the coal.' },
        { id: 'grave', needs: ['grimm.night', 'item:bell:crypt-tin', 'canon.where'], q: 'You dug plot forty-four on Tuesday.', a: 'For the Canon. He said dig a hole four feet deep and do not tell Grimm. He put a tin box in it. I filled it in. That is all I did.' },
        { id: 'box', needs: ['grimm.night', 'canon.box', 'item:bell:crypt-tin'], q: 'The box is empty now.', a: 'He rubs his face. I told one person where it was. I should not have. I told her because she asked me, and I have never said no to her.', after: 'grave', cost: 1, effect: { type: 'suspectTrait', suspectId: 'gardener' } },
        { id: 'her', q: 'Who did you tell?', a: 'Beatrix. On Sunday. I told her the Canon had buried money in the cemetery. I thought it would make her laugh. She did not laugh.', after: 'box', cost: 1, effect: { type: 'lead', at: 'asylum' } },
      ] },
    { id: 'driver', name: 'Rosalind Fay', role: 'Tram driver',
      traits: { build: 'slight', hair: 'red' },
      blurb: 'Took a tram out of the depot at a quarter to midnight without signing for it, and brought it back at twenty past one, wet.',
      motive: 'because she was paid five pounds to drive a passenger up the hill and forget it, and Constance had found out.',
      bio: 'Twenty-nine. Drives the hill tram. She took a car out at a quarter to midnight without permission and brought it back at twenty past one, wet.',
      alibi: 'Home in bed. The car went out; she says she did not take it.',
      secret: 'She drove Beatrix Ayre from Marrow House to the Close Green at midnight, for five pounds and a promise. She has not been paid.',
      opinions: { verger: 'The verger rides my tram to the depot every Saturday to drink where nobody knows him. Everybody knows him.', canon: 'The Canon has never been on a tram in his life. He sent his housekeeper down with an envelope for me once.', matron: 'The Matron pays me to forget who I drive from Marrow House. Then she forgets to pay.', tutor: 'Mr. Blake rides with his boys and looks out of the window the whole way so he does not have to talk to them.', astro: 'Dr. Quint rides up at dusk and down at dawn and never once sits down.', gardener: 'Peter Nane talks about the Ayre girl the whole way down the hill. I have told him it is no use. He knows.', sister: 'I drove Beatrix Ayre up the hill at midnight with the lights off. She sat with a rosary round her wrist and did not speak.' },
      topics: [
        { id: 'night', needs: ['item:bell:depot-sheet', 'marley.night'], q: 'Car seven went out at a quarter to midnight.', a: 'It did. I was in bed. She looks away. No. I took it. I drove somebody up the hill with the lights off for five pounds and I have not been paid.' },
        { id: 'who', q: 'Who did you drive?', a: 'Beatrix Ayre. From the Marrow House gate to the Close Green. She got out and stood on the grass and looked up at the tower. I waited. Then I did not wait.', after: 'night', cost: 1, effect: { type: 'suspectTrait', suspectId: 'driver' } },
        { id: 'wet', needs: ['marley.night', 'shale.night', 'shale.walkway'], q: 'The car came back wet.', a: 'I ran the car down to the reservoir stop after. To think. I sat on the wall in the rain. Somebody came along the walkway at one with a key and a bag and did not see me. I saw them. They dropped something that rang on the stone.', after: 'who', cost: 1, effect: { type: 'lead', at: 'reservoir' } },
        { id: 'paid', needs: ['driver.who', 'obj:bell:pass'], q: 'Who promised the five pounds?', a: 'A note under the depot door. Five pounds to drive a patient to the Green at midnight, no questions. Handwriting like a schoolboy’s. I needed the money. I always need the money.' },
      ] },
    { id: 'sister', name: 'Beatrix Ayre', role: 'The victim’s sister',
      traits: { build: 'tall', hair: 'dark' },
      blurb: 'Arrived on the hill three days ago. Has not said why.',
      motive: 'because nine years is how long Constance let her sit in Marrow House.',
      bio: 'Thirty-six. Constance’s younger sister. She has been a patient at Marrow House for nine years. Three days ago she walked out. She says she was released. Marrow House says nothing.',
      alibi: 'In her bed at Marrow House. The gate log says otherwise.',
      secret: 'She went out through the gate at eleven-forty and was driven to the Close Green. She stood under the tower at midnight and counted the bells. She had rung nine to her sister through the walls of Marrow House every night for nine years.',
      opinions: { verger: 'The verger would not let me up the tower on Wednesday. He said Constance had told him not to. She had not.', canon: 'The Canon signed the papers that put me away. He signed them in green ink. I have thought about that green ink for nine years.', matron: 'Matron Crake is not cruel. That would be easier. She is careful.', tutor: 'Mr. Blake gave my letter to my sister. He is the only person on this hill who did what I asked.', astro: 'The astronomer watched me from her dome at midnight. I saw the lens catch the light. I waved. She did not wave back.', gardener: 'Peter brings me flowers. He told me where the Canon buried his money. I did not dig it up. I wanted to.', driver: 'Rosalind drove me up the hill. I promised her five pounds I do not have. I will pay her when I have it.' },
      topics: [
        { id: 'night', q: 'Where were you at midnight?', a: 'On the Close Green, under the tower. Looking up. The bell rang nine. I thought it was for me. I thought she was saying sorry.' },
        { id: 'nine', q: 'Why nine?', a: 'Nine years. Every night in Marrow House I rang nine on the water pipe with a spoon, so she would hear it up the hill. She never heard. I thought at midnight she finally had.', after: 'night' },
        { id: 'after', needs: ['ferris.night', 'quaile.back', 'obj:bell:rosary'], q: 'What did you do after the bell?', a: 'She looks at her hands. I ran. Down to the reservoir. I took a boat from the wall stage. I lost the oars and then my rosary and I rowed with my hands. I was on the far side before I knew it. I walked up the hill wet and sat on the tea room step until they opened.', after: 'night', cost: 1, effect: { type: 'suspectTrait', suspectId: 'sister' } },
        { id: 'saw', q: 'Did you see anyone at the tower?', a: 'Somebody on the outside of it. On the rungs. Coming down fast, while the ninth bell was still ringing. They went the other way from me. Toward the pump house.', after: 'after', cost: 1, effect: { type: 'lead', at: 'pumphouse' } },
        { id: 'letter', needs: ['tutor.letter', 'matron.bag', 'quaile.night'], q: 'You sent your sister a letter.', a: 'Through Mr. Blake. It said: I know you signed it. I know why. Ring nine for me once and I will forgive you. She rang nine. Somebody rang nine.' },
      ] },
  ],

  culprit: 'gardener',
  clues: BELL_CLUES,

  witnesses: [
    { id: 'tull', at: 'rectory', name: 'Ivy Tull', role: 'housekeeper, the Rectory',
      intro: 'Mrs. Tull. I keep the Canon’s house. I know who comes to his door and what they want from him.',
      bio: 'Housekeeper at the Rectory for twenty-five years. She pours the Canon’s sherry and counts the glasses.',
      knows: ['canon', 'verger', 'sister'],
      aboutLine: 'They take tea in this house. I’ve poured it and I’ve watched.',
      leadLine: 'Somebody came down the hill in the dark and left through the garden. There were footprints toward', leadAt: 'cemetery',
      spentLine: 'The Canon wouldn’t want me talking. Neither do I.',
      opinions: { canon: 'The Canon’s light went out at eleven. It came on again at a quarter to one. He was not in his bed. His curtains were shut.', verger: 'Cormac Ill came to the kitchen door at half past six with his hands red from scrubbing and said, she has fallen. She had not fallen.', sister: 'The younger Miss Ayre came to this door on Wednesday and asked for the Canon. He would not see her. I gave her tea in the kitchen. She did not drink it.' },
      topics: [
        { id: 'night', q: 'What happened in this house at midnight?', a: 'The bell rang nine. I counted. The Canon’s door opened. I heard him on the stairs. Then the garden door. He was out the best part of an hour.' },
        { id: 'garden', q: 'Where did he go?', a: 'Down the hill. There were footprints in the morning, toward the cemetery. Big footprints. He came back at a quarter to one with mud to the knee and put his cassock in the laundry basket himself. He has never done that. Then he sat up writing.', after: 'night', cost: 1, effect: { type: 'lead', at: 'cemetery' } },
        { id: 'constance', q: 'Did Sister Constance come here?', a: 'Thursday. She sat in the study with the Canon for an hour and came out white. She said to me, Ivy, I have been part of something wicked for nine years. I said, we all have, Sister.' },
      ] },
    { id: 'wick', at: 'academy', name: 'Josiah Wick', role: 'porter, Ordell Academy',
      intro: 'Wick. I lock the school gates at ten. Tonight somebody had a key that wasn’t mine.',
      bio: 'Porter at the Academy for thirty years. He rings the school bell every morning and counts the boys every night.',
      knows: ['tutor', 'astro'],
      aboutLine: 'On the staff, or near enough. I see them across the quad every morning.',
      leadLine: 'A boy found something on the playing fields at dawn and was too scared to say so. It ended up at', leadAt: 'observ',
      spentLine: 'The gate is shut and I have a bell to ring in three hours.',
      opinions: { tutor: 'Mr. Blake went out at half past eleven with two boys and came back at one. He signed nothing. He never does.', astro: 'Dr. Quint sends a note down for the boys on clear nights. Friday was not clear. She sent the note anyway.' },
      topics: [
        { id: 'night', q: 'Who had a key that wasn’t yours?', a: 'Harris, third form. He has the verger’s tower key and the gate key both. He went out at half past ten and came back at half past twelve without either.' },
        { id: 'harris', q: 'Where is Harris now?', a: 'In the sanatorium at the back of the school, with a fever he has not got. It is a locked ward; nobody outside the school knows the door is there. He will not come out. He says a man took the key from him on the path by the reservoir and told him to forget it.', after: 'night', cost: 1, effect: { type: 'reveal', locationId: 'sanatorium', suspectId: 'harris' } },
        { id: 'constance', q: 'Did you know Sister Constance?', a: 'She rang for the school every morning at seven. Twelve strokes, then seven. Never one out. Friday morning nobody rang. That is how I knew before anyone told me.' },
      ] },
    { id: 'greer', at: 'almshouse', name: 'Mother Greer', role: 'resident, the Almshouse',
      intro: 'They call me Mother Greer. Seventy-one years in this parish. I’ve buried two of the people on your list, and I’ll bury a third.',
      bio: 'Born on the hill. Has outlived three canons and most of her neighbours. She does not sleep.',
      knows: ['matron', 'gardener', 'driver'],
      aboutLine: 'I’ve known that one since they were small. Small people grow into big people. They don’t turn into different ones.',
      leadLine: 'I don’t sleep. I heard the Canon’s garden gate, and I saw a cassock go down the path toward', leadAt: 'cemetery',
      spentLine: 'I’m tired, child. Come back when it’s light, and bring biscuits.',
      opinions: { matron: 'Sybil Crake was a nurse in this almshouse before she was a matron. She was kind then. Money is a hard thing to be kind through.', gardener: 'Peter Nane brings me tobacco and takes my advice, which is a fair trade. I told him to leave the Ayre girl alone. He did not.', driver: 'Rosalind Fay’s mother died in bed nine here. Rosalind drove the tram past the window every day for a year and never came in.' },
      topics: [
        { id: 'night', q: 'What did you hear?', a: 'Nine bells. Then the Canon’s garden gate, which squeals. Then a man on the path under my window going down toward the cemetery, fast, holding his skirts up. A cassock. I have seen enough cassocks to know one in the dark.' },
        { id: 'bundle', q: 'Did he come back?', a: 'At a quarter to one, slower, with a square tin under his arm and mud to the knee. He held it against his chest the way you hold something you should not have. Empty, by the way it swung.', after: 'night', cost: 1, effect: { type: 'lead', at: 'rectory' } },
        { id: 'constance', q: 'Did you know Sister Constance?', a: 'I taught her to ring. Sixty years ago I rang that bell myself. She came to me on Thursday and asked whether a person could be forgiven for something they signed. I said only if they unsigned it. She said she was going to try.' },
      ] },
    { id: 'marley', at: 'depot', name: 'Fen Marley', role: 'night dispatcher, the Tram Depot',
      intro: 'Marley. I sign the trams out and back in. The last car is at eleven. Tonight one went out at a quarter to midnight and I didn’t sign it.',
      bio: 'Night dispatcher for eight years. The schedule is the only thing on the hill he trusts.',
      knows: ['driver', 'tutor', 'sister'],
      aboutLine: 'They ride the last car. You learn a person by which seat they take.',
      leadLine: 'Rosalind ran car seven down to the reservoir stop after the Green and left it standing. Whatever she saw there, she saw from', leadAt: 'reservoir',
      spentLine: 'The schedule is the schedule. I’ve said what I know.',
      opinions: { driver: 'Rosalind took car seven at a quarter to midnight with the lights off. I saw her hands on the brake from the office. She brought it back at twenty past one, wet to the knees.', tutor: 'Mr. Blake rode down on Wednesday with the Ayre woman two seats behind him and did not know it. She knew him. She watched the back of his head the whole way.', sister: 'The Ayre woman rode up on my car on Wednesday with one bag and no ticket. She sat in the front seat and looked at the tower the whole way up.' },
      topics: [
        { id: 'night', q: 'Car seven.', a: 'Out at a quarter to midnight, unsigned. Back at twenty past one, wet. Rosalind Fay driving. One passenger up, from the Marrow House gate to the Close Green. None down.' },
        { id: 'route', q: 'Where did she take it after the Green?', a: 'Down to the reservoir stop. The trip wheel counts the stops, and it counted that one and then nothing for half an hour. She left the car standing by the wall with the lights off and sat out in the rain. Then she brought it home.', after: 'night', cost: 1, effect: { type: 'lead', at: 'reservoir' } },
        { id: 'constance', q: 'Did Sister Constance ride the tram?', a: 'Never. She walked. Two hundred and eleven steps up the tower and a mile down the hill and back every day for twenty years. She said the walk was the prayer.' },
      ] },
    { id: 'lister', at: 'glasshouse', name: 'Bo Lister', role: 'stoker, the Glasshouse',
      intro: 'Lister. I keep the boilers going so the orchids don’t freeze. It’s warmer in here than anywhere on the hill, so people come in.',
      bio: 'Stoker at the Glasshouse for six years. He sees the hill come in from the cold and talk.',
      knows: ['gardener', 'astro', 'matron'],
      aboutLine: 'They come in to get warm. You see a person clearly in this light.',
      leadLine: 'The Canon burned a page in my firebox on Friday afternoon and didn’t burn all of it. The number on the corner belongs to', leadAt: 'cemetery',
      spentLine: 'The boilers need me. The police don’t.',
      opinions: { gardener: 'Nane left at half past ten and said he had a hole to fill. He came back at half past three, wet to the knee, and sat down on the coal with his hands wrapped in a rag. He did not get up till six.', astro: 'Dr. Quint sends down for orchids and I carry them up. Her dome smelled of chloral on Friday.', matron: 'The Matron came in at one to get warm, with reservoir mud on her shoes and her cap gone. She asked whether I had seen the Ayre girl. I had not.' },
      topics: [
        { id: 'night', q: 'What was burned in your firebox?', a: 'Paper. A ledger page and a letter. The Canon himself came in at five on Friday afternoon, which he never does, shoved them in and stood there until they went. Not all of it went. I pulled a corner out.' },
        { id: 'corner', q: 'What was on it?', a: 'A number. Forty-four. And a signature in green ink. The Canon signs in green ink. Everybody on the hill knows that.', after: 'night', cost: 1, effect: { type: 'lead', at: 'cemetery' } },
        { id: 'constance', q: 'Did Sister Constance come here?', a: 'Wednesday. She stood in the warm for an hour and asked me whether the boilers could burn a ledger. I said they could burn anything. She said, good.' },
      ] },
    { id: 'grimm', at: 'cemetery', name: 'Silas Grimm', role: 'gravedigger',
      intro: 'Grimm. I dig the graves. Tonight I found a hole I didn’t dig, and I want to know who did.',
      bio: 'Gravedigger for twenty years, and a drinker for nineteen of them. When he is drunk, the gardener digs.',
      knows: ['verger', 'canon'],
      aboutLine: 'They stand over the graves I dig. You see what a person is at a funeral.',
      leadLine: 'Fresh earth was moved, and something was taken out, not put in. The footprints run down to', leadAt: 'waterboard',
      spentLine: 'I have a hole to fill and I’ve said too much already.',
      opinions: { verger: 'The verger tells Nane where to dig when I am drunk. I am drunk a good deal. I still know my own cemetery.', canon: 'The Canon stood over plot forty-four on Tuesday evening with his hat off like there was somebody in it. There was not.' },
      topics: [
        { id: 'night', q: 'The hole you didn’t dig.', a: 'Plot forty-four. Dug Tuesday by Nane, four feet, with a tin box in it. Dug up again Friday night by somebody in a hurry who left the box and took what was in it.' },
        { id: 'tracks', q: 'Footprints.', a: 'From the plot to the gate and down toward the Water Board. Deep ones, a big man’s, one foot dragging. Then a second set over the top of them, from the gate to the plot and back up the hill. Smaller, and in a hurry.', after: 'night', cost: 1, effect: { type: 'lead', at: 'waterboard' } },
        { id: 'constance', q: 'Did Sister Constance come to the cemetery?', a: 'Every Sunday to her mother. Thursday she came and stood at plot forty-four for a long time and then she went to the Rectory. She walked like a woman going to a fight.' },
      ] },
    { id: 'ansell', at: 'foundry', name: 'Hew Ansell', role: 'bell founder',
      intro: 'Ansell. My grandfather cast that bell. I’ve tuned it every Easter since I could hold a hammer. I know its voice. Last night somebody rang it who didn’t.',
      bio: 'Third generation of bell founders. He can tell who rang a bell by how it sounds.',
      knows: ['verger', 'canon'],
      aboutLine: 'They’ve been up the tower with me. You learn a person by how they climb.',
      leadLine: 'A bolt from the bell clapper was taken from my bench last week. I found it this morning, dropped on the path toward', leadAt: 'reservoir',
      spentLine: 'The furnace is lit. I’m not.',
      opinions: { verger: 'Cormac Ill has been up my tower a thousand times and cannot ring. He has no ear. Whoever rang nine had no ear either.', canon: 'The Canon climbed the tower once, in 1928, and was sick at the top. He has not been up since.' },
      topics: [
        { id: 'night', q: 'You know the bell’s voice.', a: 'Nine strokes, ragged. Rung by somebody who let go of the rope at the top of the pull. Not a ringer. Somebody who had watched ringing and never done it.' },
        { id: 'bolt', q: 'A clapper bolt was taken from your bench.', a: 'Last week. Found this morning on the path to the reservoir. Somebody wanted the bell silenced and then changed their mind and rang it anyway.', after: 'night', cost: 1, effect: { type: 'lead', at: 'reservoir' } },
        { id: 'constance', q: 'You knew Sister Constance.', a: 'Twenty years. The best ringer on the hill. She came to the foundry on Thursday and asked me how a rope is cut so it cannot be rung. I told her. I thought she was afraid of somebody.' },
      ] },
    { id: 'pym', at: 'chapterhouse', name: 'Dorcas Pym', role: 'archivist, the Chapter House',
      intro: 'Miss Pym. Four hundred years of parish records, and I’ve read all of them. Sister Constance came to me last week for the crypt account books. I gave them to her.',
      bio: 'Archivist for thirty-one years. Knows which page of which book holds which secret.',
      knows: ['canon', 'tutor', 'astro'],
      aboutLine: 'They read here. You can tell a person by which books they ask for.',
      leadLine: 'A page was cut out of the crypt ledger on Friday afternoon by somebody who knew exactly which page. The page was about', leadAt: 'cemetery',
      spentLine: 'The reading room closes at dusk, and it’s long past dusk.',
      opinions: { canon: 'The Canon has not opened a parish register in ten years. He sent for the crypt ledger on Friday afternoon. I sent it. It came back at five with a page missing and glue on the stub.', tutor: 'Mr. Blake reads the 1939 register. The year the Ayre girl was committed. He has read it three times.', astro: 'Dr. Quint reads the weather records. Every clear night for a hundred years. She is looking for something in the sky. She has not found it.' },
      topics: [
        { id: 'night', q: 'A page was cut from the crypt ledger.', a: 'Plot forty-four. The Canon sent for the ledger on Friday afternoon and it came back at five with the page gone. Cut with a razor by somebody who has never cut a page in his life; he left glue on the stub and his thumb in the glue.' },
        { id: 'page', q: 'What was on the page?', a: 'An interment on plot forty-four in March. A fee of forty pounds. No name. Nobody was buried there. Constance and I walked up on Thursday and looked, and the earth was fresh. She did not say a word all the way back.', after: 'night', cost: 1, effect: { type: 'lead', at: 'cemetery' } },
        { id: 'constance', q: 'What did Sister Constance want from you?', a: 'The crypt ledger and the 1939 register. She read both here on Wednesday and made notes. She said, Dorcas, I signed my sister away for four hundred pounds and I did not even know it. She meant the Canon had taken the money. I think she meant more than that.' },
      ] },
    { id: 'oakes', at: 'deanery', name: 'Cyrus Oakes', role: 'clerk, Diocesan Office',
      intro: 'Oakes. I type the diocese’s letters, including the one asking you to be discreet. I didn’t agree with it.',
      bio: 'Clerk to the Dean for nine years. He types what he is told and underlines what he thinks.',
      knows: ['canon', 'matron', 'tutor'],
      aboutLine: 'They come before the Dean. You notice who is nervous in front of a bishop.',
      leadLine: 'A letter was delivered by hand for the Dean at one in the morning and burned unread. The corner I saved talks about', leadAt: 'crypt',
      spentLine: 'I’ve said more than the diocese would like. That’s all.',
      opinions: { canon: 'The Canon asked the Dean for discretion on Friday morning. Before anybody was dead. I typed the letter. I dated it Saturday.', matron: 'The Matron’s quarterly report on the Ayre patient is the same every quarter, word for word. I have typed it thirty-six times.', tutor: 'Mr. Blake wrote to the Dean in March offering to resign. The Dean never answered. I never sent it.' },
      topics: [
        { id: 'night', q: 'A letter came for the Dean at one in the morning.', a: 'By hand. From the Rectory. The Dean burned it in the grate unread and told me to forget the hour. I have not forgotten it.' },
        { id: 'ash', q: 'Where is the ash?', a: 'In the grate. I raked out one corner. It says: ‘the page is burned and the box is empty and Constance has—’. That is where it burned.', after: 'night', cost: 1, effect: { type: 'lead', at: 'crypt' } },
        { id: 'constance', q: 'Did Sister Constance write to the Dean?', a: 'Twice. Once about the schoolmaster, which she never sent. Once about the crypt fund and Marrow House, which she posted on Thursday. It has not arrived. Letters from the hill take a day. It should have arrived.' },
      ] },
    { id: 'brannock', at: 'cottage', name: 'Mrs. Brannock', role: 'housekeeper, Verger’s Cottage',
      intro: 'Brannock. I keep house for the verger. I know which hook every key hangs on, and which one has been empty since Thursday.',
      bio: 'Keeps the verger’s cottage and the verger’s secrets, most of them.',
      knows: ['verger', 'sister'],
      aboutLine: 'They come to this kitchen. You learn a person by how they look at the key board.',
      leadLine: 'The tower key has not come back. If the boy lost it where he says he lost it, it is lying somewhere along', leadAt: 'reservoir',
      spentLine: 'The kitchen is mine and I’m closing it.',
      opinions: { verger: 'The verger was in his bed at midnight. I heard him snoring through the wall. Whatever else he is, he was asleep.', sister: 'The younger Miss Ayre came to this kitchen on Wednesday and asked for the tower key. I said no. She looked at the key board a long time and then she looked at me.' },
      topics: [
        { id: 'night', q: 'The tower key.', a: 'Off its hook since Thursday. The verger lends it to a schoolboy. The boy did not bring it back. Constance came for it at half past eleven on Friday and it was not there, and she went up anyway.' },
        { id: 'mud', q: 'Where would it be now?', a: 'The boy says he lost it on the reservoir path. If it went in the water it is gone. If it is on the wall walk it is lying in that black mud, and nobody walks the wall walk at night without the Water Board’s key.', after: 'night', cost: 1, effect: { type: 'lead', at: 'reservoir' } },
        { id: 'constance', q: 'Did Sister Constance come here?', a: 'Every night at half past eleven for the key, and every night at half past twelve to hang it back. Friday she came at half past eleven and it was not on the hook. She went up anyway. Somebody had already unlocked the door.' },
      ] },
    { id: 'lamb', at: 'dispensary', name: 'Enid Lamb', role: 'dispenser, Hill Dispensary',
      intro: 'Lamb. I keep the poisons book for the hill. It’s a short book with long names in it.',
      bio: 'The only chemist on the hill for eleven years. Remembers every hand that signed her book.',
      knows: ['matron', 'astro', 'gardener'],
      aboutLine: 'They sign my book. You notice the hand that signs for sleeping draughts.',
      leadLine: 'Somebody came in at dawn for lint and iodine with a pawn ticket still in his hand. He had come straight from', leadAt: 'pawn',
      spentLine: 'The shop is shut and the book is locked.',
      opinions: { matron: 'The Matron signs for chloral every month for a patient who does not need it. I have watched her sign for eleven years.', astro: 'Dr. Quint buys chloral for herself. She says she cannot sleep. On Friday she bought twice the usual.', gardener: 'Peter Nane bought iodine and lint at dawn on Saturday with his hands wrapped in a rag from the Glasshouse. Coal dust and blood.' },
      topics: [
        { id: 'night', q: 'Who came in at dawn?', a: 'Nane. Lint and iodine. His hands were cut across the palms, both of them, like a man who had gripped a rope or a rung too hard. He paid with pawnshop money and did not wait for the change.' },
        { id: 'hands', q: 'Rope or rung?', a: 'Iron. Rust in the cuts. I cleaned them. He said he had fallen in the Glasshouse. There is no iron in the Glasshouse. I had his hands in mine for ten minutes; I can tell you what else I saw.', after: 'night', cost: 1, effect: { type: 'culpritTrait' } },
        { id: 'constance', q: 'Did Sister Constance buy from you?', a: 'Nothing, ever. Thursday she came in and asked to see the poisons book. She read the Matron’s entries for nine years and said, that is a great deal of sleep for one woman.' },
      ] },
    { id: 'quaile', at: 'asylum', name: 'Sam Quaile', role: 'orderly, Marrow House',
      intro: 'Quaile. I do nights on the east ward. I know who’s a real patient here and who’s only wearing the gown.',
      bio: 'Orderly at Marrow House for five years. He has spent five years watching one patient who is not ill.',
      knows: ['matron', 'sister', 'tutor'],
      aboutLine: 'They’re on my ward, or they visit it. You learn a person by how they behave behind a locked door.',
      leadLine: 'The gate was open at eleven-forty and somebody went out through it carrying a bag. They went down toward', leadAt: 'depot',
      spentLine: 'The Matron would sack me for this. Out.',
      opinions: { matron: 'The Matron was in her office at midnight. I brought her tea. She was crying. She went out at half past twelve to look for Beatrix and did not come back until half past four.', sister: 'Beatrix Ayre is the sanest person in this building. I include the staff.', tutor: 'Mr. Blake came to the gate on Wednesday with a letter and a boy. The Matron would not take the letter. The boy gave it to me. I gave it to Beatrix.' },
      topics: [
        { id: 'night', q: 'The gate was open at eleven-forty.', a: 'I opened it. For Beatrix. With a bag. The Matron said let her go. She went down toward the tram.' },
        { id: 'back', q: 'Did she come back?', a: 'At half past four, with the Matron. Wet to the waist, no rosary, no bag. The Matron had found her on the tea room step. She got into her bed and she has not spoken since. Her hands are torn from rowing.', after: 'night', cost: 1, effect: { type: 'lead', at: 'tearooms' } },
        { id: 'constance', q: 'Did Sister Constance visit?', a: 'Thursday. First time in nine years. She sat with her sister for an hour. When she came out she went straight to the Matron’s office and I heard the word ‘papers’ through the door nine times. I counted.' },
      ] },
    { id: 'hobb', at: 'pawn', name: 'Zeb Hobb', role: 'pawnbroker',
      intro: 'Hobb. Everything the hill is ashamed of comes through this door eventually. This morning it was a gardener’s watch.',
      bio: 'Pawnbroker at the bottom of the hill for thirty years. He looks at hands, not faces.',
      knows: ['driver', 'gardener', 'verger'],
      aboutLine: 'They pawn things with me. I look at the hands that push them across the counter.',
      leadLine: 'A man sold me his watch at dawn with his hands cut across both palms. He went up the lane to', leadAt: 'dispensary',
      spentLine: 'The shop is shut. Come back with something to pawn or not at all.',
      opinions: { driver: 'Rosalind Fay pawned her mother’s ring in April and bought it back in May with a five-pound note. Tram drivers do not have five-pound notes.', gardener: 'Peter Nane pawns his watch every winter and buys it back every spring. This morning he sold it outright, which he has never done, with a bag under his arm he would not put down to sign.', verger: 'The verger pawns his mother’s watch chain every Lent and redeems it at Easter. He says it is a penance. It is a drinking habit.' },
      topics: [
        { id: 'night', q: 'Who came in at dawn?', a: 'Nane. Quarter past five. Sold me his watch outright, which he has never done in ten years. Big hands, cut across both palms, and a bag he would not put down to sign the ticket. He did not want the watch money. He wanted change he could spend.' },
        { id: 'where', q: 'You look at hands.', a: 'I do. I looked at his for as long as it took him to sign, and he signs slowly. I can tell you what I saw.', after: 'night', cost: 1, effect: { type: 'culpritTrait' } },
        { id: 'constance', q: 'Did Sister Constance ever come in?', a: 'Wednesday. She asked me to hold the eyepiece the schoolboy had pawned until Friday, and she would pay for it. Dr. Quint’s. She said the owner would need it on Friday night. She did not come on Friday.' },
      ] },
    { id: 'amsel', at: 'bookshop', name: 'Old Amsel', role: 'bookseller',
      intro: 'Amsel. Second-hand books. I sell the hill its own history back to it, and I know who buys which chapter.',
      bio: 'Bookseller for forty years. Stocks the diocese’s annual reports because somebody on the hill always wants one.',
      knows: ['astro', 'tutor', 'canon'],
      aboutLine: 'They browse here. You learn a person by what they don’t buy.',
      leadLine: 'A diocesan report was bought tonight and its photographs torn out in my doorway. The torn pages went toward', leadAt: 'observ',
      spentLine: 'The shop is closed. So is the subject.',
      opinions: { astro: 'Dr. Quint buys every book on the eye and on seeing. She bought one on Wednesday about how a witness can be wrong.', tutor: 'Mr. Blake buys nothing. He reads standing up and puts the book back. He read the 1939 diocesan report standing up on Thursday.', canon: 'The Canon has never bought a book from me. He borrows them from Miss Pym and forgets to return them.' },
      topics: [
        { id: 'night', q: 'The plates were torn out in your doorway.', a: 'At a quarter past two in the morning. A big man with cut hands banged me up, bought the 1939 report and did not wait for change. He tore out the four plates of the tower in the doorway and ran up toward the Observatory.' },
        { id: 'plates', q: 'What is on the plates?', a: 'The iron rungs on the outside of the tower. The only photograph anyone has of them. Whoever used them wanted nobody to know they were there.', after: 'night', cost: 1, effect: { type: 'lead', at: 'observ' } },
        { id: 'constance', q: 'Did Sister Constance buy books?', a: 'Wednesday. A book on canon law. She asked me which page covers a committal signed under false pretences. I showed her. She read it here and did not buy it.' },
      ] },
    { id: 'petty', at: 'tearooms', name: 'Mrs. Petty', role: 'proprietress, Terrace Tea Rooms',
      intro: 'Mrs. Petty. Milk and two sugars for the whole hill, and I hear every word said over it. I pour and I remember.',
      bio: 'Has run the tea rooms for twenty years. The hill’s gossip passes across her counter twice a day.',
      knows: ['astro', 'sister', 'matron'],
      aboutLine: 'They take tea here. I’ve set a cup in front of them and watched them lift it.',
      leadLine: 'Two women argued here at four in the morning. The one who paid took the other back up the hill to', leadAt: 'asylum',
      spentLine: 'The urn is cold, and so am I.',
      opinions: { astro: 'Dr. Quint takes her tea at six after a night in the dome. Saturday she did not come. She sent a note asking me to keep the papers from her.', sister: 'Beatrix Ayre was on my step when I came down at four, wet to the waist. She sat at that table with her hands shaking so badly she left a glove behind.', matron: 'The Matron argued with the Ayre girl here at four in the morning and paid for both teas. She never pays for anybody’s tea.' },
      topics: [
        { id: 'night', q: 'Two women argued here at four.', a: 'The Matron and Beatrix Ayre. Beatrix was wet to the waist. The Matron said, you were not there. Beatrix said, I was under it, I counted nine. The Matron said, then you saw.' },
        { id: 'saw', q: 'Saw what?', a: 'Beatrix said, a man on the outside of the tower. The Matron went white and paid and took her back up the hill to Marrow House. The glove stayed on the chair. It is there now. I have not touched it.', after: 'night', cost: 1, effect: { type: 'lead', at: 'asylum' } },
        { id: 'constance', q: 'Did Sister Constance take tea here?', a: 'Thursday. With the Canon. He talked and she did not touch her cup. When he left she sat for an hour and then she said to me, Mrs. Petty, if I fall down the stairs, I did not fall.' },
      ] },
    { id: 'rudge', at: 'inn', name: 'Tam Rudge', role: 'landlord, the Lamplighter’s Arms',
      intro: 'Rudge. The only pub on the hill. Everything the hill says out loud, it says in here first.',
      bio: 'Landlord for fifteen years. He chalks what the hill owes him on a slate, and remembers what it says.',
      knows: ['gardener', 'driver', 'verger'],
      aboutLine: 'They drink in my pub. You see a person clearest after the third drink.',
      leadLine: 'A man came in with wet boots and a dry throat and left without paying. He went out the back toward', leadAt: 'bookshop',
      spentLine: 'Time, gentlemen. That includes you.',
      opinions: { gardener: 'Nane came in at half past one with wet boots and cut hands and drank two rums and said he had rung it and laughed. He says that every night. Friday he was not laughing.', driver: 'Rosalind Fay drinks here on Saturdays and talks about the city. Friday she did not come in at all.', verger: 'The verger drinks at the depot, not here. He thinks nobody knows. The whole hill knows.' },
      topics: [
        { id: 'night', q: 'The man with wet boots.', a: 'Nane. Half past one. Cut hands, wet to the knee, two rums, no money. He said, I rang it, Tam, and laughed. He says that every night. Friday his voice was wrong.' },
        { id: 'back', q: 'He went out the back.', a: 'Up the Terrace steps toward the bookshop, with a bag he held against his chest the whole time he drank. He had not put it down once, not even for the second rum.', after: 'night', cost: 1, effect: { type: 'lead', at: 'bookshop' } },
        { id: 'constance', q: 'Did Sister Constance ever come in?', a: 'Once. Thursday. She stood at the bar and ordered nothing and said to the room, whoever has been up my tower at night, I know, and it stops now. Then she left. The room did not breathe for a minute.' },
      ] },
    { id: 'shale', at: 'pumphouse', name: 'Wat Shale', role: 'pumpman, the Pump House',
      intro: 'Shale. I keep the engines running all night. They’re loud enough to cover a bell. Not nine of them.',
      bio: 'Pumpman for twelve years. He stops the engines when he wants to hear the hill.',
      knows: ['gardener', 'driver'],
      aboutLine: 'They pass the engine house at night. You learn a person by how they walk past a noise.',
      leadLine: 'Somebody used the valve walkway at one in the morning and dropped something on the stones. Then they went along the wall to', leadAt: 'boathouse',
      spentLine: 'The engines don’t stop, and neither can I.',
      opinions: { gardener: 'Nane walked past the engine house at one with a bag and did not look at the noise. Everybody looks at the noise.', driver: 'Miss Fay sat on the reservoir wall from half past midnight till one, in the rain. I saw her from the engine door. She was there to think, she says. She was there to watch, I say.' },
      topics: [
        { id: 'night', q: 'You stopped the engines at midnight.', a: 'For four minutes, to listen. Nine bells. I wrote the number down. I have written twelve every night for twelve years. Nine is not a mistake. Nine is a message.' },
        { id: 'walkway', q: 'Somebody used the valve walkway at one.', a: 'With the Water Board key. They dropped something that rang on the stone, and did not stop for it. Then they went along the top of the wall to the boathouse side with a bag against their chest.', after: 'night', cost: 1, effect: { type: 'lead', at: 'boathouse' } },
        { id: 'constance', q: 'Did you know Sister Constance?', a: 'By the bell. Twelve years, twelve strokes, and I set my engines by her. Friday I stopped them to listen and I have not been able to start them right since.' },
      ] },
    { id: 'ferris', at: 'boathouse', name: 'Old Ferris', role: 'boatman, the Reservoir',
      intro: 'Ferris. Two rowing boats and a tally book. Tonight one went out from the wall stage without a tally and came in to mine without its oars.',
      bio: 'Boatman at the reservoir for twenty years. He counts the boats out and in, and the oars with them.',
      knows: ['astro', 'gardener'],
      aboutLine: 'They take a boat out sometimes. You learn a person by how they row.',
      leadLine: 'Skiff two came in to my stage at half past one without oars. The footprints from it go up the bank toward', leadAt: 'inn',
      spentLine: 'The water is cold and I’m colder. Go.',
      opinions: { astro: 'Dr. Quint rows out to the middle on clear nights to see the sky in the water. She was not out on Friday. Friday was not clear.', gardener: 'Nane came off the wall walk at ten past one with a bag against his chest and his hands wrapped in a rag, and went along the bank toward the Lamplighter’s. He did not look at the boats. Everybody looks at the boats.' },
      topics: [
        { id: 'night', q: 'One boat went out without a tally.', a: 'Skiff two, from the wall stage on the Close side, at twenty to one. A woman, rowing badly, for this side. She lost the oars halfway. She came in against my stage at half past one with her hands, and left the boat and went up the bank. I found a rosary in the bottom of it this morning.' },
        { id: 'bank', q: 'Where did she go?', a: 'Up the bank toward the Lamplighter’s, and past it. Small steps, wandering. Wet to the waist. I did not go after her. I should have.', after: 'night', cost: 1, effect: { type: 'lead', at: 'inn' } },
        { id: 'constance', q: 'Did Sister Constance come to the water?', a: 'Every Sunday after the last bell. She sat in skiff two and did not row. She told me once the reservoir was the only place on the hill where she could not hear herself think. I think she meant that kindly.' },
      ] },
    { id: 'agnes', at: 'laundry', name: 'Sister Agnes', role: 'laundress, Hill Laundry',
      intro: 'Sister Agnes. Every church robe and every sheet on the hill comes through my coppers. I see what people would rather I didn’t.',
      bio: 'Runs the laundry for the diocese. Knows the hill by its stains.',
      knows: ['sister', 'matron'],
      aboutLine: 'They send their linen here. You learn a lot from a person’s linen.',
      leadLine: 'A cassock came in at dawn with mud up to the knee and a tear at the shoulder. The bundle it came in was sent back to', leadAt: 'rectory',
      spentLine: 'The coppers are boiling. I’ve said my piece.',
      opinions: { sister: 'Beatrix Ayre’s things came to the laundry on Saturday morning from Marrow House. Wet through. Reservoir water. The Matron sent them herself.', matron: 'The Matron sends her own linen here. It is always clean. That is the strange thing.' },
      topics: [
        { id: 'night', q: 'A cassock came in at dawn.', a: 'From the Rectory. Mud to the knee, a tear at the right shoulder. The Canon’s size. Somebody in the Canon’s cassock was in the river.' },
        { id: 'tear', q: 'The tear.', a: 'Iron. Rust in the thread. Whoever wore it caught it on something iron and pulled hard. The cemetery railings are iron, and nothing else on that path is. I sent the bundle back to the Rectory with the tear mended. I should not have mended it.', after: 'night', cost: 1, effect: { type: 'lead', at: 'rectory' } },
        { id: 'constance', q: 'Did you know Sister Constance?', a: 'We were novices together. She rang and I washed. Thursday she brought me her own habit to wash and said, Agnes, I want to be clean for Sunday. I did not know what she meant. I do now.' },
      ] },
    { id: 'coyle', at: 'waterboard', name: 'Hettie Coyle', role: 'clerk, Ordell Water Board',
      intro: 'Coyle. Every gallon that leaves the reservoir goes in my book, and every key to the valves hangs behind me. One went out at ten to eleven last night and did not come back till three.',
      bio: 'Clerk at the Water Board for seven years. Nobody signs for a valve key without her seeing their hand.',
      knows: ['canon', 'driver'],
      aboutLine: 'They come for the valve key. You learn a person by how they sign for it.',
      leadLine: 'The valve key came back at three with somebody else’s initials in the book. That somebody walked out toward', leadAt: 'glasshouse',
      spentLine: 'The board is closed. Good night.',
      opinions: { canon: 'The Canon has a standing order for valve key three, for the Glasshouse water. He has never once used it himself. Nane signs for him.', driver: 'Miss Fay has never signed my book. She rides past the door twice a day and has never once looked in. Friday her car stood at the reservoir stop for half an hour with its lights off. I saw it from the back window.' },
      topics: [
        { id: 'night', q: 'Key three.', a: 'Out at ten to eleven against the Canon’s standing order, in the hand that always signs for him. Back at three in the morning, initialled by that same hand under its own name for once. Nobody waters anything at ten to eleven at night.' },
        { id: 'initials', q: 'Whose initials came back?', a: 'P.N. Peter Nane. He signs the Canon’s name for the Glasshouse water every month. On Saturday morning at three he signed his own, with his hands cut, and went up toward the Glasshouse.', after: 'night', cost: 1, effect: { type: 'lead', at: 'glasshouse' } },
        { id: 'constance', q: 'Did Sister Constance come to the Water Board?', a: 'Wednesday. She asked who had keys to the walkway. I read her the list. She wrote down one name and underlined it. I did not see which.' },
      ] },
  ],

  items: [
    { id: 'item:bell:sherry', at: 'rectory', kind: 'receipt', label: 'The Canon’s wine merchant, account',
      source: 'HARDACRE & SONS · WINE MERCHANTS', title: 'Account, the Rectory, April',
      body: ['Twelve of sherry, six of port, and a note from the merchant: “Canon — the crypt fund cheque was returned again. We must ask.” Mrs. Tull has watched him drink the twelve.'],
      spoken: 'The Canon’s wine account, and a note about a returned cheque.',
      reading: 'Mrs. Tull knows what the Canon drinks and how. It tells you something about him. Check his row in the Notebook.', about: ['canon'], effect: { type: 'suspectTrait', suspectId: 'canon' } },
    { id: 'item:bell:crypt-ledger', at: 'chapterhouse', kind: 'ledger', label: 'Crypt ledger, a page razored out', stamp: 'CONFIDENTIAL',
      source: 'THE CHAPTER HOUSE · CRYPT REGISTER', title: 'Interments and fees, this year',
      body: ['Plot forty-four: an interment in March, a fee of forty pounds, no name, and the page it was on razored out on Friday afternoon while the Canon had the book in his study. The stub is still in the binding, and Miss Pym knows which page it was because she gave the book to Constance on Wednesday.', 'Whoever cut it left a thumbprint in the glue.'],
      spoken: 'The crypt ledger with a page razored out on Friday afternoon, and a thumbprint in the glue.',
      reading: 'Somebody wanted plot forty-four forgotten. A red mark on the map shows where to look.', about: ['canon', 'gardener'], effect: { type: 'lead', at: 'cemetery' } },
    { id: 'item:bell:key-board', at: 'cottage', kind: 'photo', label: 'Photograph, the key board',
      source: 'HILL DIVISION · PHOTOGRAPHIC UNIT', title: 'Plate 3: the verger’s key board',
      body: ['Forty hooks, thirty-nine keys, and the empty hook labelled TOWER in the verger’s hand. In the flash, the verger himself, caught in the doorway, and something about him the constable did not notice at the time.'],
      spoken: 'A photograph of the key board with the tower hook empty, and the verger in the doorway.',
      reading: 'The camera flash caught the verger. It tells you something about him. Check his row in the Notebook.', about: ['verger'], effect: { type: 'suspectTrait', suspectId: 'verger' } },
    { id: 'item:bell:unposted', at: 'academy', kind: 'letter', label: 'Constance’s unposted letter', stamp: 'PERSONAL',
      source: 'FOUND IN A MASTER’S DESK, ORDELL ACADEMY', title: 'To the Dean, unposted',
      body: ['“…I must therefore report that Mr. Blake has been seen with the boys of the third form at the Observatory after lights out on three occasions, and that Dr. Quint has declined to say what they were shown. — C. Ayre.” Sealed, stamped, never posted, and found in the desk of the man it names.'],
      spoken: 'Constance’s letter to the Dean, sealed and never posted, found in Blake’s own desk.',
      reading: 'Blake had the letter that would have ruined him. A motive. Nothing to mark.', about: ['tutor', 'astro'], effect: { type: 'none' } },
    { id: 'item:bell:poisons', at: 'dispensary', kind: 'ledger', label: 'Poisons book, chloral', stamp: 'CONFIDENTIAL',
      source: 'HILL DISPENSARY · POISONS BOOK', title: 'Entries, April',
      body: ['Chloral hydrate, two drachms, signed S. CRAKE, for Marrow House, the 8th. Miss Lamb watched her sign, as she has watched her sign every month for eleven years.'],
      spoken: 'The poisons book: chloral for Marrow House, signed by the Matron on the eighth.',
      reading: 'Miss Lamb has watched the Matron sign for eleven years. It tells you something about her. Check her row in the Notebook.', about: ['matron'], effect: { type: 'suspectTrait', suspectId: 'matron' } },
    { id: 'item:bell:depot-sheet', at: 'depot', kind: 'ledger', label: 'Depot sign-out sheet',
      source: 'THE TRAM DEPOT · CARS', title: 'Sign-out, night of the 9th',
      body: ['Car 7 — out 23:45 — unsigned — back 01:20 — “wet”. The dispatcher did not sign it out and does not know how she got the key. He watched her bring it back, and what she did with her hands while he asked.'],
      spoken: 'The depot sheet: car seven out at a quarter to midnight, unsigned, back at twenty past one, wet.',
      reading: 'Marley watched Rosalind Fay bring the tram back. It tells you something about her. Check her row in the Notebook.', about: ['driver'], effect: { type: 'suspectTrait', suspectId: 'driver' } },
    { id: 'item:bell:valve-book', at: 'waterboard', kind: 'ledger', label: 'Valve key book',
      source: 'ORDELL WATER BOARD · KEYS', title: 'Valve keys, the 9th',
      body: ['Key 3 out at 22:50 against the Canon’s standing order, in the hand that always signs for him; returned 03:00, initialled P.N. The walkway it opens runs along the top of the reservoir wall, and the wet prints on it run one way.'],
      spoken: 'The valve key book: key three out at ten to eleven in the Canon’s name, and back at three initialled P.N.',
      reading: 'The wet footprints on the walkway go somewhere. A red mark on the map shows where.', effect: { type: 'lead', at: 'reservoir' } },
    { id: 'item:bell:crypt-tin', at: 'crypt', kind: 'report', label: 'The crypt fund, counted', stamp: 'CONFIDENTIAL',
      source: 'THE CRYPT · FUND BOX', title: 'Crypt restoration fund',
      fields: [['Should hold', '£412'], ['Holds', '£31'], ['Signatures on withdrawals', 'one, throughout']],
      body: ['Four hundred pounds gone from a box with one signature on every slip. Constance had asked to see the box on Thursday. On Friday she was dead.'],
      spoken: 'The crypt fund: four hundred pounds gone, one signature on every slip.',
      reading: 'A motive for the Canon, with a sum attached. Nothing to mark.', about: ['canon'], effect: { type: 'none' } },
    { id: 'item:bell:tower-view', at: 'watertower', kind: 'photo', label: 'Photograph from the Waterworks Tower',
      source: 'HILL DIVISION · PHOTOGRAPHIC UNIT', title: 'Plate 9: the bell tower, from the water tower',
      body: ['Taken at dawn with a long lens: the tower, the stair window, and on the outside of the tower a line of iron rungs the diocese had forgotten about, running from the ringing floor to the ground. The bottom rung is bright where the rust has been worn off tonight.'],
      spoken: 'A photograph from the water tower: iron rungs on the outside of the bell tower, the bottom one bright.',
      reading: 'The killer came down the outside of the tower on the iron rungs. Nothing to mark, but it changes who could have done it.', effect: { type: 'none' } },
    { id: 'item:bell:tea-glove', at: 'tearooms', kind: 'note', label: 'A glove left on a chair',
      source: 'TERRACE TEA ROOMS · LOST PROPERTY', title: 'One glove, left hand',
      body: ['A woman’s glove, left hand, grey kid, left on a chair after words at four in the morning. Mrs. Petty saw the hand that took it off. She also saw the hand it belonged to, and the difference.'],
      spoken: 'A left-hand glove, grey kid, left on a chair after words at four in the morning.',
      reading: 'Mrs. Petty saw the hands. It tells you something about Beatrix Ayre. Check her row in the Notebook.', about: ['sister'], effect: { type: 'suspectTrait', suspectId: 'sister' } },
    { id: 'item:bell:report-plates', at: 'bookshop', kind: 'clipping', label: 'Diocesan report, plates torn out',
      source: 'AMSEL’S BOOKS · SECOND-HAND', title: 'Diocesan Report, 1939, plates I–IV',
      body: ['The plates show the crypt, the tower, and the outside of the tower with its iron rungs — the only photograph anyone has of them. Torn out in the doorway tonight and carried off. What is left is a caption: “Rungs to be removed, 1940.” They were not.', 'Amsel knows who bought it and will save you the walk.'],
      spoken: 'A diocesan report with the plates of the tower torn out in the shop doorway.',
      reading: 'Amsel saw who bought it and where they went. Two hours back on the clock.', effect: { type: 'time', hours: -2 } },
    { id: 'item:bell:inn-slate', at: 'inn', kind: 'ledger', label: 'The Lamplighter’s slate',
      source: 'THE LAMPLIGHTER’S ARMS · SLATE', title: 'Tonight',
      body: ['Rudge chalks what the hill owes him. Tonight: “wet boots, two rums, no coin, said he had rung it and laughed.” No name. You will lose an hour finding out it was the drunk who says that every night.'],
      spoken: 'The Lamplighter’s slate: wet boots, two rums, and a man who said he had rung it and laughed.',
      reading: 'It was the drunk who says that every night. An hour wasted.', effect: { type: 'time', hours: 1 } },
  ],

  objects: [
    { id: 'obj:bell:key', at: 'reservoir', name: 'The tower key, with river mud on it', drawing: 'key',
      desc: 'Found on the reservoir walkway. This is the key to the bell tower. It has been in the water.',
      spoken: 'The bell tower key, on the reservoir walkway, with river mud on it.',
      unlocks: [
        { person: 'brannock', line: 'This is the key from the empty hook.', reply: 'It is. It went missing on Thursday. The verger lends it to a boy from the Academy. He thinks I don’t know. The boy meets a girl from Marrow House up there.',
          effect: { type: 'suspectTrait', suspectId: 'verger' } },
        { person: 'verger', line: 'Your key. Found in the reservoir.', reply: 'I lent it to a boy. Blake’s boy, the thin one. He was to bring it back by eleven. He didn’t. I was in my bed, Inspector. I found her at six and I washed the stairs because I could not look at them.',
          effect: { type: 'clear', suspectId: 'verger' } },
      ] },
    { id: 'obj:bell:rosary', at: 'boathouse', name: 'A rosary with a bent cross', drawing: 'rosary',
      desc: 'Found in the bottom of skiff two when the boatman pulled it in. The beads are still wet.',
      spoken: 'A rosary from the bottom of skiff two, the beads wet, the cross bent.',
      unlocks: [
        { person: 'sister', line: 'Is this yours?', reply: 'Mine. I dropped it in the boat, after the oars. I rowed across because the tram driver had gone and I could not walk past the gate. I stood under the tower at midnight. I counted nine. Then I ran.',
          effect: { type: 'clear', suspectId: 'sister' } },
        { person: 'agnes', line: 'Do you know this rosary?', reply: 'Beatrix Ayre’s. I mended the string for her in ’39, before they took her up the hill. She wears it round her wrist. If it came off, she was struggling with something.',
          effect: { type: 'suspectTrait', suspectId: 'sister' } },
      ] },
    { id: 'obj:bell:pass', at: 'asylum', name: 'A Marrow House visitor pass', drawing: 'card',
      desc: 'A visitor’s card for Marrow House, made out to B. Ayre. A patient does not need a visitor pass.',
      spoken: 'A Marrow House visitor pass, made out to B. Ayre.',
      unlocks: [
        { person: 'quaile', line: 'A patient with a visitor pass?', reply: 'Because she isn’t a patient. The Matron writes her up as one every month and takes the family’s money. I’ve watched the Matron sign that form for five years. I know her hand.',
          effect: { type: 'suspectTrait', suspectId: 'matron' } },
        { person: 'matron', line: 'Explain this.', reply: 'She sits down. Beatrix Ayre has never been ill. The family paid me to keep her. Constance came on Thursday and said it would stop. I was in my office at midnight, Inspector. Quaile brought me tea at twelve. Ask him.',
          effect: { type: 'clear', suspectId: 'matron' } },
      ] },
    { id: 'obj:bell:eyepiece', at: 'pawn', name: 'A telescope eyepiece, engraved H.Q.', drawing: 'eyepiece',
      desc: 'Pawned at Hobb’s by somebody who was not the astronomer.',
      spoken: 'A brass telescope eyepiece from the pawnshop, engraved H.Q.',
      unlocks: [
        { person: 'astro', line: 'Yours. Pawned on Tuesday.', reply: 'One of the boys took it. Blake’s third form. I let them use the telescope and one of them steals from me. I was at the eyepiece at midnight, Inspector. I saw the tower. I saw someone come down the outside. I drew them. I will not say who, because I am not sure.',
          effect: { type: 'clear', suspectId: 'astro' } },
        { person: 'hobb', line: 'Who pawned this?', reply: 'A schoolboy. Thin. Academy scarf. He said it was his father’s. Sister Constance came in on Wednesday and asked me to hold it until Friday and she would pay. Nobody has bought it out.',
          effect: { type: 'suspectTrait', suspectId: 'tutor' } },
      ] },
    { id: 'obj:bell:glove', at: 'tearooms', name: 'A grey glove, left hand', drawing: 'glove',
      desc: 'Left on a chair at the tea rooms after an argument at four in the morning.',
      spoken: 'A grey kid glove, left hand, from a chair in the tea rooms.',
      unlocks: [
        { person: 'petty', line: 'Whose glove?', reply: 'The younger Ayre girl’s. She argued with the Matron here at four. She took her gloves off to hold her tea and her hands shook so badly she left one behind.',
          effect: { type: 'suspectTrait', suspectId: 'sister' } },
        { person: 'tutor', line: 'Do you know this glove?', reply: 'Beatrix Ayre’s. She came to the Academy on Wednesday and asked me to give her sister a letter. I did. I have not told anyone that. I was at the Observatory at midnight with Dr. Quint and two boys. Ask her.',
          effect: { type: 'lead', at: 'observ' } },
      ] },
    { id: 'obj:bell:photo', at: 'bookshop', name: 'A photograph of the tower’s iron rungs', drawing: 'photo',
      desc: 'Torn from a diocese report. It shows iron rungs on the outside of the bell tower, from the top to the ground.',
      spoken: 'A photograph torn from a diocese report: iron rungs on the outside of the tower.',
      unlocks: [
        { person: 'amsel', line: 'Who bought the report?', reply: 'A man who tore the pages out in my doorway and ran. He wanted the only photograph of those rungs to disappear. He had scratched hands and river mud on his shoes. Whoever came down those rungs went into the water after.',
          effect: { type: 'culpritTrait' } },
        { person: 'canon', line: 'These rungs were supposed to be removed in 1940.', reply: 'I never had them removed. There was no money. There is never money. I could not climb them if you paid me, Inspector. Look at me.',
          effect: { type: 'suspectTrait', suspectId: 'canon' } },
      ] },
  ],
  story: {
    backstory: [
      'Sister Constance Ayre was forty-four. She had rung the bell of St. Ordell’s for twenty years. Twelve strokes at midnight, every night, for a hundred and four years before her and twenty with her. She never missed one.',
      'Nine years ago her younger sister Beatrix was put into Marrow House asylum. The family paid for the bed. Constance signed the papers. Three days before she died, Beatrix walked out of Marrow House and came up the hill.',
      'In her last week Constance asked to see the crypt account books, the Marrow House register, and a letter she had written to the Dean about a schoolmaster. She was putting things right. On the hill, that is dangerous.',
      'At midnight on Friday the bell rang nine times. Nine is how many years Beatrix was locked away. By six in the morning Constance was dead at the bottom of the tower stairs, and the bell rope had been cut from the ringing floor.',
    ],
    timeline: [
      { time: '10:00 PM', text: 'The Academy gates are locked. Somebody has a key that is not the porter’s.' },
      { time: '10:50 PM', text: 'A valve key is signed out at the Water Board in the Canon’s name. Nobody waters anything at that hour.' },
      { time: '11:00 PM', text: 'A schoolboy on the reservoir path has the tower key taken out of his pocket by a man whose face he cannot see.' },
      { time: '11:30 PM', text: 'Sister Constance comes for the tower key. It is not on its hook. She goes up anyway; the door is already unlocked.' },
      { time: '11:40 PM', text: 'The Marrow House gate is logged open. Beatrix Ayre goes out carrying a bag.' },
      { time: '11:45 PM', text: 'Tram car 7 leaves the depot, unsigned, lights off, for the Marrow House gate.' },
      { time: '11:58 PM', text: 'The pump house engines are stopped for four minutes, ‘to listen’.' },
      { time: '12:00 AM', text: 'The bell rings nine times, rung by somebody who does not know how. Beatrix counts them from the Close Green.' },
      { time: '12:04 AM', text: 'The Observatory log says ‘tower’. The astronomer sees somebody climb down the outside of it and go toward the reservoir.' },
      { time: '12:05 AM', text: 'The Canon goes out by the Rectory garden door toward the cemetery. He is back at a quarter to one, mud to the knee.' },
      { time: '12:20 AM', text: 'Plot forty-four is dug up. The tin box is left. What was in it is not.' },
      { time: '12:30 AM', text: 'It begins to rain. A tram stands at the reservoir stop with its lights off.' },
      { time: '12:40 AM', text: 'Skiff two leaves the wall stage without a tally, rowed badly.' },
      { time: '1:00 AM', text: 'Somebody crosses the reservoir wall with the valve key and a bag. The Marrow House gate is closed again. A letter reaches the Dean by hand.' },
      { time: '1:30 AM', text: 'A man with cut hands and wet boots drinks two rums at the Lamplighter’s and says he rang it.' },
      { time: '3:00 AM', text: 'The valve key comes back to the Water Board, initialled P.N.' },
      { time: '4:00 AM', text: 'Two women argue in the tea rooms. A glove is left on a chair.' },
      { time: '6:00 AM', text: 'The verger finds Sister Constance at the foot of the stairs.' },
    ],
    truth: [
      'Peter Nane signed the valve key out at ten to eleven, took the tower key from the schoolboy on the reservoir path at eleven, and was at the top of the two hundred and eleven steps when Constance came up to ring twelve.',
      'He struck her from behind, cut the rope so nobody could ring for help, and then rang nine himself, badly, with the cut end. He thought it was what Beatrix wanted. He had taken her flowers every Sunday for four years and built a whole life out of it that she knew nothing about.',
      'He came down the iron rungs on the outside of the tower, cutting his hands, dug up the Canon’s tin box on the way past the cemetery, crossed the reservoir wall at one with the valve key and four hundred pounds in a bag, and was drinking at the Lamplighter’s by half past one, saying he had rung it, and laughing. He spent the rest of the night trying to make the rungs disappear and the money go unnoticed, and failed at both.',
      'The Canon heard nine, went out to move his money and found it gone; he tore his cassock on the cemetery railings and wrote to the Dean. Rosalind Fay drove Beatrix to the Green for five pounds and sat on the reservoir wall in the rain to see who came along it. Neither of them killed anybody.',
      'Beatrix Ayre stood under the tower at midnight and counted the bells. She thought her sister was ringing nine for her. She thought it was an apology. She has not been told otherwise. You should be the one to tell her.',
    ],
  },

  epilogue: {
    win: `They ring twelve at midnight again, and the hill pretends that settles it. You stand in
      the wet grass under two hundred and eleven steps of cold stone and count to nine, once, for
      Constance Ayre. Then you go home.`,
    loss: `The diocese gets its discretion. ‘Accidental fall,’ says the certificate, on stairs that
      turn the wrong way. The bell rings twelve. Somebody on this hill hears nine every night for
      the rest of their life. It is not you.`,
  },
};

export default def;
