import type { CaseDef } from '../../types/game-types';

// The Ninth Bell. Cathedral Hill: thirty locations from the tower down to the
// water, twenty people who will talk if the diocese does not hear about it,
// and twenty-six documents, most of them written by people who were lying.

const def: CaseDef = {
  id: 'bell',
  title: 'The Ninth Bell',
  subtitle: 'Cathedral Hill · April 1948',
  tagline: 'The bell rang nine times at midnight. By morning the bell-ringer was dead at the foot of her tower.',
  victim: 'Sister Constance Ayre',
  scene: 'tower',
  difficultyHint: 'Everyone on this hill is lying about something.',
  publicTraits: ['build', 'hair'],
  traitPool: ['hand', 'mark', 'vice', 'scent', 'shoe'],

  briefing: `At midnight the bell of St. Ordell’s rang nine times. It has rung twelve at midnight
    for a hundred and four years. At six in the morning the verger found Sister Constance Ayre
    at the bottom of the tower stairs. Her keys were still in her hand. The back of her skull was open.
    She did not fall. The stairs turn the wrong way for that. Somebody climbed two hundred and
    eleven steps in the dark to ring a number that means something to one person on this hill.
    Find out who counts to nine.`,

  radio: [
    'Hill Division. The diocese has asked for discretion. Note the request. Ignore it.',
    'Marrow House asylum logged its gate open at eleven-forty and closed again at one.',
    'The bell rope was cut clean. Whoever went up did not come down the stairs.',
  ],

  terrain: {
    sea: false, river: true, riverSource: 0.18, riverMouth: 0.5,
    lakeAt: 'reservoir', lakeName: 'THE RESERVOIR', parks: 3,
    districts: [
      { text: 'CATHEDRAL HILL', x: 300, y: 10, rot: -3 },
      { text: 'THE CLOSE', x: 560, y: 380, rot: 2 },
      { text: 'THE TERRACES', x: 960, y: 60, rot: 3 },
      { text: 'LOWER ORDELL', x: 230, y: 780, rot: -2 },
      { text: 'THE WATER', x: 900, y: 740, rot: 2 },
    ],
  },

  locations: [
    // ---- Cathedral Hill
    { id: 'tower', name: 'The Bell Tower', type: 'church', x: 470, y: 110, district: 'Cathedral Hill', desc: 'Two hundred and eleven steps, and a bell rope cut clean through.' },
    { id: 'rectory', name: 'The Rectory', type: 'manor', x: 226, y: 158, district: 'Cathedral Hill', desc: 'Sherry, silence, and a fire that is always already lit.' },
    { id: 'chapterhouse', name: 'The Chapter House', type: 'library', x: 330, y: 260, district: 'Cathedral Hill', desc: 'Four hundred years of parish records, and an archivist who has read all of them.' },
    { id: 'almshouse', name: 'The Almshouse', type: 'home', x: 170, y: 340, district: 'Cathedral Hill', desc: 'Forty beds, thirty-nine names, and a register nobody trusts.' },
    { id: 'deanery', name: 'Diocesan Office', type: 'office', x: 360, y: 50, district: 'Cathedral Hill', desc: 'Where the diocese asks for discretion, in writing, on headed paper.' },
    { id: 'foundry', name: 'Ordell Bell Foundry', type: 'factory', x: 110, y: 70, district: 'Cathedral Hill', desc: 'Cast the bell in 1844. Knows every crack in it since.' },
    // ---- The Close
    { id: 'division', name: 'Hill Division', type: 'police', x: 480, y: 330, district: 'The Close', desc: 'Three constables and a kettle. Yours, for now.' },
    { id: 'cottage', name: 'Verger’s Cottage', type: 'home', x: 570, y: 200, district: 'The Close', desc: 'Every key on the hill hangs on a board in the kitchen. One hook is empty.' },
    { id: 'green', name: 'The Close Green', type: 'park', x: 640, y: 270, district: 'The Close', desc: 'Wet grass, a sundial, and a clear view of the tower door.' },
    { id: 'academy', name: 'Ordell Academy', type: 'school', x: 716, y: 140, district: 'The Close', desc: 'Boys in grey uniforms, out of bed, and nobody counting them.' },
    { id: 'cemetery', name: 'Ordell Cemetery', type: 'cemetery', x: 322, y: 490, district: 'The Close', desc: 'Fresh earth on plot forty-four. Nobody was buried there this month.' },
    { id: 'dispensary', name: 'Hill Dispensary', type: 'shop', x: 600, y: 430, district: 'The Close', desc: 'The only chemist on the hill, and the only poisons book.' },
    // ---- The Terraces
    { id: 'observ', name: 'The Observatory', type: 'light', x: 898, y: 252, district: 'The Terraces', desc: 'One telescope pointed at the sky. One window pointed at the hill.' },
    { id: 'glasshouse', name: 'The Glasshouse', type: 'market', x: 656, y: 340, district: 'The Terraces', desc: 'Orchids and orange trees under forty tons of glass.' },
    { id: 'asylum', name: 'Marrow House', type: 'hospital', x: 872, y: 450, district: 'The Terraces', desc: 'The gate was logged open at eleven-forty. That is all they will tell you.' },
    { id: 'inn', name: 'The Lamplighter’s Arms', type: 'bar', x: 780, y: 380, district: 'The Terraces', desc: 'The only pub on the hill, and the only place the hill says what it thinks.' },
    { id: 'villa', name: 'The Quint Villa', type: 'manor', x: 1010, y: 150, district: 'The Terraces', desc: 'The astronomer’s house. Every curtain open, every light off.' },
    { id: 'bookshop', name: 'Amsel’s Books', type: 'shop', x: 960, y: 340, district: 'The Terraces', desc: 'Second-hand books, damp, and the only shop that stocks the diocese’s reports.' },
    { id: 'tearooms', name: 'Terrace Tea Rooms', type: 'cafe', x: 1040, y: 430, district: 'The Terraces', desc: 'Where the hill takes its gossip with milk and two sugars.' },
    // ---- Lower Ordell
    { id: 'depot', name: 'The Tram Depot', type: 'tram', x: 164, y: 590, district: 'Lower Ordell', desc: 'The last tram up the hill leaves at eleven. Somebody signed one out at midnight.' },
    { id: 'pawn', name: 'Hobb’s Pawn', type: 'shop', x: 220, y: 470, district: 'Lower Ordell', desc: 'A rosary, a telescope lens, and a set of keys on a church key-ring.' },
    { id: 'mission', name: 'Lower Chapel', type: 'church', x: 290, y: 630, district: 'Lower Ordell', desc: 'The poor parish. Their bell is a handbell, and it rang at midnight too.' },
    { id: 'laundry', name: 'Hill Laundry', type: 'factory', x: 100, y: 710, district: 'Lower Ordell', desc: 'Every sheet and church robe on the hill, washed by nuns who see the stains.' },
    { id: 'tallow', name: 'Tallow Street', type: 'home', x: 380, y: 730, district: 'Lower Ordell', desc: 'Where the hill’s servants sleep, when they are allowed to.' },
    { id: 'waterboard', name: 'Ordell Water Board', type: 'office', x: 520, y: 610, district: 'Lower Ordell', desc: 'Every gallon that leaves the reservoir is written down here. So is every key to the valves.' },
    // ---- The Water
    { id: 'reservoir', name: 'The Reservoir', type: 'bridge', x: 614, y: 560, district: 'The Water', desc: 'Black water behind a wall, and a walkway nobody is supposed to use.' },
    { id: 'boathouse', name: 'Reservoir Boathouse', type: 'pier', x: 760, y: 520, district: 'The Water', desc: 'Two rowing boats, one missing its oars, and a boatman who keeps count.' },
    { id: 'pumphouse', name: 'The Pump House', type: 'factory', x: 720, y: 670, district: 'The Water', desc: 'The engines run all night, loud enough to cover a bell. Almost.' },
    { id: 'crypt', name: 'The Crypt', type: 'bank', x: 888, y: 630, district: 'The Water', desc: 'Four hundred years of the church’s dead, and its account books.' },
    { id: 'watertower', name: 'Waterworks Tower', type: 'tower', x: 1000, y: 570, district: 'The Water', desc: 'The second-highest point on the hill. From the top you can see the highest.' },
  ],
  edges: [
    ['tower', 'rectory'], ['tower', 'deanery'], ['tower', 'cottage'], ['tower', 'chapterhouse'],
    ['rectory', 'almshouse'], ['rectory', 'foundry'], ['rectory', 'chapterhouse'],
    ['deanery', 'foundry'], ['deanery', 'academy'],
    ['chapterhouse', 'division'], ['chapterhouse', 'almshouse'],
    ['almshouse', 'pawn'], ['almshouse', 'depot'],
    ['cottage', 'green'], ['cottage', 'academy'],
    ['green', 'division'], ['green', 'glasshouse'],
    ['academy', 'villa'], ['academy', 'observ'],
    ['observ', 'villa'], ['observ', 'glasshouse'], ['observ', 'bookshop'],
    ['villa', 'tearooms'],
    ['bookshop', 'tearooms'], ['bookshop', 'asylum'],
    ['tearooms', 'asylum'], ['tearooms', 'watertower'],
    ['glasshouse', 'inn'], ['glasshouse', 'division'],
    ['inn', 'asylum'], ['inn', 'boathouse'],
    ['division', 'cemetery'], ['division', 'dispensary'],
    ['dispensary', 'reservoir'], ['dispensary', 'inn'],
    ['cemetery', 'pawn'], ['cemetery', 'mission'], ['cemetery', 'waterboard'],
    ['pawn', 'depot'],
    ['depot', 'laundry'], ['depot', 'mission'],
    ['mission', 'tallow'],
    ['laundry', 'tallow'],
    ['tallow', 'waterboard'],
    ['waterboard', 'reservoir'],
    ['reservoir', 'boathouse'], ['reservoir', 'pumphouse'],
    ['boathouse', 'crypt'],
    ['pumphouse', 'crypt'],
    ['asylum', 'crypt'], ['asylum', 'watertower'],
    ['crypt', 'watertower'],
  ],
  start: 'division',

  suspects: [
    { id: 'verger', name: 'Cormac Ill', role: 'The verger',
      blurb: 'Found the body. Had washed the stairs before we arrived.',
      motive: 'because she had started asking what he does with the keys at night.',
      bio: 'Fifty-nine. Verger of St. Ordell’s for thirty years. He holds every key on the hill. He found Sister Constance at six and had scrubbed the stairs by seven.',
      alibi: 'Asleep in the verger’s cottage. Nobody can confirm it.',
      secret: 'He lends the tower key to a boy from the Academy who meets a girl from Marrow House up there. The tower key was not on its hook that night because the boy had it.',
      opinions: { canon: 'The Canon is a good man with a bad ledger. I have kept his keys for twenty years. I have never kept his books.', matron: 'The Matron comes to Mass and sits at the back. She looks at the Ayre pew the whole time.', tutor: 'Mr. Blake takes the boys up the tower to see the view. I let him. I should not have.', astro: 'Dr. Quint looks at the tower more than she looks at the sky. She told me so herself.', gardener: 'Nane digs when Grimm is drunk. He dug on Tuesday. Nobody had died on Tuesday.', driver: 'Miss Fay drives the last tram and drives it too fast. She was not on it at midnight. Somebody else was.', sister: 'The younger Ayre girl came to the tower door on Wednesday and asked for her sister. I said no. I have thought about that no every hour since.' },
      topics: [
        { id: 'night', q: 'Where were you at midnight?', a: 'In my bed in the cottage. I heard the bell. I counted nine and I thought I had miscounted. I went back to sleep. God forgive me.' },
        { id: 'stairs', q: 'You washed the stairs before we came.', a: 'I did. I found her at six and I could not leave her like that. I know what I did. I would do it again.' },
        { id: 'key', q: 'The tower key was not on its hook.', a: 'He looks at his hands. I lend it out. To a boy from the school. He meets a girl up there. I thought it was harmless. I think about that word now.', after: 'night', cost: 1, effect: { type: 'suspectTrait', suspectId: 'verger' } },
        { id: 'boy', q: 'Which boy?', a: 'Blake’s third form. The tall one. He was to bring the key back by eleven. He did not. He has not come near me since.', after: 'key', cost: 1, effect: { type: 'lead' } },
        { id: 'constance', q: 'What was Sister Constance like?', a: 'Exact. She rang twelve strokes for twenty years and never one more or less. She counted everything. She had started counting the Canon’s money.' },
      ] },
    { id: 'canon', name: 'Canon Aldritch', role: 'Canon of St. Ordell’s',
      blurb: 'Says he slept through it. His bedroom window faces the tower.',
      motive: 'because the crypt account books do not survive an honest reading.',
      bio: 'Sixty-four. Canon for twenty years. He runs the crypt restoration fund. Four hundred pounds is missing from it and every withdrawal slip has his signature. Sister Constance asked to see the fund box on Thursday.',
      alibi: 'Asleep in the Rectory. His housekeeper will confirm his light went out at eleven.',
      secret: 'He took the money. Not for himself. For a woman in the city and a child who has his eyes and not his name.',
      opinions: { verger: 'Cormac Ill has kept my keys for thirty years and never once asked what they opened.', matron: 'Matron Crake and I have an understanding about the Ayre girl. I am not proud of it.', tutor: 'Mr. Blake is a good teacher with poor judgement about the hours he keeps.', astro: 'Dr. Quint sees everything from that Observatory. She has never come to confession. I wish she would.', gardener: 'Nane does what he is told and does not ask. That is why I asked him.', driver: 'Miss Fay is a good girl who needs money. Most sins on this hill start there.', sister: 'Beatrix Ayre should never have been put away. I signed the papers. Constance signed them too. We both knew.' },
      topics: [
        { id: 'night', q: 'Where were you at midnight?', a: 'Asleep. Mrs. Tull will tell you my light went out at eleven. I did not hear the bell. I am told it rang nine. I have no idea what that means.' },
        { id: 'fund', q: 'Four hundred pounds is missing from the crypt fund. Every slip has your signature.', a: 'He goes very still. Yes. I took it. Constance asked to see the box on Thursday. I said Monday. There was not going to be a Monday.' },
        { id: 'where', q: 'Where did the money go?', a: 'To a woman in the city. And a child. He has my eyes and not my name. I buried the money in a tin box on Tuesday because Constance was coming and I panicked. I am a foolish old man, not a murderer.', after: 'fund', cost: 1, effect: { type: 'suspectTrait', suspectId: 'canon' } },
        { id: 'box', q: 'The box is empty now.', a: 'Somebody dug it up on Friday night. Somebody who knew where it was. Only Nane knew where it was. And whoever Nane told.', after: 'where', cost: 1, effect: { type: 'lead' } },
        { id: 'constance', q: 'Tell me about her.', a: 'The best of us. She rang the bell for twenty years and never asked for a thing. Then she asked for the books. She was going to put everything right. On this hill, that is the one thing nobody can afford.' },
      ] },
    { id: 'matron', name: 'Matron Sybil Crake', role: 'Marrow House',
      blurb: 'Logged the asylum gate open at eleven-forty. Will not say who went through it.',
      motive: 'because one of her patients is not really a patient, and Constance had worked it out.',
      bio: 'Fifty. Matron of Marrow House asylum for eleven years. She keeps one bed for a patient who has never been ill: Beatrix Ayre, Constance’s sister, kept there on the family’s money.',
      alibi: 'In her office at Marrow House all night. The orderly saw her.',
      secret: 'She has kept Beatrix Ayre locked up for nine years knowing there was nothing wrong with her. The Ayre family paid. She stopped asking why long ago.',
      opinions: { verger: 'The verger let my patient up the tower. Then he lets a schoolboy up it. The man will lend anyone a key.', canon: 'The Canon pays the Ayre bill on the family’s behalf. Late. Every quarter.', tutor: 'Mr. Blake brought a boy to my gate on Wednesday. The boy had a letter for Beatrix. I did not take it.', astro: 'Dr. Quint signs for chloral at the dispensary. For sleep, she says. Astronomers do not sleep.', gardener: 'Nane brings the Glasshouse flowers to my wards on Sundays. He stays longer than flowers take.', driver: 'Miss Fay drove one of my patients away at midnight. I have not reported it. I should have.', sister: 'Beatrix Ayre is not ill. She has never been ill. I have written her up as ill every month for nine years.' },
      topics: [
        { id: 'night', q: 'Where were you at midnight?', a: 'In my office. Quaile brought me tea at twelve. The gate was open. I logged it open. I did not go through it.' },
        { id: 'gate', q: 'Who went through the gate at eleven-forty?', a: 'She does not answer for a long time. Beatrix. With a bag. I let her go because her sister had told me on Thursday it would stop. I thought that meant she was going home.' },
        { id: 'beatrix', q: 'Is Beatrix Ayre ill?', a: 'No. Never. The family paid for a bed and I gave them one. Constance signed the papers nine years ago. On Thursday she came to unsign them. I told her there was no such thing.', after: 'gate', cost: 1, effect: { type: 'suspectTrait', suspectId: 'matron' } },
        { id: 'bag', q: 'What was in the bag?', a: 'Her things. And a rosary. And a letter from a schoolmaster that I did not read. She went down the hill toward the tram depot.', after: 'beatrix', cost: 1, effect: { type: 'lead' } },
      ] },
    { id: 'tutor', name: 'Mr. Ewan Blake', role: 'Master at Ordell Academy',
      blurb: 'His boys were out of bed. He cannot say where he was.',
      motive: 'because she wrote a letter to the Dean about him and never posted it.',
      bio: 'Thirty-four. Teaches the third form at the Academy. Takes boys to the Observatory after lights-out. Sister Constance wrote a letter to the Dean about it. The letter was found in his desk.',
      alibi: 'Marking papers in his rooms at the Academy. Alone.',
      secret: 'He was at the Observatory with two boys and Dr. Quint, looking at Saturn. That is all it was. He knows nobody will believe that is all it was.',
      opinions: { verger: 'The verger lends the tower key to my boys. I have asked him to stop. He says it keeps them out of the pub.', canon: 'The Canon does not like me. He liked Constance. I understand both.', matron: 'Matron Crake would not take a letter from me at her gate. She looked at me like I was the one locked up.', astro: 'Halla Quint shows my boys Saturn on clear nights. That is all it is. Nobody will believe that is all it is.', gardener: 'Nane digs for the Canon. Graves and other things.', driver: 'Miss Fay drives my boys down the hill on Saturdays and back on Sundays and pretends not to know their names.', sister: 'Beatrix Ayre came to the school on Wednesday and gave me a letter for her sister. I gave it to Constance. Constance cried.' },
      topics: [
        { id: 'night', q: 'Where were you at midnight?', a: 'In my rooms, marking papers. Alone. He looks at the floor. That is not true. I was at the Observatory.' },
        { id: 'observatory', q: 'With whom?', a: 'Dr. Quint and two boys. Looking at Saturn. It was clear for ten minutes at midnight. We heard the bell. We counted nine. Quint went to the eyepiece and turned it on the tower.', after: 'night', cost: 1, effect: { type: 'suspectTrait', suspectId: 'tutor' } },
        { id: 'letter', q: 'Constance wrote to the Dean about you. The letter was in your desk.', a: 'She gave it to me. On Thursday. She said, I wrote this and I am not sending it, and I want you to know what I could have done. That is the kind of woman she was.' },
        { id: 'boy', q: 'One of your boys had the tower key.', a: 'Harris. He meets a girl from Marrow House up there. He did not bring the key back on Friday because somebody took it from him on the path. He would not say who. He is fifteen and terrified.', after: 'observatory', cost: 1, effect: { type: 'lead' } },
      ] },
    { id: 'astro', name: 'Dr. Halla Quint', role: 'Astronomer',
      blurb: 'Was awake. Was watching. Refuses to say what.',
      motive: 'because through that telescope she had seen something she could not unsee.',
      bio: 'Forty-one. Runs the Observatory. At midnight her telescope was not pointed at the sky. Her log says ‘tower’. Twice.',
      alibi: 'At the Observatory all night, observing. Her log shows it.',
      secret: 'She watched somebody climb down the outside of the tower at four minutes past midnight. She drew them in the margin of her log. She has not said who, because she is not sure, and she will not guess at a hanging.',
      opinions: { verger: 'The verger climbs the tower every day and has never once looked up.', canon: 'The Canon’s window faces the tower. His curtains were closed at midnight. They are never closed.', matron: 'The Matron keeps a patient who is not a patient. Constance told me. She told me a lot, at the end.', tutor: 'Ewan Blake was in my dome at midnight with two of his boys. I will say that in court. Nobody will believe it.', gardener: 'Nane was in the Glasshouse until two. I can see the Glasshouse from here. The boiler light was on.', driver: 'The tram went up the hill at midnight with its lights off. I saw it. Miss Fay was driving.', sister: 'Beatrix Ayre stood on the Close Green at midnight, looking up at the tower. I saw her through the glass. She was counting.' },
      topics: [
        { id: 'night', q: 'Your log says ‘tower’ at midnight. Not the sky.', a: 'The bell rang nine. I turned the telescope. I saw the tower door. Then I saw someone on the outside of the tower, on the iron rungs, coming down.' },
        { id: 'who', q: 'Who?', a: 'I do not know. A figure in dark clothes. I drew what I saw. I will not put a name to a drawing when the name means a rope. Ask me anything else.' },
        { id: 'rungs', q: 'Describe what you saw.', a: 'She takes a breath. Someone who came down fast. Someone who knew the rungs were there. At the bottom they went toward the reservoir, not the Close. They did not look back once.', after: 'who', cost: 1, effect: { type: 'culpritTrait' } },
        { id: 'chloral', q: 'You sign for chloral at the dispensary.', a: 'For sleep. I cannot sleep. I have not slept properly since Wednesday, when Constance told me what this hill has been doing to her sister.', cost: 1, effect: { type: 'suspectTrait', suspectId: 'astro' } },
      ] },
    { id: 'gardener', name: 'Peter Nane', role: 'Glasshouse gardener',
      blurb: 'Glasshouse gardener. Dug grave forty-four. Nobody is buried in it. Takes flowers to Marrow House every Sunday.',
      motive: 'because Constance signed Beatrix away, and four years of Sundays with flowers had made Beatrix his to avenge.',
      bio: 'Twenty-eight. Gardener at the Glasshouse. Digs graves for the parish when the gravedigger is drunk. He dug plot forty-four three days before anyone died.',
      alibi: 'Stoking the Glasshouse boilers until two. Then asleep in the potting shed.',
      secret: 'He took the tower key from the boy on the reservoir path. He was waiting at the top of the stairs when Constance came up. He rang nine for Beatrix, because he thought it was what she wanted, and came down the outside on the rungs.',
      opinions: { verger: 'The verger tells me where to dig. He does not tell me why.', canon: 'The Canon paid me two pounds to dig a hole on Tuesday and asked me not to tell Grimm.', matron: 'The Matron lets me bring flowers on Sundays. I bring them for one patient. She knows which.', tutor: 'Mr. Blake had a boy with him at the Glasshouse on Friday. The boy had been crying.', astro: 'Dr. Quint sends down for orchids for the dome. She says the cold kills them. It does.', driver: 'Rosalind drives me down the hill on Saturdays. She talks about leaving. She never leaves.', sister: 'Beatrix. I have taken her flowers every Sunday for four years. She is not mad. She is angry. There is a difference.' },
      topics: [
        { id: 'night', q: 'Where were you at midnight?', a: 'At the Glasshouse. Stoking. Lister will tell you. I heard the bell. I counted nine. I sat down on the coal.' },
        { id: 'grave', q: 'You dug plot forty-four on Tuesday.', a: 'For the Canon. He said dig a hole four feet deep and do not tell Grimm. He put a tin box in it. I filled it in. That is all I did.' },
        { id: 'box', q: 'The box is empty now.', a: 'He rubs his face. I told one person where it was. I should not have. I told her because she asked me, and I have never said no to her.', after: 'grave', cost: 1, effect: { type: 'suspectTrait', suspectId: 'gardener' } },
        { id: 'her', q: 'Who did you tell?', a: 'Beatrix. On Sunday. I told her the Canon had buried money in the cemetery. I thought it would make her laugh. She did not laugh.', after: 'box', cost: 1, effect: { type: 'lead' } },
      ] },
    { id: 'driver', name: 'Rosalind Fay', role: 'Tram driver',
      blurb: 'Signed a tram out of the depot at midnight and brought it back wet.',
      motive: 'because the last tram up the hill carried a passenger she was paid to forget.',
      bio: 'Twenty-nine. Drives the hill tram. She took a car out at two minutes past midnight without permission and brought it back at ten to one, wet.',
      alibi: 'Home in bed. The car went out; she says she did not take it.',
      secret: 'She drove Beatrix Ayre from Marrow House to the Close Green at midnight, for five pounds and a promise. She has not been paid.',
      opinions: { verger: 'The verger rides my tram to the depot every Saturday to drink where nobody knows him. Everybody knows him.', canon: 'The Canon has never been on a tram in his life. He sent his housekeeper down with an envelope for me once.', matron: 'The Matron pays me to forget who I drive from Marrow House. Then she forgets to pay.', tutor: 'Mr. Blake rides with his boys and looks out of the window the whole way so he does not have to talk to them.', astro: 'Dr. Quint rides up at dusk and down at dawn and never once sits down.', gardener: 'Peter Nane talks about the Ayre girl the whole way down the hill. I have told him it is no use. He knows.', sister: 'I drove Beatrix Ayre up the hill at midnight with the lights off. She sat with a rosary round her wrist and did not speak.' },
      topics: [
        { id: 'night', q: 'Car seven went out at two minutes past midnight.', a: 'It did. I was in bed. She looks away. No. I took it. I drove somebody up the hill with the lights off for five pounds and I have not been paid.' },
        { id: 'who', q: 'Who did you drive?', a: 'Beatrix Ayre. From the Marrow House gate to the Close Green. She got out and stood on the grass and looked up at the tower. I waited. Then I did not wait.', after: 'night', cost: 1, effect: { type: 'suspectTrait', suspectId: 'driver' } },
        { id: 'wet', q: 'The car came back wet.', a: 'I went down to the reservoir after. To think. I sat on the wall. Somebody came along the walkway at one with a key and a bag and did not see me. I saw them.', after: 'who', cost: 1, effect: { type: 'lead' } },
        { id: 'paid', q: 'Who promised the five pounds?', a: 'A note under the depot door. Five pounds to drive a patient to the Green at midnight, no questions. Handwriting like a schoolboy’s. I needed the money. I always need the money.' },
      ] },
    { id: 'sister', name: 'Sister Beatrix Ayre', role: 'The victim’s sister',
      blurb: 'Arrived on the hill three days ago. Has not said why.',
      motive: 'because nine is how many years Constance let her rot in Marrow House.',
      bio: 'Thirty-six. Constance’s younger sister. She has been a patient at Marrow House for nine years. Three days ago she walked out. She says she was released. Marrow House says nothing.',
      alibi: 'In her bed at Marrow House. The gate log says otherwise.',
      secret: 'She went out through the gate at eleven-forty and was driven to the Close Green. She stood under the tower at midnight and counted the bells. She had rung nine to her sister through the walls of Marrow House every night for nine years.',
      opinions: { verger: 'The verger would not let me up the tower on Wednesday. He said Constance had told him not to. She had not.', canon: 'The Canon signed the papers that put me away. He signed them in green ink. I have thought about that green ink for nine years.', matron: 'Matron Crake is not cruel. That would be easier. She is careful.', tutor: 'Mr. Blake gave my letter to my sister. He is the only person on this hill who did what I asked.', astro: 'The astronomer watched me from her dome at midnight. I saw the lens catch the light. I waved. She did not wave back.', gardener: 'Peter brings me flowers. He told me where the Canon buried his money. I did not dig it up. I wanted to.', driver: 'Rosalind drove me up the hill. I promised her five pounds I do not have. I will pay her when I have it.' },
      topics: [
        { id: 'night', q: 'Where were you at midnight?', a: 'On the Close Green, under the tower. Looking up. The bell rang nine. I thought it was for me. I thought she was saying sorry.' },
        { id: 'nine', q: 'Why nine?', a: 'Nine years. Every night in Marrow House I rang nine on the water pipe with a spoon, so she would hear it up the hill. She never heard. I thought at midnight she finally had.' },
        { id: 'after', q: 'What did you do after the bell?', a: 'She looks at her hands. I ran. Down to the reservoir. I took a boat. I lost my rosary and the oars and I rowed with my hands. I was on the far bank when the sun came up.', after: 'night', cost: 1, effect: { type: 'suspectTrait', suspectId: 'sister' } },
        { id: 'saw', q: 'Did you see anyone at the tower?', a: 'Somebody on the outside of it. On the rungs. Coming down fast, while the ninth bell was still ringing. They went the other way from me. Toward the pump house.', after: 'after', cost: 1, effect: { type: 'lead' } },
        { id: 'letter', q: 'You sent your sister a letter.', a: 'Through Mr. Blake. It said: I know you signed it. I know why. Ring nine for me once and I will forgive you. She rang nine. Somebody rang nine.' },
      ] },
  ],

  culprit: 'gardener',

  witnesses: [
    { id: 'tull', at: 'rectory', name: 'Ivy Tull', role: 'housekeeper, the Rectory',
      intro: 'Mrs. Tull. I keep the Canon’s house. I know who comes to his door and what they want from him.',
      bio: 'Housekeeper at the Rectory for twenty-five years. She pours the Canon’s sherry and counts the glasses.',
      knows: ['canon', 'verger', 'sister'],
      aboutLine: 'They take tea in this house. I’ve poured it and I’ve watched.',
      leadLine: 'Somebody came down the hill in the dark and left through the garden. There were footprints toward',
      spentLine: 'The Canon wouldn’t want me talking. Neither do I.',
      opinions: { canon: 'The Canon’s light went out at eleven. It came on again at half past twelve. He was not in his bed. His curtains were shut.', verger: 'Cormac Ill came to the kitchen door at half past six with his hands red from scrubbing and said, she has fallen. She had not fallen.', sister: 'The younger Miss Ayre came to this door on Wednesday and asked for the Canon. He would not see her. I gave her tea in the kitchen. She did not drink it.' },
      topics: [
        { id: 'night', q: 'What happened in this house at midnight?', a: 'The bell rang nine. I counted. The Canon’s door opened. I heard him on the stairs. Then the garden door. He was out for half an hour.' },
        { id: 'garden', q: 'Where did he go?', a: 'Down the hill. There were footprints in the morning, toward the cemetery. Big footprints. He came back with mud to the knee and put his cassock in the laundry basket himself. He has never done that.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'constance', q: 'Did Sister Constance come here?', a: 'Thursday. She sat in the study with the Canon for an hour and came out white. She said to me, Ivy, I have been part of something wicked for nine years. I said, we all have, Sister.' },
      ] },
    { id: 'wick', at: 'academy', name: 'Josiah Wick', role: 'porter, Ordell Academy',
      intro: 'Wick. I lock the school gates at ten. Tonight somebody had a key that wasn’t mine.',
      bio: 'Porter at the Academy for thirty years. He rings the school bell every morning and counts the boys every night.',
      knows: ['tutor', 'astro'],
      aboutLine: 'On the staff, or near enough. I see them across the quad every morning.',
      leadLine: 'A boy found something on the playing fields at dawn and was too scared to say so. It ended up at',
      spentLine: 'The gate is shut and I have a bell to ring in three hours.',
      opinions: { tutor: 'Mr. Blake went out at half past eleven with two boys and came back at one. He signed nothing. He never does.', astro: 'Dr. Quint sends a note down for the boys on clear nights. Friday was not clear. She sent the note anyway.' },
      topics: [
        { id: 'night', q: 'Who had a key that wasn’t yours?', a: 'Harris, third form. He has the verger’s tower key and the gate key both. He went out at eleven and came back at half past twelve without either.' },
        { id: 'harris', q: 'Where is Harris now?', a: 'In the sanatorium with a fever he has not got. He will not come out. He says a man took the key from him on the path by the reservoir and told him to forget it.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'constance', q: 'Did you know Sister Constance?', a: 'She rang for the school every morning at seven. Twelve strokes, then seven. Never one out. Friday morning nobody rang. That is how I knew before anyone told me.' },
      ] },
    { id: 'greer', at: 'almshouse', name: 'Mother Greer', role: 'resident, the Almshouse',
      intro: 'They call me Mother Greer. Seventy-one years in this parish. I’ve buried two of the people on your list, and I’ll bury a third.',
      bio: 'Born on the hill. Has outlived three canons and most of her neighbours. She does not sleep.',
      knows: ['matron', 'gardener', 'driver'],
      aboutLine: 'I’ve known that one since they were small. Small people grow into big people. They don’t turn into different ones.',
      leadLine: 'I don’t sleep. I heard the side door, and I saw somebody carry a bundle toward',
      spentLine: 'I’m tired, child. Come back when it’s light, and bring biscuits.',
      opinions: { matron: 'Sybil Crake was a nurse in this almshouse before she was a matron. She was kind then. Money is a hard thing to be kind through.', gardener: 'Peter Nane brings me tobacco and takes my advice, which is a fair trade. I told him to leave the Ayre girl alone. He did not.', driver: 'Rosalind Fay’s mother died in bed nine here. Rosalind drove the tram past the window every day for a year and never came in.' },
      topics: [
        { id: 'night', q: 'What did you hear?', a: 'Nine bells. Then the side door of this house. Then somebody on the path with a bundle, going down toward the water. Big steps. A man’s.' },
        { id: 'bundle', q: 'What was in the bundle?', a: 'Something that clinked. Keys, or coins, or a rosary. He held it against his chest the way you hold something you should not have.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'constance', q: 'Did you know Sister Constance?', a: 'I taught her to ring. Sixty years ago I rang that bell myself. She came to me on Thursday and asked whether a person could be forgiven for something they signed. I said only if they unsigned it. She said she was going to try.' },
      ] },
    { id: 'marley', at: 'depot', name: 'Fen Marley', role: 'night dispatcher, the Tram Depot',
      intro: 'Marley. I sign the trams out and back in. The last car is at eleven. Tonight one went out at midnight and I didn’t sign it.',
      bio: 'Night dispatcher for eight years. The schedule is the only thing on the hill he trusts.',
      knows: ['driver', 'tutor', 'sister'],
      aboutLine: 'They ride the last car. You learn a person by which seat they take.',
      leadLine: 'A parcel came off the midnight tram and was left on the bench. Somebody carried it up to',
      spentLine: 'The schedule is the schedule. I’ve said what I know.',
      opinions: { driver: 'Rosalind took car seven at two minutes past midnight with the lights off. I saw her hands on the brake from the office. She brought it back wet.', tutor: 'Mr. Blake rode down at one with two boys and a face like a funeral.', sister: 'The Ayre woman got off car seven at the Close Green at ten past midnight. Alone. She had a bag. She did not have a ticket.' },
      topics: [
        { id: 'night', q: 'Car seven.', a: 'Out at two past midnight, unsigned. Back at ten to one, wet. Rosalind Fay driving. One passenger up. None down.' },
        { id: 'parcel', q: 'A parcel came off the midnight car.', a: 'Left on the bench. A bag. Somebody carried it up the hill toward the cemetery at half past one. Not Rosalind. A man.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'constance', q: 'Did Sister Constance ride the tram?', a: 'Never. She walked. Two hundred and eleven steps up the tower and a mile down the hill and back every day for twenty years. She said the walk was the prayer.' },
      ] },
    { id: 'lister', at: 'glasshouse', name: 'Bo Lister', role: 'stoker, the Glasshouse',
      intro: 'Lister. I keep the boilers going so the orchids don’t freeze. It’s warmer in here than anywhere on the hill, so people come in.',
      bio: 'Stoker at the Glasshouse for six years. He sees the hill come in from the cold and talk.',
      knows: ['gardener', 'astro', 'matron'],
      aboutLine: 'They come in to get warm. You see a person clearly in this light.',
      leadLine: 'Somebody burned something in my firebox tonight and didn’t burn all of it. What was left went up the hill to',
      spentLine: 'The boilers need me. The police don’t.',
      opinions: { gardener: 'Nane was here till two. He heard the bell and sat down on the coal and did not get up for an hour.', astro: 'Dr. Quint sends down for orchids and I carry them up. Her dome smelled of chloral on Friday.', matron: 'The Matron comes in to get warm on her way down from Marrow House. Friday she came in at one with river mud on her shoes.' },
      topics: [
        { id: 'night', q: 'What was burned in your firebox?', a: 'Paper. A ledger page, and a letter. Somebody came in at half past midnight, shoved them in and went. Not all of it burned. I pulled a corner out.' },
        { id: 'corner', q: 'What was on it?', a: 'A number. Forty-four. And a signature in green ink. The Canon signs in green ink. Everybody on the hill knows that.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'constance', q: 'Did Sister Constance come here?', a: 'Wednesday. She stood in the warm for an hour and asked me whether the boilers could burn a ledger. I said they could burn anything. She said, good.' },
      ] },
    { id: 'grimm', at: 'cemetery', name: 'Silas Grimm', role: 'gravedigger',
      intro: 'Grimm. I dig the graves. Tonight I found a hole I didn’t dig, and I want to know who did.',
      bio: 'Gravedigger for twenty years, and a drinker for nineteen of them. When he is drunk, the gardener digs.',
      knows: ['verger', 'canon'],
      aboutLine: 'They stand over the graves I dig. You see what a person is at a funeral.',
      leadLine: 'Fresh earth was moved, and something was taken out, not put in. The cart tracks run to',
      spentLine: 'I have a hole to fill and I’ve said too much already.',
      opinions: { verger: 'The verger tells Nane where to dig when I am drunk. I am drunk a good deal. I still know my own cemetery.', canon: 'The Canon stood over plot forty-four on Tuesday evening with his hat off like there was somebody in it. There was not.' },
      topics: [
        { id: 'night', q: 'The hole you didn’t dig.', a: 'Plot forty-four. Dug Tuesday by Nane, four feet, with a tin box in it. Dug up again Friday night by somebody in a hurry who left the box and took what was in it.' },
        { id: 'tracks', q: 'Cart tracks.', a: 'From the plot to the gate and down toward the water board. Somebody wheeled something heavy. Or somebody who could not walk straight.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'constance', q: 'Did Sister Constance come to the cemetery?', a: 'Every Sunday to her mother. Thursday she came and stood at plot forty-four for a long time and then she went to the Rectory. She walked like a woman going to a fight.' },
      ] },
    { id: 'ansell', at: 'foundry', name: 'Hew Ansell', role: 'bell founder',
      intro: 'Ansell. My grandfather cast that bell. I’ve tuned it every Easter since I could hold a hammer. I know its voice. Last night somebody rang it who didn’t.',
      bio: 'Third generation of bell founders. He can tell who rang a bell by how it sounds.',
      knows: ['verger', 'canon'],
      aboutLine: 'They’ve been up the tower with me. You learn a person by how they climb.',
      leadLine: 'A bolt from the bell clapper was taken from my bench last week. I found it this morning, dropped on the path toward',
      spentLine: 'The furnace is lit. I’m not.',
      opinions: { verger: 'Cormac Ill has been up my tower a thousand times and cannot ring. He has no ear. Whoever rang nine had no ear either.', canon: 'The Canon climbed the tower once, in 1928, and was sick at the top. He has not been up since.' },
      topics: [
        { id: 'night', q: 'You know the bell’s voice.', a: 'Nine strokes, ragged. Rung by somebody who let go of the rope at the top of the pull. Not a ringer. Somebody who had watched ringing and never done it.' },
        { id: 'bolt', q: 'A clapper bolt was taken from your bench.', a: 'Last week. Found this morning on the path to the reservoir. Somebody wanted the bell silenced and then changed their mind and rang it anyway.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'constance', q: 'You knew Sister Constance.', a: 'Twenty years. The best ringer on the hill. She came to the foundry on Thursday and asked me how a rope is cut so it cannot be rung. I told her. I thought she was afraid of somebody.' },
      ] },
    { id: 'pym', at: 'chapterhouse', name: 'Dorcas Pym', role: 'archivist, the Chapter House',
      intro: 'Miss Pym. Four hundred years of parish records, and I’ve read all of them. Sister Constance came to me last week for the crypt account books. I gave them to her.',
      bio: 'Archivist for thirty-one years. Knows which page of which book holds which secret.',
      knows: ['canon', 'tutor', 'astro'],
      aboutLine: 'They read here. You can tell a person by which books they ask for.',
      leadLine: 'A page was cut out of the 1939 register tonight by somebody who knew exactly which page. They left toward',
      spentLine: 'The reading room closes at dusk, and it’s long past dusk.',
      opinions: { canon: 'The Canon has not opened a parish register in ten years. He sent for the crypt ledger on Friday afternoon. I sent it. It came back with a page missing.', tutor: 'Mr. Blake reads the 1939 register. The year the Ayre girl was committed. He has read it three times.', astro: 'Dr. Quint reads the weather records. Every clear night for a hundred years. She is looking for something in the sky. She has not found it.' },
      topics: [
        { id: 'night', q: 'A page was cut from the 1939 register.', a: 'The committal of Beatrix Ayre. Signed by the Canon, the Matron and Sister Constance. Cut out tonight by somebody with a razor and a key to this room.' },
        { id: 'key', q: 'Who has a key?', a: 'The Canon. The verger. And me. The razor was left on the desk. It was a barber’s razor. Somebody who shaves with it, not a woman.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'constance', q: 'What did Sister Constance want from you?', a: 'The crypt ledger and the 1939 register. She read both here on Wednesday and made notes. She said, Dorcas, I signed my sister away for four hundred pounds and I did not even know it. She meant the Canon had taken the money. I think she meant more than that.' },
      ] },
    { id: 'oakes', at: 'deanery', name: 'Cyrus Oakes', role: 'clerk, Diocesan Office',
      intro: 'Oakes. I type the diocese’s letters, including the one asking you to be discreet. I didn’t agree with it.',
      bio: 'Clerk to the Dean for nine years. He types what he is told and underlines what he thinks.',
      knows: ['canon', 'matron', 'tutor'],
      aboutLine: 'They come before the Dean. You notice who is nervous in front of a bishop.',
      leadLine: 'A letter was delivered by hand for the Dean at one in the morning and burned unread. The ashes are at',
      spentLine: 'I’ve said more than the diocese would like. That’s all.',
      opinions: { canon: 'The Canon asked the Dean for discretion on Friday morning. Before anybody was dead. I typed the letter. I dated it Saturday.', matron: 'The Matron’s quarterly report on the Ayre patient is the same every quarter, word for word. I have typed it thirty-six times.', tutor: 'Mr. Blake wrote to the Dean in March offering to resign. The Dean never answered. I never sent it.' },
      topics: [
        { id: 'night', q: 'A letter came for the Dean at one in the morning.', a: 'By hand. From the Rectory. The Dean burned it in the grate unread and told me to forget the hour. I have not forgotten it.' },
        { id: 'ash', q: 'Where is the ash?', a: 'In the grate. I raked out one corner. It says: ‘the ledger is in the crypt fund box and Constance has—’. That is where it burned.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'constance', q: 'Did Sister Constance write to the Dean?', a: 'Twice. Once about the schoolmaster, which she never sent. Once about the crypt fund and Marrow House, which she posted on Thursday. It has not arrived. Letters from the hill take a day. It should have arrived.' },
      ] },
    { id: 'brannock', at: 'cottage', name: 'Mrs. Brannock', role: 'housekeeper, Verger’s Cottage',
      intro: 'Brannock. I keep house for the verger. I know which hook every key hangs on, and which one has been empty since Thursday.',
      bio: 'Keeps the verger’s cottage and the verger’s secrets, most of them.',
      knows: ['verger', 'sister'],
      aboutLine: 'They come to this kitchen. You learn a person by how they look at the key board.',
      leadLine: 'The missing key came back this morning with river mud on it. That mud comes from',
      spentLine: 'The kitchen is mine and I’m closing it.',
      opinions: { verger: 'The verger was in his bed at midnight. I heard him snoring through the wall. Whatever else he is, he was asleep.', sister: 'The younger Miss Ayre came to this kitchen on Wednesday and asked for the tower key. I said no. She looked at the key board a long time and then she looked at me.' },
      topics: [
        { id: 'night', q: 'The tower key.', a: 'Off its hook since Thursday. The verger lends it to a schoolboy. The boy did not bring it back. It came back this morning by itself, on the doorstep, with river mud on it.' },
        { id: 'mud', q: 'River mud.', a: 'Reservoir mud. Black. It only comes from the wall walkway. Whoever put the key on my step had walked along the top of the dam in the dark.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'constance', q: 'Did Sister Constance come here?', a: 'Every night at half past eleven for the key, and every night at half past twelve to hang it back. Friday she came at half past eleven and it was not on the hook. She went up anyway. Somebody had already unlocked the door.' },
      ] },
    { id: 'lamb', at: 'dispensary', name: 'Enid Lamb', role: 'dispenser, Hill Dispensary',
      intro: 'Lamb. I keep the poisons book for the hill. It’s a short book with long names in it.',
      bio: 'The only chemist on the hill for eleven years. Remembers every hand that signed her book.',
      knows: ['matron', 'astro', 'gardener'],
      aboutLine: 'They sign my book. You notice the hand that signs for sleeping draughts.',
      leadLine: 'Somebody came in at dawn for lint and iodine and paid with a coin that was still wet. They went to',
      spentLine: 'The shop is shut and the book is locked.',
      opinions: { matron: 'The Matron signs for chloral every month for a patient who does not need it. I have watched her sign for eleven years.', astro: 'Dr. Quint buys chloral for herself. She says she cannot sleep. On Friday she bought twice the usual.', gardener: 'Peter Nane bought iodine and lint at dawn on Saturday with a coin that was still wet.' },
      topics: [
        { id: 'night', q: 'Who came in at dawn?', a: 'Nane. Lint and iodine. His hands were cut across the palms, both of them, like a man who had gripped a rope or a rung too hard. He paid with a wet coin.' },
        { id: 'hands', q: 'Rope or rung?', a: 'Iron. Rust in the cuts. I cleaned them. He said he had fallen in the Glasshouse. There is no iron in the Glasshouse.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'constance', q: 'Did Sister Constance buy from you?', a: 'Nothing, ever. Thursday she came in and asked to see the poisons book. She read the Matron’s entries for nine years and said, that is a great deal of sleep for one woman.' },
      ] },
    { id: 'quaile', at: 'asylum', name: 'Sam Quaile', role: 'orderly, Marrow House',
      intro: 'Quaile. I do nights on the east ward. I know who’s a real patient here and who’s only wearing the gown.',
      bio: 'Orderly at Marrow House for five years. He has spent five years watching one patient who is not ill.',
      knows: ['matron', 'sister', 'tutor'],
      aboutLine: 'They’re on my ward, or they visit it. You learn a person by how they behave behind a locked door.',
      leadLine: 'The gate was open at eleven-forty and somebody went out through it carrying a bag. They went down toward',
      spentLine: 'The Matron would sack me for this. Out.',
      opinions: { matron: 'The Matron was in her office at midnight. I brought her tea. She was crying. I did not ask.', sister: 'Beatrix Ayre is the sanest person in this building. I include the staff.', tutor: 'Mr. Blake came to the gate on Wednesday with a letter and a boy. The Matron would not take the letter. The boy gave it to me. I gave it to Beatrix.' },
      topics: [
        { id: 'night', q: 'The gate was open at eleven-forty.', a: 'I opened it. For Beatrix. With a bag. The Matron said let her go. She went down toward the tram.' },
        { id: 'back', q: 'Did she come back?', a: 'At dawn. Wet to the waist, no rosary, no bag. She got into her bed and she has not spoken since. Her hands are torn from rowing.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'constance', q: 'Did Sister Constance visit?', a: 'Thursday. First time in nine years. She sat with her sister for an hour. When she came out she went straight to the Matron’s office and I heard the word ‘papers’ through the door nine times. I counted.' },
      ] },
    { id: 'hobb', at: 'pawn', name: 'Zeb Hobb', role: 'pawnbroker',
      intro: 'Hobb. Everything the hill is ashamed of comes through this door eventually. Last week it was a set of church keys.',
      bio: 'Pawnbroker at the bottom of the hill for thirty years. He looks at hands, not faces.',
      knows: ['driver', 'gardener', 'verger'],
      aboutLine: 'They pawn things with me. I look at the hands that push them across the counter.',
      leadLine: 'The keys were bought back at midnight by a different hand. That hand went up the lane to',
      spentLine: 'The shop is shut. Come back with something to pawn or not at all.',
      opinions: { driver: 'Rosalind Fay pawned her mother’s ring in April and bought it back in May with a five-pound note. Tram drivers do not have five-pound notes.', gardener: 'Peter Nane pawns his watch every winter and buys it back every spring. This year he bought it back in November.', verger: 'The verger pawned a set of church keys last week. He said they were spares. Churches do not have spares.' },
      topics: [
        { id: 'night', q: 'The church keys.', a: 'Pawned by the verger last week. Bought back at midnight on Friday by a different hand. Big hands. Cut across the palms. He paid with a coin from the reservoir, still wet.' },
        { id: 'where', q: 'Where did he go?', a: 'Up the lane toward the cemetery. Fast. He had the keys in one hand and something in a bag in the other.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'constance', q: 'Did Sister Constance ever come in?', a: 'Wednesday. She bought the eyepiece the schoolboy had pawned. Dr. Quint’s. She said she would give it back to its owner. She said the owner would need it on Friday night.' },
      ] },
    { id: 'amsel', at: 'bookshop', name: 'Old Amsel', role: 'bookseller',
      intro: 'Amsel. Second-hand books. I sell the hill its own history back to it, and I know who buys which chapter.',
      bio: 'Bookseller for forty years. Stocks the diocese’s annual reports because somebody on the hill always wants one.',
      knows: ['astro', 'tutor', 'canon'],
      aboutLine: 'They browse here. You learn a person by what they don’t buy.',
      leadLine: 'A diocesan report was bought tonight and its photographs torn out in my doorway. The torn pages went toward',
      spentLine: 'The shop is closed. So is the subject.',
      opinions: { astro: 'Dr. Quint buys every book on the eye and on seeing. She bought one on Wednesday about how a witness can be wrong.', tutor: 'Mr. Blake buys nothing. He reads standing up and puts the book back. He read the 1939 diocesan report standing up on Thursday.', canon: 'The Canon sent for the 1939 report on Friday afternoon. I had one copy. I sent it up. It came back with the plates torn out.' },
      topics: [
        { id: 'night', q: 'The plates were torn out in your doorway.', a: 'By a big man with cut hands who bought the report and did not wait for change. He tore out the four plates of the tower and ran toward the water board.' },
        { id: 'plates', q: 'What is on the plates?', a: 'The iron rungs on the outside of the tower. The only photograph anyone has of them. Whoever used them wanted nobody to know they were there.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'constance', q: 'Did Sister Constance buy books?', a: 'Wednesday. A book on canon law. She asked me which page covers a committal signed under false pretences. I showed her. She read it here and did not buy it.' },
      ] },
    { id: 'petty', at: 'tearooms', name: 'Mrs. Petty', role: 'proprietress, Terrace Tea Rooms',
      intro: 'Mrs. Petty. Milk and two sugars for the whole hill, and I hear every word said over it. I pour and I remember.',
      bio: 'Has run the tea rooms for twenty years. The hill’s gossip passes across her counter twice a day.',
      knows: ['astro', 'sister', 'matron'],
      aboutLine: 'They take tea here. I’ve set a cup in front of them and watched them lift it.',
      leadLine: 'Two women argued here at four in the morning. One left a glove on the chair. Somebody else picked it up and went to',
      spentLine: 'The urn is cold, and so am I.',
      opinions: { astro: 'Dr. Quint takes her tea at six after a night in the dome. Saturday she did not come. She sent a note asking me to keep the papers from her.', sister: 'Beatrix Ayre sat at that table at four in the morning with her hands shaking so badly she left a glove behind.', matron: 'The Matron argued with the Ayre girl here at four in the morning and paid for both teas. She never pays for anybody’s tea.' },
      topics: [
        { id: 'night', q: 'Two women argued here at four.', a: 'The Matron and Beatrix Ayre. Beatrix was wet to the waist. The Matron said, you were not there. Beatrix said, I was under it, I counted nine. The Matron said, then you saw.' },
        { id: 'saw', q: 'Saw what?', a: 'Beatrix said, a man on the outside of the tower. The Matron went white and paid and took her back up the hill. The glove stayed on the chair. A schoolmaster came in at seven and took it.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'constance', q: 'Did Sister Constance take tea here?', a: 'Thursday. With the Canon. He talked and she did not touch her cup. When he left she sat for an hour and then she said to me, Mrs. Petty, if I fall down the stairs, I did not fall.' },
      ] },
    { id: 'rudge', at: 'inn', name: 'Tam Rudge', role: 'landlord, the Lamplighter’s Arms',
      intro: 'Rudge. The only pub on the hill. Everything the hill says out loud, it says in here first.',
      bio: 'Landlord for fifteen years. He chalks what the hill owes him on a slate, and remembers what it says.',
      knows: ['gardener', 'driver', 'verger'],
      aboutLine: 'They drink in my pub. You see a person clearest after the third drink.',
      leadLine: 'A man came in with wet boots and a dry throat and left without paying. He went out the back toward',
      spentLine: 'Time, gentlemen. That includes you.',
      opinions: { gardener: 'Nane came in at half past one with wet boots and cut hands and drank two rums and said he had rung it and laughed. He says that every night. Friday he was not laughing.', driver: 'Rosalind Fay drinks here on Saturdays and talks about the city. Friday she came in at one and did not talk.', verger: 'The verger drinks at the depot, not here. He thinks nobody knows. The whole hill knows.' },
      topics: [
        { id: 'night', q: 'The man with wet boots.', a: 'Nane. Half past one. Cut hands, wet to the knee, two rums, no money. He said, I rang it, Tam, and laughed. He says that every night. Friday his voice was wrong.' },
        { id: 'back', q: 'He went out the back.', a: 'Toward the cemetery. With a bag he had not come in with. It was on the floor by the door when he sat down and it was gone when he went.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'constance', q: 'Did Sister Constance ever come in?', a: 'Once. Thursday. She stood at the bar and ordered nothing and said to the room, whoever has been up my tower at night, I know, and it stops now. Then she left. The room did not breathe for a minute.' },
      ] },
    { id: 'shale', at: 'pumphouse', name: 'Wat Shale', role: 'pumpman, the Pump House',
      intro: 'Shale. I keep the engines running all night. They’re loud enough to cover a bell. Not nine of them.',
      bio: 'Pumpman for twelve years. He stops the engines when he wants to hear the hill.',
      knows: ['gardener', 'driver'],
      aboutLine: 'They pass the engine house at night. You learn a person by how they walk past a noise.',
      leadLine: 'Somebody used the valve walkway at one in the morning and dropped something in the channel. It washed up at',
      spentLine: 'The engines don’t stop, and neither can I.',
      opinions: { gardener: 'Nane walked past the engine house at one with a bag and did not look at the noise. Everybody looks at the noise.', driver: 'Miss Fay sat on the reservoir wall from half past midnight till one. I saw her from the engine door. She was not there to think. She was there to watch.' },
      topics: [
        { id: 'night', q: 'You stopped the engines at midnight.', a: 'For four minutes, to listen. Nine bells. I wrote the number down. I have written twelve every night for twelve years. Nine is not a mistake. Nine is a message.' },
        { id: 'walkway', q: 'Somebody used the valve walkway at one.', a: 'With the Water Board key. They dropped something in the channel. It fetched up at the boathouse. A rosary. Then they went along the wall to the far bank.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'constance', q: 'Did you know Sister Constance?', a: 'By the bell. Twelve years, twelve strokes, and I set my engines by her. Friday I stopped them to listen and I have not been able to start them right since.' },
      ] },
    { id: 'ferris', at: 'boathouse', name: 'Old Ferris', role: 'boatman, the Reservoir',
      intro: 'Ferris. Two rowing boats and a tally book. Tonight one boat went out without a tally and came back without its oars.',
      bio: 'Boatman at the reservoir for twenty years. He counts the boats out and in, and the oars with them.',
      knows: ['astro', 'gardener'],
      aboutLine: 'They take a boat out sometimes. You learn a person by how they row.',
      leadLine: 'The oars were found on the far bank this morning, with a set of footprints beside them going up to',
      spentLine: 'The water is cold and I’m colder. Go.',
      opinions: { astro: 'Dr. Quint rows out to the middle on clear nights to see the sky in the water. She was not out on Friday. Friday was not clear.', gardener: 'Nane took a boat out on Friday at half past one and brought it back at two with no oars and his hands bleeding.' },
      topics: [
        { id: 'night', q: 'One boat went out without a tally.', a: 'Skiff two. At one. A woman, rowing badly. Then skiff one, at half past one. A man, rowing well. Both came back without their oars.' },
        { id: 'bank', q: 'The far bank.', a: 'Footprints going up from the water to the tram depot path. Two sets. A woman’s, then a man’s over the top of them, an hour later.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'constance', q: 'Did Sister Constance come to the water?', a: 'Every Sunday after the last bell. She sat in skiff two and did not row. She told me once the reservoir was the only place on the hill where she could not hear herself think. I think she meant that kindly.' },
      ] },
    { id: 'agnes', at: 'laundry', name: 'Sister Agnes', role: 'laundress, Hill Laundry',
      intro: 'Sister Agnes. Every church robe and every sheet on the hill comes through my coppers. I see what people would rather I didn’t.',
      bio: 'Runs the laundry for the diocese. Knows the hill by its stains.',
      knows: ['sister', 'matron'],
      aboutLine: 'They send their linen here. You learn a lot from a person’s linen.',
      leadLine: 'A cassock came in at dawn with mud up to the knee and a tear at the shoulder. The bundle it came in was sent back to',
      spentLine: 'The coppers are boiling. I’ve said my piece.',
      opinions: { sister: 'Beatrix Ayre’s things came to the laundry on Saturday morning from Marrow House. Wet through. Reservoir water. The Matron sent them herself.', matron: 'The Matron sends her own linen here. It is always clean. That is the strange thing.' },
      topics: [
        { id: 'night', q: 'A cassock came in at dawn.', a: 'From the Rectory. Mud to the knee, a tear at the right shoulder. The Canon’s size. Somebody in the Canon’s cassock was in the river.' },
        { id: 'tear', q: 'The tear.', a: 'Iron. Rust in the thread. Whoever wore it caught it on something iron, high up, and pulled hard. I sent the bundle back to the Rectory with the tear mended. I should not have mended it.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'constance', q: 'Did you know Sister Constance?', a: 'We were novices together. She rang and I washed. Thursday she brought me her own habit to wash and said, Agnes, I want to be clean for Sunday. I did not know what she meant. I do now.' },
      ] },
    { id: 'coyle', at: 'waterboard', name: 'Hettie Coyle', role: 'clerk, Ordell Water Board',
      intro: 'Coyle. Every gallon that leaves the reservoir goes in my book, and every key to the valves hangs behind me. One didn’t come back last night.',
      bio: 'Clerk at the Water Board for seven years. Nobody signs for a valve key without her seeing their hand.',
      knows: ['canon', 'driver'],
      aboutLine: 'They come for the valve key. You learn a person by how they sign for it.',
      leadLine: 'The valve key came back at three with somebody else’s initials in the book. That somebody walked out toward',
      spentLine: 'The board is closed. Good night.',
      opinions: { canon: 'The Canon has a standing order for valve key three. He has never once used it himself. Somebody always signs for him.', driver: 'Miss Fay signed for the valve key in the Canon’s name on Friday at ten to midnight. I know her hand. She was not supposed to be here.' },
      topics: [
        { id: 'night', q: 'Key three.', a: 'Out at ten to midnight against the Canon’s order, signed in a hand that was not his. Back at three with initials that were not the first hand’s either. Two people had that key in one night.' },
        { id: 'initials', q: 'Whose initials came back?', a: 'P.N. Peter Nane. He does not have a standing order. He has never signed for a key in his life. He signed on Saturday morning at three with cut hands.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'constance', q: 'Did Sister Constance come to the Water Board?', a: 'Wednesday. She asked who had keys to the walkway. I read her the list. She wrote down one name and underlined it. I did not see which.' },
      ] },
  ],

  items: [
    { id: 'item:bell:rope', at: 'tower', kind: 'report', label: 'The bell rope, examined',
      source: 'HILL DIVISION · SCENE EXAMINATION', title: 'Bell rope, the tower',
      fields: [['Cut', 'clean, one stroke, from below'], ['Height of cut', 'five feet three from the ringing floor'], ['Fibres', 'pulled downward']],
      body: ['One stroke, from below, at five foot three. Whoever cut the rope did not climb to do it and did not reach up much to do it either.'],
      spoken: 'The bell rope, cut clean in one stroke from below, at five foot three.',
      reading: 'The rope was cut at five foot three by somebody standing on the floor. Something to think about, not something to mark yet.', effect: { type: 'none' } },
    { id: 'item:bell:sherry', at: 'rectory', kind: 'receipt', label: 'The Canon’s wine merchant, account',
      source: 'HARDACRE & SONS · WINE MERCHANTS', title: 'Account, the Rectory, April',
      body: ['Twelve of sherry, six of port, and a note from the merchant: “Canon — the crypt fund cheque was returned again. We must ask.” Mrs. Tull has watched him drink the twelve.'],
      spoken: 'The Canon’s wine account, and a note about a returned cheque.',
      reading: 'Mrs. Tull knows what the Canon drinks and how. It tells you something about him. Check his row in the Notebook.', about: ['canon'], effect: { type: 'suspectTrait', suspectId: 'canon' } },
    { id: 'item:bell:crypt-ledger', at: 'chapterhouse', kind: 'ledger', label: 'Crypt ledger, 1939, page razored', stamp: 'CONFIDENTIAL',
      source: 'THE CHAPTER HOUSE · CRYPT REGISTER', title: 'Interments, 1939',
      body: ['Plot forty-four: a name, a date, a fee of forty pounds, and the page it was on razored out tonight. The stub is still in the binding, and Miss Pym knows which page it was because she gave it to Constance last week.', 'Whoever cut it left a fingerprint in the glue.'],
      spoken: 'The crypt ledger with a page razored out tonight, and a fingerprint in the glue.',
      reading: 'Somebody wanted plot forty-four forgotten. A red mark on the map shows where to look.', about: ['canon', 'gardener'], effect: { type: 'lead' } },
    { id: 'item:bell:register', at: 'almshouse', kind: 'ledger', label: 'Almshouse register, such as it is',
      source: 'THE ALMSHOUSE · REGISTER', title: 'Beds, night of the 9th',
      body: ['Forty beds, thirty-nine names, one bed slept in that has no name against it. Mother Greer says the fortieth has been sleeping there on and off for nine years and pays in kind.'],
      spoken: 'The almshouse register: forty beds, thirty-nine names.',
      reading: 'Background. Somebody sleeps here without signing in. Nothing to mark.', effect: { type: 'none' } },
    { id: 'item:bell:discretion', at: 'deanery', kind: 'letter', label: 'The diocese asks for discretion', stamp: 'RECEIVED',
      source: 'DIOCESE OF ORDELL · THE DEAN', title: 'To the Superintendent, Hill Division',
      body: ['“…the Dean is confident the Division will treat the matter with the discretion due to the Cathedral’s standing, and will not find it necessary to trouble the Canon or the Matron of Marrow House beyond what is strictly required.”', 'Typed by Oakes, who has underlined “beyond what is strictly required” and initialled the underlining.'],
      spoken: 'The diocese asks for discretion, in writing, on behalf of the Canon and the Matron.',
      reading: 'The diocese is protecting the Canon and the Matron by name. Nothing to mark.', about: ['canon', 'matron'], effect: { type: 'none' } },
    { id: 'item:bell:tuning', at: 'foundry', kind: 'note', label: 'Founder’s tuning notes',
      source: 'ORDELL BELL FOUNDRY · BENCH BOOK', title: 'St. Ordell’s tenor, Easter 1948',
      body: ['“Rung nine at midnight by a hand that lets the rope go at the top of the stroke. Not a ringer. Somebody who has watched ringing and never done it.” In the founder’s hand, dated this morning.'],
      spoken: 'The bell founder’s note: rung by a hand that lets the rope go at the top of the stroke.',
      reading: 'The bell was rung by somebody who had watched ringing but never done it. Something to think about. Nothing to mark.', effect: { type: 'none' } },
    { id: 'item:bell:key-board', at: 'cottage', kind: 'photo', label: 'Photograph, the key board',
      source: 'HILL DIVISION · PHOTOGRAPHIC UNIT', title: 'Plate 3: the verger’s key board',
      body: ['Forty hooks, thirty-nine keys, and the empty hook labelled TOWER in the verger’s hand. In the flash, the verger himself, caught in the doorway, and something about him the constable did not notice at the time.'],
      spoken: 'A photograph of the key board with the tower hook empty, and the verger in the doorway.',
      reading: 'The camera flash caught the verger. It tells you something about him. Check his row in the Notebook.', about: ['verger'], effect: { type: 'suspectTrait', suspectId: 'verger' } },
    { id: 'item:bell:sundial', at: 'green', kind: 'note', label: 'Chalk on the sundial',
      source: 'THE CLOSE GREEN · SUNDIAL', title: 'Chalked on the dial',
      body: ['IX, in chalk, on the sundial, at the hour it would have shown had there been a sun. Below it, a small drawn bell. The rain has taken the rest.'],
      spoken: 'Nine, in chalk, on the sundial, with a small drawn bell.',
      reading: 'Background. Somebody wanted the whole hill to count to nine. Nothing to mark.', effect: { type: 'none' } },
    { id: 'item:bell:unposted', at: 'academy', kind: 'letter', label: 'Constance’s unposted letter', stamp: 'PERSONAL',
      source: 'FOUND IN A MASTER’S DESK, ORDELL ACADEMY', title: 'To the Dean, unposted',
      body: ['“…I must therefore report that Mr. Blake has been seen with the boys of the third form at the Observatory after lights out on three occasions, and that Dr. Quint has declined to say what they were shown. — C. Ayre.” Sealed, stamped, never posted, and found in the desk of the man it names.'],
      spoken: 'Constance’s letter to the Dean, sealed and never posted, found in Blake’s own desk.',
      reading: 'Blake had the letter that would have ruined him. A motive. Nothing to mark.', about: ['tutor', 'astro'], effect: { type: 'none' } },
    { id: 'item:bell:plot44', at: 'cemetery', kind: 'report', label: 'Plot forty-four, examined',
      source: 'HILL DIVISION · SCENE EXAMINATION', title: 'Plot 44, Ordell Cemetery',
      fields: [['Dug', 'Tuesday, by the gardener'], ['Depth', 'four feet, not six'], ['Contents', 'empty — and then, under the loose fill, a tin box, empty too']],
      body: ['A grave dug three days before a death, and a tin box in it that somebody emptied tonight. The gravedigger did not dig it; the gardener did.'],
      spoken: 'Plot forty-four: dug Tuesday, four feet deep, and a tin box in it emptied tonight.',
      reading: 'Nane dug a grave for a box, not a body. Ask him what was in it. Nothing to mark.', about: ['gardener'], effect: { type: 'none' } },
    { id: 'item:bell:poisons', at: 'dispensary', kind: 'ledger', label: 'Poisons book, chloral', stamp: 'CONFIDENTIAL',
      source: 'HILL DISPENSARY · POISONS BOOK', title: 'Entries, April',
      body: ['Chloral hydrate, two drachms, signed S. CRAKE, for Marrow House, the 8th. Miss Lamb watched her sign, as she has watched her sign every month for eleven years.'],
      spoken: 'The poisons book: chloral for Marrow House, signed by the Matron on the eighth.',
      reading: 'Miss Lamb has watched the Matron sign for eleven years. It tells you something about her. Check her row in the Notebook.', about: ['matron'], effect: { type: 'suspectTrait', suspectId: 'matron' } },
    { id: 'item:bell:eyepiece', at: 'pawn', kind: 'ticket', label: 'Pawn ticket, one eyepiece',
      source: 'HOBB’S PAWN · TICKETS', title: 'Ticket no. 114',
      fields: [['Item', 'telescope eyepiece, brass, engraved H.Q.'], ['Pledged', 'the 7th'], ['By', 'not the astronomer']],
      body: ['Dr. Quint’s eyepiece, pledged by somebody who is not Dr. Quint, two days before the bell. Hobb looked at the hands that pledged it.'],
      spoken: 'A pawn ticket for the astronomer’s eyepiece, pledged by somebody else.',
      reading: 'Background. Somebody took a thing from the Observatory and needed money. Ask Hobb who. Nothing to mark.', about: ['astro'], effect: { type: 'none' } },
    { id: 'item:bell:depot-sheet', at: 'depot', kind: 'ledger', label: 'Depot sign-out sheet',
      source: 'THE TRAM DEPOT · CARS', title: 'Sign-out, night of the 9th',
      body: ['Car 7 — out 00:02 — R. FAY — back 00:51 — “wet”. The dispatcher did not sign it and does not know how she got the key. He watched her bring it back, and what she did with her hands while he asked.'],
      spoken: 'The depot sheet: car seven out at two minutes past midnight, signed Fay, back at ten to one, wet.',
      reading: 'Marley watched Rosalind Fay bring the tram back. It tells you something about her. Check her row in the Notebook.', about: ['driver'], effect: { type: 'suspectTrait', suspectId: 'driver' } },
    { id: 'item:bell:handbell', at: 'mission', kind: 'note', label: 'The Lower Chapel handbell',
      source: 'LOWER CHAPEL · VESTRY', title: 'A note pinned to the bell',
      body: ['“Rung nine at midnight in answer. She would have wanted it answered.” Unsigned, in a careful hand, pinned to the handbell in the poor parish’s vestry.'],
      spoken: 'A note pinned to the Lower Chapel handbell: rung nine at midnight in answer.',
      reading: 'Somebody at the bottom of the hill knew what nine meant. Nothing to mark.', effect: { type: 'none' } },
    { id: 'item:bell:cassock', at: 'laundry', kind: 'report', label: 'Laundry ticket, one cassock',
      source: 'HILL LAUNDRY · TICKETS', title: 'Ticket, the 10th, dawn',
      fields: [['Item', 'cassock, black'], ['Condition', 'mud to the knee, tear at the right shoulder'], ['From', 'the Rectory bundle']],
      body: ['A cassock in the Rectory’s bundle with river mud to the knee. The Canon is not the only man on the hill who wears one, but he is the only one whose laundry comes from the Rectory.'],
      spoken: 'A laundry ticket for a cassock with river mud to the knee, from the Rectory bundle.',
      reading: 'Background. Somebody from the Rectory was in the river. Nothing to mark.', about: ['canon'], effect: { type: 'none' } },
    { id: 'item:bell:tallow-note', at: 'tallow', kind: 'note', label: 'A servant’s note, Tallow Street',
      source: 'FOUND UNDER A DOOR, TALLOW STREET', title: 'To whoever finds this',
      body: ['“I saw the light go up the tower and I saw it come down the outside. I will not say where. If I am asked I will say I was asleep. — A.”', 'Somebody wanted it known and did not want to be the one who knew it.'],
      spoken: 'A note pushed under a door on Tallow Street: I saw the light come down the outside.',
      reading: 'Whoever went up came down the outside of the tower. Nothing to mark, but remember it.', effect: { type: 'none' } },
    { id: 'item:bell:valve-book', at: 'waterboard', kind: 'ledger', label: 'Valve key book',
      source: 'ORDELL WATER BOARD · KEYS', title: 'Valve keys, the 9th',
      body: ['Key 3 out at 23:50 against the Canon’s standing order, returned 03:00 with initials that are not his. The walkway it opens runs along the top of the reservoir wall, and the wet prints on it run one way.'],
      spoken: 'The valve key book: key three out at ten to midnight and back at three with the wrong initials.',
      reading: 'The wet footprints on the walkway go somewhere. A red mark on the map shows where.', effect: { type: 'lead' } },
    { id: 'item:bell:wall-prints', at: 'reservoir', kind: 'cast', label: 'Prints on the reservoir wall',
      source: 'HILL DIVISION · CASTS AND IMPRESSIONS', title: 'The walkway, reservoir wall',
      body: ['A line of wet prints along the walkway at one, photographed before the rain took them. They come from the pump house side and go toward the boathouse, and they were made by somebody in a hurry who did not look down.'],
      spoken: 'Prints along the reservoir wall, from the pump house toward the boathouse.',
      reading: 'Background. Somebody crossed the reservoir wall in the dark, from the pump house toward the boathouse. Nothing to mark.', effect: { type: 'none' } },
    { id: 'item:bell:oars', at: 'boathouse', kind: 'report', label: 'The missing oars, found',
      source: 'RESERVOIR BOATHOUSE · TALLY', title: 'Skiff 2, oars',
      body: ['Found on the far bank at dawn, beside a set of prints, and a dropped thing the boatman turned over with his foot and did not pick up: a rosary, the beads wet, the cross bent.'],
      spoken: 'The missing oars on the far bank, and beside them a wet rosary with the cross bent.',
      reading: 'A rosary on the far bank. Everyone on this hill has one. Ask who lost theirs. Nothing to mark.', about: ['sister'], effect: { type: 'none' } },
    { id: 'item:bell:engine-log', at: 'pumphouse', kind: 'ledger', label: 'Engine log, the Pump House',
      source: 'THE PUMP HOUSE · ENGINE LOG', title: 'Night of the 9th',
      body: ['23:58 — engines stopped, four minutes, “to listen”. 00:02 — restarted. In four minutes of quiet on the hill, Shale heard nine, and counted them, and wrote the number down.'],
      spoken: 'The engine log: the pumps stopped for four minutes at two minutes to midnight, to listen.',
      reading: 'Background. The pumpman stopped his engines to hear the bell. Nothing to mark.', effect: { type: 'none' } },
    { id: 'item:bell:crypt-tin', at: 'crypt', kind: 'report', label: 'The crypt fund, counted', stamp: 'CONFIDENTIAL',
      source: 'THE CRYPT · FUND BOX', title: 'Crypt restoration fund',
      fields: [['Should hold', '£412'], ['Holds', '£31'], ['Signatures on withdrawals', 'one, throughout']],
      body: ['Four hundred pounds gone from a box with one signature on every slip. Constance had asked to see the box on Thursday. On Friday she was dead.'],
      spoken: 'The crypt fund: four hundred pounds gone, one signature on every slip.',
      reading: 'A motive for the Canon, with a sum attached. Nothing to mark.', about: ['canon'], effect: { type: 'none' } },
    { id: 'item:bell:tower-view', at: 'watertower', kind: 'photo', label: 'Photograph from the Waterworks Tower',
      source: 'HILL DIVISION · PHOTOGRAPHIC UNIT', title: 'Plate 9: the bell tower, from the water tower',
      body: ['Taken at dawn with a long lens: the tower, the stair window, and on the outside of the tower a line of iron rungs the diocese had forgotten about, running from the ringing floor to the ground. The bottom rung is bright where the rust has been worn off tonight.'],
      spoken: 'A photograph from the water tower: iron rungs on the outside of the bell tower, the bottom one bright.',
      reading: 'The killer came down the outside of the tower on the iron rungs. Nothing to mark, but it changes who could have done it.', effect: { type: 'none' } },
    { id: 'item:bell:gate-log', at: 'asylum', kind: 'ledger', label: 'Marrow House gate log', stamp: 'COPY',
      source: 'MARROW HOUSE · GATE', title: 'Gate log, the 9th',
      body: ['23:40 — gate open — S.C. 01:00 — gate closed — S.C. Between the lines, in pencil, rubbed out and legible when the page is tilted: B.A., OUT.'],
      spoken: 'The Marrow House gate log, with a rubbed-out name legible when the page is tilted.',
      reading: 'Beatrix Ayre went out through the gate at eleven-forty. Nothing to mark.', about: ['sister', 'matron'], effect: { type: 'none' } },
    { id: 'item:bell:observ-log', at: 'observ', kind: 'note', label: 'Observation log, Dr. Quint',
      source: 'THE OBSERVATORY · LOG', title: 'Night of the 9th',
      body: ['23:30 — cloud. 23:55 — cloud. 00:00 — “tower”. 00:04 — “tower”. 00:30 — cloud. The astronomer was not looking at the sky. She has drawn, in the margin, a small figure on a ladder.'],
      spoken: 'The observatory log: at midnight, not the sky. The tower. And a small figure drawn on a ladder.',
      reading: 'Dr. Quint watched somebody climb down the outside. Ask her who. Nothing to mark.', about: ['astro'], effect: { type: 'none' } },
    { id: 'item:bell:tea-glove', at: 'tearooms', kind: 'note', label: 'A glove left on a chair',
      source: 'TERRACE TEA ROOMS · LOST PROPERTY', title: 'One glove, left hand',
      body: ['A woman’s glove, left hand, grey kid, left on a chair after words at four in the morning. Mrs. Petty saw the hand that took it off. She also saw the hand it belonged to, and the difference.'],
      spoken: 'A left-hand glove, grey kid, left on a chair after words at four in the morning.',
      reading: 'Mrs. Petty saw the hands. It tells you something about Beatrix Ayre. Check her row in the Notebook.', about: ['sister'], effect: { type: 'suspectTrait', suspectId: 'sister' } },
    { id: 'item:bell:report-plates', at: 'bookshop', kind: 'clipping', label: 'Diocesan report, plates torn out',
      source: 'AMSEL’S BOOKS · SECOND-HAND', title: 'Diocesan Report, 1939, plates I–IV',
      body: ['The plates show the crypt, the tower, and the outside of the tower with its iron rungs — the only photograph anyone has of them. Torn out in the doorway tonight and carried off. What is left is a caption: “Rungs to be removed, 1940.” They were not.', 'Amsel knows who bought it and will save you the walk.'],
      spoken: 'A diocesan report with the plates of the tower torn out in the shop doorway.',
      reading: 'Amsel saw who bought it and where they went. Two hours back on the clock.', effect: { type: 'time', hours: -2 } },
    { id: 'item:bell:inn-slate', at: 'inn', kind: 'ledger', label: 'The Lamplighter’s slate',
      source: 'THE LAMPLIGHTER’S ARMS · SLATE', title: 'Tonight',
      body: ['Rudge chalks what the hill owes him. Tonight: “wet boots, two rums, no coin, said he had rung it and laughed.” No name. You will lose an hour finding out it was the drunk who says that every night.'],
      spoken: 'The Lamplighter’s slate: wet boots, two rums, and a man who said he had rung it and laughed.',
      reading: 'It was the drunk who says that every night. An hour wasted.', effect: { type: 'time', hours: 1 } },
  ],

  objects: [
    { id: 'obj:bell:key', at: 'reservoir', name: 'The tower key, with river mud on it', drawing: 'key',
      desc: 'Found on the reservoir walkway. This is the key to the bell tower. It has been in the water.',
      spoken: 'The bell tower key, on the reservoir walkway, with river mud on it.',
      unlocks: [
        { person: 'brannock', line: 'This is the key from the empty hook.', reply: 'It is. It went missing on Thursday. The verger lends it to a boy from the Academy. He thinks I don’t know. The boy meets a girl from Marrow House up there.',
          effect: { type: 'suspectTrait', suspectId: 'verger' } },
        { person: 'verger', line: 'Your key. Found in the reservoir.', reply: 'I lent it to a boy. Blake’s boy, the tall one. He was to bring it back by eleven. He didn’t. I was in my bed, Inspector. I found her at six and I washed the stairs because I could not look at them.',
          effect: { type: 'clear', suspectId: 'verger' } },
      ] },
    { id: 'obj:bell:rosary', at: 'boathouse', name: 'A rosary with a bent cross', drawing: 'rosary',
      desc: 'Found on the far bank of the reservoir, beside the missing oars. The beads are still wet.',
      spoken: 'A rosary on the far bank, the beads wet, the cross bent.',
      unlocks: [
        { person: 'sister', line: 'Is this yours?', reply: 'Mine. I dropped it in the boat. I rowed across because the tram driver would not take me back and I could not walk past the gate. I stood under the tower at midnight. I counted nine. Then I ran.',
          effect: { type: 'clear', suspectId: 'sister' } },
        { person: 'agnes', line: 'Do you know this rosary?', reply: 'Beatrix Ayre’s. I mended the string for her in ’39, before they took her up the hill. She wears it round her wrist. If it came off, she was struggling with something.',
          effect: { type: 'suspectTrait', suspectId: 'sister' } },
      ] },
    { id: 'obj:bell:pass', at: 'asylum', name: 'A Marrow House visitor pass', drawing: 'card',
      desc: 'A visitor’s card for Marrow House, made out to B. Ayre. A patient does not need a visitor pass.',
      spoken: 'A Marrow House visitor pass, made out to B. Ayre.',
      unlocks: [
        { person: 'quaile', line: 'A patient with a visitor pass?', reply: 'Because she isn’t a patient. The Matron writes her up as one every month and takes the family’s money. I’ve watched the Matron sign that form for five years. I know her hand.',
          effect: { type: 'suspectTrait', suspectId: 'matron' } },
        { person: 'matron', line: 'Explain this.', reply: 'She sits down. Beatrix Ayre has never been ill. The family paid me to keep her. Constance came on Thursday and said it would stop. I was in my office at midnight, Inspector. Quaile brought me tea at twelve. Ask him.',
          effect: { type: 'clear', suspectId: 'matron' } },
      ] },
    { id: 'obj:bell:eyepiece', at: 'pawn', name: 'A telescope eyepiece, engraved H.Q.', drawing: 'eyepiece',
      desc: 'Pawned at Hobb’s by somebody who was not the astronomer.',
      spoken: 'A brass telescope eyepiece from the pawnshop, engraved H.Q.',
      unlocks: [
        { person: 'astro', line: 'Yours. Pawned on Tuesday.', reply: 'One of the boys took it. Blake’s third form. I let them use the telescope and one of them steals from me. I was at the eyepiece at midnight, Inspector. I saw the tower. I saw someone come down the outside. I drew them. I will not say who, because I am not sure.',
          effect: { type: 'clear', suspectId: 'astro' } },
        { person: 'hobb', line: 'Who pawned this?', reply: 'A schoolboy. Tall. Academy scarf. He said it was his father’s. He came back on Friday and bought it out with a five-pound note. Schoolboys don’t have five-pound notes. Somebody gave it to him.',
          effect: { type: 'suspectTrait', suspectId: 'tutor' } },
      ] },
    { id: 'obj:bell:glove', at: 'tearooms', name: 'A grey glove, left hand', drawing: 'glove',
      desc: 'Left on a chair at the tea rooms after an argument at four in the morning.',
      spoken: 'A grey kid glove, left hand, from a chair in the tea rooms.',
      unlocks: [
        { person: 'petty', line: 'Whose glove?', reply: 'The younger Ayre girl’s. She argued with the Matron here at four. She took her gloves off to hold her tea and her hands shook so badly she left one behind.',
          effect: { type: 'suspectTrait', suspectId: 'sister' } },
        { person: 'tutor', line: 'Do you know this glove?', reply: 'Beatrix Ayre’s. She came to the Academy on Wednesday and asked me to give her sister a letter. I did. I have not told anyone that. I was at the Observatory at midnight with Dr. Quint and two boys. Ask her.',
          effect: { type: 'lead' } },
      ] },
    { id: 'obj:bell:photo', at: 'bookshop', name: 'A photograph of the tower’s iron rungs', drawing: 'photo',
      desc: 'Torn from a diocese report. It shows iron rungs on the outside of the bell tower, from the top to the ground.',
      spoken: 'A photograph torn from a diocese report: iron rungs on the outside of the tower.',
      unlocks: [
        { person: 'amsel', line: 'Who bought the report?', reply: 'A man who tore the pages out in my doorway and ran. He wanted the only photograph of those rungs to disappear. He had scratched hands and river mud on his shoes. Whoever came down those rungs went into the water after.',
          effect: { type: 'culpritTrait' } },
        { person: 'canon', line: 'These rungs were supposed to be removed in 1940.', reply: 'I never had them removed. There was no money. There is never money. I could not climb them if you paid me, Inspector. Look at me.',
          effect: { type: 'suspectTrait', suspectId: 'canon' } },
      ] },
  ],
  story: {
    backstory: [
      'Sister Constance Ayre was forty-four. She had rung the bell of St. Ordell’s for twenty years. Twelve strokes at midnight, every night, for a hundred and four years before her and twenty with her. She never missed one.',
      'Nine years ago her younger sister Beatrix was put into Marrow House asylum. The family paid for the bed. Constance signed the papers. Three days before she died, Beatrix walked out of Marrow House and came up the hill.',
      'In her last week Constance asked to see the crypt account books, the Marrow House register, and a letter she had written to the Dean about a schoolmaster. She was putting things right. On the hill, that is dangerous.',
      'At midnight on Friday the bell rang nine times. Nine is how many years Beatrix was locked away. By six in the morning Constance was dead at the bottom of the tower stairs, and the bell rope had been cut from the ringing floor.',
    ],
    timeline: [
      { time: '10:00 PM', text: 'The Academy gates are locked. Somebody has a key that is not the porter’s.' },
      { time: '11:40 PM', text: 'The Marrow House gate is logged open. Somebody goes out carrying a bag.' },
      { time: '11:50 PM', text: 'A valve key is signed out at the Water Board, against the Canon’s standing order.' },
      { time: '11:58 PM', text: 'The pump house engines are stopped for four minutes, ‘to listen’.' },
      { time: '12:00 AM', text: 'The bell rings nine times, rung by somebody who does not know how.' },
      { time: '12:02 AM', text: 'Tram car 7 leaves the depot, unsigned. The Observatory log says ‘tower’.' },
      { time: '12:04 AM', text: 'The astronomer sees somebody climb down the outside of the tower.' },
      { time: '1:00 AM', text: 'Somebody crosses the reservoir wall and takes a boat. The Marrow House gate is closed again.' },
      { time: '4:00 AM', text: 'Two women argue in the tea rooms. A glove is left on a chair.' },
      { time: '6:00 AM', text: 'The verger finds Sister Constance at the foot of the stairs.' },
    ],
    truth: [
      'Peter Nane took the tower key from the schoolboy on the reservoir path at eleven. He was at the top of the two hundred and eleven steps when Constance came up to ring twelve.',
      'He struck her from behind, cut the rope so nobody could ring for help, and then rang nine himself, badly, with the cut end. He thought it was what Beatrix wanted. He had taken her flowers every Sunday for four years and built a whole life out of it that she knew nothing about.',
      'He came down the iron rungs on the outside of the tower, cutting his hands, crossed the reservoir wall with the valve key Rosalind Fay had signed out for the Canon, dug up the Canon’s tin box on the way past, and was drinking at the Lamplighter’s by half past one, saying he had rung it, and laughing.',
      'Beatrix Ayre stood under the tower at midnight and counted the bells. She thought her sister was ringing nine for her. She thought it was an apology. She has not been told otherwise. You should be the one to tell her.',
    ],
  },

  epilogue: {
    win: `They ring twelve at midnight again, and the hill pretends that settles it. You stand in
      the wet grass under two hundred and eleven steps of cold stone and count to nine, once, for
      Constance Ayre. Then you go home.`,
    loss: `The diocese gets its discretion. ‘Accidental fall,’ says the certificate, on stairs that
      turn the wrong way. The bell rings twelve. Somebody on this hill hears nine every night for
      the rest of their life. It is not you.`,
  },
};

export default def;
