import type { CaseDef } from '../../types/game-types';

// The Ninth Bell. Cathedral Hill: thirty locations from the tower down to the
// water, twenty people who will talk if the diocese does not hear about it,
// and twenty-six documents, most of them written by people who were lying.

const def: CaseDef = {
  id: 'bell',
  title: 'The Ninth Bell',
  subtitle: 'Cathedral Hill · April 1948',
  tagline: 'The bell rang nine at midnight. By morning the ringer was dead at the foot of her own tower.',
  victim: 'Sister Constance Ayre',
  scene: 'tower',
  difficultyHint: 'Everyone on this hill is lying about something.',
  publicTraits: ['build', 'hair'],
  traitPool: ['hand', 'mark', 'vice', 'scent', 'shoe'],

  briefing: `At midnight the bell of St. Ordell’s rang nine times. It has rung twelve at
    midnight for a hundred and four years. At six in the morning the verger finds Sister
    Constance Ayre at the foot of the tower stair with her keys still in her hand and the back
    of her skull opened up.
    She did not fall. The stair turns the wrong way for that. And somebody climbed two hundred
    and eleven steps in the dark to ring a number that means something to exactly one person
    on this hill. Find out who counts to nine.`,

  radio: [
    'Dispatch to Hill Division. The diocese has asked for discretion. Note the request and ignore it.',
    'The asylum logged an open gate at eleven-forty. They logged it closed again at one.',
    'The bell rope is cut clean. Whoever went up did not come down the stair.',
  ],

  terrain: {
    sea: false, river: true, riverSource: 0.18, riverMouth: 0.5,
    lakeAt: 'reservoir', lakeName: 'THE RESERVOIR', parks: 3,
    districts: [
      { text: 'CATHEDRAL HILL', x: 300, y: 10, rot: -3 },
      { text: 'THE CLOSE', x: 560, y: 380, rot: 2 },
      { text: 'THE TERRACES', x: 960, y: 60, rot: 3 },
      { text: 'LOWER ORDELL', x: 230, y: 780, rot: -2 },
      { text: 'THE WATER', x: 900, y: 740, rot: 2 },
    ],
  },

  locations: [
    // ---- Cathedral Hill
    { id: 'tower', name: 'The Bell Tower', type: 'church', x: 470, y: 110, district: 'Cathedral Hill', desc: 'Two hundred and eleven steps and a rope cut clean through.' },
    { id: 'rectory', name: 'The Rectory', type: 'manor', x: 226, y: 158, district: 'Cathedral Hill', desc: 'Sherry, silence, and a fire that is always already lit.' },
    { id: 'chapterhouse', name: 'The Chapter House', type: 'library', x: 330, y: 260, district: 'Cathedral Hill', desc: 'Four hundred years of parish paper, and an archivist who has read all of it.' },
    { id: 'almshouse', name: 'The Almshouse', type: 'home', x: 170, y: 340, district: 'Cathedral Hill', desc: 'Forty beds, thirty-nine occupied, no register worth the paper.' },
    { id: 'deanery', name: 'Diocesan Office', type: 'office', x: 360, y: 50, district: 'Cathedral Hill', desc: 'Where the diocese asks for discretion, in writing, on headed paper.' },
    { id: 'foundry', name: 'Ordell Bell Foundry', type: 'factory', x: 110, y: 70, district: 'Cathedral Hill', desc: 'Cast the bell in 1844. Knows every crack in it since.' },
    // ---- The Close
    { id: 'division', name: 'Hill Division', type: 'police', x: 480, y: 330, district: 'The Close', desc: 'Three constables and a kettle. Yours, for now.' },
    { id: 'cottage', name: 'Verger’s Cottage', type: 'home', x: 570, y: 200, district: 'The Close', desc: 'Every key on the hill hangs on a board in the kitchen. One hook is empty.' },
    { id: 'green', name: 'The Close Green', type: 'park', x: 640, y: 270, district: 'The Close', desc: 'Wet grass, a sundial, and a clear line of sight to the tower door.' },
    { id: 'academy', name: 'Ordell Academy', type: 'school', x: 716, y: 140, district: 'The Close', desc: 'Boys in grey, out of bed, and nobody counting them.' },
    { id: 'cemetery', name: 'Ordell Cemetery', type: 'cemetery', x: 322, y: 490, district: 'The Close', desc: 'Fresh earth on plot forty-four, and nobody buried there this month.' },
    { id: 'dispensary', name: 'Hill Dispensary', type: 'shop', x: 600, y: 430, district: 'The Close', desc: 'The only chemist on the hill, and the only poisons book.' },
    // ---- The Terraces
    { id: 'observ', name: 'The Observatory', type: 'light', x: 898, y: 252, district: 'The Terraces', desc: 'One telescope pointed at heaven, one window pointed at the hill.' },
    { id: 'glasshouse', name: 'The Glasshouse', type: 'market', x: 656, y: 340, district: 'The Terraces', desc: 'Orchids and orange trees under forty tons of condensation.' },
    { id: 'asylum', name: 'Marrow House', type: 'hospital', x: 872, y: 450, district: 'The Terraces', desc: 'The gate was logged open at eleven-forty. That is all they will tell you.' },
    { id: 'inn', name: 'The Lamplighter’s Arms', type: 'bar', x: 780, y: 380, district: 'The Terraces', desc: 'The only public house on the hill, and the only place the hill says what it thinks.' },
    { id: 'villa', name: 'The Quint Villa', type: 'manor', x: 1010, y: 150, district: 'The Terraces', desc: 'The astronomer’s house. Every curtain open, every light off.' },
    { id: 'bookshop', name: 'Amsel’s Books', type: 'shop', x: 960, y: 340, district: 'The Terraces', desc: 'Second-hand, damp, and the only shop that stocks the diocesan reports.' },
    { id: 'tearooms', name: 'Terrace Tea Rooms', type: 'cafe', x: 1040, y: 430, district: 'The Terraces', desc: 'Where the hill takes its gossip with milk and two sugars.' },
    // ---- Lower Ordell
    { id: 'depot', name: 'The Tram Depot', type: 'tram', x: 164, y: 590, district: 'Lower Ordell', desc: 'Last car up the hill leaves at eleven. Somebody signed it out at midnight.' },
    { id: 'pawn', name: 'Hobb’s Pawn', type: 'shop', x: 220, y: 470, district: 'Lower Ordell', desc: 'A rosary, a telescope eyepiece, and a set of keys on a diocesan ring.' },
    { id: 'mission', name: 'Lower Chapel', type: 'church', x: 290, y: 630, district: 'Lower Ordell', desc: 'The poor parish. Their bell is a handbell, and it rang at midnight too.' },
    { id: 'laundry', name: 'Hill Laundry', type: 'factory', x: 100, y: 710, district: 'Lower Ordell', desc: 'Every surplice and every sheet on the hill, washed by sisters who see the stains.' },
    { id: 'tallow', name: 'Tallow Street', type: 'home', x: 380, y: 730, district: 'Lower Ordell', desc: 'Where the hill’s servants sleep, when they are let.' },
    { id: 'waterboard', name: 'Ordell Water Board', type: 'office', x: 520, y: 610, district: 'Lower Ordell', desc: 'Every gallon that leaves the reservoir is a line here. Every key to the valves is too.' },
    // ---- The Water
    { id: 'reservoir', name: 'The Reservoir', type: 'bridge', x: 614, y: 560, district: 'The Water', desc: 'Black water behind a wall, and a walkway nobody is supposed to use.' },
    { id: 'boathouse', name: 'Reservoir Boathouse', type: 'pier', x: 760, y: 520, district: 'The Water', desc: 'Two skiffs, one missing its oars, and a boatman who keeps a tally.' },
    { id: 'pumphouse', name: 'The Pump House', type: 'factory', x: 720, y: 670, district: 'The Water', desc: 'The engines run all night, loud enough to cover a bell. Almost.' },
    { id: 'crypt', name: 'The Crypt', type: 'bank', x: 888, y: 630, district: 'The Water', desc: 'Four hundred years of the diocese’s dead, and its ledgers.' },
    { id: 'watertower', name: 'Waterworks Tower', type: 'tower', x: 1000, y: 570, district: 'The Water', desc: 'The second-highest thing on the hill. From the top you can see the first.' },
  ],
  edges: [
    ['tower', 'rectory'], ['tower', 'deanery'], ['tower', 'cottage'], ['tower', 'chapterhouse'],
    ['rectory', 'almshouse'], ['rectory', 'foundry'], ['rectory', 'chapterhouse'],
    ['deanery', 'foundry'], ['deanery', 'academy'],
    ['chapterhouse', 'division'], ['chapterhouse', 'almshouse'],
    ['almshouse', 'pawn'], ['almshouse', 'depot'],
    ['cottage', 'green'], ['cottage', 'academy'],
    ['green', 'division'], ['green', 'glasshouse'],
    ['academy', 'villa'], ['academy', 'observ'],
    ['observ', 'villa'], ['observ', 'glasshouse'], ['observ', 'bookshop'],
    ['villa', 'tearooms'],
    ['bookshop', 'tearooms'], ['bookshop', 'asylum'],
    ['tearooms', 'asylum'], ['tearooms', 'watertower'],
    ['glasshouse', 'inn'], ['glasshouse', 'division'],
    ['inn', 'asylum'], ['inn', 'boathouse'],
    ['division', 'cemetery'], ['division', 'dispensary'],
    ['dispensary', 'reservoir'], ['dispensary', 'inn'],
    ['cemetery', 'pawn'], ['cemetery', 'mission'], ['cemetery', 'waterboard'],
    ['pawn', 'depot'],
    ['depot', 'laundry'], ['depot', 'mission'],
    ['mission', 'tallow'],
    ['laundry', 'tallow'],
    ['tallow', 'waterboard'],
    ['waterboard', 'reservoir'],
    ['reservoir', 'boathouse'], ['reservoir', 'pumphouse'],
    ['boathouse', 'crypt'],
    ['pumphouse', 'crypt'],
    ['asylum', 'crypt'], ['asylum', 'watertower'],
    ['crypt', 'watertower'],
  ],
  start: 'division',

  suspects: [
    { id: 'verger', name: 'Cormac Ill', role: 'The verger',
      blurb: 'Found the body. Had already washed the stair when we arrived.',
      motive: 'because she had begun to ask what he does with the keys at night.' },
    { id: 'canon', name: 'Canon Aldritch', role: 'Canon of St. Ordell’s',
      blurb: 'Says he slept through it. His window faces the tower.',
      motive: 'because the crypt ledgers do not survive an honest reading.' },
    { id: 'matron', name: 'Matron Sybil Crake', role: 'Marrow House',
      blurb: 'Logged the gate open at eleven-forty and will not say who went through it.',
      motive: 'because one of her patients is not a patient, and Constance had worked it out.' },
    { id: 'tutor', name: 'Mr. Ewan Blake', role: 'Master at Ordell Academy',
      blurb: 'Boys out of bed. A master who cannot say where he was.',
      motive: 'because she wrote a letter to the diocese and never posted it.' },
    { id: 'astro', name: 'Dr. Halla Quint', role: 'Astronomer',
      blurb: 'Was awake. Was looking. Refuses to say at what.',
      motive: 'because through that telescope she had watched something she could not unsee.' },
    { id: 'gardener', name: 'Peter Nane', role: 'Glasshouse gardener',
      blurb: 'Dug plot forty-four. Nobody is buried in plot forty-four.',
      motive: 'because the grave was dug on Tuesday and the death was on Friday.' },
    { id: 'driver', name: 'Rosalind Fay', role: 'Tram driver',
      blurb: 'Signed a car out of the depot at midnight and brought it back wet.',
      motive: 'because the last car up the hill carried a passenger she was paid to forget.' },
    { id: 'sister', name: 'Sister Beatrix Ayre', role: 'The victim’s sister',
      blurb: 'Arrived on the hill three days ago. Has not explained why.',
      motive: 'because nine is how many years Constance let her rot in Marrow House.' },
  ],

  witnesses: [
    { id: 'tull', at: 'rectory', name: 'Ivy Tull', role: 'housekeeper, the Rectory',
      intro: 'Mrs. Tull. I keep the Canon’s house, and I know who comes to his door and what they want from him.',
      knows: ['canon', 'verger', 'sister'],
      aboutLine: 'Takes tea in this house. I have poured it, and I have watched.',
      leadLine: 'Somebody came down the hill in the dark and left by the garden. There were footprints toward',
      spentLine: 'The Canon would not want me talking. Neither do I.' },
    { id: 'wick', at: 'academy', name: 'Josiah Wick', role: 'porter, Ordell Academy',
      intro: 'Wick. I lock the gates at ten. Tonight somebody had a key that was not mine.',
      knows: ['tutor', 'astro'],
      aboutLine: 'On the staff, or near enough. I see them every morning across the quad.',
      leadLine: 'A boy found something on the playing fields at dawn and was too frightened to say. It went to',
      spentLine: 'The gate is shut and I have a bell to ring in three hours.' },
    { id: 'greer', at: 'almshouse', name: 'Mother Greer', role: 'resident, the Almshouse',
      intro: 'They call me Mother Greer. Seventy-one years in this parish. I have buried two of the people you are looking for and will bury a third.',
      knows: ['matron', 'gardener', 'driver'],
      aboutLine: 'I have known that one since they were small. Small people become large people; they do not become different ones.',
      leadLine: 'I do not sleep. I heard the side door and saw somebody carry a bundle toward',
      spentLine: 'I am tired, child. Come back when it is light and bring biscuits.' },
    { id: 'marley', at: 'depot', name: 'Fen Marley', role: 'night dispatcher, the Tram Depot',
      intro: 'Marley. I sign the cars out and in. Last car is eleven. Tonight one went out at midnight and I did not sign it.',
      knows: ['driver', 'tutor', 'sister'],
      aboutLine: 'Rides the last car. You learn a person by which seat they take.',
      leadLine: 'A parcel came off the midnight car and was left on the bench. It was taken up to',
      spentLine: 'The schedule is the schedule and I have said what I know.' },
    { id: 'lister', at: 'glasshouse', name: 'Bo Lister', role: 'stoker, the Glasshouse',
      intro: 'Lister. I keep the boilers so the orchids do not freeze. It is warmer in here than anywhere in the parish, so people come.',
      knows: ['gardener', 'astro', 'matron'],
      aboutLine: 'Comes in to get warm. You see a person plainly in this light.',
      leadLine: 'Somebody burned something in my firebox tonight and did not burn all of it. What was left went up the hill to',
      spentLine: 'The boilers need me. The police do not.' },
    { id: 'grimm', at: 'cemetery', name: 'Silas Grimm', role: 'gravedigger',
      intro: 'Grimm. I dig. Tonight I found a hole I had not dug, and I want to know who did.',
      knows: ['verger', 'canon'],
      aboutLine: 'Stands over graves I dig. You see what a person is at a funeral.',
      leadLine: 'Fresh earth was moved and something was taken out of it, not put in. The cart tracks run to',
      spentLine: 'I have a hole to fill and I have already said too much.' },
    { id: 'ansell', at: 'foundry', name: 'Hew Ansell', role: 'bell founder',
      intro: 'Ansell. My grandfather cast that bell and I have tuned it every Easter since I could hold a hammer. I know its voice. Last night it was rung by somebody who does not.',
      knows: ['verger', 'canon'],
      aboutLine: 'Has been up the tower with me. You learn a person by how they climb.',
      leadLine: 'A clapper bolt was taken from my bench last week and I found it this morning, dropped on the path toward',
      spentLine: 'The furnace is lit and I am not.' },
    { id: 'pym', at: 'chapterhouse', name: 'Dorcas Pym', role: 'archivist, the Chapter House',
      intro: 'Miss Pym. Four hundred years of parish paper and I have read all of it. Sister Constance came to me last week for the crypt ledgers, and I gave them to her.',
      knows: ['canon', 'tutor', 'astro'],
      aboutLine: 'Reads here. You can tell a person by which volumes they ask for.',
      leadLine: 'A page was razored from the 1939 register tonight by somebody who knew which page. They left toward',
      spentLine: 'The reading room closes at dusk and it is well past dusk.' },
    { id: 'oakes', at: 'deanery', name: 'Cyrus Oakes', role: 'clerk, Diocesan Office',
      intro: 'Oakes. I type the diocese’s letters, including the one asking you for discretion. I did not agree with it.',
      knows: ['canon', 'matron', 'tutor'],
      aboutLine: 'Comes before the Dean. You notice a person who is nervous in front of a bishop.',
      leadLine: 'A letter arrived for the Dean by hand at one in the morning and was burned unread. The ash is at',
      spentLine: 'I have said more than the diocese would like. That is the end of it.' },
    { id: 'brannock', at: 'cottage', name: 'Mrs. Brannock', role: 'housekeeper, Verger’s Cottage',
      intro: 'Brannock. I do for the verger. I know which hook every key hangs on and which one has been empty since Thursday.',
      knows: ['verger', 'sister'],
      aboutLine: 'Comes to this kitchen. You learn a person by how they look at the key board.',
      leadLine: 'The missing key came back this morning with river mud on it. The mud is from',
      spentLine: 'The kitchen is mine and I am closing it.' },
    { id: 'lamb', at: 'dispensary', name: 'Enid Lamb', role: 'dispenser, Hill Dispensary',
      intro: 'Lamb. I keep the poisons book for the hill. It is a short book with long names in it.',
      knows: ['matron', 'astro', 'gardener'],
      aboutLine: 'Signs my book. You notice the hand that signs for chloral.',
      leadLine: 'Somebody came in at dawn for lint and iodine and paid with a coin that was still wet. They went to',
      spentLine: 'The shop is shut and the book is locked.' },
    { id: 'quaile', at: 'asylum', name: 'Sam Quaile', role: 'orderly, Marrow House',
      intro: 'Quaile. Nights on the east ward. I know who is a patient here and who is only wearing the gown.',
      knows: ['matron', 'sister', 'tutor'],
      aboutLine: 'On my ward, or visiting it. You learn a person by how they behave behind a locked door.',
      leadLine: 'The gate was open at eleven-forty and somebody went out through it carrying a bag. They went down toward',
      spentLine: 'Matron would have my post for this. Out.' },
    { id: 'hobb', at: 'pawn', name: 'Zeb Hobb', role: 'pawnbroker',
      intro: 'Hobb. Everything the hill is ashamed of comes through this door eventually. Last week it was a set of keys on a diocesan ring.',
      knows: ['driver', 'gardener', 'verger'],
      aboutLine: 'Pledges with me. I look at the hands that push things across.',
      leadLine: 'The keys were redeemed at midnight by a different hand, and the hand went up the lane to',
      spentLine: 'Shop is shut. Come back with a pledge or not at all.' },
    { id: 'amsel', at: 'bookshop', name: 'Old Amsel', role: 'bookseller',
      intro: 'Amsel. Second-hand. I sell the hill its own history back to it, and I know who buys which chapter.',
      knows: ['astro', 'tutor', 'canon'],
      aboutLine: 'Browses here. You learn a person by what they do not buy.',
      leadLine: 'A diocesan report was bought tonight and its plates torn out in my own doorway. The torn pages went toward',
      spentLine: 'The shop is closed. So is the subject.' },
    { id: 'petty', at: 'tearooms', name: 'Mrs. Petty', role: 'proprietress, Terrace Tea Rooms',
      intro: 'Petty. Milk and two sugars for the whole hill, and every word said over it. I pour and I remember.',
      knows: ['astro', 'sister', 'matron'],
      aboutLine: 'Takes tea here. I have set a cup down in front of them and watched them lift it.',
      leadLine: 'Two women had words here at four and one of them left a glove on the chair. The glove was collected by somebody else, who went to',
      spentLine: 'The urn is cold and so am I.' },
    { id: 'rudge', at: 'inn', name: 'Tam Rudge', role: 'landlord, the Lamplighter’s Arms',
      intro: 'Rudge. Only public house on the hill. Everything the hill says out loud, it says in here first.',
      knows: ['gardener', 'driver', 'verger'],
      aboutLine: 'Drinks in my house. You see a person clearest after the third.',
      leadLine: 'A man came in with wet boots and a dry throat and left without paying. He went out the back toward',
      spentLine: 'Time, gentlemen. That includes you.' },
    { id: 'shale', at: 'pumphouse', name: 'Wat Shale', role: 'pumpman, the Pump House',
      intro: 'Shale. I keep the engines running all night. They are loud enough to cover a bell. Not nine of them.',
      knows: ['gardener', 'driver'],
      aboutLine: 'Passes the engine house at night. You learn a person by how they walk past a noise.',
      leadLine: 'Somebody used the valve walkway at one in the morning and dropped something in the sluice. It fetched up at',
      spentLine: 'The engines do not stop and neither can I.' },
    { id: 'ferris', at: 'boathouse', name: 'Old Ferris', role: 'boatman, the Reservoir',
      intro: 'Ferris. Two skiffs and a tally. One skiff went out tonight without a tally and came back without its oars.',
      knows: ['astro', 'gardener'],
      aboutLine: 'Takes a skiff out sometimes. You learn a person by how they row.',
      leadLine: 'The oars were found on the far bank this morning, and beside them a set of prints going up to',
      spentLine: 'The water is cold and I am colder. Go.' },
    { id: 'agnes', at: 'laundry', name: 'Sister Agnes', role: 'laundress, Hill Laundry',
      intro: 'Sister Agnes. Every surplice and every sheet on the hill comes through my coppers. I see what people would rather I did not.',
      knows: ['sister', 'matron'],
      aboutLine: 'Sends their linen here. You learn a great deal from a person’s linen.',
      leadLine: 'A cassock came in at dawn with mud to the knee and a tear at the shoulder. The bundle it came in was sent back to',
      spentLine: 'The coppers are boiling and I have said my piece.' },
    { id: 'coyle', at: 'waterboard', name: 'Hettie Coyle', role: 'clerk, Ordell Water Board',
      intro: 'Coyle. Every gallon that leaves the reservoir is a line in my book, and every key to the valves hangs behind me. One did not come back last night.',
      knows: ['canon', 'driver'],
      aboutLine: 'Comes for the valve key. You learn a person by how they sign for it.',
      leadLine: 'The valve key came back at three with somebody else’s initials in the book. That somebody walked out toward',
      spentLine: 'The board is closed. Good night.' },
  ],

  items: [
    { id: 'item:bell:rope', at: 'tower', kind: 'report', label: 'The bell rope, examined',
      source: 'HILL DIVISION · SCENE EXAMINATION', title: 'Bell rope, the tower',
      fields: [['Cut', 'clean, one stroke, from below'], ['Height of cut', 'five feet three from the ringing floor'], ['Fibres', 'pulled downward']],
      body: ['One stroke, from below, at five foot three. Whoever cut the rope did not climb to do it and did not reach up much to do it either.'],
      spoken: 'The bell rope, cut clean in one stroke from below, at five foot three.',
      reading: 'A cut at five foot three by someone standing on the floor. A thought about height, not a fact.', effect: { type: 'none' } },
    { id: 'item:bell:sherry', at: 'rectory', kind: 'receipt', label: 'The Canon’s wine merchant, account',
      source: 'HARDACRE & SONS · WINE MERCHANTS', title: 'Account, the Rectory, April',
      body: ['Twelve of sherry, six of port, and a note from the merchant: “Canon — the crypt fund cheque was returned again. We must ask.” Mrs. Tull has watched him drink the twelve.'],
      spoken: 'The Canon’s wine account, and a note about a returned cheque.',
      reading: 'The housekeeper knows what he drinks and how. Ask her about the Canon.', about: ['canon'], effect: { type: 'suspectTrait', suspectId: 'canon' } },
    { id: 'item:bell:crypt-ledger', at: 'chapterhouse', kind: 'ledger', label: 'Crypt ledger, 1939, page razored', stamp: 'CONFIDENTIAL',
      source: 'THE CHAPTER HOUSE · CRYPT REGISTER', title: 'Interments, 1939',
      body: ['Plot forty-four: a name, a date, a fee of forty pounds, and the page it was on razored out tonight. The stub is still in the binding, and Miss Pym knows which page it was because she gave it to Constance last week.', 'Whoever cut it left a fingerprint in the glue.'],
      spoken: 'The crypt ledger with a page razored out tonight, and a fingerprint in the glue.',
      reading: 'Somebody wanted plot forty-four forgotten. Story, and a place.', about: ['canon', 'gardener'], effect: { type: 'lead' } },
    { id: 'item:bell:register', at: 'almshouse', kind: 'ledger', label: 'Almshouse register, such as it is',
      source: 'THE ALMSHOUSE · REGISTER', title: 'Beds, night of the 9th',
      body: ['Forty beds, thirty-nine names, one bed slept in that has no name against it. Mother Greer says the fortieth has been sleeping there on and off for nine years and pays in kind.'],
      spoken: 'The almshouse register: forty beds, thirty-nine names.',
      reading: 'Somebody has a bed here they do not sign for. Story.', effect: { type: 'none' } },
    { id: 'item:bell:discretion', at: 'deanery', kind: 'letter', label: 'The diocese asks for discretion', stamp: 'RECEIVED',
      source: 'DIOCESE OF ORDELL · THE DEAN', title: 'To the Superintendent, Hill Division',
      body: ['“…the Dean is confident the Division will treat the matter with the discretion due to the Cathedral’s standing, and will not find it necessary to trouble the Canon or the Matron of Marrow House beyond what is strictly required.”', 'Typed by Oakes, who has underlined “beyond what is strictly required” and initialled the underlining.'],
      spoken: 'The diocese asks for discretion, in writing, on behalf of the Canon and the Matron.',
      reading: 'The diocese is protecting two people by name. Story.', about: ['canon', 'matron'], effect: { type: 'none' } },
    { id: 'item:bell:tuning', at: 'foundry', kind: 'note', label: 'Founder’s tuning notes',
      source: 'ORDELL BELL FOUNDRY · BENCH BOOK', title: 'St. Ordell’s tenor, Easter 1948',
      body: ['“Rung nine at midnight by a hand that lets the rope go at the top of the stroke. Not a ringer. Somebody who has watched ringing and never done it.” In the founder’s hand, dated this morning.'],
      spoken: 'The bell founder’s note: rung by a hand that lets the rope go at the top of the stroke.',
      reading: 'Not a ringer, but somebody who has watched. Story, and a narrowing.', effect: { type: 'none' } },
    { id: 'item:bell:key-board', at: 'cottage', kind: 'photo', label: 'Photograph, the key board',
      source: 'HILL DIVISION · PHOTOGRAPHIC UNIT', title: 'Plate 3: the verger’s key board',
      body: ['Forty hooks, thirty-nine keys, and the empty hook labelled TOWER in the verger’s hand. In the flash, the verger himself, caught in the doorway, and something about him the constable did not notice at the time.'],
      spoken: 'A photograph of the key board with the tower hook empty, and the verger in the doorway.',
      reading: 'The flash caught the verger. Look at him.', about: ['verger'], effect: { type: 'suspectTrait', suspectId: 'verger' } },
    { id: 'item:bell:sundial', at: 'green', kind: 'note', label: 'Chalk on the sundial',
      source: 'THE CLOSE GREEN · SUNDIAL', title: 'Chalked on the dial',
      body: ['IX, in chalk, on the sundial, at the hour it would have shown had there been a sun. Below it, a small drawn bell. The rain has taken the rest.'],
      spoken: 'Nine, in chalk, on the sundial, with a small drawn bell.',
      reading: 'Somebody wanted the hill to count. Story.', effect: { type: 'none' } },
    { id: 'item:bell:unposted', at: 'academy', kind: 'letter', label: 'Constance’s unposted letter', stamp: 'PERSONAL',
      source: 'FOUND IN A MASTER’S DESK, ORDELL ACADEMY', title: 'To the Dean, unposted',
      body: ['“…I must therefore report that Mr. Blake has been seen with the boys of the third form at the Observatory after lights out on three occasions, and that Dr. Quint has declined to say what they were shown. — C. Ayre.” Sealed, stamped, never posted, and found in the desk of the man it names.'],
      spoken: 'Constance’s letter to the Dean, sealed and never posted, found in Blake’s own desk.',
      reading: 'Blake had the letter that would have ruined him. A motive on paper.', about: ['tutor', 'astro'], effect: { type: 'none' } },
    { id: 'item:bell:plot44', at: 'cemetery', kind: 'report', label: 'Plot forty-four, examined',
      source: 'HILL DIVISION · SCENE EXAMINATION', title: 'Plot 44, Ordell Cemetery',
      fields: [['Dug', 'Tuesday, by the gardener'], ['Depth', 'four feet, not six'], ['Contents', 'empty — and then, under the loose fill, a tin box, empty too']],
      body: ['A grave dug three days before a death, and a tin box in it that somebody emptied tonight. The gravedigger did not dig it; the gardener did.'],
      spoken: 'Plot forty-four: dug Tuesday, four feet deep, and a tin box in it emptied tonight.',
      reading: 'Nane dug a grave for something that was not a body. Story.', about: ['gardener'], effect: { type: 'none' } },
    { id: 'item:bell:poisons', at: 'dispensary', kind: 'ledger', label: 'Poisons book, chloral', stamp: 'CONFIDENTIAL',
      source: 'HILL DISPENSARY · POISONS BOOK', title: 'Entries, April',
      body: ['Chloral hydrate, two drachms, signed S. CRAKE, for Marrow House, the 8th. Miss Lamb watched her sign, as she has watched her sign every month for eleven years.'],
      spoken: 'The poisons book: chloral for Marrow House, signed by the Matron on the eighth.',
      reading: 'Lamb has watched Crake sign for eleven years. Ask her about the Matron.', about: ['matron'], effect: { type: 'suspectTrait', suspectId: 'matron' } },
    { id: 'item:bell:eyepiece', at: 'pawn', kind: 'ticket', label: 'Pawn ticket, one eyepiece',
      source: 'HOBB’S PAWN · TICKETS', title: 'Ticket no. 114',
      fields: [['Item', 'telescope eyepiece, brass, engraved H.Q.'], ['Pledged', 'the 7th'], ['By', 'not the astronomer']],
      body: ['Dr. Quint’s eyepiece, pledged by somebody who is not Dr. Quint, two days before the bell. Hobb looked at the hands that pledged it.'],
      spoken: 'A pawn ticket for the astronomer’s eyepiece, pledged by somebody else.',
      reading: 'Somebody took a thing from the Observatory and needed money. Story.', about: ['astro'], effect: { type: 'none' } },
    { id: 'item:bell:depot-sheet', at: 'depot', kind: 'ledger', label: 'Depot sign-out sheet',
      source: 'THE TRAM DEPOT · CARS', title: 'Sign-out, night of the 9th',
      body: ['Car 7 — out 00:02 — R. FAY — back 00:51 — “wet”. The dispatcher did not sign it and does not know how she got the key. He watched her bring it back, and what she did with her hands while he asked.'],
      spoken: 'The depot sheet: car seven out at two minutes past midnight, signed Fay, back at ten to one, wet.',
      reading: 'Marley watched her bring the car back. Ask him about the driver.', about: ['driver'], effect: { type: 'suspectTrait', suspectId: 'driver' } },
    { id: 'item:bell:handbell', at: 'mission', kind: 'note', label: 'The Lower Chapel handbell',
      source: 'LOWER CHAPEL · VESTRY', title: 'A note pinned to the bell',
      body: ['“Rung nine at midnight in answer. She would have wanted it answered.” Unsigned, in a careful hand, pinned to the handbell in the poor parish’s vestry.'],
      spoken: 'A note pinned to the Lower Chapel handbell: rung nine at midnight in answer.',
      reading: 'Somebody down the hill knew what nine meant. Story.', effect: { type: 'none' } },
    { id: 'item:bell:cassock', at: 'laundry', kind: 'report', label: 'Laundry ticket, one cassock',
      source: 'HILL LAUNDRY · TICKETS', title: 'Ticket, the 10th, dawn',
      fields: [['Item', 'cassock, black'], ['Condition', 'mud to the knee, tear at the right shoulder'], ['From', 'the Rectory bundle']],
      body: ['A cassock in the Rectory’s bundle with river mud to the knee. The Canon is not the only man on the hill who wears one, but he is the only one whose laundry comes from the Rectory.'],
      spoken: 'A laundry ticket for a cassock with river mud to the knee, from the Rectory bundle.',
      reading: 'Somebody at the Rectory was in the river. Story.', about: ['canon'], effect: { type: 'none' } },
    { id: 'item:bell:tallow-note', at: 'tallow', kind: 'note', label: 'A servant’s note, Tallow Street',
      source: 'FOUND UNDER A DOOR, TALLOW STREET', title: 'To whoever finds this',
      body: ['“I saw the light go up the tower and I saw it come down the outside. I will not say where. If I am asked I will say I was asleep. — A.”', 'Somebody wanted it known and did not want to be the one who knew it.'],
      spoken: 'A note pushed under a door on Tallow Street: I saw the light come down the outside.',
      reading: 'Whoever went up did not come down the stair. The radio said as much. Story.', effect: { type: 'none' } },
    { id: 'item:bell:valve-book', at: 'waterboard', kind: 'ledger', label: 'Valve key book',
      source: 'ORDELL WATER BOARD · KEYS', title: 'Valve keys, the 9th',
      body: ['Key 3 out at 23:50 against the Canon’s standing order, returned 03:00 with initials that are not his. The walkway it opens runs along the top of the reservoir wall, and the wet prints on it run one way.'],
      spoken: 'The valve key book: key three out at ten to midnight and back at three with the wrong initials.',
      reading: 'The prints on the walkway go somewhere. Follow them.', effect: { type: 'lead' } },
    { id: 'item:bell:wall-prints', at: 'reservoir', kind: 'cast', label: 'Prints on the reservoir wall',
      source: 'HILL DIVISION · CASTS AND IMPRESSIONS', title: 'The walkway, reservoir wall',
      body: ['A line of wet prints along the walkway at one, photographed before the rain took them. They come from the pump house side and go toward the boathouse, and they were made by somebody in a hurry who did not look down.'],
      spoken: 'Prints along the reservoir wall, from the pump house toward the boathouse.',
      reading: 'Somebody crossed the wall in the dark. Story.', effect: { type: 'none' } },
    { id: 'item:bell:oars', at: 'boathouse', kind: 'report', label: 'The missing oars, found',
      source: 'RESERVOIR BOATHOUSE · TALLY', title: 'Skiff 2, oars',
      body: ['Found on the far bank at dawn, beside a set of prints, and a dropped thing the boatman turned over with his foot and did not pick up: a rosary, the beads wet, the cross bent.'],
      spoken: 'The missing oars on the far bank, and beside them a wet rosary with the cross bent.',
      reading: 'A rosary on the far bank. The sisters have rosaries. So does everyone on this hill.', about: ['sister'], effect: { type: 'none' } },
    { id: 'item:bell:engine-log', at: 'pumphouse', kind: 'ledger', label: 'Engine log, the Pump House',
      source: 'THE PUMP HOUSE · ENGINE LOG', title: 'Night of the 9th',
      body: ['23:58 — engines stopped, four minutes, “to listen”. 00:02 — restarted. In four minutes of quiet on the hill, Shale heard nine, and counted them, and wrote the number down.'],
      spoken: 'The engine log: the pumps stopped for four minutes at two minutes to midnight, to listen.',
      reading: 'The pumpman stopped his engines to hear the bell. Story.', effect: { type: 'none' } },
    { id: 'item:bell:crypt-tin', at: 'crypt', kind: 'report', label: 'The crypt fund, counted', stamp: 'CONFIDENTIAL',
      source: 'THE CRYPT · FUND BOX', title: 'Crypt restoration fund',
      fields: [['Should hold', '£412'], ['Holds', '£31'], ['Signatures on withdrawals', 'one, throughout']],
      body: ['Four hundred pounds gone from a box with one signature on every slip. Constance had asked to see the box on Thursday. On Friday she was dead.'],
      spoken: 'The crypt fund: four hundred pounds gone, one signature on every slip.',
      reading: 'A motive with a sum attached. Not a hand or a hair.', about: ['canon'], effect: { type: 'none' } },
    { id: 'item:bell:tower-view', at: 'watertower', kind: 'photo', label: 'Photograph from the Waterworks Tower',
      source: 'HILL DIVISION · PHOTOGRAPHIC UNIT', title: 'Plate 9: the bell tower, from the water tower',
      body: ['Taken at dawn with a long lens: the tower, the stair window, and on the outside of the tower a line of iron rungs the diocese had forgotten about, running from the ringing floor to the ground. The bottom rung is bright where the rust has been worn off tonight.'],
      spoken: 'A photograph from the water tower: iron rungs on the outside of the bell tower, the bottom one bright.',
      reading: 'Whoever went up came down the outside. Story, and how.', effect: { type: 'none' } },
    { id: 'item:bell:gate-log', at: 'asylum', kind: 'ledger', label: 'Marrow House gate log', stamp: 'COPY',
      source: 'MARROW HOUSE · GATE', title: 'Gate log, the 9th',
      body: ['23:40 — gate open — S.C. 01:00 — gate closed — S.C. Between the lines, in pencil, rubbed out and legible when the page is tilted: B.A., OUT.'],
      spoken: 'The Marrow House gate log, with a rubbed-out name legible when the page is tilted.',
      reading: 'Beatrix Ayre went out through the gate at twenty to midnight. Story, and a cold one.', about: ['sister', 'matron'], effect: { type: 'none' } },
    { id: 'item:bell:observ-log', at: 'observ', kind: 'note', label: 'Observation log, Dr. Quint',
      source: 'THE OBSERVATORY · LOG', title: 'Night of the 9th',
      body: ['23:30 — cloud. 23:55 — cloud. 00:00 — “tower”. 00:04 — “tower”. 00:30 — cloud. The astronomer was not looking at the sky. She has drawn, in the margin, a small figure on a ladder.'],
      spoken: 'The observatory log: at midnight, not the sky. The tower. And a small figure drawn on a ladder.',
      reading: 'Quint watched somebody come down the outside. Story.', about: ['astro'], effect: { type: 'none' } },
    { id: 'item:bell:tea-glove', at: 'tearooms', kind: 'note', label: 'A glove left on a chair',
      source: 'TERRACE TEA ROOMS · LOST PROPERTY', title: 'One glove, left hand',
      body: ['A woman’s glove, left hand, grey kid, left on a chair after words at four in the morning. Mrs. Petty saw the hand that took it off. She also saw the hand it belonged to, and the difference.'],
      spoken: 'A left-hand glove, grey kid, left on a chair after words at four in the morning.',
      reading: 'Mrs. Petty saw the hands. Ask her about the sister.', about: ['sister'], effect: { type: 'suspectTrait', suspectId: 'sister' } },
    { id: 'item:bell:report-plates', at: 'bookshop', kind: 'clipping', label: 'Diocesan report, plates torn out',
      source: 'AMSEL’S BOOKS · SECOND-HAND', title: 'Diocesan Report, 1939, plates I–IV',
      body: ['The plates show the crypt, the tower, and the outside of the tower with its iron rungs — the only photograph anyone has of them. Torn out in the doorway tonight and carried off. What is left is a caption: “Rungs to be removed, 1940.” They were not.', 'Amsel knows who bought it and will save you the walk.'],
      spoken: 'A diocesan report with the plates of the tower torn out in the shop doorway.',
      reading: 'Amsel saw the buyer and knows where they went. Time saved.', effect: { type: 'time', hours: -2 } },
    { id: 'item:bell:inn-slate', at: 'inn', kind: 'ledger', label: 'The Lamplighter’s slate',
      source: 'THE LAMPLIGHTER’S ARMS · SLATE', title: 'Tonight',
      body: ['Rudge chalks what the hill owes him. Tonight: “wet boots, two rums, no coin, said he had rung it and laughed.” No name. You will lose an hour finding out it was the drunk who says that every night.'],
      spoken: 'The Lamplighter’s slate: wet boots, two rums, and a man who said he had rung it and laughed.',
      reading: 'It was the drunk who says that every night. An hour gone.', effect: { type: 'time', hours: 1 } },
  ],

  objects: [],
  story: { backstory: [], timeline: [], truth: [] },

  epilogue: {
    win: `They ring twelve at midnight again, and the hill pretends that settles it. You stand
      in the wet grass under two hundred and eleven steps of cold stone and you count to nine,
      once, for Constance Ayre, and then you go home.`,
    loss: `The diocese gets its discretion. Accidental fall, says the certificate, on a stair
      that turns the wrong way. The bell rings twelve. Somebody on this hill hears nine every
      night for the rest of their life, and it is not you.`,
  },
};

export default def;
