import type { CaseDef } from '../../types/game-types';

// The Ash and the Orchid. Thirty locations in five quarters of Ashgrave Bay,
// twenty people who will talk, and twenty-six documents scattered through the
// city -- some of which matter.

const def: CaseDef = {
  id: 'orchid',
  title: 'The Ash and the Orchid',
  subtitle: 'Ashgrave Bay · November 1947',
  tagline: 'A singer is dead in the best suite in the city. Nobody heard a thing.',
  victim: 'Lillian Voss',
  scene: 'gilded',
  difficultyHint: 'A good first case.',
  publicTraits: ['build', 'hair'],
  traitPool: ['hand', 'mark', 'vice', 'scent', 'shoe'],

  briefing: `Two-oh-nine in the morning. The house detective opens suite eleven-hundred.
    Lillian Voss is face down on the silk. No gun. No scream. The orchid on her table is
    snapped at the stem, and somebody put it back in the vase.
    Eleven floors. Forty-one guests. One night clerk. Nobody heard a thing.
    The trail goes cold in two days. Work fast.`,

  radio: [
    'All cars. The Gilded Hotel. The coroner is already inside.',
    'The Voss lawyers are awake. That is a warning.',
    'The Herald had a man in the lobby before we did. Ask how.',
  ],

  terrain: {
    sea: true, seaName: 'ASHGRAVE BAY', river: true, riverSource: 0.5, riverMouth: 0.56,
    parks: 3,
    districts: [
      { text: 'THE HEIGHTS', x: 260, y: 30, rot: -3 },
      { text: 'OLD TOWN', x: 640, y: 240, rot: 2 },
      { text: 'LANTERN QUARTER', x: 990, y: 40, rot: 3 },
      { text: 'THE FLATS', x: 200, y: 420, rot: -2 },
      { text: 'THE BLUFF', x: 1010, y: 560, rot: 2 },
    ],
  },

  locations: [
    // ---- The Heights
    { id: 'gilded', name: 'The Gilded Hotel', type: 'hotel', x: 150, y: 120, district: 'The Heights', desc: 'Brass and marble. Eleven floors of people paying not to be seen.' },
    { id: 'herald', name: 'The Ashgrave Herald', type: 'press', x: 340, y: 90, district: 'The Heights', desc: 'The presses run all night. Ink, sweat, everybody’s business.' },
    { id: 'lyceum', name: 'The Lyceum', type: 'theatre', x: 260, y: 230, district: 'The Heights', desc: 'Velvet and gilt. The Voss box has been theirs since 1910.' },
    { id: 'belvedere', name: 'Café Belvedere', type: 'cafe', x: 110, y: 290, district: 'The Heights', desc: 'Open all night, for people who cannot go home yet.' },
    { id: 'gardens', name: 'Ordell Gardens', type: 'park', x: 430, y: 190, district: 'The Heights', desc: 'Wet gravel, black iron, a bandstand nobody plays.' },
    { id: 'trust', name: 'Ashgrave Trust', type: 'bank', x: 480, y: 310, district: 'The Heights', desc: 'Granite outside. Brass inside. The vault opens for the right surname.' },
    // ---- Old Town
    { id: 'precinct', name: 'Ashgrave Precinct', type: 'police', x: 620, y: 340, district: 'Old Town', desc: 'Home. Bad coffee, one working telephone.' },
    { id: 'cathedral', name: 'St. Ordell’s', type: 'church', x: 570, y: 150, district: 'Old Town', desc: 'Cold stone. Colder charity.' },
    { id: 'mercy', name: 'Mercy Hospital', type: 'hospital', x: 740, y: 110, district: 'Old Town', desc: 'Ether and disinfectant. Bad records, kept well.' },
    { id: 'market', name: 'Lantern Market', type: 'market', x: 720, y: 300, district: 'Old Town', desc: 'Open till dawn. Everything for sale. Receipts optional.' },
    { id: 'library', name: 'Carnegie Library', type: 'library', x: 480, y: 440, district: 'Old Town', desc: 'Every back number of the Herald, and one reader who never leaves.' },
    { id: 'exchange', name: 'Central Exchange', type: 'office', x: 650, y: 480, district: 'Old Town', desc: 'Forty switchboards. Every call in the city, through somebody’s ears.' },
    { id: 'morgue', name: 'City Morgue', type: 'morgue', x: 820, y: 430, district: 'Old Town', desc: 'Tile, ice, and the last honest register in Ashgrave.' },
    { id: 'tram', name: 'Tram Terminus', type: 'tram', x: 560, y: 570, district: 'Old Town', desc: 'The last car up the Heights leaves at one. Somebody was on it.' },
    // ---- Lantern Quarter
    { id: 'jade', name: 'The Jade Room', type: 'club', x: 900, y: 200, district: 'Lantern Quarter', desc: 'Where Lillian sang before the Gilded found her. Her photograph is still up.' },
    { id: 'imports', name: 'Mireaux Imports', type: 'florist', x: 1010, y: 120, district: 'Lantern Quarter', desc: 'Orchids in the window. Crates in the back that were never orchids.' },
    { id: 'pharmacy', name: 'Pike’s Pharmacy', type: 'shop', x: 870, y: 320, district: 'Lantern Quarter', desc: 'Brass scales, glass jars, and a poisons register full of initials.' },
    { id: 'baths', name: 'Lantern Baths', type: 'bathhouse', x: 1050, y: 300, district: 'Lantern Quarter', desc: 'Steam and tile. Lockers rented by the hour and by the year.' },
    { id: 'cannery', name: 'The Old Cannery', type: 'factory', x: 980, y: 450, district: 'Lantern Quarter', desc: 'Shut since ’41. Still lit at night.' },
    { id: 'ferry', name: 'Ferry Landing', type: 'pier', x: 1130, y: 480, district: 'Lantern Quarter', desc: 'Last crossing at one-forty. The steward remembers faces, not names.' },
    // ---- The Flats
    { id: 'parrot', name: 'The Blue Parrot', type: 'bar', x: 150, y: 480, district: 'The Flats', desc: 'A jazz club with a back room and a worse reputation.' },
    { id: 'tenement', name: 'Tenement Row', type: 'home', x: 90, y: 610, district: 'The Flats', desc: 'Nine families to a landing. Everyone sees. Nobody says.' },
    { id: 'pawn', name: 'Cobb’s Pawnshop', type: 'shop', x: 300, y: 530, district: 'The Flats', desc: 'Where the city leaves what it cannot look at any more.' },
    { id: 'garage', name: 'Rainer Garage', type: 'garage', x: 250, y: 670, district: 'The Flats', desc: 'Two pits, one hoist, and every dented wing on the Bluff.' },
    { id: 'union', name: 'Dockers’ Union Hall', type: 'office', x: 420, y: 650, district: 'The Flats', desc: 'Folding chairs, a dues ledger, and Brandt’s name on the door in wet paint.' },
    { id: 'docks', name: 'Rainer Docks', type: 'docks', x: 600, y: 710, district: 'The Flats', desc: 'Oil on black water. The cranes never stop.' },
    { id: 'warehouse', name: 'Bonded Warehouse 4', type: 'warehouse', x: 770, y: 650, district: 'The Flats', desc: 'Customs seals on every door. One of them broken tonight.' },
    // ---- The Bluff
    { id: 'chapel', name: 'Sailors’ Chapel', type: 'church', x: 900, y: 610, district: 'The Bluff', desc: 'One room, a brass bell, prayer cards for the drowned.' },
    { id: 'manor', name: 'Voss Manor', type: 'manor', x: 1080, y: 670, district: 'The Bluff', desc: 'Fourteen rooms on the bluff. One daughter fewer.' },
    { id: 'baylight', name: 'Bay Light', type: 'light', x: 1120, y: 760, district: 'The Bluff', desc: 'One keeper, one lamp, and a log of every light on the water.' },
  ],
  edges: [
    ['gilded', 'herald'], ['gilded', 'belvedere'], ['gilded', 'lyceum'],
    ['herald', 'gardens'], ['herald', 'cathedral'],
    ['lyceum', 'gardens'], ['lyceum', 'belvedere'], ['lyceum', 'trust'],
    ['belvedere', 'parrot'],
    ['gardens', 'trust'], ['gardens', 'cathedral'],
    ['trust', 'precinct'], ['trust', 'library'],
    ['cathedral', 'mercy'], ['cathedral', 'precinct'],
    ['mercy', 'market'], ['mercy', 'jade'],
    ['precinct', 'market'], ['precinct', 'library'], ['precinct', 'exchange'],
    ['market', 'pharmacy'], ['market', 'morgue'], ['market', 'exchange'],
    ['library', 'tram'], ['library', 'pawn'],
    ['exchange', 'tram'], ['exchange', 'morgue'],
    ['morgue', 'cannery'], ['morgue', 'warehouse'],
    ['tram', 'union'], ['tram', 'docks'],
    ['jade', 'imports'], ['jade', 'pharmacy'],
    ['imports', 'baths'],
    ['pharmacy', 'baths'], ['pharmacy', 'cannery'],
    ['baths', 'ferry'],
    ['cannery', 'ferry'], ['cannery', 'chapel'],
    ['ferry', 'manor'],
    ['parrot', 'tenement'], ['parrot', 'pawn'],
    ['tenement', 'garage'],
    ['pawn', 'garage'], ['pawn', 'union'],
    ['garage', 'union'],
    ['union', 'docks'],
    ['docks', 'warehouse'],
    ['warehouse', 'chapel'],
    ['chapel', 'manor'], ['chapel', 'baylight'],
    ['manor', 'baylight'],
  ],
  start: 'precinct',

  suspects: [
    { id: 'vera', name: 'Vera Lang', role: 'Torch singer, The Blue Parrot',
      traits: { build: 'slight', hair: 'red' },
      blurb: 'Sang the eleven o’clock show. Wanted Lillian’s spot at the Gilded.',
      motive: 'because the top of the bill only fits one name.',
      bio: 'Twenty-six. Started singing in the back room of the Blue Parrot. Lillian got her a job at the Jade Room, then got her fired from it. They used to be friends. Vera says they still were.',
      alibi: 'On stage at the Blue Parrot until one. Then home, alone.',
      secret: 'She went to the Gilded at one-thirty to ask Lillian for her old job back. Lillian laughed at her. Vera left by the side door and told nobody she had been there.',
      opinions: { strand: 'Emil Strand rents out the hotel’s ninth floor by the hour. He thinks nobody knows. Lillian knew.', pike: 'Dr. Pike gives half the rich people in this city their pills. He gave Lillian hers too.', roland: 'Roland is a sweet boy who owes money to people who are not sweet.', shaw: 'Perpetua Shaw wrote that I sang flat. I didn’t. She wanted my job for a friend of hers.', brandt: 'Brandt drinks at the Parrot and never pays. Nobody dares ask him to.', mireaux: 'Cass Mireaux sends flowers to people who never ordered any. Ask yourself why.', tovar: 'The Deacon takes money from the church collection. Everyone in the Flats knows. Nobody on the Heights does.' },
      topics: [
        { id: 'night', q: 'Where were you at two this morning?', a: 'On stage at the Blue Parrot until one. Two encores. Then a cab home, and bed. Ask Bix, the barman. He’ll tell you.' },
        { id: 'lillian', q: 'What was Lillian to you?', a: 'A friend, first. Then my boss. Then the woman who got me fired from the Jade Room over a dress. We were going to make up. We were always going to make up.' },
        { id: 'billing', q: 'Your set list says she owed you the top spot on the bill.', a: 'She promised me the top spot in July. Then she got the Gilded job and forgot all about it. I underlined it because I was angry. It doesn’t mean anything more than that.', after: 'lillian' },
        { id: 'side-door', q: 'Somebody used the hotel’s side door at half past one. Was that you?', a: 'A long silence. Yes. I went to ask her for my old job back. She laughed at me. I left. She was alive when I left, Inspector. She was laughing.', after: 'night', cost: 1, effect: { type: 'suspectTrait', suspectId: 'vera' } },
        { id: 'who', q: 'If it wasn’t you, then who?', a: 'Somebody with a key. That side door locks from the inside. I only got in because it was open, and it was open because somebody was expected.', after: 'side-door' },
      ] },
    { id: 'strand', name: 'Emil Strand', role: 'Night manager, The Gilded',
      traits: { build: 'tall', hair: 'dark' },
      blurb: 'Night manager. He has a key to every door in the hotel.',
      motive: 'because she knew which rooms he rented by the hour, and to whom.',
      bio: 'Forty-four. Night manager for nine years. He rents rooms by the hour to people who want privacy, and he keeps a book of their names. Lillian found the book.',
      alibi: 'At the front desk all night. He says the clerk will confirm it.',
      secret: 'He was not at the desk. He was at Café Belvedere with a city councillor’s wife. The second coffee on the check was hers.',
      opinions: { vera: 'Miss Lang came in through the side door at half past one. I saw her from the balcony. I didn’t stop her.', pike: 'Dr. Pike keeps a room on the ninth floor. I don’t ask what for.', roland: 'Roland Voss argued with his sister at ten o’clock. The whole floor heard it.', shaw: 'Miss Shaw spends more nights in this hotel than she does at home. Never as a paying guest.', brandt: 'Brandt collects union money in my lobby. I let him. It’s cheaper than not letting him.', mireaux: 'Madame Mireaux sends the orchids every Monday. The bill goes to the Voss family.', tovar: 'The Deacon collects from my staff every Friday. She keeps half of it, I’m told.' },
      topics: [
        { id: 'night', q: 'Where were you at two this morning?', a: 'At the front desk. Miss Pruett will confirm it. I was at the desk from midnight until six.' },
        { id: 'book', q: 'Lillian found your book of room bookings. What was in it?', a: 'Names, times, room numbers. Half the city council. She said she would never use it. She said it like somebody deciding when.', cost: 1, effect: { type: 'suspectTrait', suspectId: 'strand' } },
        { id: 'keys', q: 'You have a key to every door, including the side door.', a: 'I have the master key. So does the house detective. And until Tuesday, so did Miss Voss. She asked me for one. I gave it to her. I don’t know why she wanted it.', after: 'night' },
        { id: 'coffee', q: 'Two coffees at Café Belvedere at one-fifteen, signed with your initials. You said you were at the desk.', a: 'His face goes grey. I stepped out for twenty minutes. Miss Pruett covered for me. If you need to know who the second coffee was for, I’ll tell you somewhere with a door that shuts.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'orchid', q: 'The orchid was put back in its vase. Who tidies up in this hotel at two in the morning?', a: 'Nobody. Whoever did that has stood in a lot of hotel rooms and left them looking as if nobody had been there.' },
      ] },
    { id: 'pike', name: 'Dr. Aurelio Pike', role: 'Society physician',
      traits: { build: 'slight', hair: 'grey' },
      blurb: 'Doctor to the rich. Writes the prescriptions that keep them going.',
      motive: 'because she was going to name his pharmacy in open court.',
      bio: 'Sixty. Doctor to the families of the Heights. He signs out ether and morphine from his own pharmacy, and the register is full of initials, not names. Lillian was his patient. Then she became a witness against him.',
      alibi: 'Asleep at home. Then at Mercy Hospital at three, stitching a man’s hand.',
      secret: 'The man he stitched was a courier. Pike’s pharmacy moves drugs, and Cass Mireaux brings them in under the orchids.',
      opinions: { vera: 'Miss Lang has a sore throat I’ve treated and a temper I haven’t.', strand: 'Strand sends me patients. I send him a cheque. That’s the whole arrangement.', roland: 'Roland Voss has been my patient since he was nine. Bad nerves. He never grew out of them.', shaw: 'Perpetua Shaw wrote about my pharmacy once. I haven’t slept properly since.', brandt: 'I stitched Brandt’s hand in 1946. He didn’t flinch. Men who don’t flinch worry me.', mireaux: 'Madame Mireaux imports flowers. I’m a doctor. That’s all I know about flowers.', tovar: 'The Deacon’s brother is in Marrow House asylum. I signed the papers. She has never forgiven me for being right.' },
      topics: [
        { id: 'night', q: 'Where were you at two this morning?', a: 'Asleep at home. Then at Mercy Hospital at three, stitching up a man’s hand. The admission slip is there. Read it.' },
        { id: 'patient', q: 'Lillian was your patient. What were you giving her?', a: 'Nothing she shouldn’t have had. Something to help her sleep. I signed for it. It wasn’t enough to hurt her, and she never tried to take enough.' },
        { id: 'court', q: 'She was going to name your pharmacy in court.', a: 'She said so, on Wednesday. She had the poisons register, or a copy of it. I’d like to know where she got it as much as you would.', cost: 1, effect: { type: 'suspectTrait', suspectId: 'pike' } },
        { id: 'ether', q: 'You signed out four ounces of ether on Thursday.', a: 'For an operation that didn’t happen. The patient never came. The ether is still in my bag. I can show you. I’d rather you didn’t ask what else is in the bag.', after: 'court' },
        { id: 'hand', q: 'Whose hand did you stitch?', a: 'A man who gave no name and paid cash. Left hand, cut on glass. He’d been somewhere with a lot of broken glass.', after: 'night', cost: 1, effect: { type: 'lead' } },
      ] },
    { id: 'mireaux', name: 'Cass Mireaux', role: 'Importer of rare flowers',
      traits: { build: 'slight', hair: 'dark' },
      blurb: 'Imports orchids through the docks. Imports other things under them.',
      motive: 'because the orchids were never the cargo, and she had worked that out.',
      bio: 'Thirty-eight. From Marseille. She brings in forty crates of orchids a month. Twelve of them she signs for herself, at night. Lillian’s orchids came from her shop. So did the one on the dressing table.',
      alibi: 'At the bonded warehouse until two, counting crates. The clerk saw her.',
      secret: 'The twelve crates hold morphine for Dr. Pike. She signs for them herself because the bond clerk was starting to ask questions.',
      opinions: { vera: 'Vera Lang wants what Lillian had. She has wanted it since she was nineteen.', strand: 'Strand rents rooms to men who buy my flowers for women who aren’t their wives.', pike: 'Dr. Pike is a customer. For flowers.', roland: 'Roland Voss owes money at my dock. I don’t collect it myself.', shaw: 'Shaw came to my warehouse in October asking about crates. I gave her orchids. She went away.', brandt: 'Brandt moves what I need moved and doesn’t ask questions. I like that in a man.', tovar: 'The Deacon buys lilies for funerals on credit and pays for them out of the collection plate.' },
      topics: [
        { id: 'night', q: 'Where were you at two this morning?', a: 'At the bonded warehouse, counting crates. Latimer, the clerk, saw me. He always sees me.' },
        { id: 'orchids', q: 'The orchid on her dressing table came from you.', a: 'Every orchid on the Heights comes from me. I sent that one on Monday. Somebody snapped it. Somebody who has no idea what they cost.' },
        { id: 'manifest', q: 'Twelve crates on your manifest are signed in your handwriting, not the clerk’s.', a: 'A very long pause. The clerk was ill. I signed for them myself. That isn’t a crime.', cost: 1, effect: { type: 'suspectTrait', suspectId: 'mireaux' } },
        { id: 'cable', q: '‘Don’t let her see the manifest.’ That’s a telegram from Marseille with your name on it.', a: 'Then you already know she saw it. She came to the warehouse on Wednesday and read it standing up. She said nothing at all. That was worse.', after: 'manifest', cost: 1, effect: { type: 'lead' } },
        { id: 'scarf', q: 'Did you give her a silk scarf?', a: 'Yes. Orchid-scented. She wore it for a month. Then she gave it back, on the day she read the manifest.' },
      ] },
    { id: 'tovar', name: 'Deacon Iris Tovar', role: 'St. Ordell’s',
      traits: { build: 'broad', hair: 'dark' },
      blurb: 'Runs the soup kitchen and the collection plate. Only one of the two adds up.',
      motive: 'because the parish accounts only balanced while she stayed quiet.',
      bio: 'Fifty-five. A deacon for twenty years. The soup kitchen feeds two hundred people. The collection plate takes in enough for four hundred. Lillian gave to both, and she counted.',
      alibi: 'Praying in the vestry from midnight until dawn.',
      secret: 'She has taken money from the collection plate for years. Not for herself. For her brother in Marrow House asylum, whose bills nobody else pays.',
      opinions: { vera: 'Miss Lang sings in a club I don’t go to. She sings well. I’ve heard her through the wall.', strand: 'Mr. Strand puts money in the plate every Friday. Guilt money. It spends the same.', pike: 'Dr. Pike had my brother committed. He was right to. I’ll never say that to his face.', roland: 'Roland Voss sits in the family pew and watches the door.', shaw: 'Miss Shaw comes to Mass to see who else does.', brandt: 'Nikolai Brandt gives to the soup kitchen every week. In cash. Nobody knows where it comes from.', mireaux: 'Madame Mireaux sends lilies for every funeral in the parish. She knows about most of them before I do.' },
      topics: [
        { id: 'night', q: 'Where were you at two this morning?', a: 'In the vestry, praying. Old Wyn will tell you the light was on.' },
        { id: 'letter', q: 'Lillian wrote to you about the parish accounts.', a: 'She did. And she was right. Two hundred pounds a year, for nine years, for my brother in Marrow House. I was going to confess to the Canon on Sunday.', cost: 1, effect: { type: 'suspectTrait', suspectId: 'tovar' } },
        { id: 'hymnal', q: 'Your hymn book was found on the bandstand steps in the park, with an orchid petal pressed inside it.', a: 'She stops. I was in the park, not the vestry. I walk when I can’t pray. I found the petal on the path and kept it. I don’t know why.', after: 'night' },
        { id: 'gate', q: 'Who did you see in the park?', a: 'A man on the bandstand, in a hat. He sat there for an hour without smoking. That’s how I knew he was waiting for somebody.', after: 'hymnal', cost: 1, effect: { type: 'lead' } },
      ] },
    { id: 'roland', name: 'Roland Voss', role: 'The victim’s brother',
      traits: { build: 'tall', hair: 'dark' },
      blurb: 'Her brother. He inherits everything.',
      motive: 'because the estate passes whole to the surviving child.',
      bio: 'Thirty. The younger Voss. He plays cards at Rosie’s, writes cheques at the Trust, and apologises at the manor. Lillian changed her will on Tuesday. He found out on Thursday.',
      alibi: 'At the Lyceum theatre until eleven. Then home to the manor. The driver will say so.',
      secret: 'He opened Lillian’s deposit box at ten to midnight and took the new will. He still has it. He has not read past the first page.',
      opinions: { vera: 'Vera was Lil’s real friend. They fought like sisters. I should know.', strand: 'Strand let me into her suite once when I lost my key. He didn’t ask why.', pike: 'Pike has had a hand in my pocket since I was nine. Pills, advice, bills.', shaw: 'Shaw wrote that I cried in the wrong order. How does anyone cry in the wrong order?', brandt: 'Brandt collects debts for men I owe money to. He’s polite about it. That’s the frightening part.', mireaux: 'The Frenchwoman lent me money in the spring. Lil paid it back. I never asked how much.', tovar: 'The Deacon buried our mother. She was kind then, and she’s kind now. It’s exhausting.' },
      topics: [
        { id: 'night', q: 'Where were you at two this morning?', a: 'At the manor, in bed. The driver brought me home at midnight. He’ll tell you so. He always tells you so.' },
        { id: 'argument', q: 'You argued with her at ten o’clock.', a: 'About money. It was always about money. She said she was changing her will. I said some things. I walked out. That was the last thing I ever said to her, and it was a bad thing.' },
        { id: 'box', q: 'Her safe-deposit box was opened at ten to midnight. By you.', a: 'He puts his hands over his face. I wanted to see what she’d done. I took the new will. I haven’t read it. I can’t.', after: 'argument', cost: 1, effect: { type: 'suspectTrait', suspectId: 'roland' } },
        { id: 'car', q: 'The family car came into the garage at ten to three with the front wing smashed.', a: 'I hit the manor gate. At midnight. I’d been drinking. That’s all it was.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'will', q: 'What does the will say?', a: 'I don’t know. I told you. It’s in a drawer, and I look at the drawer.', after: 'box' },
      ] },
    { id: 'brandt', name: 'Nikolai Brandt', role: 'Dock union enforcer',
      traits: { build: 'broad', hair: 'dark' },
      blurb: 'Union enforcer. Four men who owe him money say he was somewhere else.',
      motive: 'because Cass Mireaux paid him to keep her quiet, and he has never once asked what quiet means.',
      bio: 'Thirty-five. Collects union dues and other people’s debts. Broke a man’s hand at the cannery in 1946. Sends money to his mother on Tenement Row every week.',
      alibi: 'At the union hall, counting dues. Four men saw him there.',
      secret: 'He answered the telephone at the Jade Room at two. It was Lillian, saying she knew. Mireaux had told him what to do if that call came. He went in by the side door Vera had left open.',
      opinions: { vera: 'Vera sings. I listen. She never sings the one I ask for.', strand: 'Strand pays the union to keep the hotel quiet. Every month, on time.', pike: 'Pike stitched my hand once. Good hands, bad eyes. He never looked at my face.', roland: 'The Voss boy owes forty dollars at Rosie’s card room. I collect for Rosie. I haven’t collected yet.', shaw: 'Shaw wrote about the union once and got it right. I didn’t like that.', mireaux: 'The Frenchwoman pays cash and doesn’t talk. Best kind of work there is.', tovar: 'The Deacon feeds my mother’s whole floor every Thursday. I give what I can.' },
      topics: [
        { id: 'night', q: 'Where were you at two this morning?', a: 'At the union hall, counting dues. Four men saw me. If you want their names, you can have them.' },
        { id: 'four', q: 'Your four men were at Rosie’s card room. So were you.', a: 'He looks at the floor for a long time. Fine. Rosie’s until one. Then the docks. Then home.', cost: 1, effect: { type: 'suspectTrait', suspectId: 'brandt' } },
        { id: 'crate', q: 'What were you doing at the docks?', a: 'Moving a crate for the Frenchwoman. Off a cart and into a boat. I didn’t open it. I never open them.', after: 'four', cost: 1, effect: { type: 'lead' } },
        { id: 'letter', q: 'There’s a threatening letter on union paper nailed to the cannery door.', a: 'I don’t type. Somebody at the hall does. Somebody who wants the cannery to think it came from me.', after: 'night' },
        { id: 'mother', q: 'You send money to your mother on Tenement Row.', a: 'Every week. She thinks it’s union wages. It isn’t always union wages. Leave her out of this.' },
      ] },
    { id: 'shaw', name: 'Perpetua Shaw', role: 'Columnist, The Herald',
      traits: { build: 'slight', hair: 'dark' },
      blurb: 'Newspaper columnist. She was in the hotel lobby before the police arrived.',
      motive: 'because the column had run dry, and a dead heiress runs for a month.',
      bio: 'Forty-two. Writes the gossip column six days a week and has for twenty years. She knows something about everyone and prints half of it. Lillian was her best material and her oldest enemy.',
      alibi: 'A bellboy telephoned her at two-thirty. She came straight over.',
      secret: 'There was no bellboy. She was already in the hotel at one, on the ninth floor, with somebody she refuses to name.',
      opinions: { vera: 'Vera Lang sang flat in July. I wrote it. She’s never forgiven me for being accurate.', strand: 'Strand’s ninth floor is the best-kept secret on the Heights. Which means I’ve known for years.', pike: 'Dr. Pike keeps a poisons register that would ruin him. Lillian had a copy. I’d give a lot to know where it is.', roland: 'I wrote that Roland cried at the wrong moment. I meant it kindly. It didn’t read that way.', brandt: 'Brandt is the only honest man in the union. He’s honestly dangerous.', mireaux: 'Cass Mireaux gave me orchids to stop me asking questions. I took the orchids. I kept asking.', tovar: 'Iris Tovar takes from the collection plate. I’ve known for two years. I haven’t printed it. Ask me why.' },
      topics: [
        { id: 'night', q: 'You were in the lobby before the police. How?', a: 'A bellboy telephoned me. I tip bellboys. That’s my whole profession.' },
        { id: 'lobby', q: 'The photograph shows you in the lobby at two-forty with your hat off. You’d been there a while.', a: 'I’d been in the building since one o’clock. On the ninth floor. With somebody. If you print that, I’ll print you.', after: 'night', cost: 1, effect: { type: 'suspectTrait', suspectId: 'shaw' } },
        { id: 'column', q: 'Your column that morning was about her.', a: 'My column every morning is about somebody. Alive, she was the best material in the city. Dead, she’s a month of columns, and I hate every one of them.' },
        { id: 'notes', q: 'Lillian kept notes on everyone. Where are they?', a: 'Gone from her suite, I’d guess. If I had them, you’d be reading them in tomorrow’s paper and I’d be on a train out of town.', after: 'column', cost: 1, effect: { type: 'lead' } },
        { id: 'ninth', q: 'Who were you with on the ninth floor?', a: 'No. Not for you, not for the Commissioner, not for God. Ask me anything else.', after: 'lobby' },
      ] },
  ],

  culprit: 'brandt',

  witnesses: [
    { id: 'pruett', at: 'gilded', name: 'Ada Pruett', role: 'night clerk, the Gilded',
      intro: 'I’m Ada Pruett. I’ve worked the night desk here for eleven years. I see everyone who comes in the front door. Most of the ones who use the side door, too.',
      bio: 'Night desk clerk for eleven years. She reads the guest register upside down and knows who is in every room.',
      knows: ['strand', 'shaw', 'roland'],
      aboutLine: 'I know that face. I can tell you one thing about them.',
      leadLine: 'Somebody left in a hurry and dropped something on the way out. Go and look at',
      spentLine: 'I have a desk to run. I’ve told you enough.',
      opinions: { strand: 'Mr. Strand wasn’t at the desk between one o’clock and twenty past. He asked me to say he was. I said I would. I’m not saying it now.', shaw: 'Miss Shaw came through the lobby at one and went up in the lift. She didn’t come down again until the police arrived.', roland: 'Mr. Voss argued with his sister at ten. He left at eleven with only one cufflink in.' },
      topics: [
        { id: 'night', q: 'What happened here tonight?', a: 'Suite 1100 rang down for ice at midnight. At nine minutes past two, Mr. Halloran, the house detective, went up with a passkey because the light was on and the door was on the chain. He came back down white as a sheet.' },
        { id: 'side', q: 'Who uses the side door?', a: 'Staff. Mr. Strand. Guests who don’t want to be seen. It locks from the inside. Tonight it was open from one o’clock until I locked it at three.' },
        { id: 'chain', q: 'The door was on the chain?', a: 'From the inside. Mr. Halloran had to cut it. So whoever killed her didn’t leave by the door. The bathroom window gives onto the fire escape, and the catch was open. Nobody on the eleventh floor opens that window in February.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'lillian', q: 'What was Miss Voss like?', a: 'Kind to the staff, hard on everyone else. She tipped in silver and remembered your name. She remembered too much about everybody, I think.' },
      ] },
    { id: 'marlowe', at: 'parrot', name: 'Bix Marlowe', role: 'barman, the Blue Parrot',
      intro: 'Bix Marlowe. I pour drinks, I listen, and I forget. Tonight I’ll make an exception.',
      bio: 'Barman for twenty years. He used to box. He remembers faces the way a boxer does, and bar tabs the way a barman does.',
      knows: ['vera', 'brandt', 'pike'],
      aboutLine: 'They drink at my bar. You notice things across a bar.',
      leadLine: 'A man came in white as a sheet and went out the back. When he came back he wasn’t carrying anything. Try',
      spentLine: 'The bar is closed. So am I.',
      opinions: { vera: 'Vera finished at one and went straight out the front door. She had her coat on before the clapping stopped.', brandt: 'Brandt came in at eleven and left at half past. He was going to Rosie’s card room. He goes every Thursday and every Thursday he says he doesn’t.', pike: 'Dr. Pike drinks here when he can’t be seen drinking on the Heights. Rye, doubles. He wasn’t in tonight.' },
      topics: [
        { id: 'night', q: 'Did anything happen here tonight?', a: 'Vera did two sets. A man came in white as a sheet, went out the back, and came back looking lighter. Somebody left a matchbook from Rosie’s on the bar, and nobody admits to going to Rosie’s.' },
        { id: 'vera', q: 'Vera left in a hurry. Where did she go?', a: 'She said home. But she took the tram up to the Heights. Her home is the other way.', cost: 1, effect: { type: 'suspectTrait', suspectId: 'vera' } },
        { id: 'lillian', q: 'Did Lillian Voss drink here?', a: 'She sang here first, before the Jade Room and the Gilded. She came back once a month, sat at the end of the bar, and didn’t sing. She was here on Tuesday.' },
      ] },
    { id: 'flett', at: 'mercy', name: 'Oona Flett', role: 'night sister, Mercy Hospital',
      intro: 'Sister Flett. I run ward four at night. People say things at three in the morning that they’d never say in daylight.',
      bio: 'Ran a field hospital in Italy during the war. Nothing on ward four surprises her. She keeps her own notes on Dr. Pike.',
      knows: ['pike', 'tovar', 'roland'],
      aboutLine: 'They’ve been through my ward. You don’t forget a patient.',
      leadLine: 'A porter found something in a coat left on the ward. He was too scared to hand it in. It ended up at',
      spentLine: 'I have patients. Come back with a warrant or a fever.',
      opinions: { pike: 'Dr. Pike stitched a man’s hand at three in the morning and let him walk out. Left hand, cut on glass. Pike didn’t write the man’s name down. I did. It wasn’t a real name.', tovar: 'The Deacon visits her brother on the second floor every Sunday. She pays his bill in cash and cries in the corridor afterwards.', roland: 'Roland Voss was on my ward in March for his nerves. He talked in his sleep about his sister.' },
      topics: [
        { id: 'night', q: 'What came through the hospital tonight?', a: 'A cut hand at three. A drunk at four. And at half past two, a telephone call asking if we had a patient called Voss. We didn’t. Not yet.' },
        { id: 'call', q: 'Who called about a Voss?', a: 'A woman. She didn’t give her name. It sounded like she was calling from a bar; there was music.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'pike', q: 'What do you keep in your notes on Dr. Pike?', a: 'Dates and amounts. Ether by the pint. I’m not a policeman. I write things down in case one ever turns up.' },
      ] },
    { id: 'rainer', at: 'docks', name: 'Sal Rainer', role: 'night watchman, Rainer Docks',
      intro: 'Sal Rainer. No relation to the docks, whatever the sign says. I walk the wharf from ten till six and I count the boats.',
      bio: 'Lost a leg on the wharf in 1939 and stayed on as night watchman. He counts boats, crates and people.',
      knows: ['mireaux', 'brandt'],
      aboutLine: 'They come down here more than they should. I’ve watched them.',
      leadLine: 'Something went into the water tonight. Something else went into somebody’s pocket. That somebody walked toward',
      spentLine: 'My shift is over. Go and bother somebody with a warm office.',
      opinions: { mireaux: 'Madame Mireaux was on the wharf at two with a lantern and a cart, waiting. She never carries things herself. Tonight she did.', brandt: 'Brandt lifted a crate into a boat at half past two, on his own. It had taken two men to lift it off the cart.' },
      topics: [
        { id: 'night', q: 'What did you see tonight?', a: 'A crate going from a cart into a boat. A woman with a lantern. And something small thrown off the end of the pier that didn’t sink.' },
        { id: 'boat', q: 'Where did the boat go?', a: 'Across the bay, toward the Bluff, with no lights. There’s only one place under the Bluff where you can land a boat without lights.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'lillian', q: 'Did Lillian Voss ever come to the docks?', a: 'On Wednesday. She stood right where you’re standing and watched the crates come off the boats for an hour. She wrote in a little notebook. She didn’t need to talk to me.' },
      ] },
    { id: 'wyn', at: 'cathedral', name: 'Old Wyn', role: 'sexton, St. Ordell’s',
      intro: 'They call me Old Wyn. I look after the church doors and the graves. The graves keep me busier.',
      bio: 'Sexton for forty years. He has buried three canons. He knows which pews creak and who sits in them.',
      knows: ['tovar', 'shaw'],
      aboutLine: 'I’ve watched that one pray. You learn things about a person when they think God is the only one looking.',
      leadLine: 'Somebody was in the vestry who had no business there. They left by the side gate, heading for',
      spentLine: 'The church is closed. Good night.',
      opinions: { tovar: 'The Deacon’s light was on in the vestry until midnight. Then it went off. It came on again at three. In between, she wasn’t in there.', shaw: 'Miss Shaw sits at the back of the church and watches who takes communion. Then she writes it down.' },
      topics: [
        { id: 'night', q: 'Who was in the church tonight?', a: 'The Deacon, on and off. And a man in the vestry at one o’clock who wasn’t the Deacon. He left by the side gate. I didn’t see his face. I saw a hat.' },
        { id: 'vestry', q: 'What did the man in the vestry want?', a: 'The letters. Miss Voss had written to the Deacon. The letters were in the vestry drawer. They aren’t there now.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'lillian', q: 'Did you know Miss Voss?', a: 'She gave to the soup kitchen and she counted the collection plate. She was the only person on the Heights who ever counted. That’s why she’s dead, if you ask me. Nobody has.' },
      ] },
    { id: 'cobb', at: 'pawn', name: 'Ezra Cobb', role: 'pawnbroker',
      intro: 'Ezra Cobb. I buy the things people can’t stand to look at any more. You’d be surprised what that includes.',
      bio: 'Thirty years in the pawnshop his father opened. He keeps a book on his regular customers, and not only for the money.',
      knows: ['vera', 'mireaux', 'strand'],
      aboutLine: 'A regular. I keep notes on my regulars.',
      leadLine: 'Somebody redeemed a pawn ticket tonight. Cash, no name, in a hurry. The item had come in from',
      spentLine: 'I’ve told you what I sell. That’s all I sell.',
      opinions: { vera: 'Miss Lang pawns a bracelet every month and buys it back the week after. Tonight she bought it back early.', mireaux: 'Madame Mireaux doesn’t pawn. She buys. Whatever the docks lose, she has by Friday.', strand: 'Mr. Strand pawned a gold lighter with his initials on it in June. He never came back for it. Somebody else did.' },
      topics: [
        { id: 'night', q: 'What came through the shop tonight?', a: 'One ticket paid off in cash at midnight, by a hand that hadn’t pawned the item. One bracelet bought back early. And a man who looked at the knives for a long time and didn’t buy one.' },
        { id: 'lighter', q: 'Who bought back Strand’s lighter?', a: 'A woman in gloves. She paid with a new banknote and didn’t wait for her change. She went up the street toward the Jade Room.', cost: 1, effect: { type: 'lead' } },
        { id: 'knives', q: 'Tell me about the man who looked at the knives.', a: 'Big. Quiet. Hands like shovels. He looked at the knives the way a man looks at something he already owns.', after: 'night', cost: 1, effect: { type: 'suspectTrait', suspectId: 'brandt' } },
      ] },
    { id: 'bell', at: 'lyceum', name: 'Dot Bell', role: 'usherette, the Lyceum',
      intro: 'I’m Dot. I show people to their seats. I know who leaves before the last act. Tonight somebody left before the first one.',
      bio: 'Nineteen. Wants to be on the stage, not beside it. She sees everything from the aisle with her torch.',
      knows: ['vera', 'shaw', 'roland'],
      aboutLine: 'A regular in the boxes. You see a lot from the aisle.',
      leadLine: 'A coat was left in box C. Somebody came back for it fast and went out toward',
      spentLine: 'The curtain’s down. So am I.',
      opinions: { roland: 'Mr. Voss left at eleven with only one cufflink in and a face like a wet Sunday.', vera: 'Miss Lang sat in the cheap seats on Tuesday and cried all through the second act. It was a comedy.', shaw: 'Miss Shaw takes box D on Thursdays so she can watch the Voss family in box C.' },
      topics: [
        { id: 'night', q: 'What happened here tonight?', a: 'The Voss box was empty from eleven o’clock. A coat was left over the rail. A woman came for it at half past one, in a hurry, wearing gloves.' },
        { id: 'coat', q: 'Whose coat was it?', a: 'A man’s camel coat. Expensive. The woman who took it wasn’t the woman who came in with him.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'lillian', q: 'Did Miss Voss come to the theatre?', a: 'Every Thursday, in box C, her father’s old seat. Last Thursday she came alone and left at the interval. She looked at me on her way out as if she wanted to say something. She didn’t.' },
      ] },
    { id: 'pardo', at: 'belvedere', name: 'Louis Pardo', role: 'waiter, Café Belvedere',
      intro: 'Louis Pardo. I work nights. I pour coffee for people who can’t sleep. I remember what they order, because it never changes.',
      bio: 'Came from Lisbon in 1938. He has served coffee to every secret affair on the Heights and never said a word about any of them.',
      knows: ['pike', 'roland', 'strand'],
      aboutLine: 'Table by the window, always. I’ve poured for them a hundred times.',
      leadLine: 'Two coffees came out at a quarter past one. Only one was drunk. Whoever left the other one walked toward',
      spentLine: 'The kitchen’s closed. Come back for breakfast.',
      opinions: { strand: 'Mr. Strand has coffee with a lady who isn’t Mrs. Strand, Tuesdays and Thursdays. Tonight he left without finishing his coffee.', pike: 'The doctor takes his coffee black. His hands shake until the second cup.', roland: 'Mr. Voss comes in after the theatre and drinks brandy out of a coffee cup. He thinks I don’t know.' },
      topics: [
        { id: 'night', q: 'Who was in here tonight?', a: 'Mr. Strand and his lady at a quarter past one. He left at twenty past as if something had bitten him. She stayed and drank both coffees. Then at three, a big man in a wet coat came in, ordered nothing, and watched the door.' },
        { id: 'lady', q: 'Who is Strand’s lady?', a: 'I pour coffee. I don’t ask names. I know she wears a wedding ring and turns it round and round when he’s late.' },
        { id: 'wet', q: 'Tell me about the man in the wet coat.', a: 'Big. Hat pulled down. He asked if the tram to the Bluff was still running. It wasn’t. He walked.', after: 'night', cost: 1, effect: { type: 'lead' } },
      ] },
    { id: 'amory', at: 'gardens', name: 'Kit Amory', role: 'night keeper, Ordell Gardens',
      intro: 'Kit Amory. I lock the park gates at ten and open them at six. In between, I see who climbs over the railings.',
      bio: 'Once a poet, published twice. Now he keeps the gardens at night and writes down only who comes in after dark.',
      knows: ['tovar', 'roland', 'vera'],
      aboutLine: 'They walk these paths at night. You learn a person by how they walk in the dark.',
      leadLine: 'Somebody sat on the bandstand steps for an hour and left something under them. Then they went toward',
      spentLine: 'The gates are locked. That includes for you.',
      opinions: { tovar: 'The Deacon walks in the park when she can’t pray. Tonight she walked from midnight until two.', roland: 'Young Mr. Voss sat on the bandstand steps on Tuesday, drank from a flask, and talked to nobody.', vera: 'Miss Lang cuts through the park to get to the Gilded. The railings on the north side are loose. She knows it.' },
      topics: [
        { id: 'night', q: 'Who came through the park tonight?', a: 'The Deacon, walking. A man sitting on the bandstand at one, waiting. And a woman climbing over the north railings at half past one, running.' },
        { id: 'man', q: 'Tell me about the man on the bandstand.', a: 'Hat down over his face. He didn’t smoke. He waited an hour. Then a woman came from the direction of the Gilded and they walked off together toward the Trust bank.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'lillian', q: 'Did Miss Voss walk here?', a: 'Every morning at seven with a book. Not a novel. An account book. She read account books the way other women read novels.' },
      ] },
    { id: 'vine', at: 'trust', name: 'Hedda Vine', role: 'teller, Ashgrave Trust',
      intro: 'I’m Hedda Vine. I work the second teller window. I see who brings money in and who takes it out.',
      bio: 'Fourteen years at the second window. She notices the nervous customers, the ones who count their money twice.',
      knows: ['roland', 'tovar', 'mireaux'],
      aboutLine: 'They have an account with us. I notice the customers who count twice.',
      leadLine: 'A safe-deposit box was opened at ten to midnight by somebody who should have been somewhere else. What they took went to',
      spentLine: 'The bank is closed. It was closed when you came in.',
      opinions: { roland: 'Mr. Voss signed for box 114 at ten to midnight. His hand shook so badly the pen went through the paper.', tovar: 'The Deacon pays two hundred pounds a year into an account in her brother’s name. Cash, in small notes.', mireaux: 'Madame Mireaux has accounts here under three different names. All of them are hers.' },
      topics: [
        { id: 'night', q: 'Who came to the vault tonight?', a: 'One person. Mr. Roland Voss, at ten to midnight. He had a key that wasn’t his and a signature that was.' },
        { id: 'tuesday', q: 'Did Miss Voss come in on Tuesday?', a: 'Yes. She put an envelope into box 114 and took nothing out. She told me: if my brother comes, let him. He needs to see it. So I let him. I shouldn’t have.', cost: 1, effect: { type: 'suspectTrait', suspectId: 'roland' } },
        { id: 'lillian', q: 'Did Miss Voss bank here?', a: 'Since she was twelve. She counted the money after the teller counted it, every single time. She was never wrong, and she never apologised for checking.' },
      ] },
    { id: 'quill', at: 'exchange', name: 'Bea Quill', role: 'night operator, Central Exchange',
      intro: 'Bea Quill. I work switchboard nine. I connect the calls. I’m not supposed to listen in. I’m not supposed to do a lot of things.',
      bio: 'Six years on the night switchboard. She can recognise a voice from three words, and she keeps a notebook she is not supposed to keep.',
      knows: ['shaw', 'strand', 'pike'],
      aboutLine: 'I know that voice. A voice at two in the morning tells you a lot.',
      leadLine: 'A call went out from suite eleven-hundred at eight minutes to two. The number it reached is at',
      spentLine: 'The board is lit up. Nine calls waiting. None of them are yours.',
      opinions: { shaw: 'Miss Shaw telephones the Herald from hotel lobbies at all hours. Tonight she called from the Gilded at a quarter past two. Before the police had been called.', strand: 'Mr. Strand gets a call every Thursday at one o’clock from a woman on the Heights. Tonight the call came and he wasn’t at the desk to take it.', pike: 'Dr. Pike telephones his pharmacy at midnight most nights. Tonight he telephoned the docks instead.' },
      topics: [
        { id: 'night', q: 'What calls did you connect tonight?', a: 'All of them. At 12:52 a call went out from suite 1100, Miss Voss’s room, to the number Lantern 4-4. It lasted a minute and ten seconds. That was the last call ever made from that room.' },
        { id: 'call', q: 'Whose number is Lantern 4-4?', a: 'It’s the telephone by the bar at the Jade Room. Somebody there took a call from a woman who was about to die. I listened in. I shouldn’t have. She said: I know what you did.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'lillian', q: 'Did she telephone anyone else this week?', a: 'Everyone. The Trust bank. The Herald. Mercy Hospital. The pharmacy. A shipping office. She was ringing round the whole city like a woman settling her accounts.' },
      ] },
    { id: 'marsh', at: 'tram', name: 'Ollie Marsh', role: 'conductor, the Bluff line',
      intro: 'Ollie Marsh. I’m the conductor on the last tram up the Bluff. I punch the tickets, and I remember the people who don’t have one.',
      bio: 'Thirty years on the Bluff line. He knows every regular by the seat they choose. He has been a witness at two trials and enjoyed both.',
      knows: ['brandt', 'tovar', 'vera'],
      aboutLine: 'They ride my tram. You learn a person by which seat they take.',
      leadLine: 'Somebody got off at the wrong stop and walked back the way we’d come. They were heading for',
      spentLine: 'The depot is shut. I’ve been on my feet fourteen hours.',
      opinions: { brandt: 'Brandt rides my tram standing up at the back, so he can see everyone. Tonight he rode the last car up the Heights at one, and the last car down at a quarter past two, and got off at the docks.', tovar: 'The Deacon rides to Marrow House on Sundays and comes back with red eyes.', vera: 'Miss Lang got on at the Parrot at one and got off at the Heights. Her home is down in the Flats.' },
      topics: [
        { id: 'night', q: 'Who rode the last tram?', a: 'Eleven passengers. A singer going the wrong way for home. A big man who got off at the docks. And somebody who got off at the wrong stop and walked back.' },
        { id: 'wrong', q: 'Tell me about the one who walked back.', a: 'Coat collar turned up. Got off at the Trust bank and walked back down the hill toward the Gilded. I punched the ticket but I didn’t see the face. I saw good shoes.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'lillian', q: 'Did Miss Voss ride the tram?', a: 'Never. She had the family car. Except on Wednesday. On Wednesday she rode down to the docks with me and stared out of the window the whole way, as if she was memorising it.' },
      ] },
    { id: 'grey', at: 'library', name: 'Tobias Grey', role: 'night librarian',
      intro: 'Tobias Grey. The reading room stays open all night for people who can’t sleep. I stay open with it. I know what everybody in this city reads.',
      bio: 'He was a lawyer once. He was disbarred. Now he shelves the newspapers and reads them before anyone else does.',
      knows: ['shaw', 'pike'],
      aboutLine: 'They read here. You can tell a person by what they look up.',
      leadLine: 'Somebody cut a page out of an old newspaper with a razor tonight. They left fast, heading for',
      spentLine: 'This is a library. Lower your voice and leave.',
      opinions: { shaw: 'Miss Shaw reads her own old columns here. Twenty years of them. She’s looking for something she wrote and forgot.', pike: 'Dr. Pike came in on Wednesday and asked for the Herald from 1946, the cannery fire. He read it twice and put it back upside down.' },
      topics: [
        { id: 'night', q: 'Who was in the reading room tonight?', a: 'One man, at midnight, with a razor blade. He cut a page out of a 1946 newspaper and left. The page was about the cannery fire.' },
        { id: 'razor', q: 'Which way did he go?', a: 'Toward the Trust bank. He had ink on his fingers. Not printer’s ink. Fountain-pen ink.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'lillian', q: 'Did Miss Voss read here?', a: 'Every Thursday afternoon for six months. Old newspapers, account books, the shipping registers. She was building a case against somebody. I don’t think she finished it.' },
      ] },
    { id: 'roe', at: 'morgue', name: 'Nettie Roe', role: 'attendant, City Morgue',
      intro: 'Nettie Roe. I keep the morgue register and I wash the bodies. The bodies are easier.',
      bio: 'Twelve years at the morgue. Her register is the only one in the city nobody has paid to change.',
      knows: ['pike', 'roland'],
      aboutLine: 'They came down to see the body. People give themselves away standing over a corpse.',
      leadLine: 'A visitor left something in the coat room and never came back for it. It was sent on to',
      spentLine: 'I have three bodies to wash before morning. Find your own way out.',
      opinions: { pike: 'Dr. Pike came down at four to see her. He touched her hand and said her name. Then he asked to see her personal effects. I said no.', roland: 'Mr. Voss came at five. He didn’t go in. He stood in the corridor and asked me whether she had suffered. I lied.' },
      topics: [
        { id: 'night', q: 'What did she have on her?', a: 'A ring, bent out of shape. A brass key stamped 114. An orchid stem. No handbag, no money. Somebody took the bag and left the key. So they didn’t know what the key was for.' },
        { id: 'ring', q: 'The ring was bent?', a: 'Bent at the setting. She hit somebody with it. There’s a hair caught in it that isn’t hers.', after: 'night' },
        { id: 'visitor', q: 'Who came to see her?', a: 'The doctor at four. The brother at five. And at six, a woman who wouldn’t give her name. She stood outside the door for ten minutes and then left. Gloves. Perfume.', cost: 1, effect: { type: 'lead' } },
      ] },
    { id: 'dunn', at: 'pharmacy', name: 'Cyril Dunn', role: 'dispensing chemist',
      intro: 'Cyril Dunn. I’m the chemist. I fill the prescriptions. I don’t ask what they’re for, and I don’t forget who asked.',
      bio: 'Dispensing chemist under Dr. Pike for eight years. He signs nothing. He remembers everything.',
      knows: ['pike', 'mireaux', 'vera'],
      aboutLine: 'A customer. I’ve handed them their little bottles across this counter.',
      leadLine: 'Somebody bought bandages and iodine at midnight with a shaking hand. They went toward',
      spentLine: 'The shop is shut. So is the register.',
      opinions: { pike: 'Dr. Pike signs the poisons register himself now. He never used to. He started in September.', mireaux: 'Madame Mireaux buys nothing here herself. She sends a boy. The boy signs with a cross.', vera: 'Miss Lang buys something for her throat every week and something for her nerves every month.' },
      topics: [
        { id: 'night', q: 'Who came in tonight?', a: 'A man at midnight, for bandages and iodine. One hand was shaking and the other was cut. He paid in silver and didn’t want a receipt.' },
        { id: 'register', q: 'Show me the poisons register.', a: 'Here. Ether, four ounces, Thursday, signed A. Pike. He has signed for eleven pints this year. There isn’t that much surgery on the whole of the Heights.', cost: 1, effect: { type: 'suspectTrait', suspectId: 'pike' } },
        { id: 'lillian', q: 'Did Miss Voss come here?', a: 'Once, on Wednesday. She asked to see the register. I showed her. She copied a page into a little notebook and thanked me. I’ve been waiting ever since for somebody to come and ask me about it.' },
      ] },
    { id: 'fane', at: 'jade', name: 'Lulu Fane', role: 'barmaid, the Jade Room',
      intro: 'Lulu Fane. I’ve worked this bar since Lillian sang here. I remember who came to listen to her and who came to watch her.',
      bio: 'She sang here herself before she lost her voice. Now she pours drinks. She still knows every song on the list.',
      knows: ['vera', 'brandt', 'strand'],
      aboutLine: 'They drink here. They sit where they can see the door.',
      leadLine: 'The telephone by the bar rang at two. Whoever answered it put down their drink and walked out toward',
      spentLine: 'Last orders was at two. That goes for questions too.',
      opinions: { vera: 'Vera had a drink here at half past one, still in her stage dress with a coat over it. She’d been crying. She said it was the rain.', brandt: 'Brandt sat by the door from half past midnight and watched the telephone. When it rang at eight minutes to one he took it himself, listened, and walked out without paying.', strand: 'Emil Strand left his lighter on my bar at half past two. He didn’t notice. He was watching the door.' },
      topics: [
        { id: 'night', q: 'The telephone rang at two o’clock.', a: 'It did. A man answered it. Big, in a hat. He listened without saying a word, put the receiver down, and walked out. He left a full glass on the bar. Nobody leaves a full glass.' },
        { id: 'man', q: 'Who was the man?', a: 'Not a regular. He came in at half past twelve and sat where he could see the telephone. He was waiting for it. When it rang at eight minutes to one he took it, listened, said nothing, and left without paying.', after: 'night', cost: 1, effect: { type: 'culpritTrait' } },
        { id: 'lillian', q: 'Lillian used to sing here.', a: 'For three years. She was better than this room deserved. She came back in October, sat at the end of the bar, and told me she was going to burn the whole Heights down. I thought she meant a song.' },
      ] },
    { id: 'vasko', at: 'garage', name: 'Pete Vasko', role: 'mechanic, Rainer Garage',
      intro: 'Pete Vasko. Every car on the Bluff comes through my garage. Tonight one came in with the front wing smashed.',
      bio: 'Fixes the cars of the Bluff and never asks what they hit. He was a tank mechanic in the war and misses it.',
      knows: ['brandt', 'roland'],
      aboutLine: 'They bring their car here. You learn a person by what they do to a car.',
      leadLine: 'There was something in the glove box that didn’t belong to the owner. I put it back. The car went on to',
      spentLine: 'The garage is shut. I have a Packard to finish.',
      opinions: { roland: 'Young Mr. Voss brings the Packard in with a new dent every month. Tonight it was the front wing. He said he hit the gate. He didn’t hit a gate.', brandt: 'Brandt doesn’t drive. He gets driven. Tonight somebody drove him from the docks up to the Bluff at a quarter to three in a car that wasn’t his.' },
      topics: [
        { id: 'night', q: 'Tell me about the Packard’s wing.', a: 'Smashed in on the passenger side, about hip height. There was paint in the dent. Not gate paint. Black paint. That car hit something painted black, and hit it hard.' },
        { id: 'glove', q: 'What was in the glove box?', a: 'A woman’s glove. Just one. Grey leather. Too small to be Miss Voss’s, I’d say.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'driver', q: 'Who drove it in?', a: 'Not Mr. Voss. A man in a chauffeur’s coat who didn’t know where the headlight switch was. Anyone who drives that car every day knows where the switch is.' },
      ] },
    { id: 'latimer', at: 'warehouse', name: 'Hugh Latimer', role: 'bond clerk, Warehouse 4',
      intro: 'Hugh Latimer. Every crate in this warehouse has a customs seal, and every seal has my initials on it. Tonight one of them has somebody else’s.',
      bio: 'A careful man in a careless job. He has been asking questions about twelve particular crates for six weeks.',
      knows: ['mireaux', 'brandt', 'strand'],
      aboutLine: 'They sign my book. You notice the hand that signs.',
      leadLine: 'A crate went out at half past two in the morning with no paperwork. The cart went toward',
      spentLine: 'I’m a clerk. Clerks don’t know things. Please close the door.',
      opinions: { mireaux: 'Madame Mireaux signs for twelve crates a month herself. I asked her why. I’ve stopped asking.', brandt: 'Brandt took a crate out of bay four at half past two in the morning without any paperwork. I wrote it down. He watched me write it down.', strand: 'Mr. Strand takes delivery of two crates a month at the hotel. The paperwork says orchids.' },
      topics: [
        { id: 'night', q: 'Customs seal 4471 was broken tonight.', a: 'At half past two in the morning. By Brandt, on Madame Mireaux’s orders. The crate went onto a cart, the cart went to the docks, and then a boat. After that I stopped watching.' },
        { id: 'twelve', q: 'What’s in the twelve crates?', a: 'Not orchids. Orchids don’t weigh that much. I opened one in September. I closed it again. I have a family.', cost: 1, effect: { type: 'suspectTrait', suspectId: 'mireaux' } },
        { id: 'lillian', q: 'Miss Voss came to the warehouse.', a: 'On Wednesday. She read the manifest standing up and asked me whether I had ever opened a crate. I said no. She looked at me as if she knew I was lying. I was.' },
      ] },
    { id: 'denk', at: 'ferry', name: 'Milo Denk', role: 'steward, the ferry',
      intro: 'Milo Denk. I run the ferry. Last crossing is at one-forty. I don’t know names, but I never forget a face I’ve seen after midnight.',
      bio: 'Twenty years on the ferry. He counts the passengers going out and coming back, and the numbers do not always match.',
      knows: ['mireaux', 'tovar'],
      aboutLine: 'They ride my ferry. You get to know a person on a cold deck.',
      leadLine: 'Somebody came over on the last boat carrying a bundle and left without it. The bundle went up to',
      spentLine: 'The boat is tied up. So am I.',
      opinions: { mireaux: 'Madame Mireaux takes the last ferry every Thursday with a suitcase and comes back on Friday without it.', tovar: 'The Deacon takes the ferry to Marrow House on Sundays. She sits at the back and doesn’t look at the water.' },
      topics: [
        { id: 'night', q: 'Who was on the last ferry?', a: 'Nine people. A woman with a bundle. A man in a wet coat. The bundle went over and didn’t come back. The man went over and didn’t come back either.' },
        { id: 'bundle', q: 'Tell me about the woman with the bundle.', a: 'Gloves. Perfume so strong you could smell it over the diesel. She carried the bundle up toward the manor as if it was a baby. It wasn’t a baby.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'lillian', q: 'Did Miss Voss ever take the ferry?', a: 'On Wednesday, to the Bluff. She stood at the rail the whole way and asked me what the boats without lights were. I said fishing boats. She said they weren’t.' },
      ] },
    { id: 'sorrel', at: 'baylight', name: 'Ned Sorrel', role: 'keeper, Bay Light',
      intro: 'Ned Sorrel. I keep the lighthouse lamp and I keep the log. Every light on the water goes in it. Most of the lights on the Bluff, too.',
      bio: 'Thirty years in the lighthouse. He talks to the lamp. He writes down every light he sees because nobody else will.',
      knows: ['mireaux', 'brandt'],
      aboutLine: 'They pass under my lamp. You learn a person by what they carry.',
      leadLine: 'A lantern went along the cliff path at half past two. It stopped, then came back without something. It stopped at',
      spentLine: 'The lamp needs trimming. You need to go.',
      opinions: { mireaux: 'The Frenchwoman’s boats land under the Bluff with no lights. I write it in the log. Nobody reads my log.', brandt: 'Brandt came up the cliff path at three with a lantern and went back down without it.' },
      topics: [
        { id: 'night', q: 'What did you see from the lighthouse tonight?', a: 'A boat with no lights at two o’clock. A lantern on the cliff path at half past two, stopping at the old stairs. And the manor: every window lit at three, and every window dark by four.' },
        { id: 'stair', q: 'What’s at the old stairs?', a: 'A cave. Dry inside. The smugglers used it before the lighthouse was built. Somebody uses it now.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'lillian', q: 'Did you know Miss Voss?', a: 'She came up the tower on Wednesday and asked to see my log. She read three months of it, said thank you, and went down the stairs as if she was counting them.' },
      ] },
  ],

  items: [
    { id: 'item:orchid:lobby-photo', at: 'herald', kind: 'photo', label: 'Press photograph, the Gilded lobby', stamp: 'COPY',
      source: 'THE ASHGRAVE HERALD · PICTURE DESK', title: 'Lobby, the Gilded, 2:40 AM',
      body: ['Taken before the first uniform arrived. Perpetua Shaw in the foreground, notebook out, hat off. Something about her in the flash that you would not have noticed by lamplight.', 'On the back in grease pencil: HOLD FOR MORNING.'],
      spoken: 'A press photograph of the lobby, taken before the first uniform arrived.',
      reading: 'The photograph shows something about Perpetua Shaw. Check her row in the Notebook.', about: ['shaw'], effect: { type: 'suspectTrait', suspectId: 'shaw' } },
    { id: 'item:orchid:check', at: 'belvedere', kind: 'receipt', label: 'Café Belvedere check',
      source: 'CAFÉ BELVEDERE · OPEN ALL NIGHT', title: 'Check no. 2207',
      fields: [['Coffee, black', '2'], ['Time', '1:15 AM'], ['Signed', '“E.S.”']],
      body: ['Two coffees, one drunk. Signed to the house account in a hand the waiter knows.', 'The second cup was still warm when the chair emptied.'],
      spoken: 'A café check for two coffees at a quarter past one, signed E.S.',
      reading: 'The waiter saw which way the second person went. A red mark on the map shows where.', about: ['strand'], effect: { type: 'lead' } },
    { id: 'item:orchid:box-log', at: 'trust', kind: 'ledger', label: 'Safe-deposit access log', stamp: 'CONFIDENTIAL',
      source: 'ASHGRAVE TRUST · VAULT', title: 'Access log, box 114',
      body: ['11:50 PM — R. VOSS — box 114 — signed out 11:58. The signature is hurried and the pen dug through the page.', 'Miss Vine remembers the hand that signed, and what it looked like doing it.'],
      spoken: 'The vault log: box one-fourteen, opened by R. Voss at ten to midnight.',
      reading: 'The teller watched Roland Voss sign. It tells you something about him. Check his row in the Notebook.', about: ['roland'], effect: { type: 'suspectTrait', suspectId: 'roland' } },
    { id: 'item:orchid:cab-chit', at: 'market', kind: 'receipt', label: 'Cab chit, Lantern Cab Co.',
      source: 'LANTERN CAB CO. · ALL NIGHT', title: 'Fare chit no. 88',
      fields: [['From', 'Lantern Market'], ['To', 'the Bluff'], ['Time', '2:20 AM'], ['Driver', 'Kaspar']],
      body: ['The driver is still on the rank outside, and he knows a way up the Bluff that is not on any map.'],
      spoken: 'A cab chit, market to the Bluff at twenty past two, and the driver still on the rank.',
      reading: 'The cab driver knows the short cuts. Two hours back on the clock.', effect: { type: 'time', hours: -2 } },
    { id: 'item:orchid:operator-log', at: 'exchange', kind: 'note', label: 'Operator’s log, board nine',
      source: 'CENTRAL EXCHANGE · BOARD 9', title: 'Calls placed from the Gilded, suite 1100',
      body: ['12:52 AM — outgoing — LANTERN 4-4 — duration one minute ten. The last call the suite ever made.', 'Quill wrote the number down when she should not have.'],
      spoken: 'The operator’s log: the last call from suite eleven-hundred, at eight minutes to two.',
      reading: 'The number is an address. Somebody was telephoned fifteen minutes before she died. A red mark on the map shows where.', effect: { type: 'lead' } },
    { id: 'item:orchid:effects', at: 'morgue', kind: 'report', label: 'Inventory of personal effects',
      source: 'CITY MORGUE · REGISTER', title: 'Effects of the deceased, Voss, L.',
      fields: [['Ring', 'one, gold, setting bent'], ['Key', 'one, brass, stamped 114'], ['Orchid', 'one stem, snapped'], ['Purse', 'no money']],
      body: ['A brass key stamped one-fourteen in the pocket of a woman with no purse to spend. The morgue does not guess what it opens. You are allowed to.'],
      spoken: 'The inventory of her effects: a bent ring, a brass key stamped one-fourteen, and no money.',
      reading: 'Box 114 is at Ashgrave Trust. She had the key. Somebody else opened the box. Go and ask.', about: ['roland'], effect: { type: 'none' } },
    { id: 'item:orchid:floor-photo', at: 'jade', kind: 'photo', label: 'Photograph, the Jade Room floor',
      source: 'THE JADE ROOM · HOUSE PHOTOGRAPHER', title: 'The eleven o’clock spot, Nov. 3',
      body: ['Vera Lang on the little stage at eleven, in the flash. The house photographer sells these at the door for a dollar. This one was not bought; it was taken.', 'You can see a great deal of a person in a flash photograph.'],
      spoken: 'A house photograph of Vera Lang on the Jade Room stage at eleven.',
      reading: 'The photograph shows something about Vera Lang. Check her row in the Notebook.', about: ['vera'], effect: { type: 'suspectTrait', suspectId: 'vera' } },
    { id: 'item:orchid:manifest', at: 'imports', kind: 'ledger', label: 'Import manifest, forty crates', stamp: 'COPY',
      source: 'MIREAUX IMPORTS · MANIFEST', title: 'Consignment, SS Marseillaise',
      body: ['Forty crates, orchids, Marseille to Ashgrave. Twenty-eight initialled at the dock by the bond clerk. Twelve initialled by somebody else, in the importer’s own hand, at the warehouse, at night.', 'She signed for them herself. The clerk remembers the hand.'],
      spoken: 'An import manifest: forty crates of orchids, and twelve of them signed for at night.',
      reading: 'Mireaux signed twelve crates herself, and the clerk watched her. It tells you something about her. Check her row in the Notebook.', about: ['mireaux'], effect: { type: 'suspectTrait', suspectId: 'mireaux' } },
    { id: 'item:orchid:poisons', at: 'pharmacy', kind: 'ledger', label: 'Poisons register, page 31', stamp: 'CONFIDENTIAL',
      source: 'PIKE’S PHARMACY · POISONS REGISTER', title: 'Entries, Nov. 3',
      body: ['10:05 PM — ether, four oz. — signed A. PIKE — purpose: “surgical”. The signature is his, the chemist says, and the hand that made it he has watched a thousand times.'],
      spoken: 'The poisons register: four ounces of ether, signed out by Doctor Pike at ten.',
      reading: 'The chemist watched Dr. Pike sign. It tells you something about him. Check his row in the Notebook.', about: ['pike'], effect: { type: 'suspectTrait', suspectId: 'pike' } },
    { id: 'item:orchid:locker-tag', at: 'baths', kind: 'ticket', label: 'Locker tag no. 9, unclaimed',
      source: 'LANTERN BATHS · LOCKERS', title: 'Tag no. 9',
      body: ['A coat, wet through, hung in locker nine at half past two and never claimed. In the pocket, a second locker tag from somewhere else in the city.'],
      spoken: 'An unclaimed locker tag, and a wet coat with another tag in the pocket.',
      reading: 'The second tag is from another locker in the city. A red mark on the map shows where.', effect: { type: 'lead' } },
    { id: 'item:orchid:dues', at: 'union', kind: 'ledger', label: 'Dues ledger, November',
      source: 'DOCKERS’ UNION LOCAL 9 · DUES', title: 'Collections, week of Nov. 3',
      body: ['Every entry in Brandt’s hand, and every hand that paid him remembered by the man who keeps the book. He knows more about the collector than the collector knows about himself.'],
      spoken: 'The union dues ledger, every line in Brandt’s hand.',
      reading: 'The bookkeeper has watched Brandt write for years. It tells you something about him. Check his row in the Notebook.', about: ['brandt'], effect: { type: 'suspectTrait', suspectId: 'brandt' } },
    { id: 'item:orchid:seal', at: 'warehouse', kind: 'report', label: 'Customs seal report, bay 4',
      source: 'H.M. CUSTOMS · BONDED STORE', title: 'Seal broken, bay 4',
      fields: [['Seal', 'no. 4471, broken'], ['Found', '1:10 AM, by the bond clerk'], ['Missing', 'one crate, orchids']],
      body: ['A crate went out without paper, and the cart tracks in the wet lead out of the yard and up the road.'],
      spoken: 'A customs report: a seal broken and a crate gone, with cart tracks leading out of the yard.',
      reading: 'The cart tracks lead somewhere. A red mark on the map shows where.', effect: { type: 'lead' } },
    { id: 'item:orchid:unfinished', at: 'manor', kind: 'letter', label: 'Lillian’s unfinished letter', stamp: 'PERSONAL',
      source: 'VOSS MANOR · HER WRITING DESK', title: 'To Roland, unfinished',
      body: ['“Rollo — I have changed the will and I have told Father’s lawyer why. When you read this you will already know. I am sorry it had to be me who—”', 'The pen stops. The rest of the page is clean.'],
      spoken: 'An unfinished letter from Lillian to her brother about the will.',
      reading: 'The estate was about to go elsewhere. A motive for Roland. Nothing to mark.', about: ['roland'], effect: { type: 'none' } },
    { id: 'item:orchid:keeper-log', at: 'baylight', kind: 'note', label: 'Keeper’s log, the cliff path',
      source: 'BAY LIGHT · KEEPER’S LOG', title: 'Lights on the Bluff, night of Nov. 3',
      body: ['2:30 — lantern on the cliff path, stops at the old stair, returns. 2:55 — lantern again, further out. 3:10 — nothing. The keeper thinks it was the fishermen. You will have to go and look to be sure it was not, and it costs you an hour to find out it was.'],
      spoken: 'The keeper’s log: a lantern on the cliff path at half past two, and again at five to three.',
      reading: 'It was only the fishermen. An hour wasted.', effect: { type: 'time', hours: 1 } },
  ],

  objects: [
    { id: 'obj:orchid:key', at: 'morgue', name: 'A brass key stamped 114', drawing: 'key',
      desc: 'From her pocket. She had no purse and no money. She had this.',
      spoken: 'A brass key from her pocket, stamped one-fourteen.',
      unlocks: [
        { person: 'vine', line: 'Box one-fourteen. Whose is it?', reply: 'Hers. She opened it Tuesday and put something in. Her brother opened it last night and took something out. I watched his hands the whole time.',
          effect: { type: 'suspectTrait', suspectId: 'roland' } },
        { person: 'roland', line: 'Your sister’s key. What was in the box, Roland?', reply: 'You have no right to that. She—. She changed the will. I took it. I have not read it. I could not.',
          effect: { type: 'culpritTrait' } },
      ] },
    { id: 'obj:orchid:lighter', at: 'jade', name: 'A gold lighter, E.S.', drawing: 'lighter',
      desc: 'Left on the Jade Room bar. Initials on the base.',
      spoken: 'A gold lighter on the Jade Room bar, initials E.S.',
      unlocks: [
        { person: 'strand', line: 'Yours. It was on the Jade Room bar at two. You said you were at the desk.', reply: 'I was not at the desk. I was at the Belvedere. With someone. If it comes out, she is finished. So am I.',
          effect: { type: 'clear', suspectId: 'strand' } },
        { person: 'fane', line: 'Who left this?', reply: 'Emil Strand. Two o’clock, near enough. He had his hands round a glass like it might get away.',
          effect: { type: 'suspectTrait', suspectId: 'strand' } },
      ] },
    { id: 'obj:orchid:matchbook', at: 'parrot', name: 'A matchbook from Rosie’s', drawing: 'matchbook',
      desc: 'Half the matches gone. Rosie’s is a card room. Nobody admits to Rosie’s.',
      spoken: 'A matchbook from Rosie’s, half the matches gone.',
      unlocks: [
        { person: 'marlowe', line: 'Rosie’s. Who plays there?', reply: 'Brandt. Every Thursday, and he loses. He was there Thursday. He lost big.',
          effect: { type: 'suspectTrait', suspectId: 'brandt' } },
        { person: 'brandt', line: 'Rosie’s. Thursday night. You were at the hall, you said.', reply: 'I was at Rosie’s. Then I was at the docks moving a crate for the Frenchwoman. Ask the watchman. Ask what was in it. I never did.',
          effect: { type: 'lead' } },
      ] },
    { id: 'obj:orchid:scarf', at: 'baths', name: 'A silk scarf, orchid scent', drawing: 'scarf',
      desc: 'From the locker with the wet coat. Orchid perfume, heavy.',
      spoken: 'A silk scarf from the wet coat, heavy with orchid.',
      unlocks: [
        { person: 'mireaux', line: 'This is your scent.', reply: 'It is Lillian’s scarf. I gave it to her. She gave it back the night she found the manifest. She said she did not want anything of mine near her.',
          effect: { type: 'suspectTrait', suspectId: 'mireaux' } },
        { person: 'vera', line: 'Recognise this?', reply: 'Lillian’s. She wore it the night she had me fired. Whoever had it last had it at the baths. Lillian never went to the baths.',
          effect: { type: 'lead' } },
      ] },
    { id: 'obj:orchid:cufflink', at: 'gilded', name: 'A cufflink, engraved R.V.', drawing: 'cufflink',
      desc: 'Under the dressing table in suite eleven-hundred. One of a pair.',
      spoken: 'A cufflink under the dressing table, engraved R.V.',
      unlocks: [
        { person: 'roland', line: 'Yours. Found under her table.', reply: 'I was there at ten. We argued. I left at eleven. Dot Bell saw me leave the Lyceum after, alone. I did not go back. I swear to God I did not go back.',
          effect: { type: 'clear', suspectId: 'roland' } },
        { person: 'bell', line: 'Roland Voss. When did he leave?', reply: 'Eleven. Alone. He had one cufflink in. I notice cufflinks. He did not come back for the second act.',
          effect: { type: 'suspectTrait', suspectId: 'roland' } },
      ] },
    { id: 'obj:orchid:watch', at: 'manor', name: 'A pocket watch, stopped at 1:52', drawing: 'watch',
      desc: 'Lillian’s father’s. Dropped on the manor stairs. The glass is cracked.',
      spoken: 'A pocket watch on the manor stairs, stopped at eight minutes to two.',
      unlocks: [
        { person: 'quill', line: 'One fifty-two. That was the call from the suite.', reply: 'It was. One minute ten. She said one thing and hung up. She said: I know what you did, and I am telling them tomorrow.',
          effect: { type: 'culpritTrait' } },
        { person: 'pike', line: 'The watch stopped at one fifty-two. You were her doctor. What stops a watch?', reply: 'A fall. Or a hand that closes on it. Ether does not stop watches, Inspector. Ether stops people.',
          effect: { type: 'suspectTrait', suspectId: 'pike' } },
      ] },
  ],
  story: {
    backstory: [
      'Lillian Voss was twenty-six. Heiress to the Voss estate, singer at the Jade Room, then the Gilded. Rich enough to do what she liked. Bored enough to look into things.',
      'For six months she had been looking into everyone. Her brother’s debts. The parish plate. Strand’s book of rooms. Pike’s register. Mireaux’s crates. Shaw’s column. She kept notes. The notes are gone.',
      'On Tuesday she changed her will. On Thursday she told her brother. On Thursday night she was dead.',
      'The orchid on her table came from Mireaux Imports. Somebody snapped it and put it back. That is the only thing in the room anybody bothered to tidy.',
    ],
    timeline: [
      { time: '10:00 PM', text: 'Roland Voss at the Gilded. Raised voices in suite 1100. He leaves at eleven.' },
      { time: '11:50 PM', text: 'Box 114 at the Trust is opened. Roland signs. His hand shakes.' },
      { time: '1:15 AM', text: 'Two coffees at the Belvedere, one drunk. Signed E.S.' },
      { time: '1:30 AM', text: 'Someone comes in by the Gilded’s side door. The night clerk does not see a face.' },
      { time: '12:52 AM', text: 'Suite 1100 places a call to the Jade Room bar. One minute ten seconds. A man who was waiting for it takes it and leaves.' },
      { time: '1:00 AM', text: 'The last car up the Heights leaves the terminus. Somebody is on it.' },
      { time: '1:52 AM', text: 'Her watch stops.' },
      { time: '2:09 AM', text: 'The house detective opens suite 1100. She is dead. The bathroom window onto the fire escape is unlatched.' },
      { time: '2:15 AM', text: 'The last car down the Heights leaves. Somebody gets off at the docks.' },
      { time: '2:40 AM', text: 'Perpetua Shaw is in the lobby with her notebook out. Before the police.' },
    ],
    truth: [
      'Lillian telephoned the Jade Room at eight minutes to one and said she knew about the crates and was going to the police in the morning. Nikolai Brandt was sitting by the telephone waiting for it. Cass Mireaux had told him what to do if that call ever came.',
      'He rode the last car up the Heights at one, waited on the bandstand in the park, and at half past one went in through the side door, which Vera Lang had left open when she ran out crying. He hit Lillian once. He put the orchid back in the vase because Mireaux had told him to leave the room tidy, and he does what he is told. He left by the bathroom window and the fire escape, and the door stayed on its chain.',
      'Then he took the last car down to the docks at a quarter past two, moved a crate into a boat for Mireaux at half past, and went up the cliff path with a lantern to hide the coat in the smugglers’ cave under the Bay Light. He told his mother it was union wages.',
      'The will was never read. Roland Voss has it in a drawer. It leaves him everything, on one condition: that he stop gambling. She wrote it to save him. He thought it was written to punish him. That is the whole of this family.',
    ],
  },

  epilogue: {
    win: `The cuffs go on in the lobby of the Gilded, under the chandelier. The morning
      edition is already on the street. Somebody sets the orchid back in the vase on the way out.
      Ashgrave forgets by Thursday. You do not.`,
    loss: `The Herald moves it to page nine. Then nineteen. Then nowhere. The suite is let
      again by Christmas. Lillian Voss becomes a name people almost remember. The rain
      keeps doing what rain does.`,
  },
};

export default def;
