import type { CaseDef } from '../../types/game-types';

// The Ash and the Orchid. Thirty locations in five quarters of Ashgrave Bay,
// twenty people who will talk, and twenty-six documents scattered through the
// city -- some of which matter.

const def: CaseDef = {
  id: 'orchid',
  title: 'The Ash and the Orchid',
  subtitle: 'Ashgrave Bay · November 1947',
  tagline: 'A singer is dead in the best suite in the city. Nobody heard a thing.',
  victim: 'Lillian Voss',
  scene: 'gilded',
  difficultyHint: 'A good first case.',
  publicTraits: ['build', 'hair'],
  traitPool: ['hand', 'mark', 'vice', 'scent', 'shoe'],

  briefing: `Two-oh-nine in the morning. The house detective opens suite eleven-hundred.
    Lillian Voss is face down on the silk. No gun. No scream. The orchid on her table is
    snapped at the stem, and somebody put it back in the vase.
    Eleven floors. Forty-one guests. One night clerk. Nobody heard a thing.
    The trail goes cold in two days. Work fast.`,

  radio: [
    'All cars. The Gilded Hotel. The coroner is already inside.',
    'The Voss lawyers are awake. That is a warning.',
    'The Herald had a man in the lobby before we did. Ask how.',
  ],

  terrain: {
    sea: true, seaName: 'ASHGRAVE BAY', river: true, riverSource: 0.5, riverMouth: 0.56,
    parks: 3,
    districts: [
      { text: 'THE HEIGHTS', x: 260, y: 30, rot: -3 },
      { text: 'OLD TOWN', x: 640, y: 240, rot: 2 },
      { text: 'LANTERN QUARTER', x: 990, y: 40, rot: 3 },
      { text: 'THE FLATS', x: 200, y: 420, rot: -2 },
      { text: 'THE BLUFF', x: 1010, y: 560, rot: 2 },
    ],
  },

  locations: [
    // ---- The Heights
    { id: 'gilded', name: 'The Gilded Hotel', type: 'hotel', x: 150, y: 120, district: 'The Heights', desc: 'Brass and marble. Eleven floors of people paying not to be seen.' },
    { id: 'herald', name: 'The Ashgrave Herald', type: 'press', x: 340, y: 90, district: 'The Heights', desc: 'The presses run all night. Ink, sweat, everybody’s business.' },
    { id: 'lyceum', name: 'The Lyceum', type: 'theatre', x: 260, y: 230, district: 'The Heights', desc: 'Velvet and gilt. The Voss box has been theirs since 1910.' },
    { id: 'belvedere', name: 'Café Belvedere', type: 'cafe', x: 110, y: 290, district: 'The Heights', desc: 'Open all night, for people who cannot go home yet.' },
    { id: 'gardens', name: 'Ordell Gardens', type: 'park', x: 430, y: 190, district: 'The Heights', desc: 'Wet gravel, black iron, a bandstand nobody plays.' },
    { id: 'trust', name: 'Ashgrave Trust', type: 'bank', x: 480, y: 310, district: 'The Heights', desc: 'Granite outside. Brass inside. The vault opens for the right surname.' },
    // ---- Old Town
    { id: 'precinct', name: 'Ashgrave Precinct', type: 'police', x: 620, y: 340, district: 'Old Town', desc: 'Home. Bad coffee, one working telephone.' },
    { id: 'cathedral', name: 'St. Ordell’s', type: 'church', x: 570, y: 150, district: 'Old Town', desc: 'Cold stone. Colder charity.' },
    { id: 'mercy', name: 'Mercy Hospital', type: 'hospital', x: 740, y: 110, district: 'Old Town', desc: 'Ether and disinfectant. Bad records, kept well.' },
    { id: 'market', name: 'Lantern Market', type: 'market', x: 720, y: 300, district: 'Old Town', desc: 'Open till dawn. Everything for sale. Receipts optional.' },
    { id: 'library', name: 'Carnegie Library', type: 'library', x: 480, y: 440, district: 'Old Town', desc: 'Every back number of the Herald, and one reader who never leaves.' },
    { id: 'exchange', name: 'Central Exchange', type: 'office', x: 650, y: 480, district: 'Old Town', desc: 'Forty switchboards. Every call in the city, through somebody’s ears.' },
    { id: 'morgue', name: 'City Morgue', type: 'morgue', x: 820, y: 430, district: 'Old Town', desc: 'Tile, ice, and the last honest register in Ashgrave.' },
    { id: 'tram', name: 'Tram Terminus', type: 'tram', x: 560, y: 570, district: 'Old Town', desc: 'The last car up the Heights leaves at one. Somebody was on it.' },
    // ---- Lantern Quarter
    { id: 'jade', name: 'The Jade Room', type: 'club', x: 900, y: 200, district: 'Lantern Quarter', desc: 'Where Lillian sang before the Gilded found her. Her photograph is still up.' },
    { id: 'imports', name: 'Mireaux Imports', type: 'florist', x: 1010, y: 120, district: 'Lantern Quarter', desc: 'Orchids in the window. Crates in the back that were never orchids.' },
    { id: 'pharmacy', name: 'Pike’s Pharmacy', type: 'shop', x: 870, y: 320, district: 'Lantern Quarter', desc: 'Brass scales, glass jars, and a poisons register full of initials.' },
    { id: 'baths', name: 'Lantern Baths', type: 'bathhouse', x: 1050, y: 300, district: 'Lantern Quarter', desc: 'Steam and tile. Lockers rented by the hour and by the year.' },
    { id: 'cannery', name: 'The Old Cannery', type: 'factory', x: 980, y: 450, district: 'Lantern Quarter', desc: 'Shut since ’41. Still lit at night.' },
    { id: 'ferry', name: 'Ferry Landing', type: 'pier', x: 1130, y: 480, district: 'Lantern Quarter', desc: 'Last crossing at one-forty. The steward remembers faces, not names.' },
    // ---- The Flats
    { id: 'parrot', name: 'The Blue Parrot', type: 'bar', x: 150, y: 480, district: 'The Flats', desc: 'A jazz club with a back room and a worse reputation.' },
    { id: 'tenement', name: 'Tenement Row', type: 'home', x: 90, y: 610, district: 'The Flats', desc: 'Nine families to a landing. Everyone sees. Nobody says.' },
    { id: 'pawn', name: 'Cobb’s Pawnshop', type: 'shop', x: 300, y: 530, district: 'The Flats', desc: 'Where the city leaves what it cannot look at any more.' },
    { id: 'garage', name: 'Rainer Garage', type: 'garage', x: 250, y: 670, district: 'The Flats', desc: 'Two pits, one hoist, and every dented wing on the Bluff.' },
    { id: 'union', name: 'Dockers’ Union Hall', type: 'office', x: 420, y: 650, district: 'The Flats', desc: 'Folding chairs, a dues ledger, and Brandt’s name on the door in wet paint.' },
    { id: 'docks', name: 'Rainer Docks', type: 'docks', x: 600, y: 710, district: 'The Flats', desc: 'Oil on black water. The cranes never stop.' },
    { id: 'warehouse', name: 'Bonded Warehouse 4', type: 'warehouse', x: 770, y: 650, district: 'The Flats', desc: 'Customs seals on every door. One of them broken tonight.' },
    // ---- The Bluff
    { id: 'chapel', name: 'Sailors’ Chapel', type: 'church', x: 900, y: 610, district: 'The Bluff', desc: 'One room, a brass bell, prayer cards for the drowned.' },
    { id: 'manor', name: 'Voss Manor', type: 'manor', x: 1080, y: 670, district: 'The Bluff', desc: 'Fourteen rooms on the bluff. One daughter fewer.' },
    { id: 'baylight', name: 'Bay Light', type: 'light', x: 1120, y: 760, district: 'The Bluff', desc: 'One keeper, one lamp, and a log of every light on the water.' },
  ],
  edges: [
    ['gilded', 'herald'], ['gilded', 'belvedere'], ['gilded', 'lyceum'],
    ['herald', 'gardens'], ['herald', 'cathedral'],
    ['lyceum', 'gardens'], ['lyceum', 'belvedere'], ['lyceum', 'trust'],
    ['belvedere', 'parrot'],
    ['gardens', 'trust'], ['gardens', 'cathedral'],
    ['trust', 'precinct'], ['trust', 'library'],
    ['cathedral', 'mercy'], ['cathedral', 'precinct'],
    ['mercy', 'market'], ['mercy', 'jade'],
    ['precinct', 'market'], ['precinct', 'library'], ['precinct', 'exchange'],
    ['market', 'pharmacy'], ['market', 'morgue'], ['market', 'exchange'],
    ['library', 'tram'], ['library', 'pawn'],
    ['exchange', 'tram'], ['exchange', 'morgue'],
    ['morgue', 'cannery'], ['morgue', 'warehouse'],
    ['tram', 'union'], ['tram', 'docks'],
    ['jade', 'imports'], ['jade', 'pharmacy'],
    ['imports', 'baths'],
    ['pharmacy', 'baths'], ['pharmacy', 'cannery'],
    ['baths', 'ferry'],
    ['cannery', 'ferry'], ['cannery', 'chapel'],
    ['ferry', 'manor'],
    ['parrot', 'tenement'], ['parrot', 'pawn'],
    ['tenement', 'garage'],
    ['pawn', 'garage'], ['pawn', 'union'],
    ['garage', 'union'],
    ['union', 'docks'],
    ['docks', 'warehouse'],
    ['warehouse', 'chapel'],
    ['chapel', 'manor'], ['chapel', 'baylight'],
    ['manor', 'baylight'],
  ],
  start: 'precinct',

  suspects: [
    { id: 'vera', name: 'Vera Lang', role: 'Torch singer, The Blue Parrot',
      blurb: 'Had the eleven o’clock spot. Wanted Lillian’s.',
      motive: 'because the top of the bill only fits one name.',
      bio: 'Twenty-six. Came up from the Flats singing in the Parrot’s back room. Lillian got her the Jade Room, then got her fired from it. They were friends once. Vera still says so.',
      alibi: 'On stage at the Parrot till one. Then home. Alone.',
      secret: 'She was at the Gilded at one-thirty, to beg for the Jade Room back. Lillian laughed at her. She left by the side door and told nobody.',
      opinions: { strand: 'Strand? He rents the ninth floor by the hour and thinks nobody knows. Lillian knew.', pike: 'Pike keeps half the Heights upright and the other half asleep. He kept Lillian both.', roland: 'Rollo. Sweet boy. Owes money to people who are not sweet.', shaw: 'Shaw wrote that I sang flat. I did not sing flat. She wanted the Jade Room for someone else.', brandt: 'Brandt drinks at the Parrot and never pays. Nobody asks him to.', mireaux: 'The Frenchwoman sends flowers to people who did not order flowers.', tovar: 'The Deacon takes from the plate. Everybody on the Flats knows. Nobody on the Heights does.' },
      topics: [
        { id: 'night', q: 'Where were you at two this morning?', a: 'On stage till one. Two encores. Then a cab, then bed. Bix will tell you. He always tells you.' },
        { id: 'lillian', q: 'What was Lillian to you?', a: 'A friend. Then a boss. Then a woman who had me fired from the Jade Room over a dress. We were going to make it up. We were always going to make it up.' },
        { id: 'billing', q: 'The set list says she owed you the top of the bill.', a: 'She promised it to me in July. Then she took the Gilded and forgot. I underlined it because I was angry, not because I meant anything by it.', after: 'lillian' },
        { id: 'side-door', q: 'Somebody used the side door of the Gilded at half past one. Was it you?', a: 'A long silence. Yes. I went to ask for the Jade Room back. She laughed. I left. She was alive when I left, Inspector. She was laughing.', after: 'night', cost: 1, effect: { type: 'suspectTrait', suspectId: 'vera' } },
        { id: 'who', q: 'If it was not you, who?', a: 'Somebody with a key. The side door locks from inside. I got in because it was open, and it was open because somebody was expected.', after: 'side-door' },
      ] },
    { id: 'strand', name: 'Emil Strand', role: 'Night manager, The Gilded',
      blurb: 'Has a key to every door in the building.',
      motive: 'because she knew which rooms he rented by the hour, and to whom.',
      bio: 'Forty-four. Night manager for nine years. Rents suites by the hour to people who need them and keeps a book he should not keep. Lillian found the book.',
      alibi: 'At the desk all night. The clerk will say so.',
      secret: 'He was not at the desk. He was at the Belvedere with a councilman’s wife, and the second coffee was hers.',
      opinions: { vera: 'Miss Lang came through the side door at half one. I saw her from the mezzanine. I did not stop her.', pike: 'Dr. Pike has a standing order on the ninth floor. I do not ask what for.', roland: 'Young Mr. Voss argued with his sister at ten. The whole floor heard.', shaw: 'Miss Shaw is in this hotel more nights than she is not. Never as a guest.', brandt: 'Brandt collects for the union in my lobby. I let him. It is cheaper.', mireaux: 'Madame Mireaux sends the orchids. Every Monday. The bill goes to the estate.', tovar: 'The Deacon takes the collection from our staff on Fridays. Half of it, anyway.' },
      topics: [
        { id: 'night', q: 'Where were you at two?', a: 'At the desk. Miss Pruett will confirm. I was at the desk from midnight to six.' },
        { id: 'book', q: 'Lillian found your book of rooms. What was in it?', a: 'Names. Hours. Room numbers. Half the council. She said she would not use it. She said it like a woman deciding when.', cost: 1, effect: { type: 'suspectTrait', suspectId: 'strand' } },
        { id: 'keys', q: 'You have a key to every door. Including the side door.', a: 'I have the master. So does the house detective. So, until Tuesday, did Miss Voss. She asked for one. I gave it to her. I do not know why she wanted it.', after: 'night' },
        { id: 'coffee', q: 'Two coffees at the Belvedere at one-fifteen, signed E.S. You were at the desk?', a: 'He goes grey. I stepped out. Twenty minutes. Miss Pruett covered. If you need to know who the second coffee was, I will tell you in a room with a door.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'orchid', q: 'The orchid was put back in the vase. Who tidies up in this hotel?', a: 'Nobody, at two in the morning. Whoever did that has stood in a lot of hotel rooms and left them looking like nobody was there.' },
      ] },
    { id: 'pike', name: 'Dr. Aurelio Pike', role: 'Society physician',
      blurb: 'Writes the prescriptions that keep this city upright.',
      motive: 'because she was going to name his pharmacy in open court.',
      bio: 'Sixty. Physician to the Heights. Signs out ether by the pint and morphine by the ounce, and the register is mostly initials. Lillian was his patient. Then she was his witness.',
      alibi: 'Stitching a hand at Mercy at three. Before that, asleep.',
      secret: 'The man he stitched was a courier. Pike’s pharmacy moves more than orchids, and Mireaux moves it.',
      opinions: { vera: 'Miss Lang has a throat I have treated and a temper I have not.', strand: 'Strand sends me patients. I send him a cheque. That is the whole of it.', roland: 'Roland Voss has been my patient since he was nine. Nerves. He has never grown out of them.', shaw: 'Perpetua Shaw wrote about my pharmacy once. I have not slept properly since.', brandt: 'I stitched Brandt’s hand in ’46. He did not flinch. Men who do not flinch worry me.', mireaux: 'Madame Mireaux imports flowers. I am a doctor. That is all I know about flowers.', tovar: 'The Deacon’s brother is in Marrow House. I signed the papers. She has never forgiven me for being right.' },
      topics: [
        { id: 'night', q: 'Where were you at two?', a: 'Asleep. Then at Mercy at three, stitching a hand. The admission slip is there. Read it.' },
        { id: 'patient', q: 'Lillian was your patient. What was she taking?', a: 'Nothing she should not. Something for sleep. I signed for it. It was not enough to hurt her and she did not take enough to try.' },
        { id: 'court', q: 'She was going to name your pharmacy in court.', a: 'She said so. On Wednesday. She had the register, or a copy of it. Where she got it I would like to know as much as you would.', cost: 1, effect: { type: 'suspectTrait', suspectId: 'pike' } },
        { id: 'ether', q: 'You signed out four ounces of ether on Thursday.', a: 'For a surgical case that did not happen. The patient did not come. The ether is in my bag. I can show you. I would rather you did not ask what else is in the bag.', after: 'court' },
        { id: 'hand', q: 'Whose hand did you stitch?', a: 'A man who did not give a name and paid cash. Left hand. Cut with glass. He had been somewhere with a great deal of glass.', after: 'night', cost: 1, effect: { type: 'lead' } },
      ] },
    { id: 'mireaux', name: 'Cass Mireaux', role: 'Importer of rare flowers',
      blurb: 'Brings orchids in through the docks. Other things, under them.',
      motive: 'because the orchids were never the cargo, and she had worked that out.',
      bio: 'Thirty-eight. Marseille, then Ashgrave. Forty crates a month. Twelve of them she signs for herself, at night. Lillian’s orchids came from her. So did the one on the table.',
      alibi: 'At the warehouse till two, counting crates. The clerk saw her.',
      secret: 'The twelve crates are morphine for Pike. She signed for them herself because the bond clerk was starting to ask questions.',
      opinions: { vera: 'Vera Lang wants what Lillian had. She has wanted it since she was nineteen.', strand: 'Strand rents rooms to men who buy my flowers for women who are not their wives.', pike: 'Dr. Pike is a customer. Of flowers.', roland: 'The brother owes money to my dock. I do not collect it myself.', shaw: 'Shaw came to the warehouse in October asking about crates. I gave her orchids. She went away.', brandt: 'Brandt moves what I need moved. He does not ask. I like that in a man.', tovar: 'The Deacon buys lilies for funerals on credit and pays for them from the plate.' },
      topics: [
        { id: 'night', q: 'Where were you at two?', a: 'At the bonded warehouse, counting crates. Latimer saw me. He always sees me.' },
        { id: 'orchids', q: 'The orchid on her table was yours.', a: 'Every orchid on the Heights is mine. I sent that one on Monday. Somebody snapped it. Somebody who does not know what they cost.' },
        { id: 'manifest', q: 'Twelve crates on the manifest are in your hand, not the clerk’s.', a: 'A pause you could drive a truck through. The clerk was ill. I signed. That is not a crime.', cost: 1, effect: { type: 'suspectTrait', suspectId: 'mireaux' } },
        { id: 'cable', q: '‘Do not let her see the manifest.’ A cable from Marseille, with your name on it.', a: 'Then you know she saw it. She came to the warehouse on Wednesday and read it standing up. She said nothing. That was worse.', after: 'manifest', cost: 1, effect: { type: 'lead' } },
        { id: 'scarf', q: 'Did you give her a scarf?', a: 'Silk. Orchid. She wore it a month. Then she gave it back with the manifest still in her eyes.' },
      ] },
    { id: 'tovar', name: 'Deacon Iris Tovar', role: 'St. Ordell’s',
      blurb: 'Runs the soup line and the collection plate. One of them balances.',
      motive: 'because the parish accounts only balanced while she stayed quiet.',
      bio: 'Fifty-five. Twenty years a deacon. The soup line feeds two hundred. The plate collects for four hundred. Lillian gave to both, and counted.',
      alibi: 'In the vestry, praying, from midnight to dawn.',
      secret: 'She has taken from the plate for years. Not for herself. For a brother in Marrow House whose bills nobody else pays.',
      opinions: { vera: 'Miss Lang sings in a place I do not go. She sings well. I have heard it through the wall.', strand: 'Mr. Strand gives to the plate on Fridays. Guilt money. It spends the same.', pike: 'Dr. Pike put my brother away. He was right to. I will not say it to his face.', roland: 'Roland Voss sits in the family pew and looks at the door.', shaw: 'Miss Shaw comes to Mass to see who else does.', brandt: 'Nikolai Brandt gives to the soup line every week. Cash. Nobody knows where from.', mireaux: 'Madame Mireaux sends lilies for every funeral in the parish. She knows about most of them before I do.' },
      topics: [
        { id: 'night', q: 'Where were you at two?', a: 'In the vestry. On my knees. Old Wyn will tell you the light was on.' },
        { id: 'letter', q: 'Lillian wrote to you about the parish books.', a: 'She did. She was right. Two hundred a year, for nine years, for a brother in Marrow House. I was going to tell the Canon on Sunday.', cost: 1, effect: { type: 'suspectTrait', suspectId: 'tovar' } },
        { id: 'hymnal', q: 'Your hymnal was on the bandstand steps with an orchid petal in it.', a: 'She stops. I was in the gardens. Not the vestry. I walk when I cannot pray. I found the petal on the path and kept it. I do not know why.', after: 'night' },
        { id: 'gate', q: 'Who did you see in the gardens?', a: 'A man on the bandstand. A hat. He sat an hour and did not smoke, which is how I knew he was waiting for somebody.', after: 'hymnal', cost: 1, effect: { type: 'lead' } },
      ] },
    { id: 'roland', name: 'Roland Voss', role: 'The victim’s brother',
      blurb: 'Inherits everything. Cried in the wrong order.',
      motive: 'because the estate passes whole to the surviving child.',
      bio: 'Thirty. The younger Voss. Cards at Rosie’s, cheques at the Trust, apologies at the manor. Lillian changed the will on Tuesday. He found out on Thursday.',
      alibi: 'At the Lyceum till eleven. Then the manor. The driver will say so.',
      secret: 'He opened her deposit box at ten to midnight and took the new will. He has it still. He has not read past the first page.',
      opinions: { vera: 'Vera was Lil’s friend. Real friend. They fought like sisters. I would know.', strand: 'Strand let me into her suite once when I lost my key. He did not ask why.', pike: 'Pike has had a hand in my pockets since I was nine. Prescriptions. Advice. Bills.', shaw: 'Shaw wrote that I cried in the wrong order. How does a person cry in the wrong order?', brandt: 'Brandt collects for men I owe. He is polite about it. That is the frightening part.', mireaux: 'The Frenchwoman lent me money in the spring. Lil paid it back. I did not ask how much.', tovar: 'The Deacon buried our mother. She was kind. She is still kind. It is exhausting.' },
      topics: [
        { id: 'night', q: 'Where were you at two?', a: 'At the manor. In bed. The driver brought me up at midnight. He will say so. He always says so.' },
        { id: 'argument', q: 'You argued with her at ten.', a: 'About money. Always about money. She said she was changing the will. I said things. I left. That was the last thing I said to her, and it was a bad thing.' },
        { id: 'box', q: 'Box one-fourteen was opened at ten to midnight. By you.', a: 'His hands go to his face. I wanted to see what she had done. I took it. I have not read it. I cannot.', after: 'argument', cost: 1, effect: { type: 'suspectTrait', suspectId: 'roland' } },
        { id: 'car', q: 'The Packard came into the garage at ten to three with a wing stove in.', a: 'I hit the gate. The manor gate. At midnight. I was—. I had been drinking. That is all it was.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'will', q: 'What is in the will?', a: 'I do not know. I have told you. I have it in a drawer and I look at the drawer.', after: 'box' },
      ] },
    { id: 'brandt', name: 'Nikolai Brandt', role: 'Dock union enforcer',
      blurb: 'Settles arguments the cheap way. Four men who owe him say he was elsewhere.',
      motive: 'because somebody paid, and he never asks why.',
      bio: 'Thirty-five. Collects the dues and the debts. Broke a man’s hand at the cannery in ’46 and the man thanked him. Sends money to his mother on Tenement Row every week.',
      alibi: 'At the union hall, counting dues. Four men saw him.',
      secret: 'The four men were at Rosie’s. Brandt was at the docks, moving a crate for Mireaux, and he does not know what was in it.',
      opinions: { vera: 'Vera sings. I listen. She never sings the one I ask for.', strand: 'Strand pays the union to keep the hotel quiet. Every month. On time.', pike: 'Pike stitched me once. Good hands. Bad eyes. He did not look at my face the whole time.', roland: 'The kid owes forty at Rosie’s. I collect for Rosie. I have not collected yet.', shaw: 'Shaw wrote about the union once and got it right. I did not like that.', mireaux: 'The Frenchwoman pays cash and does not talk. Best kind of work there is.', tovar: 'The Deacon feeds my mother’s landing every Thursday. I give what I can.' },
      topics: [
        { id: 'night', q: 'Where were you at two?', a: 'The hall. Counting dues. Four men saw me. You want their names, you can have their names.' },
        { id: 'four', q: 'Your four men were at Rosie’s. So were you.', a: 'He looks at the floor a long time. Fine. Rosie’s till one. Then the docks. Then home.', cost: 1, effect: { type: 'suspectTrait', suspectId: 'brandt' } },
        { id: 'crate', q: 'What were you doing at the docks?', a: 'Moving a crate. For the Frenchwoman. Off a cart and into a boat. I did not open it. I never open them.', after: 'four', cost: 1, effect: { type: 'lead' } },
        { id: 'letter', q: 'There is a threat on union paper nailed to the cannery door.', a: 'I do not type. Somebody at the hall does. Somebody who wants the cannery to think it was me.', after: 'night' },
        { id: 'mother', q: 'You send money to Tenement Row.', a: 'Every week. She thinks it is union wages. It is not always union wages. Leave her out of this.' },
      ] },
    { id: 'shaw', name: 'Perpetua Shaw', role: 'Columnist, The Herald',
      blurb: 'Was in the lobby before the police. Has never said why.',
      motive: 'because the column had run dry, and a dead heiress runs for a month.',
      bio: 'Forty-two. “Around the Town”, six days a week, twenty years. Knows everything about everyone and prints half of it. Lillian was her best copy and her oldest enemy.',
      alibi: 'Tipped off by a bellboy at two-thirty. Came straight over.',
      secret: 'There was no bellboy. She was in the hotel at one, on the ninth floor, with somebody she will not name.',
      opinions: { vera: 'Vera Lang sang flat in July. I wrote it. She has never forgiven me for being accurate.', strand: 'Strand’s ninth floor is the best-kept secret on the Heights, which is to say I have known for years.', pike: 'Aurelio Pike has a register that would end him. Lillian had a copy. I would give a great deal to know where.', roland: 'Roland cried at the wrong moment. I meant it kindly. It did not read that way.', brandt: 'Brandt is the only honest man in the union, in that he is honestly dangerous.', mireaux: 'Cass Mireaux gave me orchids to stop asking questions. I took the orchids. I kept asking.', tovar: 'Iris Tovar takes from the plate. I have known for two years. I have not printed it. Ask me why.' },
      topics: [
        { id: 'night', q: 'You were in the lobby before we were. How?', a: 'A bellboy telephoned. I tip bellboys. It is the whole of my profession.' },
        { id: 'lobby', q: 'The photograph puts you in the lobby at two-forty with your hat off.', a: 'I had been in the building since one. On the ninth floor. With somebody. If you print that, I will print you.', after: 'night', cost: 1, effect: { type: 'suspectTrait', suspectId: 'shaw' } },
        { id: 'column', q: 'Your column that morning was about her.', a: 'My column every morning is about somebody. She was the best copy in the city. Alive. Dead she is a month of columns and I hate every one of them.' },
        { id: 'notes', q: 'Lillian kept notes on everyone. Where are they?', a: 'Gone from the suite, I would guess. If I had them you would be reading them in tomorrow’s edition and I would be on a train.', after: 'column', cost: 1, effect: { type: 'lead' } },
        { id: 'ninth', q: 'Who were you with on the ninth floor?', a: 'No. Not for you, not for the Commissioner, not for God. Ask me anything else.', after: 'lobby' },
      ] },
  ],

  witnesses: [
    { id: 'pruett', at: 'gilded', name: 'Ada Pruett', role: 'night clerk, the Gilded',
      intro: 'Ada Pruett. Night desk, eleven years. I see everyone who comes in the front. Most of the side door too.',
      bio: 'Eleven years on the night desk. Reads the register upside down. Knows who is in which room and with whom.',
      knows: ['strand', 'shaw', 'roland'],
      aboutLine: 'I know the face. One thing about them, and then you go.',
      leadLine: 'Somebody left in a hurry and dropped something on the way. Look at',
      spentLine: 'I have a desk. I have said enough.',
      opinions: { strand: 'Mr. Strand was not at the desk from one till twenty past. He asked me to say he was. I said I would. I am not saying it now.', shaw: 'Miss Shaw came through the lobby at one. Up in the lift. Not down again till the police came.', roland: 'Mr. Voss argued with his sister at ten. He left at eleven with one cufflink in.' },
      topics: [
        { id: 'night', q: 'What happened here tonight?', a: 'Suite eleven-hundred rang down at midnight for ice. At two-oh-nine Mr. Halloran, the house detective, went up with a passkey because the light was on and the door was on the chain. He came down white.' },
        { id: 'side', q: 'Who uses the side door?', a: 'Staff. Mr. Strand. Guests who do not want to be guests. It locks from inside. Tonight it was open from one till I locked it at three.' },
        { id: 'chain', q: 'The door was on the chain?', a: 'From inside. Mr. Halloran cut it. Whoever left did not leave by the door.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'lillian', q: 'What was Miss Voss like?', a: 'Kind to the staff. Hard on everybody else. She tipped in silver and remembered your name. She remembered too much, I think.' },
      ] },
    { id: 'marlowe', at: 'parrot', name: 'Bix Marlowe', role: 'barman, the Blue Parrot',
      intro: 'Bix. I pour, I listen, I forget. Tonight I will make an exception.',
      bio: 'Twenty years behind the bar. Was a fighter. Has a fighter’s memory for faces and a barman’s for tabs.',
      knows: ['vera', 'brandt', 'pike'],
      aboutLine: 'Sits at my bar. You notice things across a bar.',
      leadLine: 'A man came in white as a sheet and went out the back. He came back lighter. Try',
      spentLine: 'Bar is closed. So am I.',
      opinions: { vera: 'Vera came off at one and went straight out the front. She had her coat on before the applause stopped.', brandt: 'Brandt was in at eleven, out at half past. He was going to Rosie’s. He goes every Thursday and every Thursday he says he is not.', pike: 'Pike drinks here when he cannot drink on the Heights. Rye. Doubles. He was not in tonight.' },
      topics: [
        { id: 'night', q: 'Anything happen here tonight?', a: 'Vera did two sets. A man came in white, went out the back, came back lighter. Somebody left a matchbook from Rosie’s on the bar, and nobody admits to Rosie’s.' },
        { id: 'vera', q: 'Vera left fast. Where to?', a: 'She said home. She took the tram up the Heights. Home is the other way.', cost: 1, effect: { type: 'suspectTrait', suspectId: 'vera' } },
        { id: 'lillian', q: 'Did Lillian Voss drink here?', a: 'She sang here first. Before the Jade Room, before the Gilded. She came back once a month and sat at the end of the bar and did not sing. She was here Tuesday.' },
      ] },
    { id: 'flett', at: 'mercy', name: 'Oona Flett', role: 'night sister, Mercy Hospital',
      intro: 'Sister Flett. Ward four, nights. People say things at three in the morning.',
      bio: 'Ran a field hospital in Italy. Nothing on ward four surprises her. Keeps her own notes on Dr. Pike.',
      knows: ['pike', 'tovar', 'roland'],
      aboutLine: 'They have been through my ward. You do not forget a patient.',
      leadLine: 'A porter found something in a coat left on the ward. He was too scared to hand it in. It went to',
      spentLine: 'I have patients. Come back with a warrant or a fever.',
      opinions: { pike: 'Dr. Pike stitched a man’s hand at three and let him walk. Left hand, cut with glass. He did not write the man’s name. I did. It was not a real name.', tovar: 'The Deacon comes to see her brother on the second floor every Sunday. She pays his bill in cash and cries in the corridor.', roland: 'Roland Voss was on ward four in March. Nerves, the chart said. He talked in his sleep about his sister.' },
      topics: [
        { id: 'night', q: 'What came through Mercy tonight?', a: 'A cut hand at three. A drunk at four. And a telephone call at half past two asking whether we had a Voss. We did not. Not yet.' },
        { id: 'call', q: 'Who called about a Voss?', a: 'A woman. She did not give a name. She sounded like she was calling from a bar.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'pike', q: 'What do you keep in your notes on Dr. Pike?', a: 'Dates. Amounts. Ether by the pint. I am not a policeman. I write things down in case one turns up.' },
      ] },
    { id: 'rainer', at: 'docks', name: 'Sal Rainer', role: 'night watchman, Rainer Docks',
      intro: 'Rainer. No relation. I walk the wharf ten till six and I count the boats.',
      bio: 'Lost a leg on the wharf in ’39 and stayed. Counts boats, crates and people, in that order.',
      knows: ['mireaux', 'brandt'],
      aboutLine: 'Comes down here more than a person should. I have watched.',
      leadLine: 'Something went in the water tonight. Something else went in a pocket. The pocket walked toward',
      spentLine: 'Shift is over. Go and bother somebody warm.',
      opinions: { mireaux: 'Madame Mireaux was on the wharf at half one with a lantern and a cart. She does not carry things herself. Tonight she carried.', brandt: 'Brandt lifted a crate into a boat at two. Alone. It took two men to lift it off the cart.' },
      topics: [
        { id: 'night', q: 'What did you see tonight?', a: 'A crate off a cart into a boat. A woman with a lantern. And something small thrown off the end of the pier that did not sink.' },
        { id: 'boat', q: 'Where did the boat go?', a: 'Across the bay. Toward the Bluff. No light. There is only one place to land under the Bluff without a light.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'lillian', q: 'Did Lillian Voss ever come to the docks?', a: 'Wednesday. She stood where you are standing and watched the crates come off for an hour. She wrote in a little book. She did not talk to me. She did not need to.' },
      ] },
    { id: 'wyn', at: 'cathedral', name: 'Old Wyn', role: 'sexton, St. Ordell’s',
      intro: 'Wyn. I keep the doors and the graves. One is busier than the other.',
      bio: 'Sexton for forty years. Buried three canons. Knows which pews creak and who sits in them.',
      knows: ['tovar', 'shaw'],
      aboutLine: 'I have watched that one at prayer. You learn things about a person on their knees.',
      leadLine: 'Somebody was in the vestry who should not have been. They left by the side gate toward',
      spentLine: 'The church is closed. Good night.',
      opinions: { tovar: 'The Deacon’s light was on in the vestry till midnight. Then off. Then on again at three. In between she was not in the vestry.', shaw: 'Miss Shaw sits at the back and watches who takes communion. She writes it down after.' },
      topics: [
        { id: 'night', q: 'Who was in the church tonight?', a: 'The Deacon, on and off. A man in the vestry at one who was not the Deacon. He went out the side gate. I did not see a face. I saw a hat.' },
        { id: 'vestry', q: 'What did the man in the vestry want?', a: 'The letters. Miss Voss wrote to the Deacon. The letters were in the vestry drawer. They are not now.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'lillian', q: 'Did you know Miss Voss?', a: 'She gave to the soup line and counted the plate. She was the only one on the Heights who ever counted. That is why she is dead, if you ask me. Nobody has.' },
      ] },
    { id: 'cobb', at: 'pawn', name: 'Ezra Cobb', role: 'pawnbroker',
      intro: 'Cobb. I buy what people cannot look at any more. You would be surprised what that is.',
      bio: 'Thirty years in the shop his father opened. Keeps a book on regulars, and not only for the money.',
      knows: ['vera', 'mireaux', 'strand'],
      aboutLine: 'Regular. I keep a book on regulars.',
      leadLine: 'A ticket was redeemed tonight. Cash, no name, in a hurry. It came in from',
      spentLine: 'I have told you what I sell. That is all I sell.',
      opinions: { vera: 'Miss Lang pawns a bracelet every month and redeems it the week after. Tonight she redeemed it early.', mireaux: 'Madame Mireaux does not pawn. She buys. Whatever the docks lose, she has by Friday.', strand: 'Mr. Strand pawned a lighter in June. Gold, initials. He never came back for it. Somebody else did.' },
      topics: [
        { id: 'night', q: 'What came through the shop tonight?', a: 'One ticket redeemed for cash at midnight by a hand that did not pledge it. One bracelet redeemed early. One man who looked at the knives and did not buy.' },
        { id: 'lighter', q: 'Who redeemed Strand’s lighter?', a: 'A woman. Gloves. She paid with a new note and did not wait for change. She went up toward the Jade Room.', cost: 1, effect: { type: 'lead' } },
        { id: 'knives', q: 'The man who looked at the knives.', a: 'Big. Quiet. Hands like shovels. He looked at the knives the way a man looks at something he already owns.', after: 'night', cost: 1, effect: { type: 'suspectTrait', suspectId: 'brandt' } },
      ] },
    { id: 'bell', at: 'lyceum', name: 'Dot Bell', role: 'usherette, the Lyceum',
      intro: 'Dot. I know which seats leave before the last act. Tonight somebody left before the first.',
      bio: 'Nineteen. Wants to be on the stage, not beside it. Sees everything from the aisle with a torch.',
      knows: ['vera', 'shaw', 'roland'],
      aboutLine: 'Regular in the boxes. You see a lot from the aisle.',
      leadLine: 'A coat was left in box C. Somebody came back for it fast, and went out toward',
      spentLine: 'Curtain is down. So am I.',
      opinions: { roland: 'Mr. Voss left at eleven with one cufflink in and his face like a wet Sunday.', vera: 'Miss Lang sat in the stalls on a comp on Tuesday and cried through the second act. It was a comedy.', shaw: 'Miss Shaw takes box D on Thursdays and watches box C.' },
      topics: [
        { id: 'night', q: 'What happened here tonight?', a: 'The Voss box was empty from eleven. A coat was left over the rail. A woman came for it at half past one, in a hurry, in gloves.' },
        { id: 'coat', q: 'Whose coat?', a: 'A man’s. Camel. Expensive. The woman who took it was not the woman who came with him.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'lillian', q: 'Did Miss Voss come to the Lyceum?', a: 'Every Thursday. Box C, her father’s seat. Last Thursday she came alone and left at the interval. She looked at me on the way out like she was going to say something. She did not.' },
      ] },
    { id: 'pardo', at: 'belvedere', name: 'Louis Pardo', role: 'waiter, Café Belvedere',
      intro: 'Pardo. Nights. I pour coffee for people who cannot sleep. I remember what they order. It never changes.',
      bio: 'Came from Lisbon in ’38. Has poured for every affair on the Heights and never said a word about one.',
      knows: ['pike', 'roland', 'strand'],
      aboutLine: 'Table by the window, always. I have poured for them a hundred times.',
      leadLine: 'Two coffees at a quarter past one. One drunk. The other chair went cold and its owner went toward',
      spentLine: 'Kitchen is closed. Come back for breakfast.',
      opinions: { strand: 'Mr. Strand takes coffee with a lady who is not Mrs. Strand. Tuesdays and Thursdays. Tonight he left his coffee.', pike: 'The doctor takes his coffee black and his hands shake till the second cup.', roland: 'Mr. Voss comes in after the Lyceum and drinks brandy in a coffee cup because he thinks I do not know.' },
      topics: [
        { id: 'night', q: 'Who was in tonight?', a: 'Mr. Strand and his lady, one-fifteen. He left at twenty past like something bit him. She stayed and finished both coffees. Then a man in a wet coat at three who ordered nothing and watched the door.' },
        { id: 'lady', q: 'Who is Strand’s lady?', a: 'I pour. I do not know names. I know she wears a wedding ring and turns it round when he is late.' },
        { id: 'wet', q: 'The man in the wet coat.', a: 'Big. Hat. He asked whether the Bluff tram was still running. It was not. He walked.', after: 'night', cost: 1, effect: { type: 'lead' } },
      ] },
    { id: 'amory', at: 'gardens', name: 'Kit Amory', role: 'night keeper, Ordell Gardens',
      intro: 'Amory. I lock the gates at ten and open them at six. In between I see who climbs the railings.',
      bio: 'A poet, once, published twice. Now keeps the gardens and writes nothing down but who comes in after dark.',
      knows: ['tovar', 'roland', 'vera'],
      aboutLine: 'Walks the paths at night. You learn a person by how they walk in the dark.',
      leadLine: 'Somebody sat on the bandstand steps an hour and left something under them. They went toward',
      spentLine: 'Gates are locked. That includes to you.',
      opinions: { tovar: 'The Deacon walks the gardens when she cannot pray. Tonight she walked from midnight till two.', roland: 'Young Voss sat on the bandstand steps on Tuesday and drank from a flask and talked to nobody.', vera: 'Miss Lang cuts through the gardens to the Gilded. The railings on the north side are loose. She knows it.' },
      topics: [
        { id: 'night', q: 'Who came through the gardens tonight?', a: 'The Deacon, walking. A man on the bandstand at one, waiting. A woman over the north railings at half one, running.' },
        { id: 'man', q: 'The man on the bandstand.', a: 'Hat down. Did not smoke. Waited an hour and then a woman came from the Gilded side and they went off together toward the Trust.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'lillian', q: 'Did Miss Voss walk here?', a: 'Every morning at seven with a book. Not a novel. A ledger. She read ledgers like other women read novels.' },
      ] },
    { id: 'vine', at: 'trust', name: 'Hedda Vine', role: 'teller, Ashgrave Trust',
      intro: 'Miss Vine. Second window. I see the money come and go, and the faces it belongs to.',
      bio: 'Second window for fourteen years. Was promised the first. Notices a customer who counts twice.',
      knows: ['roland', 'tovar', 'mireaux'],
      aboutLine: 'Has an account with us. I notice a customer who counts twice.',
      leadLine: 'A deposit box was opened at ten to midnight by somebody who should have been elsewhere. What came out went to',
      spentLine: 'The bank is closed. It was closed when you came in.',
      opinions: { roland: 'Mr. Voss signed for box one-fourteen at ten to midnight. His hand shook so badly the pen went through the page.', tovar: 'The Deacon deposits two hundred a year into an account in her brother’s name. Cash. Small notes.', mireaux: 'Madame Mireaux banks in three names. All of them hers.' },
      topics: [
        { id: 'night', q: 'Who came to the vault tonight?', a: 'One person. Mr. Roland Voss. Ten to midnight. He had a key that was not his and a signature that was.' },
        { id: 'tuesday', q: 'Miss Voss came on Tuesday?', a: 'She put an envelope in one-fourteen and took nothing out. She said, if my brother comes, let him. He will need to see it. I let him. I should not have.', cost: 1, effect: { type: 'suspectTrait', suspectId: 'roland' } },
        { id: 'lillian', q: 'Did Miss Voss bank here?', a: 'Since she was twelve. She counted the teller’s count. Every time. She was never wrong and she never apologised for checking.' },
      ] },
    { id: 'quill', at: 'exchange', name: 'Bea Quill', role: 'night operator, Central Exchange',
      intro: 'Quill. Board nine. I connect the calls. I am not supposed to listen. I am not supposed to do a lot of things.',
      bio: 'Board nine, nights, six years. Can tell a voice from three words. Keeps a notebook she is not supposed to keep.',
      knows: ['shaw', 'strand', 'pike'],
      aboutLine: 'I know the voice. A voice at two in the morning tells you plenty.',
      leadLine: 'A call went out from suite eleven-hundred at eight to two. The number it reached is at',
      spentLine: 'Board is lit. Nine calls waiting. None of them yours.',
      opinions: { shaw: 'Miss Shaw rings the Herald from hotel lobbies at all hours. Tonight she rang from the Gilded at two-fifteen. Before the police were called.', strand: 'Mr. Strand takes a call every Thursday at one from a number on the Heights. A woman. Tonight the call came and he was not at the desk.', pike: 'Dr. Pike rings the pharmacy at midnight most nights. Tonight he rang the docks.' },
      topics: [
        { id: 'night', q: 'What went through board nine tonight?', a: 'Everything. Suite eleven-hundred, out, at one fifty-two. Lantern four-four. One minute ten. Then nothing from that suite ever again.' },
        { id: 'call', q: 'Lantern four-four. Where is that?', a: 'The bar telephone at the Jade Room. Somebody there took a call from a woman who was about to die. I listened. I should not have. She said she knew.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'lillian', q: 'Did she call anyone else this week?', a: 'Everyone. The Trust. The Herald. Mercy. The pharmacy. A shipping office. She was ringing round the whole city like a woman settling accounts.' },
      ] },
    { id: 'marsh', at: 'tram', name: 'Ollie Marsh', role: 'conductor, the Bluff line',
      intro: 'Marsh. Last car up the Bluff. I punch the tickets and I remember who has none.',
      bio: 'Thirty years on the Bluff line. Knows every regular by their seat. Was a witness at two trials and enjoyed it.',
      knows: ['brandt', 'tovar', 'vera'],
      aboutLine: 'Rides my car. You learn a person by which seat they take.',
      leadLine: 'Somebody got off at the wrong stop and walked back the way we came. They were headed for',
      spentLine: 'Depot is shut. Fourteen hours on my feet.',
      opinions: { brandt: 'Brandt rides the Bluff car standing up, at the back, so he can see everyone. Tonight he got off at the docks.', tovar: 'The Deacon rides to Marrow House on Sundays and comes back with her eyes red.', vera: 'Miss Lang got on at the Parrot at one and off at the Heights. Home is the Flats.' },
      topics: [
        { id: 'night', q: 'Who rode the last car?', a: 'Eleven passengers. A singer going the wrong way. A big man who got off at the docks. And somebody who got off at the wrong stop and walked back.' },
        { id: 'wrong', q: 'The one who walked back.', a: 'Coat collar up. Got off at the Trust and walked back down toward the Gilded. I punched the ticket. I did not see the face. I saw good shoes.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'lillian', q: 'Did Miss Voss ride the tram?', a: 'Never. She had the Packard. Except Wednesday. Wednesday she rode to the docks with me and looked out of the window the whole way like she was memorising it.' },
      ] },
    { id: 'grey', at: 'library', name: 'Tobias Grey', role: 'night librarian',
      intro: 'Grey. The reading room stays open for the insomniacs. I stay open with it. I know what everybody reads.',
      bio: 'Was a lawyer. Was disbarred. Now shelves the Herald and reads it before anyone else.',
      knows: ['shaw', 'pike'],
      aboutLine: 'Reads here. You can tell a person by what they look up.',
      leadLine: 'A back number was cut with a razor tonight. The reader left fast, toward',
      spentLine: 'This is a library. Lower your voice and leave.',
      opinions: { shaw: 'Miss Shaw reads her own columns here. Twenty years of them. She is looking for something she wrote and forgot.', pike: 'Dr. Pike came in on Wednesday and asked for the Herald from 1946. The cannery fire. He read it twice and put it back upside down.' },
      topics: [
        { id: 'night', q: 'Who was in the reading room tonight?', a: 'One man at midnight with a razor. He cut a page from a 1946 Herald and left. The page was about the cannery fire.' },
        { id: 'razor', q: 'Which way did he go?', a: 'Toward the Trust. He had ink on his fingers. Not printer’s ink. Fountain pen.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'lillian', q: 'Did Miss Voss read here?', a: 'Every Thursday afternoon for six months. Back numbers, ledgers, the shipping registers. She was building something. I do not think she finished.' },
      ] },
    { id: 'roe', at: 'morgue', name: 'Nettie Roe', role: 'attendant, City Morgue',
      intro: 'Roe. I keep the register and I wash the dead. The dead are tidier.',
      bio: 'Twelve years in the morgue. The register in her hand is the only one in the city nobody has paid to change.',
      knows: ['pike', 'roland'],
      aboutLine: 'Came down to see her. People give themselves away over a slab.',
      leadLine: 'A visitor left something in the coat room and did not come back. It went on to',
      spentLine: 'Three to wash before morning. Find your own way out.',
      opinions: { pike: 'Dr. Pike came down at four to see her. He touched her hand and said her name. Then he asked to see the effects. I said no.', roland: 'Mr. Voss came at five. He did not go in. He stood in the corridor and asked me if she had suffered. I lied.' },
      topics: [
        { id: 'night', q: 'What did she have on her?', a: 'A ring, bent. A key, brass, one-fourteen. An orchid stem. No purse. No money. Somebody took the purse and left the key, which means they did not know what the key was.' },
        { id: 'ring', q: 'The ring was bent.', a: 'In the setting. She hit somebody with it. There is a hair caught in it that is not hers.', after: 'night' },
        { id: 'visitor', q: 'Who came to see her?', a: 'The doctor at four. The brother at five. And a woman at six who would not give a name and stood outside the door for ten minutes and then left. Gloves. Perfume.', cost: 1, effect: { type: 'lead' } },
      ] },
    { id: 'dunn', at: 'pharmacy', name: 'Cyril Dunn', role: 'dispensing chemist',
      intro: 'Dunn. I dispense. I do not ask what it is for. I do not forget who asked.',
      bio: 'Dispensing chemist under Pike for eight years. Signs nothing. Remembers everything.',
      knows: ['pike', 'mireaux', 'vera'],
      aboutLine: 'Customer. I have handed them their little bottles across this counter.',
      leadLine: 'Somebody bought bandages and iodine at midnight with a shaking hand. They went toward',
      spentLine: 'Shop is shut. Register is shut with it.',
      opinions: { pike: 'Dr. Pike signs the register himself now. He did not use to. He started in September.', mireaux: 'Madame Mireaux buys nothing here. She sends a boy for it. The boy signs with a cross.', vera: 'Miss Lang buys something for her throat every week and something for her nerves every month.' },
      topics: [
        { id: 'night', q: 'Who came in tonight?', a: 'Bandages and iodine at midnight. A man with a shaking hand and a cut on the other one. He paid in silver. He did not want a receipt.' },
        { id: 'register', q: 'Show me the poisons register.', a: 'Ether, four ounces, Thursday, signed A. Pike. He has signed for eleven pints this year. There is not that much surgery on the Heights.', cost: 1, effect: { type: 'suspectTrait', suspectId: 'pike' } },
        { id: 'lillian', q: 'Did Miss Voss come here?', a: 'Once. Wednesday. She asked to see the register. I showed her. She copied a page in a little book and thanked me. I have been waiting for somebody to come and ask me that since.' },
      ] },
    { id: 'fane', at: 'jade', name: 'Lulu Fane', role: 'barmaid, the Jade Room',
      intro: 'Lulu. I have worked this bar since Lillian sang here. I remember who came to hear her and who came to watch.',
      bio: 'Sang here herself, before her voice went. Pours now. Still knows every song on the list.',
      knows: ['vera', 'brandt', 'strand'],
      aboutLine: 'Drinks here. Sits where they can see the door.',
      leadLine: 'The telephone by the bar rang at two. Whoever answered left their drink and walked out toward',
      spentLine: 'Last orders was two. That goes for questions.',
      opinions: { vera: 'Vera drank here at half one in her stage dress with her coat over it. She had been crying. She said it was the rain.', brandt: 'Brandt sat by the door from midnight and watched the telephone. When it rang at two he did not answer it. Somebody else did.', strand: 'Emil Strand left his lighter on my bar at two. He did not notice. He was looking at the door.' },
      topics: [
        { id: 'night', q: 'The telephone rang at two.', a: 'It did. A man answered. Big. Hat. He listened, he did not speak, he put it down and he went out. He left a full glass. Nobody leaves a full glass.' },
        { id: 'man', q: 'Who was the man?', a: 'Not a regular. He came in at one and sat where he could see the telephone. He was waiting for it. He knew it would ring.', after: 'night', cost: 1, effect: { type: 'culpritTrait' } },
        { id: 'lillian', q: 'Lillian sang here.', a: 'Three years. She was better than the room. She came back in October and sat at the end of the bar and told me she was going to burn the whole Heights down. I thought she meant a song.' },
      ] },
    { id: 'vasko', at: 'garage', name: 'Pete Vasko', role: 'mechanic, Rainer Garage',
      intro: 'Vasko. Four wheels on the Bluff, I have had my hands in it. Tonight one came in with a wing stove in.',
      bio: 'Fixes the Bluff’s cars and never asks what they hit. Was a tank mechanic. Misses it.',
      knows: ['brandt', 'roland'],
      aboutLine: 'Brings the car here. You learn a person by what they do to a car.',
      leadLine: 'Something in the glove box was not the owner’s. I put it back. The car went on to',
      spentLine: 'Shop is shut. I have a Packard to finish.',
      opinions: { roland: 'Young Voss brings the Packard in with a new dent every month. Tonight it was the wing. He said the gate. It was not the gate.', brandt: 'Brandt does not drive. He gets driven. Tonight somebody drove him up the Bluff in a car that was not his.' },
      topics: [
        { id: 'night', q: 'The Packard. Tell me about the wing.', a: 'Stove in on the near side, at about hip height. Paint in it. Not gate paint. Black paint. Something with black paint on it got hit hard.' },
        { id: 'glove', q: 'What was in the glove box?', a: 'A woman’s glove. One. Grey kid. Not Miss Voss’s size, I would guess. Smaller.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'driver', q: 'Who drove it in?', a: 'Not Mr. Voss. A man in a chauffeur’s coat who did not know where the lights were. Nobody who drives that car every day does not know where the lights are.' },
      ] },
    { id: 'latimer', at: 'warehouse', name: 'Hugh Latimer', role: 'bond clerk, Warehouse 4',
      intro: 'Latimer. Every crate in here has a seal. Every seal has my initials. Tonight one has somebody else’s.',
      bio: 'A careful man in a careless job. Has been asking questions about twelve crates for six weeks.',
      knows: ['mireaux', 'brandt', 'strand'],
      aboutLine: 'Signs my book. You notice the hand that signs.',
      leadLine: 'A crate went out at one without paper. The cart went toward',
      spentLine: 'I am a clerk. Clerks do not know things. Close the door.',
      opinions: { mireaux: 'Madame Mireaux signs for twelve crates a month herself. I have asked why. I have stopped asking.', brandt: 'Brandt took a crate out of bay four at one without paper. I logged it. He watched me log it.', strand: 'Mr. Strand takes delivery of two crates a month at the hotel. Orchids, the paper says.' },
      topics: [
        { id: 'night', q: 'Seal four-four-seven-one was broken tonight.', a: 'At one. By Brandt, on Madame Mireaux’s word. The crate went on a cart. The cart went to the docks. Then a boat. Then I stopped watching.' },
        { id: 'twelve', q: 'What is in the twelve crates?', a: 'Not orchids. Orchids do not weigh what those weigh. I opened one in September. I closed it again. I have a family.', cost: 1, effect: { type: 'suspectTrait', suspectId: 'mireaux' } },
        { id: 'lillian', q: 'Miss Voss came to the warehouse.', a: 'Wednesday. She read the manifest standing up and asked me whether I had ever opened one. I said no. She looked at me like she knew I was lying. I was.' },
      ] },
    { id: 'denk', at: 'ferry', name: 'Milo Denk', role: 'steward, the ferry',
      intro: 'Denk. Last crossing at one-forty. I do not do names. I never forget a face after midnight.',
      bio: 'Twenty years on the crossing. Counts heads going over and heads coming back, and the numbers do not always match.',
      knows: ['mireaux', 'tovar'],
      aboutLine: 'Crosses with me. You get to know a person on a cold deck.',
      leadLine: 'Somebody came over on the last boat with a bundle and left without it. The bundle went up to',
      spentLine: 'Boat is tied up. So am I.',
      opinions: { mireaux: 'Madame Mireaux crosses on the last boat every Thursday with a case and comes back Friday without it.', tovar: 'The Deacon crosses on Sundays to Marrow House. She sits at the stern and does not look at the water.' },
      topics: [
        { id: 'night', q: 'Who crossed on the last boat?', a: 'Nine. A woman with a bundle. A man in a wet coat. The bundle came over and did not go back. The man came over and did not go back either.' },
        { id: 'bundle', q: 'The woman with the bundle.', a: 'Gloves. Perfume you could smell over the diesel. She carried it up toward the manor like it was a baby. It was not a baby.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'lillian', q: 'Did Miss Voss cross?', a: 'Wednesday. To the Bluff. She stood at the rail the whole way and asked me what the boats without lights were. I said fishing. She said they were not.' },
      ] },
    { id: 'sorrel', at: 'baylight', name: 'Ned Sorrel', role: 'keeper, Bay Light',
      intro: 'Sorrel. I keep the lamp and I keep the log. Every light on the water goes in it. Most of the Bluff too.',
      bio: 'Thirty years in the light. Talks to the lamp. Writes down every light he sees because nobody else will.',
      knows: ['mireaux', 'brandt'],
      aboutLine: 'Passes under my lamp. You learn a person by what they carry.',
      leadLine: 'A lantern went along the cliff path at half two. It stopped, and came back without something. It stopped at',
      spentLine: 'The lamp needs trimming. You need to go.',
      opinions: { mireaux: 'The Frenchwoman’s boats land under the Bluff without lights. I log them. Nobody reads my log.', brandt: 'Brandt came up the cliff path at half two with a lantern and went back without it.' },
      topics: [
        { id: 'night', q: 'What did the lamp see tonight?', a: 'A boat without lights at two. A lantern on the cliff path at half two, stopping at the old stair. And the manor: every window lit at three, and every window dark by four.' },
        { id: 'stair', q: 'What is at the old stair?', a: 'A cave. Dry. The smugglers used it before the light was built. Somebody uses it now.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'lillian', q: 'Did you know Miss Voss?', a: 'She came up the tower on Wednesday and asked to see the log. She read three months of it and said thank you and went down the stairs like she was counting them.' },
      ] },
  ],

  items: [
    { id: 'item:orchid:column', at: 'herald', kind: 'clipping', label: 'Herald society column, Nov. 3',
      source: 'THE ASHGRAVE HERALD · SOCIETY', title: '“Around the Town”, by Perpetua Shaw',
      body: ['“…and a certain songbird of the Heights, lately of the Jade Room, was seen leaving the Lyceum before the curtain with a face like thunder and a brother two steps behind. One wonders what the Voss table talks about, when it talks.”', 'Cut from the page with scissors, not a razor.'],
      spoken: 'A society column, cut from the page, with the songbird of the Heights in it.',
      reading: 'Shaw was writing about Lillian the day she died. Colour, and a temper. Nothing for the notebook.', about: ['shaw', 'roland'], effect: { type: 'none' } },
    { id: 'item:orchid:lobby-photo', at: 'herald', kind: 'photo', label: 'Press photograph, the Gilded lobby', stamp: 'COPY',
      source: 'THE ASHGRAVE HERALD · PICTURE DESK', title: 'Lobby, the Gilded, 2:40 AM',
      body: ['Taken before the first uniform arrived. Perpetua Shaw in the foreground, notebook out, hat off. Something about her in the flash that you would not have noticed by lamplight.', 'On the back in grease pencil: HOLD FOR MORNING.'],
      spoken: 'A press photograph of the lobby, taken before the first uniform arrived.',
      reading: 'A good photograph gives a person away.', about: ['shaw'], effect: { type: 'suspectTrait', suspectId: 'shaw' } },
    { id: 'item:orchid:stub', at: 'lyceum', kind: 'ticket', label: 'Lyceum stub, box C',
      source: 'THE LYCEUM · BOX OFFICE', title: 'Box C, Nov. 3, evening performance',
      fields: [['Box', 'C, the Voss box'], ['Torn', 'no — never presented'], ['Found', 'under the seat']],
      body: ['The Voss box, and the stub never torn. Somebody had a seat for the evening and did not sit in it.'],
      spoken: 'A ticket for the Voss box, never torn.',
      reading: 'Somebody in that family was not where the family was. Story, not evidence.', about: ['roland'], effect: { type: 'none' } },
    { id: 'item:orchid:check', at: 'belvedere', kind: 'receipt', label: 'Café Belvedere check',
      source: 'CAFÉ BELVEDERE · OPEN ALL NIGHT', title: 'Check no. 2207',
      fields: [['Coffee, black', '2'], ['Time', '1:15 AM'], ['Signed', '“E.S.”']],
      body: ['Two coffees, one drunk. Signed to the house account in a hand the waiter knows.', 'The second cup was still warm when the chair emptied.'],
      spoken: 'A café check for two coffees at a quarter past one, signed E.S.',
      reading: 'Whoever left the second cup left in a hurry, and the waiter saw which way.', about: ['strand'], effect: { type: 'lead' } },
    { id: 'item:orchid:petal', at: 'gardens', kind: 'note', label: 'A pressed orchid petal', stamp: 'PERSONAL',
      source: 'FOUND IN A HYMNAL, BANDSTAND STEPS', title: 'Pressed between the pages',
      body: ['A hymnal, parish issue, St. Ordell’s stamped inside the cover. Between the psalms, a single orchid petal pressed flat and brown at the edges.', 'Somebody sat here with the church’s book and the dead woman’s flower.'],
      spoken: 'A parish hymnal on the bandstand steps, with an orchid petal pressed inside.',
      reading: 'Colour. It puts the parish and the orchid in one place, and nothing in the notebook.', about: ['tovar'], effect: { type: 'none' } },
    { id: 'item:orchid:box-log', at: 'trust', kind: 'ledger', label: 'Safe-deposit access log', stamp: 'CONFIDENTIAL',
      source: 'ASHGRAVE TRUST · VAULT', title: 'Access log, box 114',
      body: ['11:50 PM — R. VOSS — box 114 — signed out 11:58. The signature is hurried and the pen dug through the page.', 'Miss Vine remembers the hand that signed, and what it looked like doing it.'],
      spoken: 'The vault log: box one-fourteen, opened by R. Voss at ten to midnight.',
      reading: 'The teller watched him sign. That is worth something about him.', about: ['roland'], effect: { type: 'suspectTrait', suspectId: 'roland' } },
    { id: 'item:orchid:deacon-letter', at: 'cathedral', kind: 'letter', label: 'Letter to the Deacon', stamp: 'PERSONAL',
      source: 'FOUND IN THE VESTRY', title: 'To Deacon Tovar, unsent reply attached',
      body: ['“Iris — I have seen the books. The soup line does not cost what the plate collects and you know it. I will not say anything before Sunday. After Sunday I make no promises. — L.”', 'Pinned to it, half a reply in the Deacon’s hand, crossed out twice.'],
      spoken: 'A letter from Lillian to the Deacon about the parish books, and half a reply.',
      reading: 'A motive in ink. It does not describe anybody’s hands or hair.', about: ['tovar'], effect: { type: 'none' } },
    { id: 'item:orchid:admission', at: 'mercy', kind: 'report', label: 'Admission slip, ward four',
      source: 'MERCY HOSPITAL · ADMISSIONS', title: 'Ward four, night of Nov. 3',
      fields: [['Patient', 'male, 30s, laceration to left hand'], ['Admitted', '3:05 AM'], ['Discharged', 'against advice, 3:40 AM'], ['Physician', 'Dr. A. Pike']],
      body: ['Pike stitched a man’s hand at three in the morning and let him walk out with the thread still wet. Neither of them gave a name.'],
      spoken: 'An admission slip: a man with a cut hand, stitched by Doctor Pike at three, and gone by four.',
      reading: 'Somebody bled tonight and Pike helped him not talk about it. Story.', about: ['pike'], effect: { type: 'none' } },
    { id: 'item:orchid:cab-chit', at: 'market', kind: 'receipt', label: 'Cab chit, Lantern Cab Co.',
      source: 'LANTERN CAB CO. · ALL NIGHT', title: 'Fare chit no. 88',
      fields: [['From', 'Lantern Market'], ['To', 'the Bluff'], ['Time', '2:20 AM'], ['Driver', 'Kaspar']],
      body: ['The driver is still on the rank outside, and he knows a way up the Bluff that is not on any map.'],
      spoken: 'A cab chit, market to the Bluff at twenty past two, and the driver still on the rank.',
      reading: 'A driver who knows the shortcuts saves you time.', effect: { type: 'time', hours: -2 } },
    { id: 'item:orchid:fire-clipping', at: 'library', kind: 'clipping', label: 'Herald, 1946: the cannery fire',
      source: 'THE ASHGRAVE HERALD · BACK NUMBER', title: '“Cannery fire ruled accident”',
      body: ['Two dead, no charges, and a paragraph near the bottom noting that the building was insured through an importer on the Lantern side and the night watch was a union man.', 'Somebody has underlined both names in pencil.'],
      spoken: 'A back number of the Herald, the cannery fire, with two names underlined.',
      reading: 'Old business between an importer and the union. It explains a friendship, not a murder.', about: ['mireaux', 'brandt'], effect: { type: 'none' } },
    { id: 'item:orchid:operator-log', at: 'exchange', kind: 'note', label: 'Operator’s log, board nine',
      source: 'CENTRAL EXCHANGE · BOARD 9', title: 'Calls placed from the Gilded, suite 1100',
      body: ['1:52 AM — outgoing — LANTERN 4-4 — duration one minute ten. The last call the suite ever made.', 'Quill wrote the number down when she should not have.'],
      spoken: 'The operator’s log: the last call from suite eleven-hundred, at eight minutes to two.',
      reading: 'A number is an address. Somebody was rung a quarter of an hour before she died.', effect: { type: 'lead' } },
    { id: 'item:orchid:effects', at: 'morgue', kind: 'report', label: 'Inventory of personal effects',
      source: 'CITY MORGUE · REGISTER', title: 'Effects of the deceased, Voss, L.',
      fields: [['Ring', 'one, gold, setting bent'], ['Key', 'one, brass, stamped 114'], ['Orchid', 'one stem, snapped'], ['Purse', 'no money']],
      body: ['A brass key stamped one-fourteen in the pocket of a woman with no purse to spend. The morgue does not guess what it opens. You are allowed to.'],
      spoken: 'The inventory of her effects: a bent ring, a brass key stamped one-fourteen, and no money.',
      reading: 'One-fourteen is a box at the Trust. She had the key; somebody else opened the box.', about: ['roland'], effect: { type: 'none' } },
    { id: 'item:orchid:transfer', at: 'tram', kind: 'ticket', label: 'Tram transfer, the Bluff line',
      source: 'ASHGRAVE TRAMWAYS', title: 'Transfer, punched 1:20 AM',
      body: ['A transfer punched at twenty past one on the last car up the Bluff, dropped between the seats. Nobody transfers at that hour unless they are going somewhere they do not want a cab to remember.'],
      spoken: 'A tram transfer, punched at twenty past one on the last car to the Bluff.',
      reading: 'Somebody rode to the Bluff late and quiet. Story.', effect: { type: 'none' } },
    { id: 'item:orchid:floor-photo', at: 'jade', kind: 'photo', label: 'Photograph, the Jade Room floor',
      source: 'THE JADE ROOM · HOUSE PHOTOGRAPHER', title: 'The eleven o’clock spot, Nov. 3',
      body: ['Vera Lang on the little stage at eleven, in the flash. The house photographer sells these at the door for a dollar. This one was not bought; it was taken.', 'You can see a great deal of a person in a flash photograph.'],
      spoken: 'A house photograph of Vera Lang on the Jade Room stage at eleven.',
      reading: 'A flash photograph tells you something about her.', about: ['vera'], effect: { type: 'suspectTrait', suspectId: 'vera' } },
    { id: 'item:orchid:manifest', at: 'imports', kind: 'ledger', label: 'Import manifest, forty crates', stamp: 'COPY',
      source: 'MIREAUX IMPORTS · MANIFEST', title: 'Consignment, SS Marseillaise',
      body: ['Forty crates, orchids, Marseille to Ashgrave. Twenty-eight initialled at the dock by the bond clerk. Twelve initialled by somebody else, in the importer’s own hand, at the warehouse, at night.', 'She signed for them herself. The clerk remembers the hand.'],
      spoken: 'An import manifest: forty crates of orchids, and twelve of them signed for at night.',
      reading: 'She signed twelve crates herself. The clerk watched her do it.', about: ['mireaux'], effect: { type: 'suspectTrait', suspectId: 'mireaux' } },
    { id: 'item:orchid:poisons', at: 'pharmacy', kind: 'ledger', label: 'Poisons register, page 31', stamp: 'CONFIDENTIAL',
      source: 'PIKE’S PHARMACY · POISONS REGISTER', title: 'Entries, Nov. 3',
      body: ['10:05 PM — ether, four oz. — signed A. PIKE — purpose: “surgical”. The signature is his, the chemist says, and the hand that made it he has watched a thousand times.'],
      spoken: 'The poisons register: four ounces of ether, signed out by Doctor Pike at ten.',
      reading: 'Dunn watched him sign. That is worth something about the doctor.', about: ['pike'], effect: { type: 'suspectTrait', suspectId: 'pike' } },
    { id: 'item:orchid:locker-tag', at: 'baths', kind: 'ticket', label: 'Locker tag no. 9, unclaimed',
      source: 'LANTERN BATHS · LOCKERS', title: 'Tag no. 9',
      body: ['A coat, wet through, hung in locker nine at half past two and never claimed. In the pocket, a second locker tag from somewhere else in the city.'],
      spoken: 'An unclaimed locker tag, and a wet coat with another tag in the pocket.',
      reading: 'The second tag is from somewhere else. Somebody left a trail of lockers.', effect: { type: 'lead' } },
    { id: 'item:orchid:threat', at: 'cannery', kind: 'letter', label: 'An unsigned letter, union paper',
      source: 'FOUND NAILED TO THE CANNERY DOOR', title: 'On Dockers’ Union letterhead',
      body: ['“You were told. The next one is not a warning.” Typed, unsigned, on the union’s own paper, with the union’s own typewriter — the capital W drops.', 'Brandt does not type. Somebody at the hall does.'],
      spoken: 'An unsigned threat on union paper, nailed to the cannery door.',
      reading: 'Somebody at the union threatened somebody at the cannery. Story.', about: ['brandt'], effect: { type: 'none' } },
    { id: 'item:orchid:ferry-ticket', at: 'ferry', kind: 'ticket', label: 'Ferry ticket, last crossing',
      source: 'ASHGRAVE BAY FERRY', title: 'One crossing, 1:40 AM',
      body: ['A ticket for the last boat, punched, found on the deck by the rail where a person stands who does not want to be inside with the others.'],
      spoken: 'A ticket for the last ferry, found by the rail.',
      reading: 'Somebody crossed the bay late. The steward would know who.', effect: { type: 'none' } },
    { id: 'item:orchid:set-list', at: 'parrot', kind: 'note', label: 'Set list, Vera Lang', stamp: 'PERSONAL',
      source: 'THE BLUE PARROT · BACKSTAGE', title: 'Set list, Nov. 3',
      body: ['Eleven songs in Vera’s hand, and at the bottom, underlined so hard it tore: “L. owes me the top of the bill and she knows it.”'],
      spoken: 'Vera Lang’s set list, with a line at the bottom underlined hard enough to tear.',
      reading: 'A grudge, written down. Not a hand or a hair.', about: ['vera'], effect: { type: 'none' } },
    { id: 'item:orchid:mother', at: 'tenement', kind: 'letter', label: 'Letter from a mother', stamp: 'PERSONAL',
      source: 'FOUND ON A LANDING, TENEMENT ROW', title: 'To Nikolai, from your mother',
      body: ['“Kolya — the money came and I did not ask where from and I will not. Come for Sunday. Wear the good coat. Your sister says you have been fighting again and I told her you would never.”', 'It has been read many times and folded small.'],
      spoken: 'A letter from Brandt’s mother, folded small and read many times.',
      reading: 'Somebody loves him. It does not help the notebook.', about: ['brandt'], effect: { type: 'none' } },
    { id: 'item:orchid:repair', at: 'garage', kind: 'receipt', label: 'Repair chit, black Packard',
      source: 'RAINER GARAGE · WORK ORDER', title: 'Black Packard, Voss Manor',
      fields: [['Damage', 'near-side wing stove in'], ['Brought in', '2:50 AM'], ['Driver', '“family”'], ['Paid', 'cash, in advance']],
      body: ['The Voss car, brought in at ten to three with a wing folded like paper and cash paid before the work was done. The mechanic did not ask what it hit.'],
      spoken: 'A work order for the Voss Packard, brought in at ten to three with a wing stove in.',
      reading: 'The family car was out and hit something. Story, unless it was somebody.', about: ['roland'], effect: { type: 'none' } },
    { id: 'item:orchid:dues', at: 'union', kind: 'ledger', label: 'Dues ledger, November',
      source: 'DOCKERS’ UNION LOCAL 9 · DUES', title: 'Collections, week of Nov. 3',
      body: ['Every entry in Brandt’s hand, and every hand that paid him remembered by the man who keeps the book. He knows more about the collector than the collector knows about himself.'],
      spoken: 'The union dues ledger, every line in Brandt’s hand.',
      reading: 'The bookkeeper has watched Brandt write for years. He can tell you something.', about: ['brandt'], effect: { type: 'suspectTrait', suspectId: 'brandt' } },
    { id: 'item:orchid:marseille', at: 'docks', kind: 'telegram', label: 'Telegram from Marseille',
      source: 'WESTERN UNION · CABLE OFFICE', title: 'Cable, for C. Mireaux',
      body: ['SHIPMENT SPLIT AT LE HAVRE STOP TWELVE TRAVEL SEPARATE STOP DO NOT LET HER SEE THE MANIFEST STOP'],
      spoken: 'A cable from Marseille, for Cass Mireaux: do not let her see the manifest.',
      reading: 'Somebody did not want Lillian reading a manifest. A motive, and only that.', about: ['mireaux'], effect: { type: 'none' } },
    { id: 'item:orchid:seal', at: 'warehouse', kind: 'report', label: 'Customs seal report, bay 4',
      source: 'H.M. CUSTOMS · BONDED STORE', title: 'Seal broken, bay 4',
      fields: [['Seal', 'no. 4471, broken'], ['Found', '1:10 AM, by the bond clerk'], ['Missing', 'one crate, orchids']],
      body: ['A crate went out without paper, and the cart tracks in the wet lead out of the yard and up the road.'],
      spoken: 'A customs report: a seal broken and a crate gone, with cart tracks leading out of the yard.',
      reading: 'The tracks go somewhere. Follow them.', effect: { type: 'lead' } },
    { id: 'item:orchid:prayer-card', at: 'chapel', kind: 'note', label: 'A prayer card, “for Lillian”',
      source: 'SAILORS’ CHAPEL · CARDS FOR THE DROWNED', title: 'For Lillian',
      body: ['A card from the rack, filled in before dawn in a man’s hand: FOR LILLIAN, WHO KNEW. No surname. The ink was still wet when the sexton found it.'],
      spoken: 'A prayer card in the Sailors’ Chapel, for Lillian, who knew.',
      reading: 'Somebody prayed for her before the Herald had printed her name. Story.', about: ['strand', 'roland'], effect: { type: 'none' } },
    { id: 'item:orchid:unfinished', at: 'manor', kind: 'letter', label: 'Lillian’s unfinished letter', stamp: 'PERSONAL',
      source: 'VOSS MANOR · HER WRITING DESK', title: 'To Roland, unfinished',
      body: ['“Rollo — I have changed the will and I have told Father’s lawyer why. When you read this you will already know. I am sorry it had to be me who—”', 'The pen stops. The rest of the page is clean.'],
      spoken: 'An unfinished letter from Lillian to her brother about the will.',
      reading: 'The estate was about to pass elsewhere. A motive, and a heartbreaking one. Not evidence.', about: ['roland'], effect: { type: 'none' } },
    { id: 'item:orchid:keeper-log', at: 'baylight', kind: 'note', label: 'Keeper’s log, the cliff path',
      source: 'BAY LIGHT · KEEPER’S LOG', title: 'Lights on the Bluff, night of Nov. 3',
      body: ['2:30 — lantern on the cliff path, stops at the old stair, returns. 2:55 — lantern again, further out. 3:10 — nothing. The keeper thinks it was the fishermen. You will have to go and look to be sure it was not, and it costs you an hour to find out it was.'],
      spoken: 'The keeper’s log: a lantern on the cliff path at half past two, and again at five to three.',
      reading: 'It was the fishermen. An hour gone.', effect: { type: 'time', hours: 1 } },
  ],

  objects: [
    { id: 'obj:orchid:key', at: 'morgue', name: 'A brass key stamped 114', drawing: 'key',
      desc: 'From her pocket. She had no purse and no money. She had this.',
      spoken: 'A brass key from her pocket, stamped one-fourteen.',
      unlocks: [
        { person: 'vine', line: 'Box one-fourteen. Whose is it?', reply: 'Hers. She opened it Tuesday and put something in. Her brother opened it last night and took something out. I watched his hands the whole time.',
          effect: { type: 'suspectTrait', suspectId: 'roland' } },
        { person: 'roland', line: 'Your sister’s key. What was in the box, Roland?', reply: 'You have no right to that. She—. She changed the will. I took it. I have not read it. I could not.',
          effect: { type: 'culpritTrait' } },
      ] },
    { id: 'obj:orchid:lighter', at: 'jade', name: 'A gold lighter, E.S.', drawing: 'lighter',
      desc: 'Left on the Jade Room bar. Initials on the base.',
      spoken: 'A gold lighter on the Jade Room bar, initials E.S.',
      unlocks: [
        { person: 'strand', line: 'Yours. It was on the Jade Room bar at two. You said you were at the desk.', reply: 'I was not at the desk. I was at the Belvedere. With someone. If it comes out, she is finished. So am I.',
          effect: { type: 'clear', suspectId: 'strand' } },
        { person: 'fane', line: 'Who left this?', reply: 'Emil Strand. Two o’clock, near enough. He had his hands round a glass like it might get away.',
          effect: { type: 'suspectTrait', suspectId: 'strand' } },
      ] },
    { id: 'obj:orchid:matchbook', at: 'parrot', name: 'A matchbook from Rosie’s', drawing: 'matchbook',
      desc: 'Half the matches gone. Rosie’s is a card room. Nobody admits to Rosie’s.',
      spoken: 'A matchbook from Rosie’s, half the matches gone.',
      unlocks: [
        { person: 'marlowe', line: 'Rosie’s. Who plays there?', reply: 'Brandt. Every Thursday, and he loses. He was there Thursday. He lost big.',
          effect: { type: 'suspectTrait', suspectId: 'brandt' } },
        { person: 'brandt', line: 'Rosie’s. Thursday night. You were at the hall, you said.', reply: 'I was at Rosie’s. Then I was at the docks moving a crate for the Frenchwoman. Ask the watchman. Ask what was in it. I never did.',
          effect: { type: 'lead' } },
      ] },
    { id: 'obj:orchid:scarf', at: 'baths', name: 'A silk scarf, orchid scent', drawing: 'scarf',
      desc: 'From the locker with the wet coat. Orchid perfume, heavy.',
      spoken: 'A silk scarf from the wet coat, heavy with orchid.',
      unlocks: [
        { person: 'mireaux', line: 'This is your scent.', reply: 'It is Lillian’s scarf. I gave it to her. She gave it back the night she found the manifest. She said she did not want anything of mine near her.',
          effect: { type: 'suspectTrait', suspectId: 'mireaux' } },
        { person: 'vera', line: 'Recognise this?', reply: 'Lillian’s. She wore it the night she had me fired. Whoever had it last had it at the baths. Lillian never went to the baths.',
          effect: { type: 'lead' } },
      ] },
    { id: 'obj:orchid:cufflink', at: 'gilded', name: 'A cufflink, engraved R.V.', drawing: 'cufflink',
      desc: 'Under the dressing table in suite eleven-hundred. One of a pair.',
      spoken: 'A cufflink under the dressing table, engraved R.V.',
      unlocks: [
        { person: 'roland', line: 'Yours. Found under her table.', reply: 'I was there at ten. We argued. I left at eleven. Dot Bell saw me leave the Lyceum after, alone. I did not go back. I swear to God I did not go back.',
          effect: { type: 'clear', suspectId: 'roland' } },
        { person: 'bell', line: 'Roland Voss. When did he leave?', reply: 'Eleven. Alone. He had one cufflink in. I notice cufflinks. He did not come back for the second act.',
          effect: { type: 'suspectTrait', suspectId: 'roland' } },
      ] },
    { id: 'obj:orchid:watch', at: 'manor', name: 'A pocket watch, stopped at 1:52', drawing: 'watch',
      desc: 'Lillian’s father’s. Dropped on the manor stairs. The glass is cracked.',
      spoken: 'A pocket watch on the manor stairs, stopped at eight minutes to two.',
      unlocks: [
        { person: 'quill', line: 'One fifty-two. That was the call from the suite.', reply: 'It was. One minute ten. She said one thing and hung up. She said: I know what you did, and I am telling them tomorrow.',
          effect: { type: 'culpritTrait' } },
        { person: 'pike', line: 'The watch stopped at one fifty-two. You were her doctor. What stops a watch?', reply: 'A fall. Or a hand that closes on it. Ether does not stop watches, Inspector. Ether stops people.',
          effect: { type: 'suspectTrait', suspectId: 'pike' } },
      ] },
  ],
  story: {
    backstory: [
      'Lillian Voss was twenty-six. Heiress to the Voss estate, singer at the Jade Room, then the Gilded. Rich enough to do what she liked. Bored enough to look into things.',
      'For six months she had been looking into everyone. Her brother’s debts. The parish plate. Strand’s book of rooms. Pike’s register. Mireaux’s crates. Shaw’s column. She kept notes. The notes are gone.',
      'On Tuesday she changed her will. On Thursday she told her brother. On Thursday night she was dead.',
      'The orchid on her table came from Mireaux Imports. Somebody snapped it and put it back. That is the only thing in the room anybody bothered to tidy.',
    ],
    timeline: [
      { time: '10:00 PM', text: 'Roland Voss at the Gilded. Raised voices in suite 1100. He leaves at eleven.' },
      { time: '11:50 PM', text: 'Box 114 at the Trust is opened. Roland signs. His hand shakes.' },
      { time: '1:15 AM', text: 'Two coffees at the Belvedere, one drunk. Signed E.S.' },
      { time: '1:30 AM', text: 'Someone comes in by the Gilded’s side door. The night clerk does not see a face.' },
      { time: '1:52 AM', text: 'Suite 1100 places a call. One minute ten seconds.' },
      { time: '2:00 AM', text: 'The telephone at the Jade Room bar rings. Someone leaves.' },
      { time: '2:09 AM', text: 'The house detective opens suite 1100. She is dead.' },
      { time: '2:40 AM', text: 'Perpetua Shaw is in the lobby with her notebook out. Before the police.' },
    ],
    truth: [
      'Everyone on the list had a reason. Only one of them had the key to the side door, and the nerve.',
      'Lillian called them at eight minutes to two and said she knew. She said she was telling the police in the morning. She thought the call would make them stop. It made them come.',
      'The blow was not planned. The orchid was. Whoever put it back in the vase wanted the room to look like nothing had happened. That is the tell of somebody who has tidied up after themselves before.',
      'The will was never read. Roland Voss has it in a drawer. He will read it eventually. It leaves him everything, on one condition: that he stop gambling. She wrote it to save him. He thought it was written to punish him. That is the whole of this family.',
    ],
  },

  epilogue: {
    win: `The cuffs go on in the lobby of the Gilded, under the chandelier. The morning
      edition is already on the street. Somebody sets the orchid back in the vase on the way out.
      Ashgrave forgets by Thursday. You do not.`,
    loss: `The Herald moves it to page nine. Then nineteen. Then nowhere. The suite is let
      again by Christmas. Lillian Voss becomes a name people almost remember. The rain
      keeps doing what rain does.`,
  },
};

export default def;
