import type { CaseDef } from '../../types/game-types';

// The Ash and the Orchid. Thirty locations in five quarters of Ashgrave Bay,
// twenty people who will talk, and twenty-six documents scattered through the
// city -- some of which matter.

const def: CaseDef = {
  id: 'orchid',
  title: 'The Ash and the Orchid',
  subtitle: 'Ashgrave Bay · November 1947',
  tagline: 'A singer dies in the best suite in the city, and nobody heard a thing.',
  victim: 'Lillian Voss',
  scene: 'gilded',
  difficultyHint: 'A good first case.',
  publicTraits: ['build', 'hair'],
  traitPool: ['hand', 'mark', 'vice', 'scent', 'shoe'],

  briefing: `Nine minutes past two, the house detective at the Gilded Hotel opens suite
    eleven-hundred and finds Lillian Voss face down in six hundred dollars of Chinese silk.
    No gunshot. No scream. The orchid on her dressing table has been snapped clean off at the
    stem, and somebody took the time to set it back in the vase.
    Eleven floors, forty-one guests, one night clerk, and not one of them heard a thing.
    You have until this story goes cold, detectives. In this city that is not very long.`,

  radio: [
    'Dispatch to all cars. The Gilded Hotel. Coroner is already inside.',
    'The Voss family has lawyers awake at four in the morning. Consider that a warning.',
    'Herald has a man in the lobby. He was there before we were. Ask yourself how.',
  ],

  terrain: {
    sea: true, seaName: 'ASHGRAVE BAY', river: true, riverSource: 0.5, riverMouth: 0.56,
    parks: 3,
    districts: [
      { text: 'THE HEIGHTS', x: 260, y: 30, rot: -3 },
      { text: 'OLD TOWN', x: 640, y: 240, rot: 2 },
      { text: 'LANTERN QUARTER', x: 990, y: 40, rot: 3 },
      { text: 'THE FLATS', x: 200, y: 420, rot: -2 },
      { text: 'THE BLUFF', x: 1010, y: 560, rot: 2 },
    ],
  },

  locations: [
    // ---- The Heights
    { id: 'gilded', name: 'The Gilded Hotel', type: 'hotel', x: 150, y: 120, district: 'The Heights', desc: 'Brass, marble, and eleven floors of people paying not to be noticed.' },
    { id: 'herald', name: 'The Ashgrave Herald', type: 'press', x: 340, y: 90, district: 'The Heights', desc: 'Presses running all night. Ink, sweat, and everybody’s business.' },
    { id: 'lyceum', name: 'The Lyceum', type: 'theatre', x: 260, y: 230, district: 'The Heights', desc: 'Velvet and gilt, and a box the Voss family has kept since 1910.' },
    { id: 'belvedere', name: 'Café Belvedere', type: 'cafe', x: 110, y: 290, district: 'The Heights', desc: 'Open all night for people who cannot go home yet.' },
    { id: 'gardens', name: 'Ordell Gardens', type: 'park', x: 430, y: 190, district: 'The Heights', desc: 'Wet gravel, black iron, and a bandstand nobody has played in since the war.' },
    { id: 'trust', name: 'Ashgrave Trust', type: 'bank', x: 480, y: 310, district: 'The Heights', desc: 'Granite outside, brass inside, and a vault that opens for the right surname.' },
    // ---- Old Town
    { id: 'precinct', name: 'Ashgrave Precinct', type: 'police', x: 620, y: 340, district: 'Old Town', desc: 'Home. Bad coffee, worse paperwork, one working telephone.' },
    { id: 'cathedral', name: 'St. Ordell’s', type: 'church', x: 570, y: 150, district: 'Old Town', desc: 'Cold stone and colder charity.' },
    { id: 'mercy', name: 'Mercy Hospital', type: 'hospital', x: 740, y: 110, district: 'Old Town', desc: 'Ether and disinfectant. They keep bad records here, and keep them well.' },
    { id: 'market', name: 'Lantern Market', type: 'market', x: 720, y: 300, district: 'Old Town', desc: 'Open till dawn. Everything for sale, receipts optional.' },
    { id: 'library', name: 'Carnegie Library', type: 'library', x: 480, y: 440, district: 'Old Town', desc: 'Every back number of the Herald, and one reader who never seems to leave.' },
    { id: 'exchange', name: 'Central Exchange', type: 'office', x: 650, y: 480, district: 'Old Town', desc: 'Forty switchboards and every call in the city passing through somebody’s ears.' },
    { id: 'morgue', name: 'City Morgue', type: 'morgue', x: 820, y: 430, district: 'Old Town', desc: 'Tile, ice, and the last honest register in Ashgrave.' },
    { id: 'tram', name: 'Tram Terminus', type: 'tram', x: 560, y: 570, district: 'Old Town', desc: 'The last car up the Heights leaves at one. Somebody was on it.' },
    // ---- Lantern Quarter
    { id: 'jade', name: 'The Jade Room', type: 'club', x: 900, y: 200, district: 'Lantern Quarter', desc: 'Where Lillian sang before the Gilded found her. They kept her photograph up.' },
    { id: 'imports', name: 'Mireaux Imports', type: 'florist', x: 1010, y: 120, district: 'Lantern Quarter', desc: 'Orchids in the window. Crates in the back that were never orchids.' },
    { id: 'pharmacy', name: 'Pike’s Pharmacy', type: 'shop', x: 870, y: 320, district: 'Lantern Quarter', desc: 'Brass scales, glass jars, and a poisons register that is mostly initials.' },
    { id: 'baths', name: 'Lantern Baths', type: 'bathhouse', x: 1050, y: 300, district: 'Lantern Quarter', desc: 'Steam, tile, and lockers that are rented by the hour and by the year.' },
    { id: 'cannery', name: 'The Old Cannery', type: 'factory', x: 980, y: 450, district: 'Lantern Quarter', desc: 'Shut since ’41 and still somehow lit at night.' },
    { id: 'ferry', name: 'Ferry Landing', type: 'pier', x: 1130, y: 480, district: 'Lantern Quarter', desc: 'Last crossing at one-forty. The steward remembers faces, not names.' },
    // ---- The Flats
    { id: 'parrot', name: 'The Blue Parrot', type: 'bar', x: 150, y: 480, district: 'The Flats', desc: 'A jazz club with a back room and a worse reputation.' },
    { id: 'tenement', name: 'Tenement Row', type: 'home', x: 90, y: 610, district: 'The Flats', desc: 'Nine families to a landing. Everyone sees, nobody says.' },
    { id: 'pawn', name: 'Cobb’s Pawnshop', type: 'shop', x: 300, y: 530, district: 'The Flats', desc: 'Where the city leaves the things it cannot look at anymore.' },
    { id: 'garage', name: 'Rainer Garage', type: 'garage', x: 250, y: 670, district: 'The Flats', desc: 'Two pits, one hoist, and every dented wing on the Bluff.' },
    { id: 'union', name: 'Dockers’ Union Hall', type: 'office', x: 420, y: 650, district: 'The Flats', desc: 'Folding chairs, a dues ledger, and Brandt’s name on the door in fresh paint.' },
    { id: 'docks', name: 'Rainer Docks', type: 'docks', x: 600, y: 710, district: 'The Flats', desc: 'Oil on black water. The cranes never stop.' },
    { id: 'warehouse', name: 'Bonded Warehouse 4', type: 'warehouse', x: 770, y: 650, district: 'The Flats', desc: 'Customs seals on every door, and one of them broken tonight.' },
    // ---- The Bluff
    { id: 'chapel', name: 'Sailors’ Chapel', type: 'church', x: 900, y: 610, district: 'The Bluff', desc: 'One room, a brass bell, and prayer cards for the drowned.' },
    { id: 'manor', name: 'Voss Manor', type: 'manor', x: 1080, y: 670, district: 'The Bluff', desc: 'Fourteen rooms on the bluff, and one daughter fewer.' },
    { id: 'baylight', name: 'Bay Light', type: 'light', x: 1120, y: 760, district: 'The Bluff', desc: 'One keeper, one lamp, and a log of every light on the water.' },
  ],
  edges: [
    ['gilded', 'herald'], ['gilded', 'belvedere'], ['gilded', 'lyceum'],
    ['herald', 'gardens'], ['herald', 'cathedral'],
    ['lyceum', 'gardens'], ['lyceum', 'belvedere'], ['lyceum', 'trust'],
    ['belvedere', 'parrot'],
    ['gardens', 'trust'], ['gardens', 'cathedral'],
    ['trust', 'precinct'], ['trust', 'library'],
    ['cathedral', 'mercy'], ['cathedral', 'precinct'],
    ['mercy', 'market'], ['mercy', 'jade'],
    ['precinct', 'market'], ['precinct', 'library'], ['precinct', 'exchange'],
    ['market', 'pharmacy'], ['market', 'morgue'], ['market', 'exchange'],
    ['library', 'tram'], ['library', 'pawn'],
    ['exchange', 'tram'], ['exchange', 'morgue'],
    ['morgue', 'cannery'], ['morgue', 'warehouse'],
    ['tram', 'union'], ['tram', 'docks'],
    ['jade', 'imports'], ['jade', 'pharmacy'],
    ['imports', 'baths'],
    ['pharmacy', 'baths'], ['pharmacy', 'cannery'],
    ['baths', 'ferry'],
    ['cannery', 'ferry'], ['cannery', 'chapel'],
    ['ferry', 'manor'],
    ['parrot', 'tenement'], ['parrot', 'pawn'],
    ['tenement', 'garage'],
    ['pawn', 'garage'], ['pawn', 'union'],
    ['garage', 'union'],
    ['union', 'docks'],
    ['docks', 'warehouse'],
    ['warehouse', 'chapel'],
    ['chapel', 'manor'], ['chapel', 'baylight'],
    ['manor', 'baylight'],
  ],
  start: 'precinct',

  suspects: [
    { id: 'vera', name: 'Vera Lang', role: 'Torch singer, The Blue Parrot',
      blurb: 'Had the eleven o’clock spot and Lillian’s old billing.',
      motive: 'because the top of the bill only fits one name.' },
    { id: 'strand', name: 'Emil Strand', role: 'Night manager, The Gilded',
      blurb: 'The only man with a key to every door in that building.',
      motive: 'because she knew which rooms he rented by the hour, and to whom.' },
    { id: 'pike', name: 'Dr. Aurelio Pike', role: 'Society physician',
      blurb: 'Writes the prescriptions that keep this city upright.',
      motive: 'because she was going to name his pharmacy in open court.' },
    { id: 'mireaux', name: 'Cass Mireaux', role: 'Importer of rare flowers',
      blurb: 'Brings orchids in through the docks. And other things, under them.',
      motive: 'because the orchids were never the cargo, and she had worked that out.' },
    { id: 'tovar', name: 'Deacon Iris Tovar', role: 'St. Ordell’s',
      blurb: 'Runs the soup line and the collection plate. One of them balances.',
      motive: 'because the parish accounts only balanced while she stayed quiet.' },
    { id: 'roland', name: 'Roland Voss', role: 'The victim’s brother',
      blurb: 'Inherits everything and cried in the wrong order.',
      motive: 'because the estate passes whole to the surviving child.' },
    { id: 'brandt', name: 'Nikolai Brandt', role: 'Dock union enforcer',
      blurb: 'Settles arguments the cheap way. Alibi supplied by four men who owe him.',
      motive: 'because somebody paid, and he has never once asked why.' },
    { id: 'shaw', name: 'Perpetua Shaw', role: 'Columnist, The Herald',
      blurb: 'Was in the lobby before the police were. Has never explained that.',
      motive: 'because the column had run dry, and a dead heiress runs for a month.' },
  ],

  witnesses: [
    { id: 'pruett', at: 'gilded', name: 'Ada Pruett', role: 'night clerk, the Gilded',
      intro: 'Ada Pruett. Night desk, eleven years. I see everyone who comes in the front, and most of the ones who use the side door.',
      knows: ['strand', 'shaw', 'roland'],
      aboutLine: 'I know the face. I could tell you one thing about them, and I will.',
      leadLine: 'Somebody left in a hurry and did not stop for what they dropped. If I were you I would look at',
      spentLine: 'I have a desk to mind and I have said enough for one night.' },
    { id: 'marlowe', at: 'parrot', name: 'Bix Marlowe', role: 'barman, the Blue Parrot',
      intro: 'Bix. I pour, I listen, I forget. Tonight I will make an exception for one of those.',
      knows: ['vera', 'brandt', 'pike'],
      aboutLine: 'Sits at my bar. You notice things across a bar.',
      leadLine: 'A man came in white as a sheet and went straight out the back. Whatever he was carrying, he was not carrying it when he came back. Try',
      spentLine: 'Bar is closed, detective. So is my mouth.' },
    { id: 'flett', at: 'mercy', name: 'Oona Flett', role: 'night sister, Mercy Hospital',
      intro: 'Sister Flett. Nights, ward four. People say things at three in the morning that they would never say by day.',
      knows: ['pike', 'tovar', 'roland'],
      aboutLine: 'They have been through my ward. You do not forget a patient.',
      leadLine: 'One of the porters found something in a coat left on the wards and was too frightened to hand it in. It went to',
      spentLine: 'I have patients. Come back with a warrant or a fever.' },
    { id: 'rainer', at: 'docks', name: 'Sal Rainer', role: 'night watchman, Rainer Docks',
      intro: 'Rainer. No relation to the docks, whatever the sign says. I walk the wharf from ten till six and I count the boats.',
      knows: ['mireaux', 'brandt'],
      aboutLine: 'Comes down here more than a person should. I have watched them.',
      leadLine: 'Something went into the water off the end of the pier tonight and something else went into a pocket. The pocket walked toward',
      spentLine: 'Shift is over. Go and bother somebody with a warm office.' },
    { id: 'wyn', at: 'cathedral', name: 'Old Wyn', role: 'sexton, St. Ordell’s',
      intro: 'Wyn. I keep the doors and the graves. One of those is busier than the other.',
      knows: ['tovar', 'shaw'],
      aboutLine: 'I have watched that one at prayer. You learn things about a person on their knees.',
      leadLine: 'Somebody was in the vestry who should not have been, and left by the side gate toward',
      spentLine: 'The church is closed to the police and to everybody else. Good night.' },
    { id: 'cobb', at: 'pawn', name: 'Ezra Cobb', role: 'pawnbroker',
      intro: 'Cobb. I buy what people cannot look at any more. You would be surprised what that is.',
      knows: ['vera', 'mireaux', 'strand'],
      aboutLine: 'Regular. I keep a book on regulars, and not only for the money.',
      leadLine: 'A ticket was redeemed tonight in a hurry, cash, no name. The ticket came in from',
      spentLine: 'I have told you what I sell. I do not sell more than that.' },
    { id: 'bell', at: 'lyceum', name: 'Dot Bell', role: 'usherette, the Lyceum',
      intro: 'Dot. I show people to their seats and I know which ones leave before the last act. Tonight somebody left before the first.',
      knows: ['vera', 'shaw', 'roland'],
      aboutLine: 'Regular in the boxes. You see a lot from the aisle with a torch.',
      leadLine: 'A coat was left over a seat in box C and somebody came back for it in a hurry. They went out toward',
      spentLine: 'Curtain is down, detective. So am I.' },
    { id: 'pardo', at: 'belvedere', name: 'Louis Pardo', role: 'waiter, Café Belvedere',
      intro: 'Pardo. Nights. I pour coffee for people who cannot sleep and I remember what they order, because it never changes.',
      knows: ['pike', 'roland', 'strand'],
      aboutLine: 'Table by the window, always. I have poured for them a hundred times.',
      leadLine: 'Two coffees were ordered at a quarter past one and only one was drunk. The other chair was still warm when its owner went toward',
      spentLine: 'The kitchen is closed and so is my memory. Come back for breakfast.' },
    { id: 'amory', at: 'gardens', name: 'Kit Amory', role: 'night keeper, Ordell Gardens',
      intro: 'Amory. I lock the gates at ten and open them at six, and in between I see who climbs the railings.',
      knows: ['tovar', 'roland', 'vera'],
      aboutLine: 'Walks the paths at night. You learn a person by how they walk in the dark.',
      leadLine: 'Somebody sat on the bandstand steps for an hour and left something under them. When they went, they went toward',
      spentLine: 'The gates are locked. That includes to you.' },
    { id: 'vine', at: 'trust', name: 'Hedda Vine', role: 'teller, Ashgrave Trust',
      intro: 'Miss Vine. Second window. I see the money come in and go out, and the faces it belongs to.',
      knows: ['roland', 'tovar', 'mireaux'],
      aboutLine: 'Has an account with us. You notice a customer who counts twice.',
      leadLine: 'A deposit box was opened at ten to midnight by somebody who should have been elsewhere. What came out of it went to',
      spentLine: 'The bank is closed. It was closed when you arrived.' },
    { id: 'quill', at: 'exchange', name: 'Bea Quill', role: 'night operator, Central Exchange',
      intro: 'Quill. Board nine. I connect the calls and I am not supposed to listen. I am not supposed to do a lot of things.',
      knows: ['shaw', 'strand', 'pike'],
      aboutLine: 'I know the voice. You can tell a great deal from a voice at two in the morning.',
      leadLine: 'A call went out from suite eleven-hundred at eight minutes to two. The number it reached is at',
      spentLine: 'Board is lit. I have nine calls waiting and none of them are yours.' },
    { id: 'marsh', at: 'tram', name: 'Ollie Marsh', role: 'conductor, the Bluff line',
      intro: 'Marsh. Last car up the Bluff. I punch the tickets and I remember the ones who do not have one.',
      knows: ['brandt', 'tovar', 'vera'],
      aboutLine: 'Rides my car. You get to know a person by which seat they take.',
      leadLine: 'Somebody got off at the wrong stop and walked back the way we had come. They were headed for',
      spentLine: 'Depot is shut and I have been on my feet for fourteen hours.' },
    { id: 'grey', at: 'library', name: 'Tobias Grey', role: 'night librarian',
      intro: 'Grey. The reading room stays open for the insomniacs and I stay open with it. I know what everybody in this city reads.',
      knows: ['shaw', 'pike'],
      aboutLine: 'Reads here. You can tell a person by what they look up.',
      leadLine: 'A back number of the Herald was cut with a razor tonight and the reader left in a hurry toward',
      spentLine: 'This is a library. Lower your voice and leave.' },
    { id: 'roe', at: 'morgue', name: 'Nettie Roe', role: 'attendant, City Morgue',
      intro: 'Roe. I keep the register and I wash the dead. The dead are tidier.',
      knows: ['pike', 'roland'],
      aboutLine: 'Has been down here to see her. People give themselves away over a slab.',
      leadLine: 'A visitor left something in the coat room and did not come back for it. It has been sent on to',
      spentLine: 'I have three to wash before morning. You can find your own way out.' },
    { id: 'dunn', at: 'pharmacy', name: 'Cyril Dunn', role: 'dispensing chemist',
      intro: 'Dunn. I dispense. I do not ask what it is for, and I do not forget who asked.',
      knows: ['pike', 'mireaux', 'vera'],
      aboutLine: 'Customer. I have handed them their little bottles across this counter.',
      leadLine: 'Somebody bought bandages and iodine at midnight with a hand that shook. They went from here toward',
      spentLine: 'The shop is shut and the register is shut with it.' },
    { id: 'fane', at: 'jade', name: 'Lulu Fane', role: 'barmaid, the Jade Room',
      intro: 'Lulu. I have worked this bar since Lillian sang here, and I remember who came to hear her and who came to watch.',
      knows: ['vera', 'brandt', 'strand'],
      aboutLine: 'Drinks here. Sits where they can see the door.',
      leadLine: 'The telephone by the bar rang at two and whoever answered it left their drink and walked out toward',
      spentLine: 'Last orders was at two. That goes for questions.' },
    { id: 'vasko', at: 'garage', name: 'Pete Vasko', role: 'mechanic, Rainer Garage',
      intro: 'Vasko. If it has four wheels on the Bluff, I have had my hands in it. Tonight one came in with a wing stove in.',
      knows: ['brandt', 'roland'],
      aboutLine: 'Brings the car here. You learn a person by what they do to a car.',
      leadLine: 'There was something in the glove box that was not the owner’s and I put it back. The car went on to',
      spentLine: 'Shop is shut. I have a Packard to finish.' },
    { id: 'latimer', at: 'warehouse', name: 'Hugh Latimer', role: 'bond clerk, Warehouse 4',
      intro: 'Latimer. Every crate in here has a seal and every seal has my initials. Tonight one of them has somebody else’s.',
      knows: ['mireaux', 'brandt', 'strand'],
      aboutLine: 'Signs my book. You notice the hand that signs.',
      leadLine: 'A crate went out at one without paperwork. The cart that took it went toward',
      spentLine: 'I am a clerk. Clerks do not know things. Please close the door.' },
    { id: 'denk', at: 'ferry', name: 'Milo Denk', role: 'steward, the ferry',
      intro: 'Denk. Last crossing at one-forty. I do not know names but I never forget a face that comes across after midnight.',
      knows: ['mireaux', 'tovar'],
      aboutLine: 'Crosses with me. You get to know a person on a cold deck.',
      leadLine: 'Somebody came across on the last boat with a bundle and left without it. The bundle was carried up to',
      spentLine: 'The boat is tied up and so am I.' },
    { id: 'sorrel', at: 'baylight', name: 'Ned Sorrel', role: 'keeper, Bay Light',
      intro: 'Sorrel. I keep the lamp and I keep the log. Every light on the water and most of the ones on the Bluff go in it.',
      knows: ['mireaux', 'brandt'],
      aboutLine: 'Passes under my lamp. You learn a person by what they carry.',
      leadLine: 'A lantern went along the cliff path at half past two, stopped, and came back without something. It stopped at',
      spentLine: 'The lamp needs trimming and you need to go.' },
  ],

  items: [
    { id: 'item:orchid:column', at: 'herald', kind: 'clipping', label: 'Herald society column, Nov. 3',
      source: 'THE ASHGRAVE HERALD · SOCIETY', title: '“Around the Town”, by Perpetua Shaw',
      body: ['“…and a certain songbird of the Heights, lately of the Jade Room, was seen leaving the Lyceum before the curtain with a face like thunder and a brother two steps behind. One wonders what the Voss table talks about, when it talks.”', 'Cut from the page with scissors, not a razor.'],
      spoken: 'A society column, cut from the page, with the songbird of the Heights in it.',
      reading: 'Shaw was writing about Lillian the day she died. Colour, and a temper. Nothing for the notebook.', about: ['shaw', 'roland'], effect: { type: 'none' } },
    { id: 'item:orchid:lobby-photo', at: 'herald', kind: 'photo', label: 'Press photograph, the Gilded lobby', stamp: 'COPY',
      source: 'THE ASHGRAVE HERALD · PICTURE DESK', title: 'Lobby, the Gilded, 2:40 AM',
      body: ['Taken before the first uniform arrived. Perpetua Shaw in the foreground, notebook out, hat off. Something about her in the flash that you would not have noticed by lamplight.', 'On the back in grease pencil: HOLD FOR MORNING.'],
      spoken: 'A press photograph of the lobby, taken before the first uniform arrived.',
      reading: 'A good photograph gives a person away.', about: ['shaw'], effect: { type: 'suspectTrait', suspectId: 'shaw' } },
    { id: 'item:orchid:stub', at: 'lyceum', kind: 'ticket', label: 'Lyceum stub, box C',
      source: 'THE LYCEUM · BOX OFFICE', title: 'Box C, Nov. 3, evening performance',
      fields: [['Box', 'C, the Voss box'], ['Torn', 'no — never presented'], ['Found', 'under the seat']],
      body: ['The Voss box, and the stub never torn. Somebody had a seat for the evening and did not sit in it.'],
      spoken: 'A ticket for the Voss box, never torn.',
      reading: 'Somebody in that family was not where the family was. Story, not evidence.', about: ['roland'], effect: { type: 'none' } },
    { id: 'item:orchid:check', at: 'belvedere', kind: 'receipt', label: 'Café Belvedere check',
      source: 'CAFÉ BELVEDERE · OPEN ALL NIGHT', title: 'Check no. 2207',
      fields: [['Coffee, black', '2'], ['Time', '1:15 AM'], ['Signed', '“E.S.”']],
      body: ['Two coffees, one drunk. Signed to the house account in a hand the waiter knows.', 'The second cup was still warm when the chair emptied.'],
      spoken: 'A café check for two coffees at a quarter past one, signed E.S.',
      reading: 'Whoever left the second cup left in a hurry, and the waiter saw which way.', about: ['strand'], effect: { type: 'lead' } },
    { id: 'item:orchid:petal', at: 'gardens', kind: 'note', label: 'A pressed orchid petal', stamp: 'PERSONAL',
      source: 'FOUND IN A HYMNAL, BANDSTAND STEPS', title: 'Pressed between the pages',
      body: ['A hymnal, parish issue, St. Ordell’s stamped inside the cover. Between the psalms, a single orchid petal pressed flat and brown at the edges.', 'Somebody sat here with the church’s book and the dead woman’s flower.'],
      spoken: 'A parish hymnal on the bandstand steps, with an orchid petal pressed inside.',
      reading: 'Colour. It puts the parish and the orchid in one place, and nothing in the notebook.', about: ['tovar'], effect: { type: 'none' } },
    { id: 'item:orchid:box-log', at: 'trust', kind: 'ledger', label: 'Safe-deposit access log', stamp: 'CONFIDENTIAL',
      source: 'ASHGRAVE TRUST · VAULT', title: 'Access log, box 114',
      body: ['11:50 PM — R. VOSS — box 114 — signed out 11:58. The signature is hurried and the pen dug through the page.', 'Miss Vine remembers the hand that signed, and what it looked like doing it.'],
      spoken: 'The vault log: box one-fourteen, opened by R. Voss at ten to midnight.',
      reading: 'The teller watched him sign. That is worth something about him.', about: ['roland'], effect: { type: 'suspectTrait', suspectId: 'roland' } },
    { id: 'item:orchid:deacon-letter', at: 'cathedral', kind: 'letter', label: 'Letter to the Deacon', stamp: 'PERSONAL',
      source: 'FOUND IN THE VESTRY', title: 'To Deacon Tovar, unsent reply attached',
      body: ['“Iris — I have seen the books. The soup line does not cost what the plate collects and you know it. I will not say anything before Sunday. After Sunday I make no promises. — L.”', 'Pinned to it, half a reply in the Deacon’s hand, crossed out twice.'],
      spoken: 'A letter from Lillian to the Deacon about the parish books, and half a reply.',
      reading: 'A motive in ink. It does not describe anybody’s hands or hair.', about: ['tovar'], effect: { type: 'none' } },
    { id: 'item:orchid:admission', at: 'mercy', kind: 'report', label: 'Admission slip, ward four',
      source: 'MERCY HOSPITAL · ADMISSIONS', title: 'Ward four, night of Nov. 3',
      fields: [['Patient', 'male, 30s, laceration to left hand'], ['Admitted', '3:05 AM'], ['Discharged', 'against advice, 3:40 AM'], ['Physician', 'Dr. A. Pike']],
      body: ['Pike stitched a man’s hand at three in the morning and let him walk out with the thread still wet. Neither of them gave a name.'],
      spoken: 'An admission slip: a man with a cut hand, stitched by Doctor Pike at three, and gone by four.',
      reading: 'Somebody bled tonight and Pike helped him not talk about it. Story.', about: ['pike'], effect: { type: 'none' } },
    { id: 'item:orchid:cab-chit', at: 'market', kind: 'receipt', label: 'Cab chit, Lantern Cab Co.',
      source: 'LANTERN CAB CO. · ALL NIGHT', title: 'Fare chit no. 88',
      fields: [['From', 'Lantern Market'], ['To', 'the Bluff'], ['Time', '2:20 AM'], ['Driver', 'Kaspar']],
      body: ['The driver is still on the rank outside, and he knows a way up the Bluff that is not on any map.'],
      spoken: 'A cab chit, market to the Bluff at twenty past two, and the driver still on the rank.',
      reading: 'A driver who knows the shortcuts saves you time.', effect: { type: 'time', hours: -2 } },
    { id: 'item:orchid:fire-clipping', at: 'library', kind: 'clipping', label: 'Herald, 1946: the cannery fire',
      source: 'THE ASHGRAVE HERALD · BACK NUMBER', title: '“Cannery fire ruled accident”',
      body: ['Two dead, no charges, and a paragraph near the bottom noting that the building was insured through an importer on the Lantern side and the night watch was a union man.', 'Somebody has underlined both names in pencil.'],
      spoken: 'A back number of the Herald, the cannery fire, with two names underlined.',
      reading: 'Old business between an importer and the union. It explains a friendship, not a murder.', about: ['mireaux', 'brandt'], effect: { type: 'none' } },
    { id: 'item:orchid:operator-log', at: 'exchange', kind: 'note', label: 'Operator’s log, board nine',
      source: 'CENTRAL EXCHANGE · BOARD 9', title: 'Calls placed from the Gilded, suite 1100',
      body: ['1:52 AM — outgoing — LANTERN 4-4 — duration one minute ten. The last call the suite ever made.', 'Quill wrote the number down when she should not have.'],
      spoken: 'The operator’s log: the last call from suite eleven-hundred, at eight minutes to two.',
      reading: 'A number is an address. Somebody was rung a quarter of an hour before she died.', effect: { type: 'lead' } },
    { id: 'item:orchid:effects', at: 'morgue', kind: 'report', label: 'Inventory of personal effects',
      source: 'CITY MORGUE · REGISTER', title: 'Effects of the deceased, Voss, L.',
      fields: [['Ring', 'one, gold, setting bent'], ['Key', 'one, brass, stamped 114'], ['Orchid', 'one stem, snapped'], ['Purse', 'no money']],
      body: ['A brass key stamped one-fourteen in the pocket of a woman with no purse to spend. The morgue does not guess what it opens. You are allowed to.'],
      spoken: 'The inventory of her effects: a bent ring, a brass key stamped one-fourteen, and no money.',
      reading: 'One-fourteen is a box at the Trust. She had the key; somebody else opened the box.', about: ['roland'], effect: { type: 'none' } },
    { id: 'item:orchid:transfer', at: 'tram', kind: 'ticket', label: 'Tram transfer, the Bluff line',
      source: 'ASHGRAVE TRAMWAYS', title: 'Transfer, punched 1:20 AM',
      body: ['A transfer punched at twenty past one on the last car up the Bluff, dropped between the seats. Nobody transfers at that hour unless they are going somewhere they do not want a cab to remember.'],
      spoken: 'A tram transfer, punched at twenty past one on the last car to the Bluff.',
      reading: 'Somebody rode to the Bluff late and quiet. Story.', effect: { type: 'none' } },
    { id: 'item:orchid:floor-photo', at: 'jade', kind: 'photo', label: 'Photograph, the Jade Room floor',
      source: 'THE JADE ROOM · HOUSE PHOTOGRAPHER', title: 'The eleven o’clock spot, Nov. 3',
      body: ['Vera Lang on the little stage at eleven, in the flash. The house photographer sells these at the door for a dollar. This one was not bought; it was taken.', 'You can see a great deal of a person in a flash photograph.'],
      spoken: 'A house photograph of Vera Lang on the Jade Room stage at eleven.',
      reading: 'A flash photograph tells you something about her.', about: ['vera'], effect: { type: 'suspectTrait', suspectId: 'vera' } },
    { id: 'item:orchid:manifest', at: 'imports', kind: 'ledger', label: 'Import manifest, forty crates', stamp: 'COPY',
      source: 'MIREAUX IMPORTS · MANIFEST', title: 'Consignment, SS Marseillaise',
      body: ['Forty crates, orchids, Marseille to Ashgrave. Twenty-eight initialled at the dock by the bond clerk. Twelve initialled by somebody else, in the importer’s own hand, at the warehouse, at night.', 'She signed for them herself. The clerk remembers the hand.'],
      spoken: 'An import manifest: forty crates of orchids, and twelve of them signed for at night.',
      reading: 'She signed twelve crates herself. The clerk watched her do it.', about: ['mireaux'], effect: { type: 'suspectTrait', suspectId: 'mireaux' } },
    { id: 'item:orchid:poisons', at: 'pharmacy', kind: 'ledger', label: 'Poisons register, page 31', stamp: 'CONFIDENTIAL',
      source: 'PIKE’S PHARMACY · POISONS REGISTER', title: 'Entries, Nov. 3',
      body: ['10:05 PM — ether, four oz. — signed A. PIKE — purpose: “surgical”. The signature is his, the chemist says, and the hand that made it he has watched a thousand times.'],
      spoken: 'The poisons register: four ounces of ether, signed out by Doctor Pike at ten.',
      reading: 'Dunn watched him sign. That is worth something about the doctor.', about: ['pike'], effect: { type: 'suspectTrait', suspectId: 'pike' } },
    { id: 'item:orchid:locker-tag', at: 'baths', kind: 'ticket', label: 'Locker tag no. 9, unclaimed',
      source: 'LANTERN BATHS · LOCKERS', title: 'Tag no. 9',
      body: ['A coat, wet through, hung in locker nine at half past two and never claimed. In the pocket, a second locker tag from somewhere else in the city.'],
      spoken: 'An unclaimed locker tag, and a wet coat with another tag in the pocket.',
      reading: 'The second tag is from somewhere else. Somebody left a trail of lockers.', effect: { type: 'lead' } },
    { id: 'item:orchid:threat', at: 'cannery', kind: 'letter', label: 'An unsigned letter, union paper',
      source: 'FOUND NAILED TO THE CANNERY DOOR', title: 'On Dockers’ Union letterhead',
      body: ['“You were told. The next one is not a warning.” Typed, unsigned, on the union’s own paper, with the union’s own typewriter — the capital W drops.', 'Brandt does not type. Somebody at the hall does.'],
      spoken: 'An unsigned threat on union paper, nailed to the cannery door.',
      reading: 'Somebody at the union threatened somebody at the cannery. Story.', about: ['brandt'], effect: { type: 'none' } },
    { id: 'item:orchid:ferry-ticket', at: 'ferry', kind: 'ticket', label: 'Ferry ticket, last crossing',
      source: 'ASHGRAVE BAY FERRY', title: 'One crossing, 1:40 AM',
      body: ['A ticket for the last boat, punched, found on the deck by the rail where a person stands who does not want to be inside with the others.'],
      spoken: 'A ticket for the last ferry, found by the rail.',
      reading: 'Somebody crossed the bay late. The steward would know who.', effect: { type: 'none' } },
    { id: 'item:orchid:set-list', at: 'parrot', kind: 'note', label: 'Set list, Vera Lang', stamp: 'PERSONAL',
      source: 'THE BLUE PARROT · BACKSTAGE', title: 'Set list, Nov. 3',
      body: ['Eleven songs in Vera’s hand, and at the bottom, underlined so hard it tore: “L. owes me the top of the bill and she knows it.”'],
      spoken: 'Vera Lang’s set list, with a line at the bottom underlined hard enough to tear.',
      reading: 'A grudge, written down. Not a hand or a hair.', about: ['vera'], effect: { type: 'none' } },
    { id: 'item:orchid:mother', at: 'tenement', kind: 'letter', label: 'Letter from a mother', stamp: 'PERSONAL',
      source: 'FOUND ON A LANDING, TENEMENT ROW', title: 'To Nikolai, from your mother',
      body: ['“Kolya — the money came and I did not ask where from and I will not. Come for Sunday. Wear the good coat. Your sister says you have been fighting again and I told her you would never.”', 'It has been read many times and folded small.'],
      spoken: 'A letter from Brandt’s mother, folded small and read many times.',
      reading: 'Somebody loves him. It does not help the notebook.', about: ['brandt'], effect: { type: 'none' } },
    { id: 'item:orchid:repair', at: 'garage', kind: 'receipt', label: 'Repair chit, black Packard',
      source: 'RAINER GARAGE · WORK ORDER', title: 'Black Packard, Voss Manor',
      fields: [['Damage', 'near-side wing stove in'], ['Brought in', '2:50 AM'], ['Driver', '“family”'], ['Paid', 'cash, in advance']],
      body: ['The Voss car, brought in at ten to three with a wing folded like paper and cash paid before the work was done. The mechanic did not ask what it hit.'],
      spoken: 'A work order for the Voss Packard, brought in at ten to three with a wing stove in.',
      reading: 'The family car was out and hit something. Story, unless it was somebody.', about: ['roland'], effect: { type: 'none' } },
    { id: 'item:orchid:dues', at: 'union', kind: 'ledger', label: 'Dues ledger, November',
      source: 'DOCKERS’ UNION LOCAL 9 · DUES', title: 'Collections, week of Nov. 3',
      body: ['Every entry in Brandt’s hand, and every hand that paid him remembered by the man who keeps the book. He knows more about the collector than the collector knows about himself.'],
      spoken: 'The union dues ledger, every line in Brandt’s hand.',
      reading: 'The bookkeeper has watched Brandt write for years. He can tell you something.', about: ['brandt'], effect: { type: 'suspectTrait', suspectId: 'brandt' } },
    { id: 'item:orchid:marseille', at: 'docks', kind: 'telegram', label: 'Telegram from Marseille',
      source: 'WESTERN UNION · CABLE OFFICE', title: 'Cable, for C. Mireaux',
      body: ['SHIPMENT SPLIT AT LE HAVRE STOP TWELVE TRAVEL SEPARATE STOP DO NOT LET HER SEE THE MANIFEST STOP'],
      spoken: 'A cable from Marseille, for Cass Mireaux: do not let her see the manifest.',
      reading: 'Somebody did not want Lillian reading a manifest. A motive, and only that.', about: ['mireaux'], effect: { type: 'none' } },
    { id: 'item:orchid:seal', at: 'warehouse', kind: 'report', label: 'Customs seal report, bay 4',
      source: 'H.M. CUSTOMS · BONDED STORE', title: 'Seal broken, bay 4',
      fields: [['Seal', 'no. 4471, broken'], ['Found', '1:10 AM, by the bond clerk'], ['Missing', 'one crate, orchids']],
      body: ['A crate went out without paper, and the cart tracks in the wet lead out of the yard and up the road.'],
      spoken: 'A customs report: a seal broken and a crate gone, with cart tracks leading out of the yard.',
      reading: 'The tracks go somewhere. Follow them.', effect: { type: 'lead' } },
    { id: 'item:orchid:prayer-card', at: 'chapel', kind: 'note', label: 'A prayer card, “for Lillian”',
      source: 'SAILORS’ CHAPEL · CARDS FOR THE DROWNED', title: 'For Lillian',
      body: ['A card from the rack, filled in before dawn in a man’s hand: FOR LILLIAN, WHO KNEW. No surname. The ink was still wet when the sexton found it.'],
      spoken: 'A prayer card in the Sailors’ Chapel, for Lillian, who knew.',
      reading: 'Somebody prayed for her before the Herald had printed her name. Story.', about: ['strand', 'roland'], effect: { type: 'none' } },
    { id: 'item:orchid:unfinished', at: 'manor', kind: 'letter', label: 'Lillian’s unfinished letter', stamp: 'PERSONAL',
      source: 'VOSS MANOR · HER WRITING DESK', title: 'To Roland, unfinished',
      body: ['“Rollo — I have changed the will and I have told Father’s lawyer why. When you read this you will already know. I am sorry it had to be me who—”', 'The pen stops. The rest of the page is clean.'],
      spoken: 'An unfinished letter from Lillian to her brother about the will.',
      reading: 'The estate was about to pass elsewhere. A motive, and a heartbreaking one. Not evidence.', about: ['roland'], effect: { type: 'none' } },
    { id: 'item:orchid:keeper-log', at: 'baylight', kind: 'note', label: 'Keeper’s log, the cliff path',
      source: 'BAY LIGHT · KEEPER’S LOG', title: 'Lights on the Bluff, night of Nov. 3',
      body: ['2:30 — lantern on the cliff path, stops at the old stair, returns. 2:55 — lantern again, further out. 3:10 — nothing. The keeper thinks it was the fishermen. You will have to go and look to be sure it was not, and it costs you an hour to find out it was.'],
      spoken: 'The keeper’s log: a lantern on the cliff path at half past two, and again at five to three.',
      reading: 'It was the fishermen. An hour gone.', effect: { type: 'time', hours: 1 } },
  ],

  epilogue: {
    win: `The cuffs go on in the lobby of the Gilded, under the chandelier, with the morning
      edition already screaming it. Somebody sets the orchid back in the vase on the way out.
      Ashgrave will forget by Thursday. You will not.`,
    loss: `The Herald moves it to page nine, then page nineteen, then nowhere. The suite is
      let again by Christmas. Lillian Voss becomes a thing people almost remember, and the
      rain keeps on doing what rain does.`,
  },
};

export default def;
