import type { CaseDef } from '../../types/game-types';

// Salt and Silence. The Harbour District: thirty locations from Customs Row
// down to the Narrows, twenty people who will talk if you do not ask like
// police, and twenty-six documents the tide did not take.

const def: CaseDef = {
  id: 'salt',
  title: 'Salt and Silence',
  subtitle: 'The Harbour District · February 1948',
  tagline: 'They pulled the union boss out of the bay with his pockets sewn shut and full of salt.',
  victim: 'Aurel Bask',
  scene: 'pier9',
  difficultyHint: 'Tight streets, fast tongues.',
  publicTraits: ['build', 'hair'],
  traitPool: ['hand', 'mark', 'vice', 'scent', 'shoe'],

  briefing: `Low tide at Pier Nine gives up Aurel Bask, twenty years head of the longshoremen
    and thirty hours dead. Somebody sewed his coat pockets shut and filled them with rock salt,
    which is not how you sink a man -- it is how you tell three thousand dockers what happens
    to a man who talks. The wound is under the ribs and it went up.
    Half this harbour wanted him gone and the other half worked for him. Nobody here talks to
    police, so do not ask like police. Move before the tide turns twice.`,

  radio: [
    'Dispatch. Harbour Station. Do not go down to Pier Nine alone and do not go in uniform.',
    'The union votes on a new boss Thursday. Every candidate is on your list.',
    'Customs has been sitting on a manifest for six weeks. Lean on them.',
  ],

  terrain: {
    sea: true, seaName: 'THE NARROWS', river: false, parks: 1,
    districts: [
      { text: 'CUSTOMS ROW', x: 450, y: 10, rot: -2 },
      { text: 'THE HALL', x: 760, y: 120, rot: 2 },
      { text: 'GRIEVE POINT', x: 1000, y: 90, rot: 4 },
      { text: 'THE SALT YARDS', x: 230, y: 620, rot: -3 },
      { text: 'THE NARROWS', x: 800, y: 600, rot: 2 },
    ],
  },

  locations: [
    // ---- Customs Row
    { id: 'pier9', name: 'Pier Nine', type: 'docks', x: 250, y: 170, district: 'Customs Row', desc: 'Where they found him. Still taped off, still stinking.' },
    { id: 'harbourmaster', name: 'Harbourmaster’s Office', type: 'office', x: 300, y: 60, district: 'Customs Row', desc: 'Every boat in and out, in a hand that never wavers. The clerk’s does.' },
    { id: 'customs', name: 'The Customs House', type: 'bank', x: 470, y: 110, district: 'Customs Row', desc: 'Every crate in this harbour is a line in a ledger here. Most lines are lies.' },
    { id: 'marconi', name: 'Marconi Station', type: 'radio', x: 640, y: 60, district: 'Customs Row', desc: 'Every wireless message on the water, and one operator who writes them all down twice.' },
    { id: 'excise', name: 'Dockside Café', type: 'cafe', x: 380, y: 240, district: 'Customs Row', desc: 'Tea, tobacco and the only warm room between the Row and the Hall.' },
    { id: 'bondstore', name: 'Bond Store 12', type: 'warehouse', x: 560, y: 220, district: 'Customs Row', desc: 'Six weeks of crates nobody has opened, under a seal somebody has.' },
    { id: 'pawnshop', name: 'Lundy’s Pawn', type: 'shop', x: 60, y: 250, district: 'Customs Row', desc: 'Sextants, wedding rings, and one knife with a very particular handle.' },
    // ---- The Hall
    { id: 'hall', name: 'Longshoremen’s Hall', type: 'office', x: 720, y: 160, district: 'The Hall', desc: 'Folding chairs, a dead man’s photograph, and an election on Thursday.' },
    { id: 'printers', name: 'The Docker’s Voice', type: 'press', x: 800, y: 60, district: 'The Hall', desc: 'The union paper. Set by hand, read by three thousand, believed by most.' },
    { id: 'station', name: 'Harbour Station', type: 'police', x: 480, y: 330, district: 'The Hall', desc: 'Two desks, one cell, and a radiator that screams.' },
    { id: 'chandler', name: 'Vetch & Son, Chandlers', type: 'shop', x: 650, y: 330, district: 'The Hall', desc: 'Rope, oil, and every kind of hook a man could need.' },
    { id: 'shipping', name: 'Salvi Shipping', type: 'office', x: 780, y: 300, district: 'The Hall', desc: 'Three companies, one office, one lamp that is always on.' },
    { id: 'bank', name: 'Harbour Savings', type: 'bank', x: 560, y: 440, district: 'The Hall', desc: 'Where the dues go, and where they sometimes come from.' },
    { id: 'hospital', name: 'Seamen’s Infirmary', type: 'hospital', x: 760, y: 480, district: 'The Hall', desc: 'Dr. Fenn’s wards. The certificates are written fast here.' },
    // ---- Grieve Point
    { id: 'light', name: 'Grieve Point Light', type: 'light', x: 920, y: 240, district: 'Grieve Point', desc: 'One keeper, one lamp, and the best view of who comes in at night.' },
    { id: 'raskhouse', name: 'The Rask House', type: 'manor', x: 1040, y: 150, district: 'Grieve Point', desc: 'Grey shingles on the point. The widow keeps the lamp in the window lit for a man seven years drowned.' },
    { id: 'chapel', name: 'Fishermen’s Chapel', type: 'church', x: 1000, y: 380, district: 'Grieve Point', desc: 'Names of the lost on brass, and one added this week in chalk.' },
    { id: 'coastguard', name: 'Coastguard Tower', type: 'tower', x: 1060, y: 520, district: 'Grieve Point', desc: 'A log of every hull that crosses the Narrows after dark. Most of them are lies too.' },
    { id: 'icehouse', name: 'The Ice House', type: 'warehouse', x: 870, y: 450, district: 'Grieve Point', desc: 'Cold enough to keep a body honest.' },
    // ---- The Salt Yards
    { id: 'brine', name: 'The Brine & Bell', type: 'bar', x: 170, y: 340, district: 'The Salt Yards', desc: 'Sawdust, rum, and forty men who saw nothing.' },
    { id: 'seamen', name: 'Seamen’s Mission', type: 'home', x: 80, y: 460, district: 'The Salt Yards', desc: 'Forty cots, a stove, and a warden who counts who does not come back.' },
    { id: 'tram', name: 'Quay Tram Stop', type: 'tram', x: 420, y: 420, district: 'The Salt Yards', desc: 'The last car along the quay at midnight. The conductor punches faces, not tickets.' },
    { id: 'drydock', name: 'Number Four Drydock', type: 'factory', x: 330, y: 490, district: 'The Salt Yards', desc: 'A hull the size of a church, propped up on stilts.' },
    { id: 'baths', name: 'Harbour Baths', type: 'bathhouse', x: 170, y: 580, district: 'The Salt Yards', desc: 'Steam, tile, and the only place in the district nobody wears a coat.' },
    { id: 'saltworks', name: 'The Salt Works', type: 'factory', x: 240, y: 700, district: 'The Salt Yards', desc: 'Where rock salt is bagged by the hundredweight, and nobody counts the bags.' },
    { id: 'ropewalk', name: 'The Ropewalk', type: 'warehouse', x: 500, y: 650, district: 'The Salt Yards', desc: 'A quarter mile of shed, and a needle for every thickness of line.' },
    // ---- The Narrows
    { id: 'trawler', name: 'The Trawler Berths', type: 'docks', x: 620, y: 570, district: 'The Narrows', desc: 'Nets, gulls, and boats that go out empty and come back heavy.' },
    { id: 'cannery', name: 'Narrows Cannery', type: 'factory', x: 760, y: 700, district: 'The Narrows', desc: 'Still running, on fish nobody catches.' },
    { id: 'morgue', name: 'Harbour Morgue', type: 'morgue', x: 900, y: 620, district: 'The Narrows', desc: 'Bask is on the third slab, and the salt is still in a bag beside him.' },
    { id: 'slip', name: 'Ferry Slip', type: 'pier', x: 1120, y: 680, district: 'The Narrows', desc: 'The only way off the point that does not go past the tower.' },
  ],
  edges: [
    ['pier9', 'harbourmaster'], ['pier9', 'pawnshop'], ['pier9', 'brine'], ['pier9', 'customs'],
    ['harbourmaster', 'customs'],
    ['customs', 'marconi'], ['customs', 'bondstore'], ['customs', 'excise'],
    ['marconi', 'hall'], ['marconi', 'printers'],
    ['hall', 'printers'], ['hall', 'shipping'], ['hall', 'bondstore'], ['hall', 'light'],
    ['printers', 'raskhouse'],
    ['light', 'raskhouse'], ['light', 'chapel'], ['light', 'shipping'],
    ['raskhouse', 'chapel'],
    ['chapel', 'coastguard'], ['chapel', 'icehouse'],
    ['coastguard', 'slip'], ['coastguard', 'morgue'],
    ['excise', 'station'], ['excise', 'brine'],
    ['bondstore', 'station'], ['bondstore', 'chandler'],
    ['station', 'tram'], ['station', 'chandler'], ['station', 'bank'],
    ['chandler', 'shipping'], ['chandler', 'hospital'],
    ['shipping', 'hospital'],
    ['hospital', 'icehouse'], ['hospital', 'trawler'],
    ['icehouse', 'morgue'],
    ['brine', 'seamen'], ['brine', 'tram'], ['brine', 'drydock'],
    ['seamen', 'baths'],
    ['pawnshop', 'seamen'],
    ['tram', 'drydock'], ['tram', 'bank'],
    ['bank', 'trawler'], ['bank', 'ropewalk'],
    ['drydock', 'baths'], ['drydock', 'ropewalk'],
    ['baths', 'saltworks'],
    ['saltworks', 'ropewalk'],
    ['ropewalk', 'trawler'],
    ['trawler', 'cannery'],
    ['cannery', 'morgue'], ['cannery', 'slip'],
    ['morgue', 'slip'],
  ],
  start: 'station',

  suspects: [
    { id: 'hollis', name: 'Dov Hollis', role: 'Union vice-chair',
      blurb: 'Second chair for eleven years. First chair as of Thursday.',
      motive: 'because second chair for eleven years is its own kind of sentence.' },
    { id: 'wren', name: 'Etta Wren', role: 'Customs inspector',
      blurb: 'Signed off on six weeks of crates she never opened.',
      motive: 'because the manifest he was carrying had her signature on every page.' },
    { id: 'okafor', name: 'Bernard Okafor', role: 'Chandler, Vetch & Son',
      blurb: 'Sells the rope. Keeps a list of who buys it.',
      motive: 'because the debt was called in, and he had nothing left to pay it with.' },
    { id: 'salvi', name: 'Nunzio Salvi', role: 'Shipping agent',
      blurb: 'Three companies, one office, no employees.',
      motive: 'because a strike would have cost him a season he could not afford to lose.' },
    { id: 'tilda', name: 'Tilda Rask', role: 'Widow of the last boss',
      blurb: 'Her husband went into the bay in ’41. Nobody was ever charged.',
      motive: 'because seven years is a long time to hold a thing, and no time at all.' },
    { id: 'keeper', name: 'Mr. Garrow', role: 'Lighthouse keeper',
      blurb: 'Sees everything from Grieve Point and reports none of it.',
      motive: 'because he saw the boat, and then he was in it.' },
    { id: 'fenn', name: 'Dr. Ilse Fenn', role: 'Harbour surgeon',
      blurb: 'Wrote the death certificate before the body was cold. Wrote it wrong.',
      motive: 'because the wound went up, and only she knew what that meant.' },
    { id: 'ledoux', name: 'Marcel Ledoux', role: 'Trawler skipper',
      blurb: 'Goes out with an empty hold twice a week and comes back low in the water.',
      motive: 'because Bask had started counting the boats, and the counting was nearly done.' },
  ],

  witnesses: [
    { id: 'teague', at: 'brine', name: 'Mags Teague', role: 'landlady, the Brine & Bell',
      intro: 'Mags. Forty men in here every night and I know what every one of them drinks and owes.',
      knows: ['hollis', 'ledoux', 'tilda'],
      aboutLine: 'Drinks in my house. I could draw them from memory.',
      leadLine: 'Somebody settled a tab tonight that has been open since March. In coin. They came in from',
      spentLine: 'Last orders was an hour ago, detective. That goes for questions.' },
    { id: 'aldous', at: 'customs', name: 'Percy Aldous', role: 'night clerk, the Customs House',
      intro: 'Aldous. I copy the manifests. Every crate in this harbour crosses my desk twice, once as it is and once as it is declared.',
      knows: ['wren', 'salvi'],
      aboutLine: 'Signs my book. You notice the hand that signs.',
      leadLine: 'A manifest was altered tonight and the ink is still wet. The crate it describes is at',
      spentLine: 'I am a clerk. Clerks do not know things. Please close the door.' },
    { id: 'vetch', at: 'chandler', name: 'Young Vetch', role: 'apprentice, Vetch & Son',
      intro: 'Tom Vetch. The son on the sign. Everyone who works this harbour buys rope from us and I cut it for them.',
      knows: ['okafor', 'salvi', 'fenn'],
      aboutLine: 'Customer. I measure their rope; I have measured them.',
      leadLine: 'Somebody bought forty feet of line tonight and paid double to have it cut quiet. They took it down to',
      spentLine: 'Dad says not to talk to police. I have talked enough.' },
    { id: 'kite', at: 'morgue', name: 'Amos Kite', role: 'attendant, Harbour Morgue',
      intro: 'Kite. I sit with the dead. They are better company than you would think and worse than you would hope.',
      knows: ['fenn', 'tilda'],
      aboutLine: 'Has been down to see Bask. People give themselves away over a slab.',
      leadLine: 'A visitor left something in the coat room and did not come back for it. It was sent on to',
      spentLine: 'I have three to wash before morning. You can find your own way out.' },
    { id: 'pell', at: 'trawler', name: 'Iggy Pell', role: 'deckhand',
      intro: 'Pell. I mend nets and I keep my head down. Tonight I looked up once, which is once too often.',
      knows: ['ledoux', 'hollis', 'keeper'],
      aboutLine: 'Works the berths. You get to know a person by their walk on wet boards.',
      leadLine: 'Something was thrown from a boat and did not sink. It fetched up by',
      spentLine: 'I said I keep my head down. I am putting it back down now.' },
    { id: 'harrow', at: 'baths', name: 'Nell Harrow', role: 'attendant, Harbour Baths',
      intro: 'Nell Harrow. Towels and tickets. Nobody has any pockets in here, which is why they talk.',
      knows: ['wren', 'tilda', 'keeper'],
      aboutLine: 'Bathes here. You cannot hide much in a towel.',
      leadLine: 'A coat was left in the changing room with something heavy in the lining. The owner ran toward',
      spentLine: 'We close at two. That is all I have for you.' },
    { id: 'gault', at: 'harbourmaster', name: 'Ruth Gault', role: 'clerk, Harbourmaster’s Office',
      intro: 'Gault. I log the boats. In, out, tonnage, master. When the log and the water disagree, I write down the water.',
      knows: ['wren', 'salvi', 'keeper'],
      aboutLine: 'Comes to my counter. You learn a person by how they lie about tonnage.',
      leadLine: 'A boat cleared out at eleven with no cargo declared and came back at three riding low. It tied up at',
      spentLine: 'The office is closed and the log is locked. Good night.' },
    { id: 'sparks', at: 'marconi', name: 'Tommy Sparks', role: 'wireless operator',
      intro: 'Sparks. Real name Tomasz, nobody uses it. Every message on the water comes through these headphones and most of them are about fish. Most.',
      knows: ['keeper', 'salvi', 'ledoux'],
      aboutLine: 'Sends through me. You can tell a person by their fist on a key.',
      leadLine: 'A message went out to a boat at one in the morning: STOP AT THE USUAL. The usual, in this harbour, is',
      spentLine: 'I have a ship calling and you are not it.' },
    { id: 'brack', at: 'hall', name: 'Mabel Brack', role: 'caretaker, the Hall',
      intro: 'Brack. I sweep up after the meetings and I have swept up after every man who ever wanted to run this union.',
      knows: ['hollis', 'tilda', 'okafor'],
      aboutLine: 'Sits in that hall every Thursday. I have swept around their feet for years.',
      leadLine: 'The back office was opened after the meeting with a key that was not the vice-chair’s. Whatever was taken went to',
      spentLine: 'The hall is locked and I am going home.' },
    { id: 'delacroix', at: 'printers', name: 'Émile Delacroix', role: 'typesetter, the Docker’s Voice',
      intro: 'Delacroix. I set the Voice by hand. I know every word before the union does, and I know who wanted which words changed.',
      knows: ['hollis', 'tilda'],
      aboutLine: 'Brings me copy. You learn a person by what they cross out.',
      leadLine: 'A notice was pulled from tomorrow’s edition at midnight by somebody who had no business in the shop. They left toward',
      spentLine: 'The forme is locked and the press is running. Mind your fingers on the way out.' },
    { id: 'oyelaran', at: 'bondstore', name: 'Femi Oyelaran', role: 'watchman, Bond Store 12',
      intro: 'Oyelaran. Six weeks I have watched these crates and six weeks nobody has come for them. Until tonight.',
      knows: ['wren', 'salvi', 'ledoux'],
      aboutLine: 'Comes to the seal. You learn a person by how they look at a seal they cannot break.',
      leadLine: 'One crate was opened and closed again badly. What came out of it went along the quay to',
      spentLine: 'I have a store to watch. I am watching it.' },
    { id: 'mott', at: 'excise', name: 'Nan Mott', role: 'owner, Dockside Café',
      intro: 'Nan. Tea at a penny, and for a penny more I will tell you who drank it. Bask drank it here every morning for twenty years.',
      knows: ['hollis', 'okafor', 'fenn'],
      aboutLine: 'Takes tea here. I have set a cup in front of them a thousand times.',
      leadLine: 'Somebody left a newspaper folded round something heavy and did not come back. I put it aside, and then somebody else took it to',
      spentLine: 'Kettle is off. So am I.' },
    { id: 'penrose', at: 'chapel', name: 'Aldo Penrose', role: 'verger, Fishermen’s Chapel',
      intro: 'Penrose. I keep the brass polished and the names read. There is a new name in chalk this week and I did not write it.',
      knows: ['tilda', 'keeper'],
      aboutLine: 'Comes to the brass. You learn a person by which name they touch.',
      leadLine: 'Somebody knelt here at four this morning with sand on their knees and left something in the poor box. It was carried off to',
      spentLine: 'The chapel is open to everyone. Everyone but you, tonight.' },
    { id: 'sable', at: 'coastguard', name: 'Jean Sable', role: 'petty officer, Coastguard',
      intro: 'Sable. I log every hull that crosses the Narrows after dark and I know which ones are not in the log.',
      knows: ['keeper', 'ledoux'],
      aboutLine: 'Passes under my glass. You learn a person by how they stand at a wheel.',
      leadLine: 'A dinghy with no light crossed at half past two and beached below',
      spentLine: 'Watch changes at six. Come back then and ask somebody else.' },
    { id: 'ives', at: 'hospital', name: 'Maud Ives', role: 'nurse, Seamen’s Infirmary',
      intro: 'Nurse Ives. I keep Dr. Fenn’s wards and I keep them better than she keeps her certificates.',
      knows: ['fenn', 'hollis', 'okafor'],
      aboutLine: 'Been through my ward. You do not forget a patient, or a visitor.',
      leadLine: 'A bag came in with a patient and went out without him. The porter carried it to',
      spentLine: 'Ward rounds. If you are not bleeding, out.' },
    { id: 'cully', at: 'icehouse', name: 'Bram Cully', role: 'foreman, the Ice House',
      intro: 'Cully. I cut ice and I stack it. Tonight a block came back to me with a hole cut in it the size of a man.',
      knows: ['ledoux', 'salvi'],
      aboutLine: 'Buys ice. You learn a person by what they need kept cold.',
      leadLine: 'A cart came for ice at three that had no business needing it. It went on toward',
      spentLine: 'Ice does not wait and neither do I.' },
    { id: 'lundy', at: 'pawnshop', name: 'Ma Lundy', role: 'pawnbroker',
      intro: 'Lundy. Everything in this harbour ends up in my window sooner or later. Tonight something came in that I would not put in the window.',
      knows: ['okafor', 'tilda', 'ledoux'],
      aboutLine: 'Pawns with me. I look at the hands that hand things over.',
      leadLine: 'A ticket was redeemed for cash at midnight by somebody who was not the one who pledged it. They went to',
      spentLine: 'Shop is shut. I have said more than the sign allows.' },
    { id: 'rook', at: 'tram', name: 'Tamsin Rook', role: 'conductor, the quay tram',
      intro: 'Rook. Last car along the quay at midnight. I punch tickets and I remember who did not want to be remembered.',
      knows: ['hollis', 'fenn', 'wren'],
      aboutLine: 'Rides my car. You learn a person by where they will not sit.',
      leadLine: 'Somebody rode to the end of the line and walked back the way we had come, toward',
      spentLine: 'Car is in the shed. So am I.' },
    { id: 'orme', at: 'saltworks', name: 'Jack Orme', role: 'night man, the Salt Works',
      intro: 'Orme. I bag salt. A hundredweight a bag, six hundred bags a night, and tonight I am one short.',
      knows: ['okafor', 'ledoux'],
      aboutLine: 'Comes for salt. You learn a person by how much they carry.',
      leadLine: 'The missing bag was carried out on a shoulder and the shoulder went up the lane toward',
      spentLine: 'The kilns need feeding. You do not.' },
    { id: 'fry', at: 'seamen', name: 'Brother Fry', role: 'warden, Seamen’s Mission',
      intro: 'Fry. Forty cots and a stove. I count them in at ten and I count them in the morning, and the numbers are not always the same.',
      knows: ['tilda', 'keeper', 'hollis'],
      aboutLine: 'Sleeps here sometimes, when there is nowhere else. You learn a person by what they dream about aloud.',
      leadLine: 'A man came in at four with his boots full of water and went out again at five without his bundle. He went toward',
      spentLine: 'The men are sleeping. Lower your voice and go.' },
  ],

  items: [
    { id: 'item:salt:autopsy-cert', at: 'morgue', kind: 'report', label: 'Death certificate, first draft', stamp: 'CONFIDENTIAL',
      source: 'HARBOUR MORGUE · CERTIFICATES', title: 'Certificate of death, Bask, A.',
      fields: [['Cause', 'drowning (struck through)'], ['Cause, amended', 'wound, left side, upward'], ['Signed', 'I. Fenn, M.D.'], ['Time signed', 'before the body was cold']],
      body: ['She wrote drowning, and then she wrote the truth over it. The morgue attendant watched her write both and remembers the hand.'],
      spoken: 'A death certificate with drowning struck through and the truth written over it.',
      reading: 'Kite watched her write it. Ask him about the doctor.', about: ['fenn'], effect: { type: 'suspectTrait', suspectId: 'fenn' } },
    { id: 'item:salt:salt-bag', at: 'saltworks', kind: 'report', label: 'Bag count, night of the 11th',
      source: 'THE SALT WORKS · TALLY', title: 'Kiln 3, night tally',
      body: ['Six hundred bagged, five hundred and ninety-nine on the pallet. The one that walked was a hundredweight, and the man who carried it did not use a cart.', 'It takes a certain kind of back to walk off with a hundredweight of salt.'],
      spoken: 'The salt works tally, one bag short, and no cart used to carry it.',
      reading: 'One bag of salt walked out on somebody’s shoulder. Colour, and a thought about backs.', effect: { type: 'none' } },
    { id: 'item:salt:ballot', at: 'hall', kind: 'note', label: 'Draft ballot, Thursday’s vote',
      source: 'LONGSHOREMEN’S HALL · BACK OFFICE', title: 'Ballot, for the office of chairman',
      body: ['Two names typed. One name crossed out in pen so hard the nib split. The name crossed out is the dead man’s. The name left is not the vice-chair’s.'],
      spoken: 'A draft ballot with the dead man’s name crossed out hard enough to split the nib.',
      reading: 'Somebody other than Hollis expected to win. Story.', about: ['hollis'], effect: { type: 'none' } },
    { id: 'item:salt:manifest', at: 'customs', kind: 'ledger', label: 'Manifest, six weeks sat on', stamp: 'COPY',
      source: 'THE CUSTOMS HOUSE · INSPECTIONS', title: 'Manifest, SS Corvina',
      body: ['Every page initialled E.W. — passed without inspection. On the last page, a second set of initials in a different ink, added tonight, over hers.', 'Aldous watched the second hand write.'],
      spoken: 'The manifest Customs sat on for six weeks, with a second set of initials added tonight.',
      reading: 'Aldous saw who added the initials. Ask him about Wren.', about: ['wren'], effect: { type: 'suspectTrait', suspectId: 'wren' } },
    { id: 'item:salt:wireless', at: 'marconi', kind: 'note', label: 'Wireless log, the 11th',
      source: 'MARCONI STATION · TRAFFIC LOG', title: 'Traffic, night of the 11th',
      body: ['01:04 — to trawler MARIE-LOUISE — STOP AT THE USUAL. 01:06 — reply — UNDERSTOOD. 03:12 — MARIE-LOUISE — ALL DONE.', 'The operator has underlined the third line twice.'],
      spoken: 'The wireless log: stop at the usual, understood, and at three, all done.',
      reading: 'A boat was told where to stop. The operator knows where the usual is.', about: ['ledoux'], effect: { type: 'lead' } },
    { id: 'item:salt:knife', at: 'pawnshop', kind: 'ticket', label: 'Pawn ticket, one knife',
      source: 'LUNDY’S PAWN · TICKETS', title: 'Ticket no. 3391',
      fields: [['Item', 'knife, rigging, bone handle'], ['Pledged', 'the 9th'], ['Redeemed', 'the 11th, midnight, cash'], ['By', 'not the pledger']],
      body: ['Pledged by one hand and redeemed by another. Ma Lundy looked hard at the second pair of hands.'],
      spoken: 'A pawn ticket for a rigging knife, redeemed at midnight by somebody who did not pledge it.',
      reading: 'Ma Lundy looked at the hands that took the knife. Ask her.', effect: { type: 'lead' } },
    { id: 'item:salt:voice', at: 'printers', kind: 'clipping', label: 'The Docker’s Voice, pulled notice',
      source: 'THE DOCKER’S VOICE · PROOF', title: 'Notice, pulled before press',
      body: ['“The Chairman will address the membership Thursday on the matter of the Corvina and the trawler berths. Members are asked to attend.” Set in type, proofed, pulled at midnight.', 'Somebody did not want three thousand men to hear about the berths.'],
      spoken: 'A notice pulled from the union paper at midnight, about the trawler berths.',
      reading: 'Bask was going to talk about the berths. A motive for half the harbour.', about: ['ledoux', 'salvi'], effect: { type: 'none' } },
    { id: 'item:salt:tide-table', at: 'harbourmaster', kind: 'ledger', label: 'Tide and movements log', stamp: 'COPY',
      source: 'HARBOURMASTER’S OFFICE · LOG', title: 'Movements, night of the 11th',
      body: ['23:10 — MARIE-LOUISE out, no cargo. 03:05 — MARIE-LOUISE in, riding low. High water 01:40. The clerk has written “low?” beside the return and underlined it.'],
      spoken: 'The movements log: a trawler out at eleven with nothing, and back at three riding low.',
      reading: 'A boat came back heavier than it left. Story.', about: ['ledoux'], effect: { type: 'none' } },
    { id: 'item:salt:lamp-letter', at: 'raskhouse', kind: 'letter', label: 'A letter kept in a drawer', stamp: 'PERSONAL',
      source: 'THE RASK HOUSE · WRITING DESK', title: 'To Tilda, 1941, never sent',
      body: ['“Tilda — if I go in the water it was not the water. Ask Bask. He knows who, and he knows why, and he will not say until it suits him. — Ambrose.”', 'Seven years in a drawer. The paper is soft from being held.'],
      spoken: 'A letter from the widow’s husband, written in 1941 and kept seven years.',
      reading: 'She has known for seven years that Bask knew. A motive, and a grief.', about: ['tilda'], effect: { type: 'none' } },
    { id: 'item:salt:keeper-log', at: 'light', kind: 'note', label: 'Keeper’s log, Grieve Point',
      source: 'GRIEVE POINT LIGHT · LOG', title: 'Night of the 11th',
      body: ['01:30 — dinghy, no light, toward the pier. 02:20 — dinghy returns. Two aboard going, one coming back. The entry is in the keeper’s hand and then crossed out in the keeper’s hand.'],
      spoken: 'The keeper’s log: a dinghy with two aboard going out, and one coming back. Crossed out.',
      reading: 'Garrow saw it and unsaw it. Story, and a nasty one.', about: ['keeper'], effect: { type: 'none' } },
    { id: 'item:salt:rope-sale', at: 'chandler', kind: 'receipt', label: 'Sales book, forty feet of line',
      source: 'VETCH & SON · SALES', title: 'The 11th, evening',
      fields: [['Item', 'line, quarter-inch, 40 ft'], ['Also', 'sailmaker’s needle, one'], ['Paid', 'double, for quiet'], ['Signed', 'B.O.']],
      body: ['Line and a needle: what you buy to sew a pocket shut. Signed by the chandler himself, in his own book, which is the strange part. Young Vetch watched him do it.'],
      spoken: 'The chandler’s sales book: forty feet of line and a sailmaker’s needle, signed B.O.',
      reading: 'Okafor sold the thread that sewed the pockets, or bought it from himself. Vetch knows the hand.', about: ['okafor'], effect: { type: 'suspectTrait', suspectId: 'okafor' } },
    { id: 'item:salt:shipping-wire', at: 'shipping', kind: 'telegram', label: 'Cable, Salvi Shipping',
      source: 'WESTERN UNION · HARBOUR OFFICE', title: 'Cable, to N. Salvi',
      body: ['STRIKE VOTE THURSDAY STOP IF IT PASSES WE ARE FINISHED STOP DO WHAT YOU MUST STOP'],
      spoken: 'A cable to Salvi: if the strike vote passes we are finished. Do what you must.',
      reading: 'Somebody told Salvi to do what he must. A motive on a form.', about: ['salvi'], effect: { type: 'none' } },
    { id: 'item:salt:dues', at: 'bank', kind: 'ledger', label: 'Union account, withdrawals',
      source: 'HARBOUR SAVINGS · LEDGER', title: 'Longshoremen’s Local, account 40',
      body: ['A withdrawal of four hundred dollars on the 10th, on a slip signed by the vice-chair. The teller remembers him signing, and what he did with the pen after.'],
      spoken: 'The union account: four hundred dollars out on the tenth, signed by the vice-chair.',
      reading: 'The teller watched Hollis sign. Something about him is in the notebook now.', about: ['hollis'], effect: { type: 'suspectTrait', suspectId: 'hollis' } },
    { id: 'item:salt:x-ray', at: 'hospital', kind: 'photo', label: 'Plate, the wound',
      source: 'SEAMEN’S INFIRMARY · RADIOGRAPHY', title: 'Plate 2: left side, the deceased',
      body: ['The blade went in under the ribs and up, toward the heart, from below. You do that from a crouch, or from a boat lower than the pier, or you do it as somebody who knows exactly where to put it.'],
      spoken: 'A radiograph of the wound: under the ribs and upward, from below.',
      reading: 'Upward from below: a boat, a crouch, or a surgeon. Story that points several ways.', about: ['fenn'], effect: { type: 'none' } },
    { id: 'item:salt:cot-book', at: 'seamen', kind: 'ledger', label: 'Mission cot book',
      source: 'SEAMEN’S MISSION · COTS', title: 'Night of the 11th',
      body: ['Cot 31: in at ten, out at four, in at five, out at six. No name. Brother Fry has written “wet” in the margin and nothing else.'],
      spoken: 'The mission cot book: somebody in and out all night, and the word “wet” in the margin.',
      reading: 'Somebody went in the water and came back to dry off. Story.', effect: { type: 'none' } },
    { id: 'item:salt:tram-ticket', at: 'tram', kind: 'ticket', label: 'Tram ticket, last car',
      source: 'HARBOUR TRAMWAYS', title: 'Ticket, punched 12:02 AM',
      body: ['Punched at two minutes past midnight on the last car along the quay, and dropped on the step where a person stands who intends to get off before the stop.'],
      spoken: 'A tram ticket punched at two minutes past midnight, dropped on the step.',
      reading: 'Story. The conductor remembers who stood on the step.', effect: { type: 'none' } },
    { id: 'item:salt:drydock-chalk', at: 'drydock', kind: 'note', label: 'Chalk on the hull',
      source: 'NUMBER FOUR DRYDOCK · THE HULL', title: 'Chalked on the plates',
      body: ['BASK KNEW — in letters a foot high, chalked on the hull in the night, and half washed off by the rain. Below it, smaller: SO DO WE.', 'The night man swears it was not there at ten.'],
      spoken: 'Chalk on the drydock hull, a foot high: Bask knew. So do we.',
      reading: 'The harbour is talking to itself. Story.', effect: { type: 'none' } },
    { id: 'item:salt:locker', at: 'baths', kind: 'ticket', label: 'Bath locker tag, unclaimed',
      source: 'HARBOUR BATHS · LOCKERS', title: 'Tag no. 17',
      body: ['A coat with something heavy sewn into the lining, left in locker seventeen and not claimed. Nell Harrow cut the lining. What was in it is in your hand: a key, stamped with the name of a store.'],
      spoken: 'A locker tag, an unclaimed coat, and a key sewn into the lining.',
      reading: 'The key opens something in this harbour. It is marked.', effect: { type: 'lead' } },
    { id: 'item:salt:needle', at: 'ropewalk', kind: 'report', label: 'Needle count, the Ropewalk',
      source: 'THE ROPEWALK · STORES', title: 'Sailmaker’s needles, stores check',
      body: ['One needle, size 14, missing from the rack since the 10th. It is the size you would use on a coat, not a sail. The storesman says a man came in for it who did not know what size to ask for and asked for “the big one”.'],
      spoken: 'A needle count at the Ropewalk: one size fourteen missing since the tenth.',
      reading: 'Somebody who does not sew bought a needle. Story.', effect: { type: 'none' } },
    { id: 'item:salt:net-tag', at: 'trawler', kind: 'ticket', label: 'Net tag, Marie-Louise',
      source: 'THE TRAWLER BERTHS · NETS', title: 'Tag, net 6, MARIE-LOUISE',
      body: ['A net tag from Ledoux’s boat, found in the water at Pier Nine, two hundred yards from where the Marie-Louise ties up. Nets do not walk. The skipper’s hand is on the tag; the deckhand knows it.'],
      spoken: 'A net tag from the Marie-Louise, found in the water off Pier Nine.',
      reading: 'Pell has watched Ledoux write those tags for years. Ask him.', about: ['ledoux'], effect: { type: 'suspectTrait', suspectId: 'ledoux' } },
    { id: 'item:salt:cannery-shift', at: 'cannery', kind: 'ledger', label: 'Shift sheet, Narrows Cannery',
      source: 'NARROWS CANNERY · SHIFTS', title: 'Night shift, the 11th',
      body: ['Forty names on the sheet and thirty-eight men on the line, the foreman says. Two clocked in and never came to the floor. Their cards were punched by the same hand.'],
      spoken: 'A shift sheet with two men clocked in who never came to the line.',
      reading: 'Two alibis were manufactured at the cannery. Story.', effect: { type: 'none' } },
    { id: 'item:salt:ice-order', at: 'icehouse', kind: 'receipt', label: 'Ice order, three in the morning',
      source: 'THE ICE HOUSE · ORDERS', title: 'Order, 3:00 AM',
      fields: [['Ice', 'two blocks'], ['For', 'Salvi Shipping'], ['Cart', 'none — carried'], ['Paid', 'cash']],
      body: ['Two blocks of ice at three in the morning for a shipping office that has no fish. The foreman wrote it up and did not ask.'],
      spoken: 'An ice order at three in the morning for a shipping office with no fish.',
      reading: 'Salvi wanted something kept cold. A thought, not a fact.', about: ['salvi'], effect: { type: 'none' } },
    { id: 'item:salt:chalk-name', at: 'chapel', kind: 'note', label: 'A name in chalk on the brass',
      source: 'FISHERMEN’S CHAPEL · THE BRASS', title: 'Added this week',
      body: ['AUREL BASK, in chalk, under the names of the drowned, written before the tide gave him up. Whoever wrote it knew he was in the water before anyone else did.'],
      spoken: 'Bask’s name in chalk on the chapel brass, written before the tide gave him up.',
      reading: 'Somebody knew he was drowned before he was found. Story, and a cold one.', effect: { type: 'none' } },
    { id: 'item:salt:coastguard-fix', at: 'coastguard', kind: 'report', label: 'Coastguard fix, dinghy',
      source: 'COASTGUARD · WATCH LOG', title: 'Fix, 02:30',
      body: ['Dinghy, no light, bearing from the tower, beached below the old salt stair. The watch took a fix and marked the chart. The mark is a place, and you can walk to it.'],
      spoken: 'A coastguard fix on a dinghy with no light, beached below the old salt stair.',
      reading: 'The chart says where it landed. Go and look.', effect: { type: 'lead' } },
    { id: 'item:salt:ferry-manifest', at: 'slip', kind: 'ticket', label: 'Ferry passenger count',
      source: 'FERRY SLIP · COUNT', title: 'Last crossing, the 11th',
      body: ['Eleven across, ten back. The steward counts heads, not names, and he counted a coat going over that did not come home.'],
      spoken: 'The ferry count: eleven across and ten back.',
      reading: 'One passenger did not return. It costs you an hour to find out it was a fisherman asleep in the shed.', effect: { type: 'time', hours: 1 } },
    { id: 'item:salt:cafe-tab', at: 'excise', kind: 'receipt', label: 'Bask’s tab, the Dockside',
      source: 'DOCKSIDE CAFÉ · TABS', title: 'A. Bask — twenty years',
      body: ['Tea, every morning, a penny. The last line is the 10th. Under it, in Nan’s hand: “Sat with D.H. an hour. Left angry. D.H. stayed.” The cabman outside remembers where D.H. went, and knows a quick way there.'],
      spoken: 'Bask’s café tab: tea every morning for twenty years, and a last line about who he sat with.',
      reading: 'A last argument, and a cabman who knows the shortcuts. Time saved.', about: ['hollis'], effect: { type: 'time', hours: -2 } },
  ],

  epilogue: {
    win: `You make the arrest at the Hall, an hour before the vote, in front of three hundred
      longshoremen who go very quiet all at once. Somebody at the back starts clapping and
      thinks better of it. The tide comes in. It always does.`,
    loss: `Thursday comes. They elect a new boss, and the new boss says all the right things
      about Aurel Bask. The salt goes into an evidence locker, and the file goes into a drawer,
      and the harbour goes back to being a place where nobody saw anything.`,
  },
};

export default def;
