import type { CaseDef } from '../../types/game-types';
import { SALT_CLUES } from './salt-clues';

// Salt and Silence. The Harbour District: thirty locations from Customs Row
// down to the Narrows, twenty people who will talk if you do not ask like
// police, and twenty-six documents the tide did not take.

const def: CaseDef = {
  id: 'salt',
  title: 'Salt and Silence',
  subtitle: 'The Harbour District · February 1948',
  tagline: 'The union boss came out of the bay with his pockets sewn shut and full of salt.',
  victim: 'Aurel Bask',
  scene: 'pier9',
  difficultyHint: 'Tight streets, fast tongues.',
  publicTraits: ['build', 'hair'],
  traitPool: ['hand', 'mark', 'vice', 'scent', 'shoe'],

  briefing: `Low tide at Pier Nine gives up Aurel Bask. Twenty years head of the longshoremen.
    Thirty hours dead. Somebody sewed his coat pockets shut and filled them with rock salt.
    That is not how you sink a man. That is how you tell three thousand dockers what happens
    to one who talks. The wound is under the ribs. It went up.
    Half this harbour wanted him gone. The other half worked for him. Nobody here talks to
    police. Do not ask like police.`,

  radio: [
    'Harbour Station. Do not go to Pier Nine alone. Do not go in uniform.',
    'The union votes Thursday. Every candidate is on your list.',
    'Customs has sat on a manifest for six weeks. Lean on them.',
  ],

  terrain: {
    sea: true, seaName: 'THE NARROWS', river: false, parks: 1,
    districts: [
      { text: 'CUSTOMS ROW', x: 450, y: 10, rot: -2 },
      { text: 'THE HALL', x: 760, y: 120, rot: 2 },
      { text: 'GRIEVE POINT', x: 1000, y: 90, rot: 4 },
      { text: 'THE SALT YARDS', x: 230, y: 620, rot: -3 },
      { text: 'THE NARROWS', x: 800, y: 600, rot: 2 },
    ],
  },

  locations: [
    // ---- Customs Row
    { id: 'pier9', name: 'Pier Nine', type: 'docks', x: 250, y: 170, district: 'Customs Row', desc: 'Where they found him. Still taped off. Still stinking.' },
    { id: 'harbourmaster', name: 'Harbourmaster’s Office', type: 'office', x: 300, y: 60, district: 'Customs Row', desc: 'Every boat in and out, in a steady hand. The clerk’s is not.' },
    { id: 'customs', name: 'The Customs House', type: 'bank', x: 470, y: 110, district: 'Customs Row', desc: 'Every crate in this harbour is a line in a ledger here. Most lines are lies.' },
    { id: 'marconi', name: 'Marconi Station', type: 'radio', x: 640, y: 60, district: 'Customs Row', desc: 'Every wireless message on the water. One operator who writes them all down twice.' },
    { id: 'excise', name: 'Dockside Café', type: 'cafe', x: 380, y: 240, district: 'Customs Row', desc: 'Tea, tobacco, and the only warm room between the Row and the Hall.' },
    { id: 'bondstore', name: 'Bond Store 12', type: 'warehouse', x: 560, y: 220, district: 'Customs Row', desc: 'Six weeks of crates nobody has opened. One seal somebody has.' },
    { id: 'pawnshop', name: 'Lundy’s Pawn', type: 'shop', x: 60, y: 250, district: 'Customs Row', desc: 'Sextants, wedding rings, and one knife with a very particular handle.' },
    // ---- The Hall
    { id: 'hall', name: 'Longshoremen’s Hall', type: 'office', x: 720, y: 160, district: 'The Hall', desc: 'Folding chairs, a dead man’s photograph, and an election on Thursday.' },
    { id: 'printers', name: 'The Docker’s Voice', type: 'press', x: 800, y: 60, district: 'The Hall', desc: 'The union paper. Set by hand. Read by three thousand. Believed by most.' },
    { id: 'station', name: 'Harbour Station', type: 'police', x: 480, y: 330, district: 'The Hall', desc: 'Two desks, one cell, a radiator that screams.' },
    { id: 'chandler', name: 'Vetch & Son, Chandlers', type: 'shop', x: 650, y: 330, district: 'The Hall', desc: 'Rope, oil, and every hook a man could need.' },
    { id: 'shipping', name: 'Salvi Shipping', type: 'office', x: 780, y: 300, district: 'The Hall', desc: 'Three companies. One office. One lamp always on.' },
    { id: 'bank', name: 'Harbour Savings', type: 'bank', x: 560, y: 440, district: 'The Hall', desc: 'Where the dues go. Where they sometimes come from.' },
    { id: 'hospital', name: 'Seamen’s Infirmary', type: 'hospital', x: 760, y: 480, district: 'The Hall', desc: 'Dr. Fenn’s wards. Certificates are written fast here.' },
    // ---- Grieve Point
    { id: 'light', name: 'Grieve Point Light', type: 'light', x: 920, y: 240, district: 'Grieve Point', desc: 'One keeper, one lamp, the best view of who comes in at night.' },
    { id: 'raskhouse', name: 'The Rask House', type: 'manor', x: 1040, y: 150, district: 'Grieve Point', desc: 'Grey shingles on the point. The widow keeps a lamp lit for a man seven years drowned.' },
    { id: 'chapel', name: 'Fishermen’s Chapel', type: 'church', x: 1000, y: 380, district: 'Grieve Point', desc: 'Names of the lost on brass. One added this week in chalk.' },
    { id: 'coastguard', name: 'Coastguard Tower', type: 'tower', x: 1060, y: 520, district: 'Grieve Point', desc: 'A log of every hull that crosses the Narrows after dark. Most of those are lies too.' },
    { id: 'icehouse', name: 'The Ice House', type: 'warehouse', x: 870, y: 450, district: 'Grieve Point', desc: 'Cold enough to keep a body honest.' },
    // ---- The Salt Yards
    { id: 'brine', name: 'The Brine & Bell', type: 'bar', x: 170, y: 340, district: 'The Salt Yards', desc: 'Sawdust, rum, forty men who saw nothing.' },
    { id: 'seamen', name: 'Seamen’s Mission', type: 'home', x: 80, y: 460, district: 'The Salt Yards', desc: 'Forty cots, a stove, and a warden who counts who does not come back.' },
    { id: 'tram', name: 'Quay Tram Stop', type: 'tram', x: 420, y: 420, district: 'The Salt Yards', desc: 'The last car along the quay at midnight. The conductor punches faces, not tickets.' },
    { id: 'drydock', name: 'Number Four Drydock', type: 'factory', x: 330, y: 490, district: 'The Salt Yards', desc: 'A hull the size of a church, propped on stilts.' },
    { id: 'baths', name: 'Harbour Baths', type: 'bathhouse', x: 170, y: 580, district: 'The Salt Yards', desc: 'Steam and tile. The only place in the district nobody wears a coat.' },
    { id: 'saltworks', name: 'The Salt Works', type: 'factory', x: 240, y: 700, district: 'The Salt Yards', desc: 'Rock salt bagged by the hundredweight. Nobody counts the bags.' },
    { id: 'ropewalk', name: 'The Ropewalk', type: 'warehouse', x: 500, y: 650, district: 'The Salt Yards', desc: 'A quarter mile of shed. A needle for every thickness of line.' },
    // ---- The Narrows
    { id: 'trawler', name: 'The Trawler Berths', type: 'docks', x: 620, y: 570, district: 'The Narrows', desc: 'Nets, gulls, and boats that go out empty and come back heavy.' },
    { id: 'cannery', name: 'Narrows Cannery', type: 'factory', x: 760, y: 700, district: 'The Narrows', desc: 'Still running. On fish nobody catches.' },
    { id: 'morgue', name: 'Harbour Morgue', type: 'morgue', x: 900, y: 620, district: 'The Narrows', desc: 'Bask is on the third slab. The salt is in a bag beside him.' },
    { id: 'slip', name: 'Ferry Slip', type: 'pier', x: 1120, y: 680, district: 'The Narrows', desc: 'The only way off the point that does not pass the tower.' },
  ],
  edges: [
    ['pier9', 'harbourmaster'], ['pier9', 'pawnshop'], ['pier9', 'brine'], ['pier9', 'customs'],
    ['harbourmaster', 'customs'],
    ['customs', 'marconi'], ['customs', 'bondstore'], ['customs', 'excise'],
    ['marconi', 'hall'], ['marconi', 'printers'],
    ['hall', 'printers'], ['hall', 'shipping'], ['hall', 'bondstore'], ['hall', 'light'],
    ['printers', 'raskhouse'],
    ['light', 'raskhouse'], ['light', 'chapel'], ['light', 'shipping'],
    ['raskhouse', 'chapel'],
    ['chapel', 'coastguard'], ['chapel', 'icehouse'],
    ['coastguard', 'slip'], ['coastguard', 'morgue'],
    ['excise', 'station'], ['excise', 'brine'],
    ['bondstore', 'station'], ['bondstore', 'chandler'],
    ['station', 'tram'], ['station', 'chandler'], ['station', 'bank'],
    ['chandler', 'shipping'], ['chandler', 'hospital'],
    ['shipping', 'hospital'],
    ['hospital', 'icehouse'], ['hospital', 'trawler'],
    ['icehouse', 'morgue'],
    ['brine', 'seamen'], ['brine', 'tram'], ['brine', 'drydock'],
    ['seamen', 'baths'],
    ['pawnshop', 'seamen'],
    ['tram', 'drydock'], ['tram', 'bank'],
    ['bank', 'trawler'], ['bank', 'ropewalk'],
    ['drydock', 'baths'], ['drydock', 'ropewalk'],
    ['baths', 'saltworks'],
    ['saltworks', 'ropewalk'],
    ['ropewalk', 'trawler'],
    ['trawler', 'cannery'],
    ['cannery', 'morgue'], ['cannery', 'slip'],
    ['morgue', 'slip'],
  ],
  start: 'station',

  suspects: [
    { id: 'hollis', name: 'Dov Hollis', role: 'Union vice-chair',
      traits: { build: 'tall', hair: 'dark' },
      blurb: 'Second in command of the union for eleven years. From Thursday, the boss.',
      motive: 'because second chair for eleven years is its own kind of sentence.',
      bio: 'Fifty-one. Loaded ships for twenty years, then ran the union’s elections. Bask’s right-hand man, and the man Bask never let take over. Everybody likes Dov. Nobody follows him.',
      alibi: 'At the union hall until midnight with the election committee. Then home. His wife will confirm it.',
      secret: 'He took four hundred dollars from the union account on the 10th to pay off a man who planned to run against him. The man took the money and ran anyway.',
      opinions: { wren: 'Etta Wren signs whatever she’s told to sign. She has a neat hand for it.', okafor: 'Bernard owes money to everyone and pays nobody. Bask called in his debt. That was cruel.', salvi: 'Salvi buys people. He bought half the union hall. He never tried to buy me. He never even offered.', tilda: 'Tilda Rask has hated Bask for seven years and me for eleven. She’s fair about it.', keeper: 'Garrow sees everything from the lighthouse. He has never given evidence about any of it.', fenn: 'The doctor and Bask were closer than the harbour knows. I knew.', ledoux: 'Ledoux goes out empty and comes back full. Bask was writing it all down. I told him not to.' },
      topics: [
        { id: 'night', q: 'Where were you on the night of the 11th?', a: 'At the union hall until midnight, with the election committee. Then home. My wife will confirm it.' },
        { id: 'chair', q: 'You were second in command for eleven years. On Thursday you become the boss.', a: 'Only because he’s dead. I didn’t want it this way. I wanted him to step down and shake my hand.' },
        { id: 'money', q: 'Four hundred dollars came out of the union account on the 10th, with your signature.', a: 'He rubs his face. I paid a man to stand down from the election. He took the money and ran against me anyway. I stole from the union and I still lost. Print that.', after: 'chair', cost: 1, effect: { type: 'suspectTrait', suspectId: 'hollis' } },
        { id: 'berths', q: 'Bask was going to make a speech about the trawler berths.', a: 'He was going to name Ledoux, Salvi and the Corvina out loud, in front of three thousand men. I told him to wait until after the vote. He said the vote was the whole point.', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'What was Bask like?', a: 'Hard. Fair. He never forgave anything. He knew who put Ambrose Rask in the bay, and he kept it to himself for seven years like a coin in his pocket.' },
      ] },
    { id: 'wren', name: 'Etta Wren', role: 'Customs inspector',
      traits: { build: 'slight', hair: 'dark' },
      blurb: 'Customs inspector. She approved six weeks of crates without opening one.',
      motive: 'because the manifest he was carrying had her signature on every page.',
      bio: 'Thirty-nine. The first woman inspector in the harbour. She cannot afford a single mistake, so on paper she never makes one. Her initials are on every page of the Corvina manifest. She opened none of the crates.',
      alibi: 'Working late at the Customs House. The clerk saw her leave at eleven.',
      secret: 'Salvi pays her two hundred dollars a month to sign without looking. She has kept every dollar in an envelope for two years and never spent one.',
      opinions: { hollis: 'Hollis is an honest man in a job with no room for one.', okafor: 'Okafor sells rope to the Corvina’s crews and pretends not to know what they tie up with it.', salvi: 'Salvi is polite. Salvi pays on time. Salvi is the worst thing in this harbour.', tilda: 'The widow came to the Customs House in 1941 with a question about a boat. Nobody answered her. I was a clerk then. I didn’t answer either.', keeper: 'Garrow writes down what he’s paid to and crosses out the rest. He and I are the same, and I hate him for it.', fenn: 'Dr. Fenn signed my father’s death certificate. Quickly, and correctly. I owe her for that.', ledoux: 'Ledoux’s boat is listed on my manifests as a fishing vessel. I have never seen a fish on it.' },
      topics: [
        { id: 'night', q: 'Where were you on the 11th?', a: 'At the Customs House until eleven. Aldous, the clerk, saw me leave. Then home. I live alone.' },
        { id: 'manifest', q: 'Six weeks of crates. Every page signed by you. Not one crate opened.', a: 'That’s right. I sign. I don’t open. Ask me why and I’ll tell you, and then I won’t have a job.' },
        { id: 'why', q: 'Tell me why.', a: 'She takes a breath. Salvi pays me two hundred dollars a month. It’s in an envelope in my flat, every dollar of it. I’ve never spent any. I don’t know what I was keeping it for. Evidence, maybe.', after: 'manifest', cost: 1, effect: { type: 'suspectTrait', suspectId: 'wren' } },
        { id: 'second', q: 'A second set of initials was added to the manifest tonight, over yours.', a: 'Not by me. Somebody wanted it to look as if I had approved the crate a second time. Somebody who knows my initials but not my pen.', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Did Bask come to see you?', a: 'On the 9th. He asked to see the Corvina manifest. I showed him. He read it and said: Etta, your name is on this. I said: I know.' },
      ] },
    { id: 'okafor', name: 'Bernard Okafor', role: 'Chandler, Vetch & Son',
      traits: { build: 'broad', hair: 'grey' },
      blurb: 'Sells rope. Keeps a list of who buys it.',
      motive: 'because the debt was called in, and he had nothing left to pay it with.',
      bio: 'Fifty-eight. Runs the ship’s chandlery for old Vetch, who has not been in the shop since 1944. He owed Bask two thousand dollars from a boat that sank. Bask demanded the money on the 9th.',
      alibi: 'Closed the shop at eight. At the Dockside Café until ten. Then home, alone.',
      secret: 'He sold forty feet of line and a sailmaker’s needle on the 11th and signed his own initials in the sales book, because the buyer put a hand on his and told him to.',
      opinions: { hollis: 'Dov is a decent man. Decent men don’t run harbours.', wren: 'Miss Wren buys nothing from me. Inspectors don’t need rope.', salvi: 'Salvi’s crews buy the best rope, pay in cash, and never come back for the same length twice.', tilda: 'Mrs. Rask buys lamp oil every week for a lamp nobody needs. I don’t charge her.', keeper: 'Garrow buys nothing. The lighthouse supplies him. He comes in to talk. He talks about 1941.', fenn: 'The doctor bought a scalpel from me once because the hospital had run out. A strange thing for a hospital to run out of.', ledoux: 'Ledoux buys rope by the hundred feet and never buys nets. Work that out for yourself.' },
      topics: [
        { id: 'night', q: 'Where were you on the 11th?', a: 'I shut the shop at eight. The Dockside Café until ten. Then home. Nobody can confirm it.' },
        { id: 'debt', q: 'You owed Bask two thousand dollars.', a: 'For a boat that sank in 1945 with everything I had on it. He lent me the money for it. On the 9th he demanded it back. I told him I couldn’t pay. He said he knew that.' },
        { id: 'line', q: 'Forty feet of line and a sailmaker’s needle, signed B.O. in your own sales book.', a: 'He closes his eyes. A man came in at closing time. Big. He put his hand over mine and said: sign it yourself. So I did. I sell rope. I didn’t sew anything.', after: 'debt', cost: 1, effect: { type: 'suspectTrait', suspectId: 'okafor' } },
        { id: 'man', q: 'Describe the man.', a: 'He had a scar across his thumb. He kept that hand turned away. He smelled of the ice house.', after: 'line', cost: 1, effect: { type: 'lead' } },
      ] },
    { id: 'salvi', name: 'Nunzio Salvi', role: 'Shipping agent',
      traits: { build: 'slight', hair: 'dark' },
      blurb: 'Shipping agent. Three companies, one office, no employees.',
      motive: 'because a strike would have cost him a season he could not afford to lose.',
      bio: 'Forty-five. Agent for the Corvina and two other ships that exist only on paper. He owes money in three ports. A strike on Thursday would finish him.',
      alibi: 'In his office all night doing accounts. The lamp was on.',
      secret: 'He ordered two blocks of ice at three in the morning for something in his back room that had to be kept cold. It was not fish. It was not Bask, either.',
      opinions: { hollis: 'Hollis will make a fine chairman. Reasonable. I like reasonable.', wren: 'Miss Wren is a professional. I admire professionals.', okafor: 'Okafor is in debt. Men in debt are useful. That isn’t a crime.', tilda: 'The widow blames everyone for a boat that sank before I ever came here.', keeper: 'Garrow is a public servant. I make contributions to public servants.', fenn: 'The doctor can’t be bought. I’ve checked.', ledoux: 'Ledoux fishes. What he catches is his business, and mine.' },
      topics: [
        { id: 'night', q: 'Where were you on the 11th?', a: 'In my office, doing the accounts. The lamp was on until dawn. Anyone on the quay can tell you.' },
        { id: 'strike', q: 'A strike on Thursday would finish you.', a: 'A strike would finish everybody. I’m nothing special. I have three ships and two of them only exist on paper. If the berths close, I’m a man with an office and nothing in it.' },
        { id: 'cable', q: '‘Do what you must.’ A telegram, sent to you.', a: 'From my partner in Marseille. He meant: settle with the union. He didn’t mean what you think. I didn’t do what you think.', after: 'strike', cost: 1, effect: { type: 'suspectTrait', suspectId: 'salvi' } },
        { id: 'ice', q: 'You ordered two blocks of ice at three in the morning.', a: 'For the back room. For cargo. Cargo that spoils. He looks at the door. It wasn’t Bask, if that’s what you’re asking. Bask was already in the water by then.', cost: 1, effect: { type: 'lead' } },
        { id: 'usual', q: '‘Stop at the usual place.’ That message went out from your office.', a: 'I don’t know what it means. He does know. He’s a bad liar and a good agent, which is a poor combination in a harbour.' },
      ] },
    { id: 'tilda', name: 'Tilda Rask', role: 'Widow of the last boss',
      traits: { build: 'slight', hair: 'grey' },
      blurb: 'Widow of the last union boss. Her husband drowned in 1941. Nobody was ever charged.',
      motive: 'because seven years is a long time to hold a thing, and no time at all.',
      bio: 'Sixty. Her husband Ambrose ran the union before Bask. He went into the bay in 1941. Tilda has kept a lamp lit for him ever since, and a letter in a drawer.',
      alibi: 'At home in the Rask House. She never goes out after dark. Everyone on the point knows it.',
      secret: 'She did go out. She walked to the chapel at four in the morning and wrote Bask’s name under the list of the drowned before anyone knew he was dead. Somebody had told her. She will not say who.',
      opinions: { hollis: 'Dov Hollis carried my husband’s coffin and then carried Bask’s bags for eleven years.', wren: 'The girl at Customs wouldn’t look at me in 1941. She looks at me now. That’s something.', okafor: 'Bernard brings me lamp oil and won’t take money for it. It’s the kind men who drown.', salvi: 'Salvi came to this harbour in 1942. One year after Ambrose. I’ve never trusted the timing.', keeper: 'Garrow was on Ambrose’s boat. He came back. Ambrose didn’t. Draw your own line between those two facts.', fenn: 'The doctor loved Bask. Everyone thinks I don’t know. I’ve been a widow. I know what it looks like.', ledoux: 'Ledoux was a boy on my husband’s boat in 1941. He was sick over the side. He hasn’t been sick since.' },
      topics: [
        { id: 'night', q: 'Where were you on the 11th?', a: 'Here, at home. I don’t go out after dark. Everyone on the point knows that.' },
        { id: 'chalk', q: 'Bask’s name was written in chalk on the chapel plaque at four in the morning. Before his body was found.', a: 'She doesn’t blink. I went out. Somebody came to my door at three and told me he was in the water. I put my coat on, walked to the chapel, and wrote his name under Ambrose’s. I’m not sorry.', after: 'night', cost: 1, effect: { type: 'suspectTrait', suspectId: 'tilda' } },
        { id: 'who', q: 'Who came to your door?', a: 'A man with wet boots. He wouldn’t come in. I didn’t see his face. I saw his hands on my gatepost. There was a scar across the thumb.', after: 'chalk', cost: 1, effect: { type: 'lead' } },
        { id: 'letter', q: 'Tell me about the letter in your drawer, from 1941.', a: 'Ambrose wrote it the morning he went out. It says: if I end up in the water, it wasn’t the water. Ask Bask. So I asked Bask. For seven years I asked Bask.' },
      ] },
    { id: 'keeper', name: 'Mr. Garrow', role: 'Lighthouse keeper',
      traits: { build: 'broad', hair: 'grey' },
      blurb: 'Lighthouse keeper. Sees everything from Grieve Point. Reports none of it.',
      motive: 'because he saw the boat, and then he was in it.',
      bio: 'Sixty-three. Keeper at Grieve Point for thirty years. He logs every light on the water and crosses out the ones he is paid to. He was on the boat with Ambrose Rask in 1941. He has never said what he saw.',
      alibi: 'In the lighthouse. Where else would he be.',
      secret: 'He logged a small boat at half past one: two men going out, one coming back. Then he crossed it out. Somebody paid him fifty dollars to cross it out. He has not touched the money.',
      opinions: { hollis: 'Hollis came up to the lighthouse once to ask what I saw in 1941. I told him nothing. He believed me. That’s Hollis.', wren: 'Miss Wren keeps a log by day and I keep one by night. Neither of us reads the other’s.', okafor: 'Okafor sold me a lamp glass in 1939 and has been apologising for the price ever since.', salvi: 'Salvi sends fifty dollars up to the lighthouse at Christmas. And at other times.', tilda: 'Tilda Rask has stared at this tower every night for seven years. I can feel it.', fenn: 'The doctor came up here in 1941 to sign a form. She looked at the water for a long time first.', ledoux: 'Ledoux lands under the point with no lights. I write it down. Then I cross it out. Then I write it again in a book nobody knows about.' },
      topics: [
        { id: 'night', q: 'What did you see on the 11th?', a: 'The water. A boat going out at eleven. A rowing boat at half past one. A boat coming in at three. I wrote down what I’m paid to write down.' },
        { id: 'crossed', q: 'The entry about the rowing boat is crossed out. In your handwriting.', a: 'Two men going out. One coming back. I crossed it out because fifty dollars came up the stairs the next morning. The money is on the shelf. I haven’t touched it.', after: 'night', cost: 1, effect: { type: 'suspectTrait', suspectId: 'keeper' } },
        { id: 'second', q: 'You keep a second log.', a: 'Under the floorboards. Everything since 1941. Every boat without lights. Every name I could put to one. Take it. I’ve carried it long enough.', after: 'crossed', cost: 1, effect: { type: 'lead' } },
        { id: 'rask', q: 'You were on Ambrose Rask’s boat.', a: 'I was. Ambrose went over the side. Bask was at the wheel. I was being sick in the bottom of the boat. I didn’t see who pushed him. I saw who didn’t pull him back.' },
      ] },
    { id: 'fenn', name: 'Dr. Ilse Fenn', role: 'Harbour surgeon',
      traits: { build: 'slight', hair: 'fair' },
      blurb: 'Harbour surgeon. Signed the death certificate before the body was cold. Signed it wrong.',
      motive: 'because the wound went up, and only she knew what that meant.',
      bio: 'Forty-four. Came from Hamburg in 1938. The only surgeon in the district, and the only one who will sign a certificate at three in the morning. She wrote ‘drowning’. Then she crossed it out and wrote the truth.',
      alibi: 'At the Infirmary all night. Nurse Ives will confirm it.',
      secret: 'She was Bask’s doctor and his lover. She knew the knife went upward because she had once shown him how a man is killed that way. She never thought he would need to know.',
      opinions: { hollis: 'Dov Hollis has a bad heart and a good one. I treat the first.', wren: 'Etta Wren came to me with a rash from worrying. I told her to spend the money. She didn’t.', okafor: 'Bernard Okafor hasn’t slept since 1945. I gave him something for it. He gave it back.', salvi: 'Salvi has never been ill a day in his life. Men like that are sick in other ways.', tilda: 'Tilda Rask should have been in my care years ago. Grief isn’t an illness. It’s a climate.', keeper: 'Garrow drinks. Not much. Just enough to cross things out.', ledoux: 'Ledoux’s hands shake in the mornings and not at sea. I know what that means.' },
      topics: [
        { id: 'night', q: 'Where were you on the 11th?', a: 'At the Infirmary all night. Nurse Ives will confirm it. She’ll also tell you I went out at one for an hour. She’s honest.' },
        { id: 'certificate', q: 'You wrote ‘drowning’ on the certificate. Then you wrote the truth over it.', a: 'I wrote drowning at one o’clock because that’s what it looked like. I looked again at two. The wound went upward. I wrote it down. That isn’t a crime. It’s the opposite of one.' },
        { id: 'out', q: 'Where did you go at one?', a: 'She looks at her hands. To the pier, to see him. Kite had telephoned me. I stood in the salt and looked at him for an hour. Then I came back, washed my hands, and did my job.', after: 'night', cost: 1, effect: { type: 'suspectTrait', suspectId: 'fenn' } },
        { id: 'bask', q: 'What was Bask to you?', a: 'A patient. Then more than a patient. Four years. Nobody in this harbour knew, which tells you how good the harbour is at knowing things.', after: 'out' },
        { id: 'knife', q: 'He once asked you how a man is killed with a knife under the ribs.', a: 'Over dinner, months ago. Ledoux was there too. I told them: from below, upward, toward the heart. I thought Bask was asking so he could see it coming. He didn’t see it coming. Somebody else at that table was listening better than he was.', after: 'bask', cost: 1, effect: { type: 'lead' } },
      ] },
    { id: 'ledoux', name: 'Marcel Ledoux', role: 'Trawler skipper',
      traits: { build: 'tall', hair: 'dark' },
      blurb: 'Trawler captain. Big man, scar across his left thumb. Goes out empty, comes back full.',
      motive: 'because Bask had counted the boats, and on Thursday he was going to say the Marie-Louise out loud.',
      bio: 'Forty. Captain of the Marie-Louise. Big, with a scar across his left thumb from a winch cable. He goes out with no nets and comes back low in the water. Everyone in the harbour knows. Bask had started writing it down.',
      alibi: 'At sea. Out at eleven, back at three. The harbourmaster’s log shows it.',
      secret: 'There was no ‘big one’ in the dinghy. He rowed himself to Pier Nine, killed Bask the way the doctor had once described to Bask over dinner, sewed the pockets, and rowed back alone. Salvi paid for the salt.',
      opinions: { hollis: 'Hollis never came down to the boats. Bask came every week. That’s the difference between them.', wren: 'The inspector signs. I sail. Neither of us looks in the hold.', okafor: 'Okafor sells me rope and looks at me as if I’m going to hang myself with it.', salvi: 'Salvi owns the boat. On paper the boat is mine. On paper I’m a fisherman.', tilda: 'The widow won’t look at me. I was a boy on her husband’s boat. I was seasick. That’s all I did.', keeper: 'Garrow sees me land every time. He has never said a word. I sent fifty dollars up his stairs and it came back down.', fenn: 'The doctor is the only person in this harbour who ever asked me if I was all right. I said yes. It wasn’t true.' },
      topics: [
        { id: 'night', q: 'Where were you on the 11th?', a: 'At sea. Out at eleven, back at three. The harbourmaster has it in the log.' },
        { id: 'empty', q: 'You went out empty and came back full.', a: 'Cargo. Off the Corvina, into the ice house. Salvi’s cargo. I don’t open it. I have a boat because I don’t open it.' },
        { id: 'dinghy', q: 'The lighthouse keeper saw a rowing boat. Two men going out, one coming back.', a: 'He’s quiet for a long time. Two men got off my boat at Pier Nine at half past eleven. One came back at half past one. I was told to wait, so I waited. I was paid not to ask questions.', after: 'empty', cost: 1, effect: { type: 'suspectTrait', suspectId: 'ledoux' } },
        { id: 'who', q: 'Who came back?', a: 'The big one. Scar across his thumb. Wet to the waist. He sat in the front of the boat and didn’t say a word all the way to the point. He got off under the lighthouse and went up the stairs.', after: 'dinghy', cost: 1, effect: { type: 'culpritTrait' } },
        { id: 'wireless', q: '‘Stop at the usual place.’', a: 'The usual place is the old salt stairs under the point. Everyone who lands without lights lands there. That’s where I dropped him off.' },
      ] },
  ],

  culprit: 'ledoux',
  clues: SALT_CLUES,

  witnesses: [
    { id: 'teague', at: 'brine', name: 'Mags Teague', role: 'landlady, the Brine & Bell',
      intro: 'Mags Teague. Forty men drink in my pub every night. I know what each one drinks and what each one owes.',
      bio: 'Thirty years behind the bar. She has buried a husband and two barmen. She keeps the tabs in her head and the grudges in a book.',
      knows: ['hollis', 'ledoux', 'tilda'],
      aboutLine: 'They drink in my pub. I could draw their face from memory.',
      leadLine: 'Somebody paid off a tab tonight that had been open since March. In coins. They came in from the direction of',
      spentLine: 'Last orders was an hour ago. That goes for questions too.',
      opinions: { hollis: 'Dov was in here from ten until one with his flask. He wasn’t celebrating. He’d lost something. Money, I think.', ledoux: 'Ledoux doesn’t drink here on the nights he sails. He wasn’t here. He was at sea, or wherever he goes instead.', tilda: 'Mrs. Rask hasn’t set foot in this pub since 1941. Sometimes she stands outside. I leave the door open.' },
      topics: [
        { id: 'night', q: 'Who was in on the 11th?', a: 'Forty men who saw nothing. Hollis with his flask. And a big man at the end of the bar who paid off a tab from March in coins and left without finishing his drink.' },
        { id: 'tab', q: 'Whose tab did he pay?', a: 'Not his own. He paid Okafor’s. Okafor wasn’t even here. The big man had a scar across his thumb and he kept that hand on the bar as if he wanted me to see it.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Did Bask drink here?', a: 'For twenty years, on the same stool. He was in on the 10th and he said: Mags, if I don’t come in tomorrow, look at who does. I laughed. I’m not laughing now.' },
      ] },
    { id: 'aldous', at: 'customs', name: 'Percy Aldous', role: 'night clerk, the Customs House',
      intro: 'Percy Aldous. I copy the shipping manifests. Every crate in this harbour crosses my desk twice: once as it really is, and once as it’s declared.',
      bio: 'Twenty-six. Copies manifests in handwriting so neat the inspectors never read them. He has read all of them.',
      knows: ['wren', 'salvi'],
      aboutLine: 'They sign my book. You notice a person’s handwriting.',
      leadLine: 'Somebody altered a manifest tonight. The ink is still wet. The crate it describes is at',
      spentLine: 'I’m a clerk. Clerks don’t know things. Please close the door.',
      opinions: { wren: 'Miss Wren left at eleven. Her initials on the manifest were dry. At midnight there were new initials, and they were wet, and they weren’t hers.', salvi: 'Mr. Salvi comes to the Customs House once a month and leaves an envelope. I copy manifests. I don’t copy envelopes.' },
      topics: [
        { id: 'night', q: 'What happened here on the 11th?', a: 'Miss Wren left at eleven. At midnight somebody let themselves in with a key and added initials to the Corvina manifest. They looked like hers. Close enough for a judge. Not close enough for me.' },
        { id: 'ink', q: 'Whose ink was it?', a: 'A fountain pen with a broad nib. Miss Wren uses a fine one. The only broad-nibbed pen I know of in this harbour is in the shipping office.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Did Bask come here?', a: 'On the 9th. He read the manifest at my desk and copied it into a little notebook. He asked me if I’d ever opened a Corvina crate. I said I was only a clerk. He said: so was I, once.' },
      ] },
    { id: 'vetch', at: 'chandler', name: 'Young Vetch', role: 'apprentice, Vetch & Son',
      intro: 'Tom Vetch. I’m the ‘Son’ on the sign. Everyone in this harbour buys rope from us. I cut it for them.',
      bio: 'Nineteen. Grandson of the name on the shop sign. He cuts rope for Okafor and watches Okafor more closely than Okafor knows.',
      knows: ['okafor', 'salvi', 'fenn'],
      aboutLine: 'A customer. I measure their rope. I’ve measured them too.',
      leadLine: 'Somebody bought forty feet of line tonight and paid double to keep it quiet. They took it to',
      spentLine: 'My dad says not to talk to police. I’ve talked enough.',
      opinions: { okafor: 'Mr. Okafor signed for the rope himself. A man had his hand on top of Mr. Okafor’s hand. I saw it from the back of the shop.', salvi: 'Salvi’s crews buy the good rope, pay cash, and never come back for the same length.', fenn: 'The doctor bought a scalpel from us last month. She said the hospital had run out. I didn’t believe her.' },
      topics: [
        { id: 'night', q: 'What did you sell on the 11th?', a: 'Forty feet of thin line and a size fourteen sailmaker’s needle. That’s for sewing a coat, not a sail. The buyer paid double to keep it quiet, and Mr. Okafor signed for it himself with the buyer’s hand on top of his.' },
        { id: 'buyer', q: 'Describe the buyer.', a: 'Big. A scar across the thumb of the hand he put on Mr. Okafor’s. His boots had been in the ice house. He never looked at me once.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Did Bask buy from you?', a: 'Every week. On the 10th he bought a padlock. A big one, for the union hall’s back office, he said. Somebody got into that office anyway.' },
      ] },
    { id: 'kite', at: 'morgue', name: 'Amos Kite', role: 'attendant, Harbour Morgue',
      intro: 'Amos Kite. I look after the dead. They’re better company than you’d think, and worse than you’d hope.',
      bio: 'Fifteen years at the morgue. He washes the bodies and reads every certificate twice. He notices when they change.',
      knows: ['fenn', 'tilda'],
      aboutLine: 'They came down to see Bask. People give themselves away when they stand over a body.',
      leadLine: 'A visitor left something in the coat room and never came back for it. It was sent on to',
      spentLine: 'I have three bodies to wash before morning. Find your own way out.',
      opinions: { fenn: 'Dr. Fenn wrote ‘drowning’ at one and went out. She came back at two with her hands washed and wrote the truth over it.', tilda: 'Mrs. Rask came at five and asked to see him. I let her. She looked at his pockets and nodded, as if something had been confirmed.' },
      topics: [
        { id: 'night', q: 'Tell me about the body.', a: 'Pockets sewn shut with sailcloth thread and a size fourteen needle. Rock salt in them, about a hundredweight between the two. The wound is under the ribs, going upward. Whoever did it was kneeling, or in a boat below him.' },
        { id: 'visitors', q: 'Who came to see him?', a: 'The doctor at one, and again at two. The widow at five. And at six, a big man who stood in the corridor and wouldn’t come in. He had a scar across his thumb, and he was crying.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'salt', q: 'Tell me about the salt.', a: 'Rock salt from the salt works, bagged. Somebody carried a hundredweight of it to the pier on his shoulder without a cart. That’s a big man, or a desperate one.' },
      ] },
    { id: 'pell', at: 'trawler', name: 'Iggy Pell', role: 'deckhand',
      intro: 'Iggy Pell. I mend nets and I keep my head down. Tonight I looked up once. That was once too many.',
      bio: 'Twenty-two. Deckhand on the Marie-Louise for two years. Nobody has ever told him what is in the hold.',
      knows: ['ledoux', 'hollis', 'keeper'],
      aboutLine: 'They work the boats. You get to know a person by how they walk on a wet deck.',
      leadLine: 'Something was thrown off a boat and it floated. It washed up near',
      spentLine: 'I told you, I keep my head down. I’m putting it back down now.',
      opinions: { ledoux: 'The skipper put two men ashore in the rowing boat and waited two hours. He smoked the whole time. He never smokes at sea.', hollis: 'Hollis came down to the boats once, in 1946. He was seasick tied up at the quay. Bask laughed at him.', keeper: 'The lighthouse keeper watches us land. He waves. Then he goes inside and writes.' },
      topics: [
        { id: 'night', q: 'What did you see from the deck?', a: 'The rowing boat go out with two men and come back with one. The skipper smoking. And something thrown off the end of the pier that floated. A bag.' },
        { id: 'bag', q: 'Where did the bag go?', a: 'With the tide, toward the salt works. It washed up on the outfall pipe. It was a coat with the pockets cut out.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'hold', q: 'What’s in the hold?', a: 'Nobody has ever told me. I’ve smelled it. It isn’t fish. It’s whatever the cannery cans when there aren’t any fish.' },
      ] },
    { id: 'harrow', at: 'baths', name: 'Nell Harrow', role: 'attendant, Harbour Baths',
      intro: 'Nell Harrow. I hand out the towels and take the tickets. Nobody has pockets in here. That’s why they talk.',
      bio: 'Has run the public baths since her father died. She hears the whole harbour with its clothes off.',
      knows: ['wren', 'tilda', 'keeper'],
      aboutLine: 'They bathe here. You can’t hide much in a towel.',
      leadLine: 'A coat was left in the changing room with something heavy sewn into the lining. Its owner ran off toward',
      spentLine: 'We close at two. That’s all I have.',
      opinions: { wren: 'Miss Wren bathes on Tuesdays and cries in the steam room where she thinks nobody can hear.', tilda: 'Mrs. Rask hasn’t been in since 1941. Her husband bathed here every Friday.', keeper: 'Garrow comes down from the lighthouse once a month and sits in the hot room like a man trying to boil something off himself.' },
      topics: [
        { id: 'night', q: 'Who came through the baths tonight?', a: 'A big man at two, wet to the waist. He wanted the hot room and wouldn’t take a towel. He left his coat in locker seventeen with something sewn into the lining.' },
        { id: 'lining', q: 'What was sewn in the lining?', a: 'A key, stamped ‘Bond Store 12’. He ran when he saw I’d found it. He ran toward the ice house.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Did Bask bathe here?', a: 'Every Friday for twenty years. On the 10th he sat in the hot room and told me the union was about to find out what it had been carrying. I thought he meant the dues.' },
      ] },
    { id: 'gault', at: 'harbourmaster', name: 'Ruth Gault', role: 'clerk, Harbourmaster’s Office',
      intro: 'Ruth Gault. I log the boats. In, out, weight, captain. When the log and the water disagree, I write down what the water says.',
      bio: 'Twelve years logging the boats. Her father was a captain who went out empty and never came back. She writes down the truth.',
      knows: ['wren', 'salvi', 'keeper'],
      aboutLine: 'They come to my counter. You learn a person by how they lie about the weight of their cargo.',
      leadLine: 'A boat went out at eleven with no cargo declared and came back at three sitting low in the water. It tied up at',
      spentLine: 'The office is closed. The log is locked.',
      opinions: { wren: 'Miss Wren’s stamps and my log should agree. Since the Corvina came in, they haven’t once.', salvi: 'Salvi declares his cargo weights the way some men declare their age.', keeper: 'Garrow and I keep the same log from opposite ends of the harbour. Mine is honest. His is crossed out.' },
      topics: [
        { id: 'night', q: 'What moved on the 11th?', a: 'The Marie-Louise out at eleven with no cargo declared. Back at three, sitting low in the water. High tide at 1:40. I wrote ‘low?’ with a question mark. The question mark is mine.' },
        { id: 'low', q: 'Sitting low with what?', a: 'Corvina cargo, for the ice house. And a passenger. The lighthouse keeper would have seen him land. Ask Garrow what he crossed out.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Bask came to this office.', a: 'On the 9th. He read six weeks of boat movements and copied every Marie-Louise entry into a notebook. He said: Ruth, you’ve been writing it all down. I said somebody had to.' },
      ] },
    { id: 'sparks', at: 'marconi', name: 'Tommy Sparks', role: 'wireless operator',
      intro: 'They call me Sparks. Real name’s Tomasz. Every wireless message on the water comes through these headphones. Most of them are about fish. Most.',
      bio: 'Polish navy, then the Marconi station. He can tell who is sending by the rhythm of their tapping. He keeps a second log the company does not know about.',
      knows: ['keeper', 'salvi', 'ledoux'],
      aboutLine: 'They send messages through me. You can tell a person by the way they tap a key.',
      leadLine: 'A message went out to a boat at one in the morning: ‘STOP AT THE USUAL PLACE.’ In this harbour, the usual place is',
      spentLine: 'I have a ship calling. It isn’t you.',
      opinions: { keeper: 'Garrow has no wireless. He doesn’t need one. He has a lamp and a grudge.', salvi: 'Salvi’s messages are all about fish, and not one of them ever names a fish.', ledoux: 'Ledoux taps a key slowly and heavily, like a man who doesn’t want to be understood.' },
      topics: [
        { id: 'night', q: 'What went over the wireless?', a: 'At 1:04, to the Marie-Louise: STOP AT THE USUAL PLACE. At 1:06 the reply: UNDERSTOOD. At 3:12, from the Marie-Louise: ALL DONE. I underlined that last one twice, because I know what it means.' },
        { id: 'sent', q: 'Who sent the first message?', a: 'It came from the shipping office key. Salvi’s. But the rhythm wasn’t Salvi’s. Salvi taps like a bird. This was like a hammer.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Did Bask send anything?', a: 'On the 10th, to the union’s city office: ONE MORE THING TO CHECK, THEN I NAME THEM. I sent it. I haven’t slept since.' },
      ] },
    { id: 'brack', at: 'hall', name: 'Mabel Brack', role: 'caretaker, the Hall',
      intro: 'Mabel Brack. I clean the hall after the meetings. I’ve cleaned up after every man who ever wanted to run this union.',
      bio: 'Caretaker of the union hall for twenty-two years. Before that she cleaned for Ambrose Rask. She trusts nobody who wants the chairman’s chair.',
      knows: ['hollis', 'tilda', 'okafor'],
      aboutLine: 'They sit in that hall every Thursday. I’ve swept around their feet for years.',
      leadLine: 'The back office was opened after the meeting with a key that wasn’t the vice-chairman’s. Whatever was taken went to',
      spentLine: 'The hall is locked. I’m going home.',
      opinions: { hollis: 'Dov left at midnight, came back at half past one, and sat in the dark. I let him. A man needs to sit in the dark sometimes.', tilda: 'Mrs. Rask has had a key to this hall since 1941. Nobody ever took it back. She has never used it.', okafor: 'Bernard came to the hall on the 10th to beg Bask for more time. Bask gave him a week. He didn’t need a week.' },
      topics: [
        { id: 'night', q: 'What happened at the hall?', a: 'The election committee until midnight. Then quiet. Then at one o’clock somebody opened the back office with a key that wasn’t the vice-chairman’s, and left with Bask’s little notebook.' },
        { id: 'book', q: 'What notebook?', a: 'The one he wrote the boats down in. He kept it in the back office. It’s gone. Whoever has it has the whole harbour in his pocket.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Twenty years. What was he like?', a: 'He never once sat down in this hall. He stood at the back like a man who didn’t expect to be allowed to stay.' },
      ] },
    { id: 'delacroix', at: 'printers', name: 'Émile Delacroix', role: 'typesetter, the Docker’s Voice',
      intro: 'Émile Delacroix. I set the type for the union newspaper. I know every word before the union does, and I know who wanted which words changed.',
      bio: 'Set type in Lyon, then here. He reads the union’s mind one letter at a time and keeps every page that was pulled before printing.',
      knows: ['hollis', 'tilda'],
      aboutLine: 'They bring me their articles. You learn a person by what they cross out.',
      leadLine: 'Somebody pulled a notice from tomorrow’s paper at midnight. They had no business in my shop. They left toward',
      spentLine: 'The press is running. Mind your fingers on the way out.',
      opinions: { hollis: 'Hollis brings me articles that say nothing, and then crosses out the nothing twice.', tilda: 'Mrs. Rask places a notice every year on the anniversary of her husband’s death. This year she placed it early.' },
      topics: [
        { id: 'night', q: 'What was pulled from the newspaper?', a: 'Bask’s notice: ‘The Chairman will address the membership on the matter of the Corvina and the trawler berths.’ Set in type, proofed, and pulled at midnight by a man with a key to my shop.' },
        { id: 'key', q: 'Who has a key?', a: 'The chairman. The vice-chairman. And the man who pays for the paper, which isn’t the union. He walked out toward the shipping office.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Did Bask write for the paper?', a: 'Every week for twenty years. Plain words, short lines. The last thing he wrote was: ‘If I am not at the vote, ask why.’' },
      ] },
    { id: 'oyelaran', at: 'bondstore', name: 'Femi Oyelaran', role: 'watchman, Bond Store 12',
      intro: 'Femi Oyelaran. I’ve guarded these crates for six weeks. In six weeks nobody came for them. Until tonight.',
      bio: 'He was a customs officer in Lagos. Here they only let him guard the crates, so he inspects them with his eyes.',
      knows: ['wren', 'salvi', 'ledoux'],
      aboutLine: 'They come to look at the seals. You learn a person by how they look at a seal they aren’t allowed to break.',
      leadLine: 'One crate was opened and closed again, badly. Whatever came out of it went along the quay to',
      spentLine: 'I have crates to watch. I’m watching them.',
      opinions: { wren: 'Miss Wren signs at the door and never comes inside. I’ve offered her a lamp. She’s never taken it.', salvi: 'Salvi’s name is on the manifest, on the seals, and on the envelope he leaves for me. I haven’t opened it.', ledoux: 'Ledoux breaks a customs seal the way other men open a bottle of beer.' },
      topics: [
        { id: 'night', q: 'Which crate was opened?', a: 'Bay four, seal number 4471. One twist. Ledoux did it, on Salvi’s orders, at one o’clock. He took out something long and wrapped up and put it on a cart.' },
        { id: 'long', q: 'Something long.', a: 'A bundle, wrapped in sailcloth. It went to the pier. I know what it was. I’d rather you heard it from somebody else.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Bask came to the bond store.', a: 'On the 9th. He asked me what was in the crates. I said I was only a watchman. He said: then watch. I’ve been watching ever since.' },
      ] },
    { id: 'mott', at: 'excise', name: 'Nan Mott', role: 'owner, Dockside Café',
      intro: 'Nan Mott. Tea is a penny. For another penny I’ll tell you who drank it. Bask drank his tea here every morning for twenty years.',
      bio: 'Has fed the harbour for thirty years. Bask sat at her counter every morning and told her nothing, which is how she came to know everything.',
      knows: ['hollis', 'okafor', 'fenn'],
      aboutLine: 'They take tea here. I’ve set a cup in front of them a thousand times.',
      leadLine: 'Somebody left a newspaper folded around something heavy and never came back for it. Somebody else took it to',
      spentLine: 'The kettle’s off. So am I.',
      opinions: { hollis: 'Dov sat with Bask for an hour on the 10th and left angry. Bask stayed and didn’t touch his tea.', okafor: 'Bernard was here until ten on the 11th with a cup he didn’t drink and a face like a debt.', fenn: 'The doctor takes tea here at six, after a night shift. On the 12th she didn’t come.' },
      topics: [
        { id: 'night', q: 'Who was in on the 11th?', a: 'Okafor until ten. Then a big man who sat in Okafor’s chair while it was still warm and ordered nothing. He left a newspaper folded around something heavy.' },
        { id: 'paper', q: 'What was in the newspaper?', a: 'A sailmaker’s needle and a spool of thread. I put it under the counter. Somebody came for it at midnight and I handed it over, because he had a scar across his thumb and I didn’t want an argument.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Twenty years of tea.', a: 'A penny a day. He never once asked for credit. On the 10th he sat with Hollis and they argued about a name. Not Hollis’s name. Somebody Bask was going to name out loud on Thursday.' },
      ] },
    { id: 'penrose', at: 'chapel', name: 'Aldo Penrose', role: 'verger, Fishermen’s Chapel',
      intro: 'Aldo Penrose. I polish the brass plaque and read out the names of the drowned. There’s a new name on it this week, in chalk. I didn’t write it.',
      bio: 'Verger for thirty years. He reads the names of the drowned every Sunday. He knew Ambrose Rask, and he knows who was on the boat.',
      knows: ['tilda', 'keeper'],
      aboutLine: 'They come to the plaque. You learn a person by which name they touch.',
      leadLine: 'Somebody knelt here at four in the morning with sand on their knees and left something in the charity box. It was carried off to',
      spentLine: 'The chapel is open to everyone. Everyone except you, tonight.',
      opinions: { tilda: 'Mrs. Rask comes every anniversary and touches one name on the plaque. This year she came early and wrote a second one.', keeper: 'Garrow hasn’t set foot inside the chapel since 1941. He stands in the doorway.' },
      topics: [
        { id: 'night', q: 'Who wrote the chalk name?', a: 'The widow, at four in the morning. Sand on her knees from the beach. Somebody had told her, and she came to write it before it was even true.' },
        { id: 'poorbox', q: 'Something was left in the charity box.', a: 'A padlock key. A big one, from the union hall’s back office. Whoever broke into that office put the key where a priest would find it. Guilt, or a joke.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'rask', q: 'Tell me about Ambrose Rask.', a: 'First name on the plaque under 1941. Bask paid for the plaque. He came every year and stood in front of it. He never prayed. He wasn’t a praying man. He was a remembering one.' },
      ] },
    { id: 'sable', at: 'coastguard', name: 'Jean Sable', role: 'petty officer, Coastguard',
      intro: 'Jean Sable, Coastguard. I log every boat that crosses the Narrows after dark. I also know which ones aren’t in the log.',
      bio: 'Coastguard for eleven years. She takes a bearing on every boat without a light and files it, whether or not anyone reads it.',
      knows: ['keeper', 'ledoux'],
      aboutLine: 'They pass under my telescope. You learn a person by how they stand at a wheel.',
      leadLine: 'A rowing boat with no lights crossed at half past two and landed below',
      spentLine: 'The watch changes at six. Ask somebody else.',
      opinions: { keeper: 'Garrow and I watch the same water. He writes down what he’s paid to. I write down what I see. We’ve never compared notes.', ledoux: 'Ledoux stands at his wheel like a man who’s been told where to go and would rather not.' },
      topics: [
        { id: 'night', q: 'What crossed the Narrows?', a: 'The Marie-Louise out at eleven with no lights. A rowing boat at half past eleven, to Pier Nine. The rowing boat back at half past one with one man in it. It landed under the old salt stairs.' },
        { id: 'man', q: 'Tell me about the one man.', a: 'Big. Wet to the waist. He went up the stairs and along the cliff, and I lost him at the lighthouse. Garrow didn’t lose him. Garrow crossed him out.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Did Bask ever come to the tower?', a: 'On the 9th. He asked to see six weeks of crossings. I gave them to him. He said: so it’s all written down. I said: it always was. Nobody ever asked.' },
      ] },
    { id: 'ives', at: 'hospital', name: 'Maud Ives', role: 'nurse, Seamen’s Infirmary',
      intro: 'Nurse Ives. I run Dr. Fenn’s wards. I run them better than she runs her paperwork.',
      bio: 'Nursed through the war. She runs the wards, keeps an eye on the doctor, and keeps her opinions of both to herself.',
      knows: ['fenn', 'hollis', 'okafor'],
      aboutLine: 'They’ve been through my ward. You don’t forget a patient. Or a visitor.',
      leadLine: 'A bag came in with a patient and left without him. The porter carried it to',
      spentLine: 'I’m doing my rounds. If you’re not bleeding, out.',
      opinions: { fenn: 'Dr. Fenn went out at one and came back at two with her hands washed. She wrote ‘drowning’ before she went and the truth after.', hollis: 'Mr. Hollis has a weak heart. He came in on the 10th with palpitations and wouldn’t say what had caused them.', okafor: 'Bernard Okafor came in on the 12th with a cut hand. He said it was rope. Rope doesn’t cut like that.' },
      topics: [
        { id: 'night', q: 'What came into the Infirmary?', a: 'A man at four with a bag. He left without the bag. Inside was a coat with the pockets cut out and salt in the seams.' },
        { id: 'bag', q: 'Where is the bag now?', a: 'The porter took it to the ice house, because that’s where the man said he worked. He doesn’t work there. He had a scar across his thumb.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Bask was here on the 10th.', a: 'For an hour, with the doctor. Not as a patient. When he left, she sat in the dispensary and didn’t move for a long time.' },
      ] },
    { id: 'cully', at: 'icehouse', name: 'Bram Cully', role: 'foreman, the Ice House',
      intro: 'Bram Cully. I cut the ice and stack it. Tonight a block came back with a hole cut in it the size of a man.',
      bio: 'Foreman at the ice house for nine years. He sells ice to fishing boats, and to people who have no fishing boats, and does not ask which is which.',
      knows: ['ledoux', 'salvi'],
      aboutLine: 'They buy ice from me. You learn a person by what they need to keep cold.',
      leadLine: 'A cart came for ice at three in the morning with no reason to need it. It went toward',
      spentLine: 'Ice doesn’t wait. Neither do I.',
      opinions: { ledoux: 'Ledoux unloads into my ice house at three in the morning. I don’t cut the blocks he uses.', salvi: 'Salvi buys ice for a shipping office. Shipping offices don’t need ice. Unless they do.' },
      topics: [
        { id: 'night', q: 'What came through the ice house?', a: 'Corvina cargo off the Marie-Louise at three. Two blocks of ice for Salvi’s back room. And a man who sat in the cold room for an hour with his coat off and his hands in the ice.' },
        { id: 'hands', q: 'Why the ice?', a: 'His hands were cut. Both of them. On glass, or a knife. He already had a scar across one thumb, and he was making new ones. He went from here toward the Seamen’s Mission.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Did Bask come here?', a: 'On the 9th. He walked through the cold room, counted the crates, and wrote in a notebook. He said: Bram, this isn’t fish. I said: no, it isn’t.' },
      ] },
    { id: 'lundy', at: 'pawnshop', name: 'Ma Lundy', role: 'pawnbroker',
      intro: 'Ma Lundy. Everything in this harbour ends up in my shop window sooner or later. Tonight something came in that I won’t put in the window.',
      bio: 'Forty years in the pawnshop. She lends money on sextants, rings and knives, and she looks hard at the hands that hand them over.',
      knows: ['okafor', 'tilda', 'ledoux'],
      aboutLine: 'They pawn things with me. I look at their hands.',
      leadLine: 'A pawn ticket was paid off at midnight, in cash, by somebody who wasn’t the person who pawned the item. They went to',
      spentLine: 'The shop is shut. I’ve said more than I should.',
      opinions: { okafor: 'Bernard pawned his knife in March so he could eat. He wouldn’t have bought it back. He couldn’t afford to.', tilda: 'Mrs. Rask pawned her wedding ring in 1942, bought it back in 1943, and hasn’t been in since.', ledoux: 'Ledoux pawns nothing. A man who never needs money is a man who’s paid in cash.' },
      topics: [
        { id: 'night', q: 'Who bought back the knife?', a: 'A big man, at midnight, with cash. A scar across his thumb. He paid Okafor’s ticket with a banknote that had been in the sea. It was still damp.' },
        { id: 'where', q: 'Where did he go?', a: 'Up the row toward the Brine & Bell, with the knife inside his coat and his hand on it.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Did Bask ever pawn anything?', a: 'Never. He came in on the 10th and bought something: a sailmaker’s needle from the tray. He said it was for mending a coat. I thought nothing of it. Now I think of nothing else.' },
      ] },
    { id: 'rook', at: 'tram', name: 'Tamsin Rook', role: 'conductor, the quay tram',
      intro: 'Tamsin Rook. I’m the conductor on the last tram along the quay at midnight. I punch the tickets, and I remember the people who’d rather I didn’t.',
      bio: 'Drove ambulances in the war. Now she punches tram tickets and remembers every face that would prefer to be forgotten.',
      knows: ['hollis', 'fenn', 'wren'],
      aboutLine: 'They ride my tram. You learn a person by where they refuse to sit.',
      leadLine: 'Somebody rode to the end of the line and then walked back the way we’d come, toward',
      spentLine: 'The tram’s in the shed. So am I.',
      opinions: { hollis: 'Mr. Hollis rode to the Brine & Bell at ten and didn’t ride back. He walked. Slowly.', fenn: 'The doctor rode toward the pier at one o’clock with her bag. She never takes the tram. She wasn’t thinking straight.', wren: 'Miss Wren rides home at eleven every night. She sits at the front and doesn’t look at anyone.' },
      topics: [
        { id: 'night', q: 'Who rode the last tram?', a: 'Eleven people. The doctor with her bag. A big man in a wet coat who rode to the end of the line and walked back. Miss Wren at the front, looking at nobody.' },
        { id: 'walked', q: 'Tell me about the one who walked back.', a: 'He went toward the salt works. He’d had a hundredweight of something on his shoulder earlier and nothing after. His hands were cut.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Did Bask ride the tram?', a: 'Every night for twenty years, standing at the back. On the 11th he didn’t. I noticed. I didn’t say anything. Who would I have said it to?' },
      ] },
    { id: 'orme', at: 'saltworks', name: 'Jack Orme', role: 'night man, the Salt Works',
      intro: 'Jack Orme. I bag salt. A hundredweight a bag, six hundred bags a night. Tonight I’m one bag short.',
      bio: 'Twenty years bagging salt. He can tell who carried a hundredweight by the way they walk afterwards.',
      knows: ['okafor', 'ledoux'],
      aboutLine: 'They come here for salt. You learn a person by how much they can carry.',
      leadLine: 'The missing bag went out on somebody’s shoulder. That somebody walked up the lane toward',
      spentLine: 'The kilns need feeding. You don’t.',
      opinions: { okafor: 'Okafor buys salt for his shop by the bag. He hasn’t bought a bag since March.', ledoux: 'Ledoux buys salt by the ton, for fish he doesn’t catch.' },
      topics: [
        { id: 'night', q: 'You’re one bag short.', a: 'Carried out on a man’s shoulder at ten o’clock. No cart. A big man. He walked up the lane toward the quay as if it weighed nothing.' },
        { id: 'lane', q: 'Where does the lane go?', a: 'To the pier, if you keep walking. He kept walking.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Did Bask ever come to the salt works?', a: 'On the 9th. He stood by the kilns and asked me who buys rock salt by the hundredweight. I said: fishermen. He said: name one.' },
      ] },
    { id: 'fry', at: 'seamen', name: 'Brother Fry', role: 'warden, Seamen’s Mission',
      intro: 'Brother Fry. Forty beds and a stove. I count the men in at ten and count them again in the morning. The numbers don’t always match.',
      bio: 'He was a sailor, then a drunk. Now he keeps forty beds at the Seamen’s Mission and counts them like a man who knows what an empty one means.',
      knows: ['tilda', 'keeper', 'hollis'],
      aboutLine: 'They sleep here sometimes. You learn a person by what they say in their sleep.',
      leadLine: 'A man came in at four with his boots full of water and left at five without his bundle. He went toward',
      spentLine: 'The men are sleeping. Keep your voice down and go.',
      opinions: { tilda: 'Mrs. Rask sends blankets every winter with her husband’s name sewn into them. I unpick the name. She knows I do.', keeper: 'Garrow sleeps here when the lighthouse gets too much for him. He talks in his sleep about a boat.', hollis: 'Dov Hollis slept in bed thirty-one on the 11th. In and out all night. He said his wife had locked him out.' },
      topics: [
        { id: 'night', q: 'Bed thirty-one.', a: 'In at ten, out at four, in at five, out at six. Wet through. A big man. He said nothing. He left a bundle at five, and I haven’t opened it.' },
        { id: 'bundle', q: 'Open it.', a: 'A coat with the pockets cut out and salt in the seams. And a padlock, a big one, with the shackle cut through.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Did Bask come to the mission?', a: 'He paid for the stove every winter. He never came inside. He stood at the door, counted the beds through the window, and left.' },
      ] },
  ],

  items: [
    { id: 'item:salt:autopsy-cert', at: 'morgue', kind: 'report', label: 'Death certificate, first draft', stamp: 'CONFIDENTIAL',
      source: 'HARBOUR MORGUE · CERTIFICATES', title: 'Certificate of death, Bask, A.',
      fields: [['Cause', 'drowning (struck through)'], ['Cause, amended', 'wound, left side, upward'], ['Signed', 'I. Fenn, M.D.'], ['Time signed', 'before the body was cold']],
      body: ['She wrote drowning, and then she wrote the truth over it. The morgue attendant watched her write both and remembers the hand.'],
      spoken: 'A death certificate with drowning struck through and the truth written over it.',
      reading: 'Kite, the morgue attendant, watched Dr. Fenn write it. It tells you something about her. Check her row in the Notebook.', about: ['fenn'], effect: { type: 'suspectTrait', suspectId: 'fenn' } },
    { id: 'item:salt:manifest', at: 'customs', kind: 'ledger', label: 'Manifest, six weeks sat on', stamp: 'COPY',
      source: 'THE CUSTOMS HOUSE · INSPECTIONS', title: 'Manifest, SS Corvina',
      body: ['Every page initialled E.W. — passed without inspection. On the last page, a second set of initials in a different ink, added tonight, over hers.', 'Aldous watched the second hand write.'],
      spoken: 'The manifest Customs sat on for six weeks, with a second set of initials added tonight.',
      reading: 'The clerk saw who added the second initials. It tells you something about Etta Wren. Check her row in the Notebook.', about: ['wren'], effect: { type: 'suspectTrait', suspectId: 'wren' } },
    { id: 'item:salt:wireless', at: 'marconi', kind: 'note', label: 'Wireless log, the 11th',
      source: 'MARCONI STATION · TRAFFIC LOG', title: 'Traffic, night of the 11th',
      body: ['01:04 — to trawler MARIE-LOUISE — STOP AT THE USUAL. 01:06 — reply — UNDERSTOOD. 03:12 — MARIE-LOUISE — ALL DONE.', 'The operator has underlined the third line twice.'],
      spoken: 'The wireless log: stop at the usual, understood, and at three, all done.',
      reading: 'A boat was told where to stop. The operator knows where ‘the usual place’ is. A red mark on the map shows it.', about: ['ledoux'], effect: { type: 'lead' } },
    { id: 'item:salt:knife', at: 'pawnshop', kind: 'ticket', label: 'Pawn ticket, one knife',
      source: 'LUNDY’S PAWN · TICKETS', title: 'Ticket no. 3391',
      fields: [['Item', 'knife, rigging, bone handle'], ['Pledged', 'the 9th'], ['Redeemed', 'the 11th, midnight, cash'], ['By', 'not the pledger']],
      body: ['Pledged by one hand and redeemed by another. Ma Lundy looked hard at the second pair of hands.'],
      spoken: 'A pawn ticket for a rigging knife, redeemed at midnight by somebody who did not pledge it.',
      reading: 'Ma Lundy looked at the hands that took the knife. A red mark on the map shows where they went.', effect: { type: 'lead' } },
    { id: 'item:salt:lamp-letter', at: 'raskhouse', kind: 'letter', label: 'A letter kept in a drawer', stamp: 'PERSONAL',
      source: 'THE RASK HOUSE · WRITING DESK', title: 'To Tilda, 1941, never sent',
      body: ['“Tilda — if I go in the water it was not the water. Ask Bask. He knows who, and he knows why, and he will not say until it suits him. — Ambrose.”', 'Seven years in a drawer. The paper is soft from being held.'],
      spoken: 'A letter from the widow’s husband, written in 1941 and kept seven years.',
      reading: 'Tilda has known for seven years that Bask knew who drowned her husband. A motive, and a grief. Nothing to mark.', about: ['tilda'], effect: { type: 'none' } },
    { id: 'item:salt:rope-sale', at: 'chandler', kind: 'receipt', label: 'Sales book, forty feet of line',
      source: 'VETCH & SON · SALES', title: 'The 11th, evening',
      fields: [['Item', 'line, quarter-inch, 40 ft'], ['Also', 'sailmaker’s needle, one'], ['Paid', 'double, for quiet'], ['Signed', 'B.O.']],
      body: ['Line and a needle: what you buy to sew a pocket shut. Signed by the chandler himself, in his own book, which is the strange part. Young Vetch watched him do it.'],
      spoken: 'The chandler’s sales book: forty feet of line and a sailmaker’s needle, signed B.O.',
      reading: 'Okafor sold the thread that sewed the pockets. Young Vetch saw who bought it. It tells you something about Okafor. Check his row in the Notebook.', about: ['okafor'], effect: { type: 'suspectTrait', suspectId: 'okafor' } },
    { id: 'item:salt:dues', at: 'bank', kind: 'ledger', label: 'Union account, withdrawals',
      source: 'HARBOUR SAVINGS · LEDGER', title: 'Longshoremen’s Local, account 40',
      body: ['A withdrawal of four hundred dollars on the 10th, on a slip signed by the vice-chair. The teller remembers him signing, and what he did with the pen after.'],
      spoken: 'The union account: four hundred dollars out on the tenth, signed by the vice-chair.',
      reading: 'The teller watched Hollis sign. It tells you something about him. Check his row in the Notebook.', about: ['hollis'], effect: { type: 'suspectTrait', suspectId: 'hollis' } },
    { id: 'item:salt:x-ray', at: 'hospital', kind: 'photo', label: 'Plate, the wound',
      source: 'SEAMEN’S INFIRMARY · RADIOGRAPHY', title: 'Plate 2: left side, the deceased',
      body: ['The blade went in under the ribs and up, toward the heart, from below. You do that from a crouch, or from a boat lower than the pier, or you do it as somebody who knows exactly where to put it.'],
      spoken: 'A radiograph of the wound: under the ribs and upward, from below.',
      reading: 'The knife went upward from below: from a boat, from a crouch, or from somebody who knew exactly where to put it. Nothing to mark.', about: ['fenn'], effect: { type: 'none' } },
    { id: 'item:salt:locker', at: 'baths', kind: 'ticket', label: 'Bath locker tag, unclaimed',
      source: 'HARBOUR BATHS · LOCKERS', title: 'Tag no. 17',
      body: ['A coat with something heavy sewn into the lining, left in locker seventeen and not claimed. Nell Harrow cut the lining. What was in it is in your hand: a key, stamped with the name of a store.'],
      spoken: 'A locker tag, an unclaimed coat, and a key sewn into the lining.',
      reading: 'The key opens something in this harbour. A red mark on the map shows where.', effect: { type: 'lead' } },
    { id: 'item:salt:net-tag', at: 'trawler', kind: 'ticket', label: 'Net tag, Marie-Louise',
      source: 'THE TRAWLER BERTHS · NETS', title: 'Tag, net 6, MARIE-LOUISE',
      body: ['A net tag from Ledoux’s boat, found in the water at Pier Nine, two hundred yards from where the Marie-Louise ties up. Nets do not walk. The skipper’s hand is on the tag; the deckhand knows it.'],
      spoken: 'A net tag from the Marie-Louise, found in the water off Pier Nine.',
      reading: 'Iggy Pell has watched Ledoux write those tags for years. It tells you something about Ledoux. Check his row in the Notebook.', about: ['ledoux'], effect: { type: 'suspectTrait', suspectId: 'ledoux' } },
    { id: 'item:salt:coastguard-fix', at: 'coastguard', kind: 'report', label: 'Coastguard fix, dinghy',
      source: 'COASTGUARD · WATCH LOG', title: 'Fix, 02:30',
      body: ['Dinghy, no light, bearing from the tower, beached below the old salt stair. The watch took a fix and marked the chart. The mark is a place, and you can walk to it.'],
      spoken: 'A coastguard fix on a dinghy with no light, beached below the old salt stair.',
      reading: 'The chart shows where the boat landed. A red mark on the map shows it.', effect: { type: 'lead' } },
    { id: 'item:salt:ferry-manifest', at: 'slip', kind: 'ticket', label: 'Ferry passenger count',
      source: 'FERRY SLIP · COUNT', title: 'Last crossing, the 11th',
      body: ['Eleven across, ten back. The steward counts heads, not names, and he counted a coat going over that did not come home.'],
      spoken: 'The ferry count: eleven across and ten back.',
      reading: 'One passenger never came back. It was a fisherman asleep in the shed. An hour wasted.', effect: { type: 'time', hours: 1 } },
    { id: 'item:salt:cafe-tab', at: 'excise', kind: 'receipt', label: 'Bask’s tab, the Dockside',
      source: 'DOCKSIDE CAFÉ · TABS', title: 'A. Bask — twenty years',
      body: ['Tea, every morning, a penny. The last line is the 10th. Under it, in Nan’s hand: “Sat with D.H. an hour. Left angry. D.H. stayed.” The cabman outside remembers where D.H. went, and knows a quick way there.'],
      spoken: 'Bask’s café tab: tea every morning for twenty years, and a last line about who he sat with.',
      reading: 'A last argument between Bask and Hollis, and a cab driver who knows the short cuts. Two hours back on the clock.', about: ['hollis'], effect: { type: 'time', hours: -2 } },
  ],

  objects: [
    { id: 'obj:salt:knife', at: 'drydock', name: 'A rigging knife, bone handle', drawing: 'knife',
      desc: 'Found in the drydock. The blade is clean. The handle is not.',
      spoken: 'A rigging knife in the drydock, bone handle, blade wiped clean.',
      unlocks: [
        { person: 'lundy', line: 'This was in your window.', reply: 'It was. Pledged by Okafor in March. Redeemed at midnight by a big man with a scar on the thumb who paid Okafor’s ticket with Okafor’s own money.',
          effect: { type: 'suspectTrait', suspectId: 'okafor' } },
        { person: 'okafor', line: 'Your knife.', reply: 'He looks at it a long time. Mine. I pawned it in March to eat. I did not redeem it. I did not have the money. Somebody paid my ticket, and then somebody used my knife.',
          effect: { type: 'clear', suspectId: 'okafor' } },
      ] },
    { id: 'obj:salt:flask', at: 'brine', name: 'A dented flask, RYE', drawing: 'flask',
      desc: 'Left on the Brine & Bell bar at one. Half full.',
      spoken: 'A dented flask of rye, left on the bar at one.',
      unlocks: [
        { person: 'teague', line: 'Whose flask?', reply: 'Dov Hollis’s. He drinks from it when he thinks I cannot see. He was here till one, not at the Hall till midnight, and he was not drinking to celebrate.',
          effect: { type: 'suspectTrait', suspectId: 'hollis' } },
        { person: 'hollis', line: 'Your flask. On Mags’s bar at one. You said the Hall till midnight, then home.', reply: 'I was at the Brine. I was drinking because I had paid a man four hundred dollars of union money to stand down and he had laughed at me. Mags saw me. Forty men saw me. Ask them.',
          effect: { type: 'clear', suspectId: 'hollis' } },
      ] },
    { id: 'obj:salt:locket', at: 'raskhouse', name: 'A locket with a lock of hair', drawing: 'locket',
      desc: 'On the widow’s writing desk. The hair is grey now. It was not when it was cut.',
      spoken: 'A locket on the widow’s desk, with a lock of hair inside.',
      unlocks: [
        { person: 'tilda', line: 'Ambrose’s?', reply: 'His. Cut the morning he went out. I have had it seven years. I went out last night, Inspector. To the chapel. To write the name of the man who let my husband drown. Somebody told me he was in the water. I wrote it. I did not put him there.',
          effect: { type: 'clear', suspectId: 'tilda' } },
        { person: 'penrose', line: 'Whose hair?', reply: 'Ambrose Rask’s. She showed me once. She came to the chapel at four and chalked Bask’s name and I let her. Whoever told her he was drowned told her before the tide did.',
          effect: { type: 'lead' } },
      ] },
    { id: 'obj:salt:seal', at: 'bondstore', name: 'A customs seal, broken, no. 4471', drawing: 'button',
      desc: 'From bay four. Broken in one twist. Whoever did it had done it before.',
      spoken: 'A customs seal from bay four, broken in one twist.',
      unlocks: [
        { person: 'wren', line: 'Your seal. Your initials. Broken tonight.', reply: 'She sits down. I initial. I do not open. Salvi pays me not to open and I have never spent a dollar of it. I was at the Customs House till eleven. Aldous saw me leave.',
          effect: { type: 'clear', suspectId: 'wren' } },
        { person: 'oyelaran', line: 'Who broke it?', reply: 'Ledoux. On Salvi’s word. One twist. He has done it before, on the Corvina crates, every month for six.',
          effect: { type: 'suspectTrait', suspectId: 'salvi' } },
      ] },
    { id: 'obj:salt:button', at: 'pier9', name: 'A brass button with thread', drawing: 'button',
      desc: 'Under the tape at Pier Nine. Torn off a coat. The thread is sailcloth.',
      spoken: 'A brass button at Pier Nine, torn off with the thread still in it.',
      unlocks: [
        { person: 'vetch', line: 'Whose coat?', reply: 'A skipper’s coat. We sell those buttons. We sold a set to Ledoux in January and he lost one in February. He came back for a match. We did not have one.',
          effect: { type: 'suspectTrait', suspectId: 'ledoux' } },
        { person: 'ledoux', line: 'Yours.', reply: 'Mine. I was at Pier Nine. I brought two men in on the dinghy and I brought one back and I did not ask the one who came back what happened to the other. I was paid not to ask. I am asking now.',
          effect: { type: 'clear', suspectId: 'ledoux' } },
      ] },
    { id: 'obj:salt:watch', at: 'morgue', name: 'Bask’s watch, stopped at 11:40', drawing: 'watch',
      desc: 'From his waistcoat. Salt in the works. It stopped when he went in.',
      spoken: 'Bask’s watch, salt in the works, stopped at twenty to midnight.',
      unlocks: [
        { person: 'kite', line: 'Eleven-forty. Does that fit?', reply: 'It fits. Dr. Fenn wrote drowning at one and the truth at two. In between she went out. She came back with her hands washed. She had been somewhere with salt.',
          effect: { type: 'culpritTrait' } },
        { person: 'fenn', line: 'His watch stopped at eleven-forty.', reply: 'She does not look at it. He came to me at ten. He said somebody wanted to meet at the pier. He asked me how a man is killed with a knife under the ribs. I told him. I thought he was asking so he could avoid it.',
          effect: { type: 'suspectTrait', suspectId: 'fenn' } },
      ] },
  ],
  story: {
    backstory: [
      'Aurel Bask ran the longshoremen for twenty years. He was not liked. He was obeyed. He kept the harbour working and the union’s money where the union could see it.',
      'Six weeks ago the Corvina came in with forty crates and a manifest nobody read. Bask started counting boats. He counted the Marie-Louise going out empty and coming back heavy. He counted the crates in the bond store. He wrote it down.',
      'Thursday there is a vote. Bask was going to speak about the berths. Everyone with money in the berths knew it. On the 11th, at ten at night, he told his doctor somebody wanted to meet him at Pier Nine.',
      'They found him at low tide with his pockets sewn shut and full of rock salt. That is a message. The harbour read it. Then it stopped talking.',
    ],
    timeline: [
      { time: '8:00 PM', text: 'Okafor closes the chandlery. Forty feet of line and a needle are sold, and signed for in his book.' },
      { time: '10:00 PM', text: 'Bask visits Dr. Fenn at the Infirmary. He tells her about a meeting at the pier.' },
      { time: '11:10 PM', text: 'The Marie-Louise clears out. No cargo declared.' },
      { time: '11:40 PM', text: 'Bask’s watch stops. He is in the water.' },
      { time: '12:00 AM', text: 'A pawn ticket for a rigging knife is redeemed at Lundy’s by a hand that did not pledge it.' },
      { time: '1:04 AM', text: 'Wireless: STOP AT THE USUAL. Reply: UNDERSTOOD.' },
      { time: '1:30 AM', text: 'The keeper logs a dinghy. Two aboard going out. He crosses it out.' },
      { time: '3:05 AM', text: 'The Marie-Louise ties up, riding low. Two blocks of ice are ordered for Salvi Shipping.' },
      { time: '4:00 AM', text: 'Bask’s name is chalked on the chapel brass, under the drowned. The tide has not given him up yet.' },
    ],
    truth: [
      'Bask went to Pier Nine because Marcel Ledoux told him a friend wanted to talk about the berths before the vote. Ledoux rowed in alone from the Marie-Louise. There was never a second man in the dinghy.',
      'He killed Bask the way Dr. Fenn had once described over a dinner Bask had invited him to: under the ribs, from below, upward. Then he sewed the pockets shut with Okafor’s needle and filled them with the salt Orme was one bag short of.',
      'The salt was for the three thousand men who would hear about it by morning. It worked. Salvi paid for all of it and never held the needle. Garrow saw the dinghy and crossed it out for fifty dollars he has not touched.',
      'Ambrose Rask went into the bay in ’41 for the same reason, off the same boat, and Ledoux was the boy being sick in the bilge. Bask knew. He never said. That is the only thing about Aurel Bask nobody in this harbour has forgiven.',
    ],
  },

  epilogue: {
    win: `You make the arrest at the Hall an hour before the vote, in front of three hundred
      longshoremen who go quiet all at once. Somebody at the back starts clapping and thinks
      better of it. The tide comes in. It always does.`,
    loss: `Thursday comes. They elect a new boss. The new boss says all the right things about
      Aurel Bask. The salt goes in an evidence locker. The file goes in a drawer. The harbour
      goes back to being a place where nobody saw anything.`,
  },
};

export default def;
