import type { CaseDef } from '../../types/game-types';

// Salt and Silence. The Harbour District: thirty locations from Customs Row
// down to the Narrows, twenty people who will talk if you do not ask like
// police, and twenty-six documents the tide did not take.

const def: CaseDef = {
  id: 'salt',
  title: 'Salt and Silence',
  subtitle: 'The Harbour District · February 1948',
  tagline: 'The union boss came out of the bay with his pockets sewn shut and full of salt.',
  victim: 'Aurel Bask',
  scene: 'pier9',
  difficultyHint: 'Tight streets, fast tongues.',
  publicTraits: ['build', 'hair'],
  traitPool: ['hand', 'mark', 'vice', 'scent', 'shoe'],

  briefing: `Low tide at Pier Nine gives up Aurel Bask. Twenty years head of the longshoremen.
    Thirty hours dead. Somebody sewed his coat pockets shut and filled them with rock salt.
    That is not how you sink a man. That is how you tell three thousand dockers what happens
    to one who talks. The wound is under the ribs. It went up.
    Half this harbour wanted him gone. The other half worked for him. Nobody here talks to
    police. Do not ask like police.`,

  radio: [
    'Harbour Station. Do not go to Pier Nine alone. Do not go in uniform.',
    'The union votes Thursday. Every candidate is on your list.',
    'Customs has sat on a manifest for six weeks. Lean on them.',
  ],

  terrain: {
    sea: true, seaName: 'THE NARROWS', river: false, parks: 1,
    districts: [
      { text: 'CUSTOMS ROW', x: 450, y: 10, rot: -2 },
      { text: 'THE HALL', x: 760, y: 120, rot: 2 },
      { text: 'GRIEVE POINT', x: 1000, y: 90, rot: 4 },
      { text: 'THE SALT YARDS', x: 230, y: 620, rot: -3 },
      { text: 'THE NARROWS', x: 800, y: 600, rot: 2 },
    ],
  },

  locations: [
    // ---- Customs Row
    { id: 'pier9', name: 'Pier Nine', type: 'docks', x: 250, y: 170, district: 'Customs Row', desc: 'Where they found him. Still taped off. Still stinking.' },
    { id: 'harbourmaster', name: 'Harbourmaster’s Office', type: 'office', x: 300, y: 60, district: 'Customs Row', desc: 'Every boat in and out, in a steady hand. The clerk’s is not.' },
    { id: 'customs', name: 'The Customs House', type: 'bank', x: 470, y: 110, district: 'Customs Row', desc: 'Every crate in this harbour is a line in a ledger here. Most lines are lies.' },
    { id: 'marconi', name: 'Marconi Station', type: 'radio', x: 640, y: 60, district: 'Customs Row', desc: 'Every wireless message on the water. One operator who writes them all down twice.' },
    { id: 'excise', name: 'Dockside Café', type: 'cafe', x: 380, y: 240, district: 'Customs Row', desc: 'Tea, tobacco, and the only warm room between the Row and the Hall.' },
    { id: 'bondstore', name: 'Bond Store 12', type: 'warehouse', x: 560, y: 220, district: 'Customs Row', desc: 'Six weeks of crates nobody has opened. One seal somebody has.' },
    { id: 'pawnshop', name: 'Lundy’s Pawn', type: 'shop', x: 60, y: 250, district: 'Customs Row', desc: 'Sextants, wedding rings, and one knife with a very particular handle.' },
    // ---- The Hall
    { id: 'hall', name: 'Longshoremen’s Hall', type: 'office', x: 720, y: 160, district: 'The Hall', desc: 'Folding chairs, a dead man’s photograph, and an election on Thursday.' },
    { id: 'printers', name: 'The Docker’s Voice', type: 'press', x: 800, y: 60, district: 'The Hall', desc: 'The union paper. Set by hand. Read by three thousand. Believed by most.' },
    { id: 'station', name: 'Harbour Station', type: 'police', x: 480, y: 330, district: 'The Hall', desc: 'Two desks, one cell, a radiator that screams.' },
    { id: 'chandler', name: 'Vetch & Son, Chandlers', type: 'shop', x: 650, y: 330, district: 'The Hall', desc: 'Rope, oil, and every hook a man could need.' },
    { id: 'shipping', name: 'Salvi Shipping', type: 'office', x: 780, y: 300, district: 'The Hall', desc: 'Three companies. One office. One lamp always on.' },
    { id: 'bank', name: 'Harbour Savings', type: 'bank', x: 560, y: 440, district: 'The Hall', desc: 'Where the dues go. Where they sometimes come from.' },
    { id: 'hospital', name: 'Seamen’s Infirmary', type: 'hospital', x: 760, y: 480, district: 'The Hall', desc: 'Dr. Fenn’s wards. Certificates are written fast here.' },
    // ---- Grieve Point
    { id: 'light', name: 'Grieve Point Light', type: 'light', x: 920, y: 240, district: 'Grieve Point', desc: 'One keeper, one lamp, the best view of who comes in at night.' },
    { id: 'raskhouse', name: 'The Rask House', type: 'manor', x: 1040, y: 150, district: 'Grieve Point', desc: 'Grey shingles on the point. The widow keeps a lamp lit for a man seven years drowned.' },
    { id: 'chapel', name: 'Fishermen’s Chapel', type: 'church', x: 1000, y: 380, district: 'Grieve Point', desc: 'Names of the lost on brass. One added this week in chalk.' },
    { id: 'coastguard', name: 'Coastguard Tower', type: 'tower', x: 1060, y: 520, district: 'Grieve Point', desc: 'A log of every hull that crosses the Narrows after dark. Most of those are lies too.' },
    { id: 'icehouse', name: 'The Ice House', type: 'warehouse', x: 870, y: 450, district: 'Grieve Point', desc: 'Cold enough to keep a body honest.' },
    // ---- The Salt Yards
    { id: 'brine', name: 'The Brine & Bell', type: 'bar', x: 170, y: 340, district: 'The Salt Yards', desc: 'Sawdust, rum, forty men who saw nothing.' },
    { id: 'seamen', name: 'Seamen’s Mission', type: 'home', x: 80, y: 460, district: 'The Salt Yards', desc: 'Forty cots, a stove, and a warden who counts who does not come back.' },
    { id: 'tram', name: 'Quay Tram Stop', type: 'tram', x: 420, y: 420, district: 'The Salt Yards', desc: 'The last car along the quay at midnight. The conductor punches faces, not tickets.' },
    { id: 'drydock', name: 'Number Four Drydock', type: 'factory', x: 330, y: 490, district: 'The Salt Yards', desc: 'A hull the size of a church, propped on stilts.' },
    { id: 'baths', name: 'Harbour Baths', type: 'bathhouse', x: 170, y: 580, district: 'The Salt Yards', desc: 'Steam and tile. The only place in the district nobody wears a coat.' },
    { id: 'saltworks', name: 'The Salt Works', type: 'factory', x: 240, y: 700, district: 'The Salt Yards', desc: 'Rock salt bagged by the hundredweight. Nobody counts the bags.' },
    { id: 'ropewalk', name: 'The Ropewalk', type: 'warehouse', x: 500, y: 650, district: 'The Salt Yards', desc: 'A quarter mile of shed. A needle for every thickness of line.' },
    // ---- The Narrows
    { id: 'trawler', name: 'The Trawler Berths', type: 'docks', x: 620, y: 570, district: 'The Narrows', desc: 'Nets, gulls, and boats that go out empty and come back heavy.' },
    { id: 'cannery', name: 'Narrows Cannery', type: 'factory', x: 760, y: 700, district: 'The Narrows', desc: 'Still running. On fish nobody catches.' },
    { id: 'morgue', name: 'Harbour Morgue', type: 'morgue', x: 900, y: 620, district: 'The Narrows', desc: 'Bask is on the third slab. The salt is in a bag beside him.' },
    { id: 'slip', name: 'Ferry Slip', type: 'pier', x: 1120, y: 680, district: 'The Narrows', desc: 'The only way off the point that does not pass the tower.' },
  ],
  edges: [
    ['pier9', 'harbourmaster'], ['pier9', 'pawnshop'], ['pier9', 'brine'], ['pier9', 'customs'],
    ['harbourmaster', 'customs'],
    ['customs', 'marconi'], ['customs', 'bondstore'], ['customs', 'excise'],
    ['marconi', 'hall'], ['marconi', 'printers'],
    ['hall', 'printers'], ['hall', 'shipping'], ['hall', 'bondstore'], ['hall', 'light'],
    ['printers', 'raskhouse'],
    ['light', 'raskhouse'], ['light', 'chapel'], ['light', 'shipping'],
    ['raskhouse', 'chapel'],
    ['chapel', 'coastguard'], ['chapel', 'icehouse'],
    ['coastguard', 'slip'], ['coastguard', 'morgue'],
    ['excise', 'station'], ['excise', 'brine'],
    ['bondstore', 'station'], ['bondstore', 'chandler'],
    ['station', 'tram'], ['station', 'chandler'], ['station', 'bank'],
    ['chandler', 'shipping'], ['chandler', 'hospital'],
    ['shipping', 'hospital'],
    ['hospital', 'icehouse'], ['hospital', 'trawler'],
    ['icehouse', 'morgue'],
    ['brine', 'seamen'], ['brine', 'tram'], ['brine', 'drydock'],
    ['seamen', 'baths'],
    ['pawnshop', 'seamen'],
    ['tram', 'drydock'], ['tram', 'bank'],
    ['bank', 'trawler'], ['bank', 'ropewalk'],
    ['drydock', 'baths'], ['drydock', 'ropewalk'],
    ['baths', 'saltworks'],
    ['saltworks', 'ropewalk'],
    ['ropewalk', 'trawler'],
    ['trawler', 'cannery'],
    ['cannery', 'morgue'], ['cannery', 'slip'],
    ['morgue', 'slip'],
  ],
  start: 'station',

  suspects: [
    { id: 'hollis', name: 'Dov Hollis', role: 'Union vice-chair',
      blurb: 'Second in command of the union for eleven years. From Thursday, the boss.',
      motive: 'because second chair for eleven years is its own kind of sentence.',
      bio: 'Fifty-one. Loaded ships for twenty years, then ran the union’s elections. Bask’s right-hand man, and the man Bask never let take over. Everybody likes Dov. Nobody follows him.',
      alibi: 'At the union hall until midnight with the election committee. Then home. His wife will confirm it.',
      secret: 'He took four hundred dollars from the union account on the 10th to pay off a man who planned to run against him. The man took the money and ran anyway.',
      opinions: { wren: 'Etta Wren initials what she is told to. She has a good hand for it.', okafor: 'Bernard owes everyone and pays nobody. Bask called it in. That was cruel.', salvi: 'Salvi buys men. He bought half the hall. He did not buy me. He did not offer.', tilda: 'Tilda Rask has hated Bask for seven years and me for eleven. She is fair about it.', keeper: 'Garrow sees everything from the light. He has never testified to anything.', fenn: 'The doctor and Bask were closer than the harbour knows. I knew.', ledoux: 'Ledoux goes out empty and comes back heavy. Bask was writing it down. I told him not to.' },
      topics: [
        { id: 'night', q: 'Where were you on the night of the 11th?', a: 'The Hall till midnight with the ballot committee. Then home. My wife will say so.' },
        { id: 'chair', q: 'Second chair for eleven years. Thursday you are first.', a: 'Because he is dead. Not because I wanted it this way. I wanted it the other way. I wanted him to step down and shake my hand.' },
        { id: 'money', q: 'Four hundred dollars came out of the union account on the 10th. Your signature.', a: 'He rubs his face. To pay a man to stand down. He took it and ran anyway. I stole from the union to lose an election. Print that.', after: 'chair', cost: 1, effect: { type: 'suspectTrait', suspectId: 'hollis' } },
        { id: 'berths', q: 'Bask was going to speak about the berths.', a: 'He was going to name Ledoux, Salvi and the Corvina. Out loud. To three thousand men. I told him to wait till after the vote. He said the vote was the point.', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'What was he like?', a: 'Hard. Fair. Never forgave a thing. He knew who put Ambrose Rask in the bay and he kept it for seven years like a coin in his pocket.' },
      ] },
    { id: 'wren', name: 'Etta Wren', role: 'Customs inspector',
      blurb: 'Customs inspector. She approved six weeks of crates without opening one.',
      motive: 'because the manifest he was carrying had her signature on every page.',
      bio: 'Thirty-nine. The first woman inspector in the harbour. She cannot afford a single mistake, so on paper she never makes one. Her initials are on every page of the Corvina manifest. She opened none of the crates.',
      alibi: 'Working late at the Customs House. The clerk saw her leave at eleven.',
      secret: 'Salvi pays her two hundred dollars a month to sign without looking. She has kept every dollar in an envelope for two years and never spent one.',
      opinions: { hollis: 'Hollis is an honest man in a job that does not have room for one.', okafor: 'Okafor sells rope to the Corvina crews and pretends he does not know what they tie with it.', salvi: 'Salvi is polite. Salvi pays on time. Salvi is the worst thing in this harbour.', tilda: 'The widow came to the Customs House in ’41 with a question about a boat. Nobody answered her. I was a clerk then. I did not answer either.', keeper: 'Garrow logs what he is paid to and crosses out the rest. He and I are the same, and I hate him for it.', fenn: 'Dr. Fenn signed my father’s certificate. Quickly. Correctly. I owe her that.', ledoux: 'Ledoux’s boat is on my manifests as a fishing vessel. I have never seen a fish on it.' },
      topics: [
        { id: 'night', q: 'Where were you on the 11th?', a: 'The Customs House till eleven. Aldous saw me leave. Then home. I live alone.' },
        { id: 'manifest', q: 'Six weeks. Every page initialled. No crate opened.', a: 'Yes. I initial. I do not open. Ask me why and I will tell you, and then I will not have a job.' },
        { id: 'why', q: 'Tell me why.', a: 'She takes a breath. Salvi pays me two hundred a month. It is in an envelope in my flat. Every dollar. I have never spent one. I do not know what I was keeping it for. Evidence, maybe.', after: 'manifest', cost: 1, effect: { type: 'suspectTrait', suspectId: 'wren' } },
        { id: 'second', q: 'A second set of initials was added tonight, over yours.', a: 'Not mine. Somebody wanted it to look like I had passed the crate a second time. Somebody who knows my initials and does not know my pen.', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Did Bask come to you?', a: 'On the 9th. He asked to see the Corvina manifest. I showed him. He read it and said, Etta, you have signed your name to this. I said I know.' },
      ] },
    { id: 'okafor', name: 'Bernard Okafor', role: 'Chandler, Vetch & Son',
      blurb: 'Sells rope. Keeps a list of who buys it.',
      motive: 'because the debt was called in, and he had nothing left to pay it with.',
      bio: 'Fifty-eight. Runs the ship’s chandlery for old Vetch, who has not been in the shop since 1944. He owed Bask two thousand dollars from a boat that sank. Bask demanded the money on the 9th.',
      alibi: 'Closed the shop at eight. At the Dockside Café until ten. Then home, alone.',
      secret: 'He sold forty feet of line and a sailmaker’s needle on the 11th and signed his own initials in the sales book, because the buyer put a hand on his and told him to.',
      opinions: { hollis: 'Dov is decent. Decent does not run a harbour.', wren: 'Miss Wren buys nothing from me. Inspectors do not need rope.', salvi: 'Salvi’s crews buy the best line and pay in cash and never come back for the same length twice.', tilda: 'Mrs. Rask buys lamp oil every week for a lamp nobody needs. I do not charge her.', keeper: 'Garrow buys nothing. The light is supplied. He comes in to talk. He talks about ’41.', fenn: 'The doctor bought a scalpel from me once because the Infirmary was out. A strange thing to run out of.', ledoux: 'Ledoux buys line by the hundred foot and nets never. Draw your own conclusion.' },
      topics: [
        { id: 'night', q: 'Where were you on the 11th?', a: 'Shut the shop at eight. The Dockside till ten. Then home. Nobody to say so.' },
        { id: 'debt', q: 'You owed Bask two thousand dollars.', a: 'From a boat that sank in ’45 with my whole stake in it. He lent me the stake. He called it in on the 9th. I told him I could not. He said he knew.' },
        { id: 'line', q: 'Forty feet of line and a needle. Signed B.O. In your own book.', a: 'He closes his eyes. A man came in at closing. Big. He put his hand on mine and said, sign it yourself. So I did. I sell rope. I did not sew anything.', after: 'debt', cost: 1, effect: { type: 'suspectTrait', suspectId: 'okafor' } },
        { id: 'man', q: 'Describe the man.', a: 'A scar across the thumb. He kept it turned away. He smelled of the ice house.', after: 'line', cost: 1, effect: { type: 'lead' } },
      ] },
    { id: 'salvi', name: 'Nunzio Salvi', role: 'Shipping agent',
      blurb: 'Shipping agent. Three companies, one office, no employees.',
      motive: 'because a strike would have cost him a season he could not afford to lose.',
      bio: 'Forty-five. Agent for the Corvina and two other ships that exist only on paper. He owes money in three ports. A strike on Thursday would finish him.',
      alibi: 'In his office all night doing accounts. The lamp was on.',
      secret: 'He ordered two blocks of ice at three in the morning for something in his back room that had to be kept cold. It was not fish. It was not Bask, either.',
      opinions: { hollis: 'Hollis will be a fine chairman. Reasonable. I like reasonable.', wren: 'Miss Wren is a professional. I admire professionals.', okafor: 'Okafor is in debt. Men in debt are useful. That is not a crime.', tilda: 'The widow blames everyone for a boat that sank before I came here.', keeper: 'Garrow is a public servant. I contribute to public servants.', fenn: 'The doctor is not for sale. I have checked.', ledoux: 'Ledoux fishes. What he catches is his business and mine.' },
      topics: [
        { id: 'night', q: 'Where were you on the 11th?', a: 'My office. Accounts. The lamp was on till dawn. Anyone on the quay will tell you.' },
        { id: 'strike', q: 'A strike on Thursday finishes you.', a: 'A strike finishes everyone. I am not special. I have three ships and two of them are paper. If the berths close I am a man with an office.' },
        { id: 'cable', q: '‘Do what you must.’ A cable to you.', a: 'From my partner in Marseille. He meant: settle with the union. He did not mean what you mean. I did not do what you mean.', after: 'strike', cost: 1, effect: { type: 'suspectTrait', suspectId: 'salvi' } },
        { id: 'ice', q: 'Two blocks of ice at three in the morning.', a: 'For the back room. For cargo. Cargo that spoils. He looks at the door. It was not Bask, if that is what you are asking. Bask was in the water by then.', cost: 1, effect: { type: 'lead' } },
        { id: 'usual', q: 'STOP AT THE USUAL.', a: 'I do not know what that means. He knows. He is a poor liar and a good agent, which is a bad combination in a harbour.' },
      ] },
    { id: 'tilda', name: 'Tilda Rask', role: 'Widow of the last boss',
      blurb: 'Widow of the last union boss. Her husband drowned in 1941. Nobody was ever charged.',
      motive: 'because seven years is a long time to hold a thing, and no time at all.',
      bio: 'Sixty. Her husband Ambrose ran the union before Bask. He went into the bay in 1941. Tilda has kept a lamp lit for him ever since, and a letter in a drawer.',
      alibi: 'At home in the Rask House. She never goes out after dark. Everyone on the point knows it.',
      secret: 'She did go out. She walked to the chapel at four in the morning and wrote Bask’s name under the list of the drowned before anyone knew he was dead. Somebody had told her. She will not say who.',
      opinions: { hollis: 'Dov Hollis carried my husband’s coffin and then carried Bask’s bags for eleven years.', wren: 'The girl at Customs would not look at me in ’41. She looks at me now. That is something.', okafor: 'Bernard brings me lamp oil and will not take money. Kind men are the ones who drown.', salvi: 'Salvi came to the harbour in ’42. One year after. I have never trusted the timing.', keeper: 'Garrow was on Ambrose’s boat. He came back. Ambrose did not. Draw a line between those.', fenn: 'The doctor loved Bask. Everyone thinks I do not know. I have been a widow. I know what it looks like.', ledoux: 'Ledoux was a boy on the Rask boat in ’41. He was sick over the side. He has never been sick since.' },
      topics: [
        { id: 'night', q: 'Where were you on the 11th?', a: 'Here. I do not go out after dark. Everyone on the point knows it.' },
        { id: 'chalk', q: 'Bask’s name was chalked on the chapel brass at four. Before he was found.', a: 'She does not blink. I went out. Somebody came to my door at three and told me he was in the water and I put on my coat and went and wrote it under Ambrose. I am not sorry.', after: 'night', cost: 1, effect: { type: 'suspectTrait', suspectId: 'tilda' } },
        { id: 'who', q: 'Who came to your door?', a: 'A man with wet boots who would not come in. I did not see his face. I saw his hands on my gatepost. There was a scar across the thumb.', after: 'chalk', cost: 1, effect: { type: 'lead' } },
        { id: 'letter', q: 'The letter in your drawer. 1941.', a: 'Ambrose wrote it the morning he went out. If I go in the water it was not the water. Ask Bask. I asked Bask. For seven years I asked Bask.' },
      ] },
    { id: 'keeper', name: 'Mr. Garrow', role: 'Lighthouse keeper',
      blurb: 'Lighthouse keeper. Sees everything from Grieve Point. Reports none of it.',
      motive: 'because he saw the boat, and then he was in it.',
      bio: 'Sixty-three. Keeper at Grieve Point for thirty years. He logs every light on the water and crosses out the ones he is paid to. He was on the boat with Ambrose Rask in 1941. He has never said what he saw.',
      alibi: 'In the lighthouse. Where else would he be.',
      secret: 'He logged a small boat at half past one: two men going out, one coming back. Then he crossed it out. Somebody paid him fifty dollars to cross it out. He has not touched the money.',
      opinions: { hollis: 'Hollis came up to the light once to ask what I saw in ’41. I told him nothing. He believed me. That is Hollis.', wren: 'Miss Wren logs by day what I log by night. Neither of us reads the other’s.', okafor: 'Okafor sold me a lamp glass in ’39 and has been apologising for the price since.', salvi: 'Salvi sends fifty dollars up the light at Christmas. And other times.', tilda: 'Tilda Rask has looked at this tower every night for seven years. I feel it.', fenn: 'The doctor came up the light in ’41 to sign something. She looked at the water a long time first.', ledoux: 'Ledoux lands under the point without lights. I log it. Then I cross it out. Then I log it again in a book nobody knows about.' },
      topics: [
        { id: 'night', q: 'What did you see on the 11th?', a: 'The water. A boat out at eleven. A dinghy at half one. A boat in at three. I logged what I am paid to log.' },
        { id: 'crossed', q: 'The dinghy entry is crossed out. In your hand.', a: 'Two aboard going out. One coming back. I crossed it out because fifty dollars came up the stair the next morning. The money is on the shelf. I have not touched it.', after: 'night', cost: 1, effect: { type: 'suspectTrait', suspectId: 'keeper' } },
        { id: 'second', q: 'You have a second log.', a: 'Under the floor. Everything since ’41. Every boat without a light. Every name I could put to one. Take it. I have carried it long enough.', after: 'crossed', cost: 1, effect: { type: 'lead' } },
        { id: 'rask', q: 'You were on the Rask boat.', a: 'I was. Ambrose went over the side and Bask was at the wheel and I was sick in the bilge. I did not see who pushed. I saw who did not pull him back.' },
      ] },
    { id: 'fenn', name: 'Dr. Ilse Fenn', role: 'Harbour surgeon',
      blurb: 'Harbour surgeon. Signed the death certificate before the body was cold. Signed it wrong.',
      motive: 'because the wound went up, and only she knew what that meant.',
      bio: 'Forty-four. Came from Hamburg in 1938. The only surgeon in the district, and the only one who will sign a certificate at three in the morning. She wrote ‘drowning’. Then she crossed it out and wrote the truth.',
      alibi: 'At the Infirmary all night. Nurse Ives will confirm it.',
      secret: 'She was Bask’s doctor and his lover. She knew the knife went upward because she had once shown him how a man is killed that way. She never thought he would need to know.',
      opinions: { hollis: 'Dov Hollis has a bad heart and a good one. I treat the first.', wren: 'Etta Wren came to me with a rash from worry. I told her to spend the money. She did not.', okafor: 'Bernard Okafor has not slept since ’45. I gave him something. He gave it back.', salvi: 'Salvi has never been ill a day. Men like that are ill in other ways.', tilda: 'Tilda Rask should have been in my care years ago. Grief is not a disease. It is a climate.', keeper: 'Garrow drinks. Not much. Enough to cross things out.', ledoux: 'Ledoux has hands that shake in the morning and not at sea. I know what that means.' },
      topics: [
        { id: 'night', q: 'Where were you on the 11th?', a: 'The Infirmary. All night. Nurse Ives will say so. She will also say I went out at one for an hour. She is honest.' },
        { id: 'certificate', q: 'You wrote drowning. Then you wrote the truth.', a: 'I wrote drowning at one because that is what it looked like. I looked again at two. The wound went up. I wrote it down. That is not a crime. It is the opposite.' },
        { id: 'out', q: 'Where did you go at one?', a: 'She looks at her hands. To the pier. To see him. Kite had called. I stood in the salt and looked at him for an hour and then I came back and washed my hands and did my job.', after: 'night', cost: 1, effect: { type: 'suspectTrait', suspectId: 'fenn' } },
        { id: 'bask', q: 'What was Bask to you?', a: 'A patient. Then not only a patient. Four years. Nobody in this harbour knew, which tells you how good the harbour is at knowing things.', after: 'out' },
        { id: 'knife', q: 'He asked you how a man is killed with a knife under the ribs.', a: 'On the 10th. I told him. Up, from below, toward the heart. I thought he was asking so he could see it coming. He did not see it coming. Whoever did it had listened better than he had.', after: 'bask', cost: 1, effect: { type: 'lead' } },
      ] },
    { id: 'ledoux', name: 'Marcel Ledoux', role: 'Trawler skipper',
      blurb: 'Trawler captain. Big man, scar across his left thumb. Goes out empty, comes back full.',
      motive: 'because Bask had counted the boats, and on Thursday he was going to say the Marie-Louise out loud.',
      bio: 'Forty. Captain of the Marie-Louise. Big, with a scar across his left thumb from a winch cable. He goes out with no nets and comes back low in the water. Everyone in the harbour knows. Bask had started writing it down.',
      alibi: 'At sea. Out at eleven, back at three. The harbourmaster’s log shows it.',
      secret: 'There was no ‘big one’ in the dinghy. He rowed himself to Pier Nine, killed Bask the way the doctor had once described to Bask over dinner, sewed the pockets, and rowed back alone. Salvi paid for the salt.',
      opinions: { hollis: 'Hollis never came down to the berths. Bask came every week. That is the difference.', wren: 'The inspector signs. I sail. Neither of us looks in the hold.', okafor: 'Okafor sells me line and looks at me like I am going to hang myself with it.', salvi: 'Salvi owns the boat. On paper the boat is mine. On paper I am a fisherman.', tilda: 'The widow will not look at me. I was a boy on her husband’s boat. I was sick. That is all I did.', keeper: 'Garrow sees me land. Every time. He has never once said a word. I put fifty dollars up his stair and it comes back down.', fenn: 'The doctor is the only one in this harbour who ever asked me if I was all right. I said yes. It was not true.' },
      topics: [
        { id: 'night', q: 'Where were you on the 11th?', a: 'At sea. Out at eleven. Back at three. The harbourmaster has it.' },
        { id: 'empty', q: 'Out empty. Back heavy.', a: 'Cargo. Off the Corvina. Into the ice house. Salvi’s. I do not open it. I have a boat because I do not open it.' },
        { id: 'dinghy', q: 'The keeper logged a dinghy. Two out. One back.', a: 'He is quiet a long time. Two men off my boat at Pier Nine at half eleven. One came back to the boat at half one. I was told to wait and I waited. I was paid not to ask.', after: 'empty', cost: 1, effect: { type: 'suspectTrait', suspectId: 'ledoux' } },
        { id: 'who', q: 'Who came back?', a: 'The big one. Scar on the thumb. Wet to the waist. He sat in the bow and did not say a word all the way to the point. He got off under the light and went up the stair.', after: 'dinghy', cost: 1, effect: { type: 'culpritTrait' } },
        { id: 'wireless', q: 'STOP AT THE USUAL.', a: 'The usual is the old salt stair under the point. Everyone who lands without a light lands there. That is where I put him off.' },
      ] },
  ],

  culprit: 'ledoux',

  witnesses: [
    { id: 'teague', at: 'brine', name: 'Mags Teague', role: 'landlady, the Brine & Bell',
      intro: 'Mags Teague. Forty men drink in my pub every night. I know what each one drinks and what each one owes.',
      bio: 'Thirty years behind the bar. She has buried a husband and two barmen. She keeps the tabs in her head and the grudges in a book.',
      knows: ['hollis', 'ledoux', 'tilda'],
      aboutLine: 'They drink in my pub. I could draw their face from memory.',
      leadLine: 'Somebody paid off a tab tonight that had been open since March. In coins. They came in from the direction of',
      spentLine: 'Last orders was an hour ago. That goes for questions too.',
      opinions: { hollis: 'Dov was in from ten till one with his flask, not celebrating. He had lost something. Money, I think.', ledoux: 'Ledoux does not drink here on sailing nights. He was not here. He was at sea, or he was where the sea is.', tilda: 'Mrs. Rask has not been in this house since ’41. She stands outside sometimes. I leave the door open.' },
      topics: [
        { id: 'night', q: 'Who was in on the 11th?', a: 'Forty men who saw nothing. Hollis with his flask. A big man at the end of the bar who paid a tab from March in coin and left without finishing his drink.' },
        { id: 'tab', q: 'Whose tab?', a: 'Not his own. He paid Okafor’s. Okafor was not here. The big man had a scar across his thumb and kept it on the bar like he wanted me to see it.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Did Bask drink here?', a: 'Twenty years. Same stool. He was in on the 10th and he said, Mags, if I do not come in tomorrow, look at who does. I laughed. I am not laughing.' },
      ] },
    { id: 'aldous', at: 'customs', name: 'Percy Aldous', role: 'night clerk, the Customs House',
      intro: 'Percy Aldous. I copy the shipping manifests. Every crate in this harbour crosses my desk twice: once as it really is, and once as it’s declared.',
      bio: 'Twenty-six. Copies manifests in handwriting so neat the inspectors never read them. He has read all of them.',
      knows: ['wren', 'salvi'],
      aboutLine: 'They sign my book. You notice a person’s handwriting.',
      leadLine: 'Somebody altered a manifest tonight. The ink is still wet. The crate it describes is at',
      spentLine: 'I’m a clerk. Clerks don’t know things. Please close the door.',
      opinions: { wren: 'Miss Wren left at eleven. Her initials were dry. At midnight they were wet again and they were not hers.', salvi: 'Mr. Salvi comes to the Customs House once a month and leaves an envelope. I copy manifests. I do not copy envelopes.' },
      topics: [
        { id: 'night', q: 'What happened here on the 11th?', a: 'Miss Wren left at eleven. At midnight somebody came in with a key and added initials to the Corvina manifest. Not hers. Close enough for a judge. Not close enough for me.' },
        { id: 'ink', q: 'Whose ink?', a: 'A fountain pen with a broad nib. Miss Wren uses a fine one. The only broad nib in this harbour that I know of is in a shipping office.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Did Bask come here?', a: 'The 9th. He read the manifest at my desk and copied it into a little book. He asked me if I had ever opened a Corvina crate. I said I was a clerk. He said, so was I, once.' },
      ] },
    { id: 'vetch', at: 'chandler', name: 'Young Vetch', role: 'apprentice, Vetch & Son',
      intro: 'Tom Vetch. I’m the ‘Son’ on the sign. Everyone in this harbour buys rope from us. I cut it for them.',
      bio: 'Nineteen. Grandson of the name on the shop sign. He cuts rope for Okafor and watches Okafor more closely than Okafor knows.',
      knows: ['okafor', 'salvi', 'fenn'],
      aboutLine: 'A customer. I measure their rope. I’ve measured them too.',
      leadLine: 'Somebody bought forty feet of line tonight and paid double to keep it quiet. They took it to',
      spentLine: 'My dad says not to talk to police. I’ve talked enough.',
      opinions: { okafor: 'Mr. Okafor signed for the line himself. A man had a hand on his hand. I saw it from the back.', salvi: 'Salvi’s crews buy the good line and pay cash and never come back for the same length.', fenn: 'The doctor bought a scalpel from us last month. She said the Infirmary was out. I did not believe her.' },
      topics: [
        { id: 'night', q: 'What sold on the 11th?', a: 'Forty feet of quarter-inch and a size fourteen needle. That is a coat, not a sail. The buyer paid double to have it cut quiet and Mr. Okafor signed for it himself with the buyer’s hand on his.' },
        { id: 'buyer', q: 'Describe the buyer.', a: 'Big. A scar across the thumb of the hand on Mr. Okafor’s hand. Boots that had been in the ice house. He did not look at me once.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Did Bask buy from you?', a: 'Every week. He bought a padlock on the 10th. A big one. For the union hall back office, he said. Somebody opened that office anyway.' },
      ] },
    { id: 'kite', at: 'morgue', name: 'Amos Kite', role: 'attendant, Harbour Morgue',
      intro: 'Amos Kite. I look after the dead. They’re better company than you’d think, and worse than you’d hope.',
      bio: 'Fifteen years at the morgue. He washes the bodies and reads every certificate twice. He notices when they change.',
      knows: ['fenn', 'tilda'],
      aboutLine: 'They came down to see Bask. People give themselves away when they stand over a body.',
      leadLine: 'A visitor left something in the coat room and never came back for it. It was sent on to',
      spentLine: 'I have three bodies to wash before morning. Find your own way out.',
      opinions: { fenn: 'Dr. Fenn wrote drowning at one and went out. She came back at two with her hands washed and wrote the truth over it.', tilda: 'Mrs. Rask came at five and asked to see him. I let her. She looked at his pockets and nodded like something had been confirmed.' },
      topics: [
        { id: 'night', q: 'Tell me about the body.', a: 'Pockets sewn shut. Sailcloth thread, size fourteen needle. Rock salt, a hundredweight between the two. Wound under the ribs, upward. Whoever did it had done it on a boat, on his knees.' },
        { id: 'visitors', q: 'Who came to see him?', a: 'The doctor at one, and again at two. The widow at five. And a big man at six who stood in the corridor and did not come in. He had a scar across his thumb and he was crying.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'salt', q: 'The salt.', a: 'Rock salt. Works salt. Bagged. Somebody carried a hundredweight to the pier on his shoulder and did not use a cart. That is a big man or a desperate one.' },
      ] },
    { id: 'pell', at: 'trawler', name: 'Iggy Pell', role: 'deckhand',
      intro: 'Iggy Pell. I mend nets and I keep my head down. Tonight I looked up once. That was once too many.',
      bio: 'Twenty-two. Deckhand on the Marie-Louise for two years. Nobody has ever told him what is in the hold.',
      knows: ['ledoux', 'hollis', 'keeper'],
      aboutLine: 'They work the boats. You get to know a person by how they walk on a wet deck.',
      leadLine: 'Something was thrown off a boat and it floated. It washed up near',
      spentLine: 'I told you, I keep my head down. I’m putting it back down now.',
      opinions: { ledoux: 'The skipper put two men ashore in the dinghy and waited two hours. He smoked the whole time. He never smokes at sea.', hollis: 'Hollis came down to the berths once, in ’46. He was sick over the side. Bask laughed.', keeper: 'The keeper sees us land. He waves. Then he goes inside and writes.' },
      topics: [
        { id: 'night', q: 'What did you see from the deck?', a: 'The dinghy go out with two. Come back with one. The skipper smoking. Something thrown off the end of the pier that floated. A bag.' },
        { id: 'bag', q: 'Where did the bag go?', a: 'With the tide. Toward the salt works. It fetched up on the outfall. It was a coat, with the pockets cut out.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'hold', q: 'What is in the hold?', a: 'I have never been told. I have smelled it. It is not fish. It is what the cannery cans when there are no fish.' },
      ] },
    { id: 'harrow', at: 'baths', name: 'Nell Harrow', role: 'attendant, Harbour Baths',
      intro: 'Nell Harrow. I hand out the towels and take the tickets. Nobody has pockets in here. That’s why they talk.',
      bio: 'Has run the public baths since her father died. She hears the whole harbour with its clothes off.',
      knows: ['wren', 'tilda', 'keeper'],
      aboutLine: 'They bathe here. You can’t hide much in a towel.',
      leadLine: 'A coat was left in the changing room with something heavy sewn into the lining. Its owner ran off toward',
      spentLine: 'We close at two. That’s all I have.',
      opinions: { wren: 'Miss Wren bathes on Tuesdays and cries in the steam where she thinks nobody hears.', tilda: 'Mrs. Rask has not been in since ’41. Her husband bathed here every Friday.', keeper: 'Garrow comes down from the light once a month and sits in the hot room like a man being boiled clean of something.' },
      topics: [
        { id: 'night', q: 'Who came through the baths?', a: 'A big man at two, wet to the waist, who wanted the hot room and would not take a towel. He left his coat in seventeen with something sewn in the lining.' },
        { id: 'lining', q: 'What was in the lining?', a: 'A key. Bond Store twelve is stamped on it. He ran when I found it. He ran toward the ice house.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Did Bask bathe here?', a: 'Fridays. Twenty years. The 10th he sat in the hot room and told me the union was about to find out what it had been carrying. I thought he meant dues.' },
      ] },
    { id: 'gault', at: 'harbourmaster', name: 'Ruth Gault', role: 'clerk, Harbourmaster’s Office',
      intro: 'Ruth Gault. I log the boats. In, out, weight, captain. When the log and the water disagree, I write down what the water says.',
      bio: 'Twelve years logging the boats. Her father was a captain who went out empty and never came back. She writes down the truth.',
      knows: ['wren', 'salvi', 'keeper'],
      aboutLine: 'They come to my counter. You learn a person by how they lie about the weight of their cargo.',
      leadLine: 'A boat went out at eleven with no cargo declared and came back at three sitting low in the water. It tied up at',
      spentLine: 'The office is closed. The log is locked.',
      opinions: { wren: 'Miss Wren’s stamps and my log should agree. Since the Corvina they have not once.', salvi: 'Salvi declares tonnage like a man declaring his age.', keeper: 'Garrow and I keep the same log from opposite ends of the harbour. Mine is honest. His is crossed out.' },
      topics: [
        { id: 'night', q: 'What moved on the 11th?', a: 'Marie-Louise out at eleven, nothing declared. Back at three, riding low. High water at one-forty. I wrote low with a question mark. The question mark is mine.' },
        { id: 'low', q: 'Riding low with what?', a: 'Corvina cargo, to the ice house. And a passenger. The keeper would have seen him land. Ask the keeper what he crossed out.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Bask came to this office.', a: 'The 9th. He read six weeks of movements and copied every Marie-Louise line into a book. He said, Ruth, you have been writing it all down. I said somebody had to.' },
      ] },
    { id: 'sparks', at: 'marconi', name: 'Tommy Sparks', role: 'wireless operator',
      intro: 'They call me Sparks. Real name’s Tomasz. Every wireless message on the water comes through these headphones. Most of them are about fish. Most.',
      bio: 'Polish navy, then the Marconi station. He can tell who is sending by the rhythm of their tapping. He keeps a second log the company does not know about.',
      knows: ['keeper', 'salvi', 'ledoux'],
      aboutLine: 'They send messages through me. You can tell a person by the way they tap a key.',
      leadLine: 'A message went out to a boat at one in the morning: ‘STOP AT THE USUAL PLACE.’ In this harbour, the usual place is',
      spentLine: 'I have a ship calling. It isn’t you.',
      opinions: { keeper: 'Garrow has no wireless. He does not need one. He has a lamp and a grudge.', salvi: 'Salvi’s messages are all about fish and none of them mention a fish by name.', ledoux: 'Ledoux’s fist on a key is heavy and slow. Like a man who does not want to be understood.' },
      topics: [
        { id: 'night', q: 'What went over the wire?', a: 'One-oh-four: to the Marie-Louise, STOP AT THE USUAL. One-oh-six: UNDERSTOOD. Three-twelve: ALL DONE. I have underlined the last one twice because I know what it means.' },
        { id: 'sent', q: 'Who sent the first one?', a: 'From the shipping office key. Salvi’s. But the fist was not Salvi’s. Salvi taps like a bird. This was a hammer.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Did Bask send anything?', a: 'The 10th. To the union office in the city. ONE MORE THING TO CHECK THEN I NAME THEM. I sent it. I have not slept since.' },
      ] },
    { id: 'brack', at: 'hall', name: 'Mabel Brack', role: 'caretaker, the Hall',
      intro: 'Mabel Brack. I clean the hall after the meetings. I’ve cleaned up after every man who ever wanted to run this union.',
      bio: 'Caretaker of the union hall for twenty-two years. Before that she cleaned for Ambrose Rask. She trusts nobody who wants the chairman’s chair.',
      knows: ['hollis', 'tilda', 'okafor'],
      aboutLine: 'They sit in that hall every Thursday. I’ve swept around their feet for years.',
      leadLine: 'The back office was opened after the meeting with a key that wasn’t the vice-chairman’s. Whatever was taken went to',
      spentLine: 'The hall is locked. I’m going home.',
      opinions: { hollis: 'Dov left at midnight. He came back at half one and sat in the dark. I let him. A man needs to sit in the dark sometimes.', tilda: 'Mrs. Rask has a key to the Hall from ’41. Nobody took it back. She has never used it.', okafor: 'Bernard came to the Hall on the 10th to beg Bask for time. Bask gave him a week. That was the 9th plus a week. He did not need it.' },
      topics: [
        { id: 'night', q: 'What happened at the Hall?', a: 'The ballot committee till midnight. Then quiet. Then at one somebody opened the back office with a key that was not the vice-chair’s, and left with Bask’s little book.' },
        { id: 'book', q: 'What book?', a: 'The one he wrote the boats in. He kept it in the back office. It is gone. Whoever has it has the whole harbour.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Twenty years. What was he like?', a: 'He never sat down in this hall. Not once. He stood at the back like a man who did not expect to be allowed to stay.' },
      ] },
    { id: 'delacroix', at: 'printers', name: 'Émile Delacroix', role: 'typesetter, the Docker’s Voice',
      intro: 'Émile Delacroix. I set the type for the union newspaper. I know every word before the union does, and I know who wanted which words changed.',
      bio: 'Set type in Lyon, then here. He reads the union’s mind one letter at a time and keeps every page that was pulled before printing.',
      knows: ['hollis', 'tilda'],
      aboutLine: 'They bring me their articles. You learn a person by what they cross out.',
      leadLine: 'Somebody pulled a notice from tomorrow’s paper at midnight. They had no business in my shop. They left toward',
      spentLine: 'The press is running. Mind your fingers on the way out.',
      opinions: { hollis: 'Hollis brings copy that says nothing and crosses out the nothing twice.', tilda: 'Mrs. Rask placed a notice every year on the anniversary. This year she placed it early.' },
      topics: [
        { id: 'night', q: 'What was pulled from the Voice?', a: 'Bask’s notice. The Chairman will address the membership on the matter of the Corvina and the berths. Set, proofed, pulled at midnight by a man with a key to my shop.' },
        { id: 'key', q: 'Who has a key?', a: 'The chairman. The vice-chair. And the man who pays for the paper, which is not the union. He walked out toward the shipping office.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Did Bask write for the Voice?', a: 'Every week for twenty years. Plain words. Short lines. The last thing he set was: If I am not at the vote, ask why.' },
      ] },
    { id: 'oyelaran', at: 'bondstore', name: 'Femi Oyelaran', role: 'watchman, Bond Store 12',
      intro: 'Femi Oyelaran. I’ve guarded these crates for six weeks. In six weeks nobody came for them. Until tonight.',
      bio: 'He was a customs officer in Lagos. Here they only let him guard the crates, so he inspects them with his eyes.',
      knows: ['wren', 'salvi', 'ledoux'],
      aboutLine: 'They come to look at the seals. You learn a person by how they look at a seal they aren’t allowed to break.',
      leadLine: 'One crate was opened and closed again, badly. Whatever came out of it went along the quay to',
      spentLine: 'I have crates to watch. I’m watching them.',
      opinions: { wren: 'Miss Wren initials at the door and does not come in. I have offered her a lamp. She has never taken it.', salvi: 'Salvi’s name is on the manifest and on the seals and on the envelope he leaves for me, which I have not opened.', ledoux: 'Ledoux breaks a seal like a man opening a beer.' },
      topics: [
        { id: 'night', q: 'Which crate was opened?', a: 'Bay four. Seal four-four-seven-one. One twist. Ledoux, on Salvi’s word, at one. He took out something long and wrapped and put it on a cart.' },
        { id: 'long', q: 'Something long.', a: 'A bundle. Sailcloth. It went to the pier. I know what it was. I would rather you found out from somebody else.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Bask came to the bond store.', a: 'The 9th. He asked me what was in the crates. I said I was a watchman. He said, then watch. I have been watching since.' },
      ] },
    { id: 'mott', at: 'excise', name: 'Nan Mott', role: 'owner, Dockside Café',
      intro: 'Nan Mott. Tea is a penny. For another penny I’ll tell you who drank it. Bask drank his tea here every morning for twenty years.',
      bio: 'Has fed the harbour for thirty years. Bask sat at her counter every morning and told her nothing, which is how she came to know everything.',
      knows: ['hollis', 'okafor', 'fenn'],
      aboutLine: 'They take tea here. I’ve set a cup in front of them a thousand times.',
      leadLine: 'Somebody left a newspaper folded around something heavy and never came back for it. Somebody else took it to',
      spentLine: 'The kettle’s off. So am I.',
      opinions: { hollis: 'Dov sat with Bask an hour on the 10th and left angry. Bask stayed and did not touch his tea.', okafor: 'Bernard was here till ten on the 11th with a cup he did not drink and a face like a debt.', fenn: 'The doctor takes her tea at six after nights. On the 12th she did not come.' },
      topics: [
        { id: 'night', q: 'Who was in on the 11th?', a: 'Okafor till ten. A big man after him who sat in Okafor’s seat while it was still warm and ordered nothing. He left a newspaper folded round something heavy.' },
        { id: 'paper', q: 'What was in the newspaper?', a: 'A needle. Sailmaker’s. And a spool of thread. I put it under the counter. Somebody came for it at midnight and I gave it to them because he had a scar across his thumb and I did not want to argue.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Twenty years of tea.', a: 'A penny a day. He never once asked for credit. The 10th he sat with Hollis and they argued about a name. Not Hollis’s. Somebody Bask was going to say out loud on Thursday.' },
      ] },
    { id: 'penrose', at: 'chapel', name: 'Aldo Penrose', role: 'verger, Fishermen’s Chapel',
      intro: 'Aldo Penrose. I polish the brass plaque and read out the names of the drowned. There’s a new name on it this week, in chalk. I didn’t write it.',
      bio: 'Verger for thirty years. He reads the names of the drowned every Sunday. He knew Ambrose Rask, and he knows who was on the boat.',
      knows: ['tilda', 'keeper'],
      aboutLine: 'They come to the plaque. You learn a person by which name they touch.',
      leadLine: 'Somebody knelt here at four in the morning with sand on their knees and left something in the charity box. It was carried off to',
      spentLine: 'The chapel is open to everyone. Everyone except you, tonight.',
      opinions: { tilda: 'Mrs. Rask comes on the anniversary and touches one name. This year she came early and wrote another.', keeper: 'Garrow has not set foot in the chapel since ’41. He stands at the door.' },
      topics: [
        { id: 'night', q: 'Who wrote the chalk?', a: 'The widow. Four in the morning. Sand on her knees from the beach. Somebody had told her, and she came to write it before it was true.' },
        { id: 'poorbox', q: 'Something was left in the poor box.', a: 'A padlock key. Big. Bask’s, from the Hall back office. Whoever opened that office put the key where a priest would find it. Guilt, or a joke.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'rask', q: 'Ambrose Rask.', a: 'First name on the brass under 1941. Bask paid for the brass. He came every year and stood in front of it and did not pray. He was not a praying man. He was a remembering one.' },
      ] },
    { id: 'sable', at: 'coastguard', name: 'Jean Sable', role: 'petty officer, Coastguard',
      intro: 'Jean Sable, Coastguard. I log every boat that crosses the Narrows after dark. I also know which ones aren’t in the log.',
      bio: 'Coastguard for eleven years. She takes a bearing on every boat without a light and files it, whether or not anyone reads it.',
      knows: ['keeper', 'ledoux'],
      aboutLine: 'They pass under my telescope. You learn a person by how they stand at a wheel.',
      leadLine: 'A rowing boat with no lights crossed at half past two and landed below',
      spentLine: 'The watch changes at six. Ask somebody else.',
      opinions: { keeper: 'Garrow and I see the same water. He logs what he is paid to. I log what I see. We have never compared.', ledoux: 'Ledoux stands at his wheel like a man who has been told where to go and would rather not.' },
      topics: [
        { id: 'night', q: 'What crossed the Narrows?', a: 'The Marie-Louise out at eleven with no light. A dinghy at half eleven to Pier Nine. The dinghy back at half one with one man. Beached under the old salt stair.' },
        { id: 'man', q: 'The one man.', a: 'Big. Wet to the waist. He went up the stair and along the cliff and I lost him at the light. Garrow did not lose him. Garrow crossed him out.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Did Bask ever come to the tower?', a: 'The 9th. He asked to see six weeks of crossings. I gave them to him. He said, so it is all written down, and I said it always was, nobody asked.' },
      ] },
    { id: 'ives', at: 'hospital', name: 'Maud Ives', role: 'nurse, Seamen’s Infirmary',
      intro: 'Nurse Ives. I run Dr. Fenn’s wards. I run them better than she runs her paperwork.',
      bio: 'Nursed through the war. She runs the wards, keeps an eye on the doctor, and keeps her opinions of both to herself.',
      knows: ['fenn', 'hollis', 'okafor'],
      aboutLine: 'They’ve been through my ward. You don’t forget a patient. Or a visitor.',
      leadLine: 'A bag came in with a patient and left without him. The porter carried it to',
      spentLine: 'I’m doing my rounds. If you’re not bleeding, out.',
      opinions: { fenn: 'Dr. Fenn went out at one and came back at two with her hands washed. She wrote drowning before she went and the truth after.', hollis: 'Mr. Hollis has a heart. He came in on the 10th with palpitations and would not say what had caused them.', okafor: 'Bernard Okafor came in on the 12th with a cut hand he said was rope. Rope does not cut like that.' },
      topics: [
        { id: 'night', q: 'What came into the Infirmary?', a: 'A man at four with a bag. He left without the bag. The bag had a coat in it with the pockets cut out and salt in the seams.' },
        { id: 'bag', q: 'Where is the bag?', a: 'The porter took it to the ice house because that is where the man said he worked. He did not work there. He had a scar across his thumb.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Bask was here on the 10th.', a: 'For an hour. With the doctor. Not as a patient. When he left she sat in the dispensary and did not move for a long time.' },
      ] },
    { id: 'cully', at: 'icehouse', name: 'Bram Cully', role: 'foreman, the Ice House',
      intro: 'Bram Cully. I cut the ice and stack it. Tonight a block came back with a hole cut in it the size of a man.',
      bio: 'Foreman at the ice house for nine years. He sells ice to fishing boats, and to people who have no fishing boats, and does not ask which is which.',
      knows: ['ledoux', 'salvi'],
      aboutLine: 'They buy ice from me. You learn a person by what they need to keep cold.',
      leadLine: 'A cart came for ice at three in the morning with no reason to need it. It went toward',
      spentLine: 'Ice doesn’t wait. Neither do I.',
      opinions: { ledoux: 'Ledoux unloads into my ice house at three in the morning and I do not cut the blocks he uses.', salvi: 'Salvi buys ice for a shipping office. Shipping offices do not need ice. Unless they do.' },
      topics: [
        { id: 'night', q: 'What came through the ice house?', a: 'Corvina cargo off the Marie-Louise at three. Two blocks for Salvi’s back room. And a man who sat in the cold room for an hour with his coat off and his hands in the ice.' },
        { id: 'hands', q: 'Why the ice?', a: 'He had cut them. Both. On glass or on a knife. He had a scar across the thumb already and he was making new ones. He went from here toward the mission.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Did Bask come here?', a: 'The 9th. He walked the cold room and counted crates and wrote in a book. He said, Bram, this is not fish. I said, no, it is not.' },
      ] },
    { id: 'lundy', at: 'pawnshop', name: 'Ma Lundy', role: 'pawnbroker',
      intro: 'Ma Lundy. Everything in this harbour ends up in my shop window sooner or later. Tonight something came in that I won’t put in the window.',
      bio: 'Forty years in the pawnshop. She lends money on sextants, rings and knives, and she looks hard at the hands that hand them over.',
      knows: ['okafor', 'tilda', 'ledoux'],
      aboutLine: 'They pawn things with me. I look at their hands.',
      leadLine: 'A pawn ticket was paid off at midnight, in cash, by somebody who wasn’t the person who pawned the item. They went to',
      spentLine: 'The shop is shut. I’ve said more than I should.',
      opinions: { okafor: 'Bernard pawned his knife in March to eat. He would not have redeemed it. He could not.', tilda: 'Mrs. Rask pawned her wedding ring in ’42 and redeemed it in ’43 and has not been back.', ledoux: 'Ledoux pawns nothing. Men who never need money are men who are paid in cash.' },
      topics: [
        { id: 'night', q: 'Who redeemed the knife?', a: 'A big man. Midnight. Cash. A scar across his thumb. He paid Okafor’s ticket with a note that had been in the sea. It was still damp.' },
        { id: 'where', q: 'Where did he go?', a: 'Up the row toward the Brine. With the knife in his coat and his hand on it.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Did Bask pawn?', a: 'Never. He came in on the 10th and bought a thing. A sailmaker’s needle, from the tray. He said it was for a coat. I thought nothing of it. I think of nothing else now.' },
      ] },
    { id: 'rook', at: 'tram', name: 'Tamsin Rook', role: 'conductor, the quay tram',
      intro: 'Tamsin Rook. I’m the conductor on the last tram along the quay at midnight. I punch the tickets, and I remember the people who’d rather I didn’t.',
      bio: 'Drove ambulances in the war. Now she punches tram tickets and remembers every face that would prefer to be forgotten.',
      knows: ['hollis', 'fenn', 'wren'],
      aboutLine: 'They ride my tram. You learn a person by where they refuse to sit.',
      leadLine: 'Somebody rode to the end of the line and then walked back the way we’d come, toward',
      spentLine: 'The tram’s in the shed. So am I.',
      opinions: { hollis: 'Mr. Hollis rode to the Brine at ten and did not ride back. He walked. Slowly.', fenn: 'The doctor rode toward the pier at one with her bag. She never takes the tram. She was not thinking.', wren: 'Miss Wren rides home at eleven every night and sits at the front and does not look at anyone.' },
      topics: [
        { id: 'night', q: 'Who rode the last car?', a: 'Eleven. The doctor with her bag. A big man in a wet coat who rode to the end and walked back. Miss Wren at the front, not looking.' },
        { id: 'walked', q: 'The one who walked back.', a: 'Toward the salt works. He had a hundredweight of something on his shoulder before and nothing after. His hands were cut.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Did Bask ride?', a: 'Every night for twenty years, standing at the back. The 11th he did not ride. I noticed. I did not say anything. Who would I say it to.' },
      ] },
    { id: 'orme', at: 'saltworks', name: 'Jack Orme', role: 'night man, the Salt Works',
      intro: 'Jack Orme. I bag salt. A hundredweight a bag, six hundred bags a night. Tonight I’m one bag short.',
      bio: 'Twenty years bagging salt. He can tell who carried a hundredweight by the way they walk afterwards.',
      knows: ['okafor', 'ledoux'],
      aboutLine: 'They come here for salt. You learn a person by how much they can carry.',
      leadLine: 'The missing bag went out on somebody’s shoulder. That somebody walked up the lane toward',
      spentLine: 'The kilns need feeding. You don’t.',
      opinions: { okafor: 'Okafor buys salt for the chandlery by the bag. He has not bought a bag since March.', ledoux: 'Ledoux buys salt by the ton for fish he does not catch.' },
      topics: [
        { id: 'night', q: 'One bag short.', a: 'Carried out on a shoulder at ten. No cart. A big man. He walked up the lane toward the quay like it weighed nothing.' },
        { id: 'lane', q: 'Where does the lane go?', a: 'To the pier, if you keep walking. He kept walking.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Did Bask ever come to the works?', a: 'The 9th. He stood at the kilns and asked me who buys rock salt by the hundredweight. I said fishermen. He said, name one.' },
      ] },
    { id: 'fry', at: 'seamen', name: 'Brother Fry', role: 'warden, Seamen’s Mission',
      intro: 'Brother Fry. Forty beds and a stove. I count the men in at ten and count them again in the morning. The numbers don’t always match.',
      bio: 'He was a sailor, then a drunk. Now he keeps forty beds at the Seamen’s Mission and counts them like a man who knows what an empty one means.',
      knows: ['tilda', 'keeper', 'hollis'],
      aboutLine: 'They sleep here sometimes. You learn a person by what they say in their sleep.',
      leadLine: 'A man came in at four with his boots full of water and left at five without his bundle. He went toward',
      spentLine: 'The men are sleeping. Keep your voice down and go.',
      opinions: { tilda: 'Mrs. Rask sends blankets every winter with her husband’s name sewn in. I take the name out. She knows I do.', keeper: 'Garrow sleeps here when the light gets too much. He talks in his sleep about a boat.', hollis: 'Dov Hollis slept here on the 11th. Cot thirty-one. In and out all night. He said his wife had locked the door.' },
      topics: [
        { id: 'night', q: 'Cot thirty-one.', a: 'In at ten, out at four, in at five, out at six. Wet. A big man. He said nothing. He left a bundle at five and I have not opened it.' },
        { id: 'bundle', q: 'Open it.', a: 'A coat. Pockets cut out. Salt in the seams. And a padlock, big, with the hasp cut through.', after: 'night', cost: 1, effect: { type: 'lead' } },
        { id: 'bask', q: 'Did Bask come to the mission?', a: 'He paid for the stove. Every winter. He never came in. He stood at the door and counted the cots through the window and left.' },
      ] },
  ],

  items: [
    { id: 'item:salt:autopsy-cert', at: 'morgue', kind: 'report', label: 'Death certificate, first draft', stamp: 'CONFIDENTIAL',
      source: 'HARBOUR MORGUE · CERTIFICATES', title: 'Certificate of death, Bask, A.',
      fields: [['Cause', 'drowning (struck through)'], ['Cause, amended', 'wound, left side, upward'], ['Signed', 'I. Fenn, M.D.'], ['Time signed', 'before the body was cold']],
      body: ['She wrote drowning, and then she wrote the truth over it. The morgue attendant watched her write both and remembers the hand.'],
      spoken: 'A death certificate with drowning struck through and the truth written over it.',
      reading: 'Kite, the morgue attendant, watched Dr. Fenn write it. It tells you something about her. Check her row in the Notebook.', about: ['fenn'], effect: { type: 'suspectTrait', suspectId: 'fenn' } },
    { id: 'item:salt:salt-bag', at: 'saltworks', kind: 'report', label: 'Bag count, night of the 11th',
      source: 'THE SALT WORKS · TALLY', title: 'Kiln 3, night tally',
      body: ['Six hundred bagged, five hundred and ninety-nine on the pallet. The one that walked was a hundredweight, and the man who carried it did not use a cart.', 'It takes a certain kind of back to walk off with a hundredweight of salt.'],
      spoken: 'The salt works tally, one bag short, and no cart used to carry it.',
      reading: 'Background. One bag of salt was carried off on somebody’s shoulder, without a cart. That takes a strong back. Nothing to mark.', effect: { type: 'none' } },
    { id: 'item:salt:ballot', at: 'hall', kind: 'note', label: 'Draft ballot, Thursday’s vote',
      source: 'LONGSHOREMEN’S HALL · BACK OFFICE', title: 'Ballot, for the office of chairman',
      body: ['Two names typed. One name crossed out in pen so hard the nib split. The name crossed out is the dead man’s. The name left is not the vice-chair’s.'],
      spoken: 'A draft ballot with the dead man’s name crossed out hard enough to split the nib.',
      reading: 'Background. Somebody other than Hollis expected to win. Nothing to mark.', about: ['hollis'], effect: { type: 'none' } },
    { id: 'item:salt:manifest', at: 'customs', kind: 'ledger', label: 'Manifest, six weeks sat on', stamp: 'COPY',
      source: 'THE CUSTOMS HOUSE · INSPECTIONS', title: 'Manifest, SS Corvina',
      body: ['Every page initialled E.W. — passed without inspection. On the last page, a second set of initials in a different ink, added tonight, over hers.', 'Aldous watched the second hand write.'],
      spoken: 'The manifest Customs sat on for six weeks, with a second set of initials added tonight.',
      reading: 'The clerk saw who added the second initials. It tells you something about Etta Wren. Check her row in the Notebook.', about: ['wren'], effect: { type: 'suspectTrait', suspectId: 'wren' } },
    { id: 'item:salt:wireless', at: 'marconi', kind: 'note', label: 'Wireless log, the 11th',
      source: 'MARCONI STATION · TRAFFIC LOG', title: 'Traffic, night of the 11th',
      body: ['01:04 — to trawler MARIE-LOUISE — STOP AT THE USUAL. 01:06 — reply — UNDERSTOOD. 03:12 — MARIE-LOUISE — ALL DONE.', 'The operator has underlined the third line twice.'],
      spoken: 'The wireless log: stop at the usual, understood, and at three, all done.',
      reading: 'A boat was told where to stop. The operator knows where ‘the usual place’ is. A red mark on the map shows it.', about: ['ledoux'], effect: { type: 'lead' } },
    { id: 'item:salt:knife', at: 'pawnshop', kind: 'ticket', label: 'Pawn ticket, one knife',
      source: 'LUNDY’S PAWN · TICKETS', title: 'Ticket no. 3391',
      fields: [['Item', 'knife, rigging, bone handle'], ['Pledged', 'the 9th'], ['Redeemed', 'the 11th, midnight, cash'], ['By', 'not the pledger']],
      body: ['Pledged by one hand and redeemed by another. Ma Lundy looked hard at the second pair of hands.'],
      spoken: 'A pawn ticket for a rigging knife, redeemed at midnight by somebody who did not pledge it.',
      reading: 'Ma Lundy looked at the hands that took the knife. A red mark on the map shows where they went.', effect: { type: 'lead' } },
    { id: 'item:salt:voice', at: 'printers', kind: 'clipping', label: 'The Docker’s Voice, pulled notice',
      source: 'THE DOCKER’S VOICE · PROOF', title: 'Notice, pulled before press',
      body: ['“The Chairman will address the membership Thursday on the matter of the Corvina and the trawler berths. Members are asked to attend.” Set in type, proofed, pulled at midnight.', 'Somebody did not want three thousand men to hear about the berths.'],
      spoken: 'A notice pulled from the union paper at midnight, about the trawler berths.',
      reading: 'Bask was going to talk about the trawler berths. A motive for half the harbour. Nothing to mark.', about: ['ledoux', 'salvi'], effect: { type: 'none' } },
    { id: 'item:salt:tide-table', at: 'harbourmaster', kind: 'ledger', label: 'Tide and movements log', stamp: 'COPY',
      source: 'HARBOURMASTER’S OFFICE · LOG', title: 'Movements, night of the 11th',
      body: ['23:10 — MARIE-LOUISE out, no cargo. 03:05 — MARIE-LOUISE in, riding low. High water 01:40. The clerk has written “low?” beside the return and underlined it.'],
      spoken: 'The movements log: a trawler out at eleven with nothing, and back at three riding low.',
      reading: 'Background. The boat came back heavier than it left. Nothing to mark.', about: ['ledoux'], effect: { type: 'none' } },
    { id: 'item:salt:lamp-letter', at: 'raskhouse', kind: 'letter', label: 'A letter kept in a drawer', stamp: 'PERSONAL',
      source: 'THE RASK HOUSE · WRITING DESK', title: 'To Tilda, 1941, never sent',
      body: ['“Tilda — if I go in the water it was not the water. Ask Bask. He knows who, and he knows why, and he will not say until it suits him. — Ambrose.”', 'Seven years in a drawer. The paper is soft from being held.'],
      spoken: 'A letter from the widow’s husband, written in 1941 and kept seven years.',
      reading: 'Tilda has known for seven years that Bask knew who drowned her husband. A motive, and a grief. Nothing to mark.', about: ['tilda'], effect: { type: 'none' } },
    { id: 'item:salt:keeper-log', at: 'light', kind: 'note', label: 'Keeper’s log, Grieve Point',
      source: 'GRIEVE POINT LIGHT · LOG', title: 'Night of the 11th',
      body: ['01:30 — dinghy, no light, toward the pier. 02:20 — dinghy returns. Two aboard going, one coming back. The entry is in the keeper’s hand and then crossed out in the keeper’s hand.'],
      spoken: 'The keeper’s log: a dinghy with two aboard going out, and one coming back. Crossed out.',
      reading: 'Background. Garrow saw the boat and then crossed it out. Ask him why. Nothing to mark.', about: ['keeper'], effect: { type: 'none' } },
    { id: 'item:salt:rope-sale', at: 'chandler', kind: 'receipt', label: 'Sales book, forty feet of line',
      source: 'VETCH & SON · SALES', title: 'The 11th, evening',
      fields: [['Item', 'line, quarter-inch, 40 ft'], ['Also', 'sailmaker’s needle, one'], ['Paid', 'double, for quiet'], ['Signed', 'B.O.']],
      body: ['Line and a needle: what you buy to sew a pocket shut. Signed by the chandler himself, in his own book, which is the strange part. Young Vetch watched him do it.'],
      spoken: 'The chandler’s sales book: forty feet of line and a sailmaker’s needle, signed B.O.',
      reading: 'Okafor sold the thread that sewed the pockets. Young Vetch saw who bought it. It tells you something about Okafor. Check his row in the Notebook.', about: ['okafor'], effect: { type: 'suspectTrait', suspectId: 'okafor' } },
    { id: 'item:salt:shipping-wire', at: 'shipping', kind: 'telegram', label: 'Cable, Salvi Shipping',
      source: 'WESTERN UNION · HARBOUR OFFICE', title: 'Cable, to N. Salvi',
      body: ['STRIKE VOTE THURSDAY STOP IF IT PASSES WE ARE FINISHED STOP DO WHAT YOU MUST STOP'],
      spoken: 'A cable to Salvi: if the strike vote passes we are finished. Do what you must.',
      reading: 'Somebody told Salvi to ‘do what he must’. A motive. Nothing to mark.', about: ['salvi'], effect: { type: 'none' } },
    { id: 'item:salt:dues', at: 'bank', kind: 'ledger', label: 'Union account, withdrawals',
      source: 'HARBOUR SAVINGS · LEDGER', title: 'Longshoremen’s Local, account 40',
      body: ['A withdrawal of four hundred dollars on the 10th, on a slip signed by the vice-chair. The teller remembers him signing, and what he did with the pen after.'],
      spoken: 'The union account: four hundred dollars out on the tenth, signed by the vice-chair.',
      reading: 'The teller watched Hollis sign. It tells you something about him. Check his row in the Notebook.', about: ['hollis'], effect: { type: 'suspectTrait', suspectId: 'hollis' } },
    { id: 'item:salt:x-ray', at: 'hospital', kind: 'photo', label: 'Plate, the wound',
      source: 'SEAMEN’S INFIRMARY · RADIOGRAPHY', title: 'Plate 2: left side, the deceased',
      body: ['The blade went in under the ribs and up, toward the heart, from below. You do that from a crouch, or from a boat lower than the pier, or you do it as somebody who knows exactly where to put it.'],
      spoken: 'A radiograph of the wound: under the ribs and upward, from below.',
      reading: 'The knife went upward from below: from a boat, from a crouch, or from somebody who knew exactly where to put it. Nothing to mark.', about: ['fenn'], effect: { type: 'none' } },
    { id: 'item:salt:cot-book', at: 'seamen', kind: 'ledger', label: 'Mission cot book',
      source: 'SEAMEN’S MISSION · COTS', title: 'Night of the 11th',
      body: ['Cot 31: in at ten, out at four, in at five, out at six. No name. Brother Fry has written “wet” in the margin and nothing else.'],
      spoken: 'The mission cot book: somebody in and out all night, and the word “wet” in the margin.',
      reading: 'Background. Somebody went into the water and came here to dry off. Ask Brother Fry. Nothing to mark.', effect: { type: 'none' } },
    { id: 'item:salt:tram-ticket', at: 'tram', kind: 'ticket', label: 'Tram ticket, last car',
      source: 'HARBOUR TRAMWAYS', title: 'Ticket, punched 12:02 AM',
      body: ['Punched at two minutes past midnight on the last car along the quay, and dropped on the step where a person stands who intends to get off before the stop.'],
      spoken: 'A tram ticket punched at two minutes past midnight, dropped on the step.',
      reading: 'Background. The conductor, Tamsin Rook, remembers who stood on the step. Nothing to mark.', effect: { type: 'none' } },
    { id: 'item:salt:drydock-chalk', at: 'drydock', kind: 'note', label: 'Chalk on the hull',
      source: 'NUMBER FOUR DRYDOCK · THE HULL', title: 'Chalked on the plates',
      body: ['BASK KNEW — in letters a foot high, chalked on the hull in the night, and half washed off by the rain. Below it, smaller: SO DO WE.', 'The night man swears it was not there at ten.'],
      spoken: 'Chalk on the drydock hull, a foot high: Bask knew. So do we.',
      reading: 'Background. The harbour is talking to itself. Nothing to mark.', effect: { type: 'none' } },
    { id: 'item:salt:locker', at: 'baths', kind: 'ticket', label: 'Bath locker tag, unclaimed',
      source: 'HARBOUR BATHS · LOCKERS', title: 'Tag no. 17',
      body: ['A coat with something heavy sewn into the lining, left in locker seventeen and not claimed. Nell Harrow cut the lining. What was in it is in your hand: a key, stamped with the name of a store.'],
      spoken: 'A locker tag, an unclaimed coat, and a key sewn into the lining.',
      reading: 'The key opens something in this harbour. A red mark on the map shows where.', effect: { type: 'lead' } },
    { id: 'item:salt:needle', at: 'ropewalk', kind: 'report', label: 'Needle count, the Ropewalk',
      source: 'THE ROPEWALK · STORES', title: 'Sailmaker’s needles, stores check',
      body: ['One needle, size 14, missing from the rack since the 10th. It is the size you would use on a coat, not a sail. The storesman says a man came in for it who did not know what size to ask for and asked for “the big one”.'],
      spoken: 'A needle count at the Ropewalk: one size fourteen missing since the tenth.',
      reading: 'Background. Somebody who doesn’t sew bought a needle. Nothing to mark.', effect: { type: 'none' } },
    { id: 'item:salt:net-tag', at: 'trawler', kind: 'ticket', label: 'Net tag, Marie-Louise',
      source: 'THE TRAWLER BERTHS · NETS', title: 'Tag, net 6, MARIE-LOUISE',
      body: ['A net tag from Ledoux’s boat, found in the water at Pier Nine, two hundred yards from where the Marie-Louise ties up. Nets do not walk. The skipper’s hand is on the tag; the deckhand knows it.'],
      spoken: 'A net tag from the Marie-Louise, found in the water off Pier Nine.',
      reading: 'Iggy Pell has watched Ledoux write those tags for years. It tells you something about Ledoux. Check his row in the Notebook.', about: ['ledoux'], effect: { type: 'suspectTrait', suspectId: 'ledoux' } },
    { id: 'item:salt:cannery-shift', at: 'cannery', kind: 'ledger', label: 'Shift sheet, Narrows Cannery',
      source: 'NARROWS CANNERY · SHIFTS', title: 'Night shift, the 11th',
      body: ['Forty names on the sheet and thirty-eight men on the line, the foreman says. Two clocked in and never came to the floor. Their cards were punched by the same hand.'],
      spoken: 'A shift sheet with two men clocked in who never came to the line.',
      reading: 'Background. Two false alibis were made at the cannery. Nothing to mark.', effect: { type: 'none' } },
    { id: 'item:salt:ice-order', at: 'icehouse', kind: 'receipt', label: 'Ice order, three in the morning',
      source: 'THE ICE HOUSE · ORDERS', title: 'Order, 3:00 AM',
      fields: [['Ice', 'two blocks'], ['For', 'Salvi Shipping'], ['Cart', 'none — carried'], ['Paid', 'cash']],
      body: ['Two blocks of ice at three in the morning for a shipping office that has no fish. The foreman wrote it up and did not ask.'],
      spoken: 'An ice order at three in the morning for a shipping office with no fish.',
      reading: 'Salvi wanted something kept cold. A thought, not a fact. Nothing to mark.', about: ['salvi'], effect: { type: 'none' } },
    { id: 'item:salt:chalk-name', at: 'chapel', kind: 'note', label: 'A name in chalk on the brass',
      source: 'FISHERMEN’S CHAPEL · THE BRASS', title: 'Added this week',
      body: ['AUREL BASK, in chalk, under the names of the drowned, written before the tide gave him up. Whoever wrote it knew he was in the water before anyone else did.'],
      spoken: 'Bask’s name in chalk on the chapel brass, written before the tide gave him up.',
      reading: 'Somebody knew Bask had drowned before he was found. Ask the verger, Aldo Penrose. Nothing to mark.', effect: { type: 'none' } },
    { id: 'item:salt:coastguard-fix', at: 'coastguard', kind: 'report', label: 'Coastguard fix, dinghy',
      source: 'COASTGUARD · WATCH LOG', title: 'Fix, 02:30',
      body: ['Dinghy, no light, bearing from the tower, beached below the old salt stair. The watch took a fix and marked the chart. The mark is a place, and you can walk to it.'],
      spoken: 'A coastguard fix on a dinghy with no light, beached below the old salt stair.',
      reading: 'The chart shows where the boat landed. A red mark on the map shows it.', effect: { type: 'lead' } },
    { id: 'item:salt:ferry-manifest', at: 'slip', kind: 'ticket', label: 'Ferry passenger count',
      source: 'FERRY SLIP · COUNT', title: 'Last crossing, the 11th',
      body: ['Eleven across, ten back. The steward counts heads, not names, and he counted a coat going over that did not come home.'],
      spoken: 'The ferry count: eleven across and ten back.',
      reading: 'One passenger never came back. It was a fisherman asleep in the shed. An hour wasted.', effect: { type: 'time', hours: 1 } },
    { id: 'item:salt:cafe-tab', at: 'excise', kind: 'receipt', label: 'Bask’s tab, the Dockside',
      source: 'DOCKSIDE CAFÉ · TABS', title: 'A. Bask — twenty years',
      body: ['Tea, every morning, a penny. The last line is the 10th. Under it, in Nan’s hand: “Sat with D.H. an hour. Left angry. D.H. stayed.” The cabman outside remembers where D.H. went, and knows a quick way there.'],
      spoken: 'Bask’s café tab: tea every morning for twenty years, and a last line about who he sat with.',
      reading: 'A last argument between Bask and Hollis, and a cab driver who knows the short cuts. Two hours back on the clock.', about: ['hollis'], effect: { type: 'time', hours: -2 } },
  ],

  objects: [
    { id: 'obj:salt:knife', at: 'drydock', name: 'A rigging knife, bone handle', drawing: 'knife',
      desc: 'Found in the drydock. The blade is clean. The handle is not.',
      spoken: 'A rigging knife in the drydock, bone handle, blade wiped clean.',
      unlocks: [
        { person: 'lundy', line: 'This was in your window.', reply: 'It was. Pledged by Okafor in March. Redeemed at midnight by a big man with a scar on the thumb who paid Okafor’s ticket with Okafor’s own money.',
          effect: { type: 'suspectTrait', suspectId: 'okafor' } },
        { person: 'okafor', line: 'Your knife.', reply: 'He looks at it a long time. Mine. I pawned it in March to eat. I did not redeem it. I did not have the money. Somebody paid my ticket, and then somebody used my knife.',
          effect: { type: 'clear', suspectId: 'okafor' } },
      ] },
    { id: 'obj:salt:flask', at: 'brine', name: 'A dented flask, RYE', drawing: 'flask',
      desc: 'Left on the Brine & Bell bar at one. Half full.',
      spoken: 'A dented flask of rye, left on the bar at one.',
      unlocks: [
        { person: 'teague', line: 'Whose flask?', reply: 'Dov Hollis’s. He drinks from it when he thinks I cannot see. He was here till one, not at the Hall till midnight, and he was not drinking to celebrate.',
          effect: { type: 'suspectTrait', suspectId: 'hollis' } },
        { person: 'hollis', line: 'Your flask. On Mags’s bar at one. You said the Hall till midnight, then home.', reply: 'I was at the Brine. I was drinking because I had paid a man four hundred dollars of union money to stand down and he had laughed at me. Mags saw me. Forty men saw me. Ask them.',
          effect: { type: 'clear', suspectId: 'hollis' } },
      ] },
    { id: 'obj:salt:locket', at: 'raskhouse', name: 'A locket with a lock of hair', drawing: 'locket',
      desc: 'On the widow’s writing desk. The hair is grey now. It was not when it was cut.',
      spoken: 'A locket on the widow’s desk, with a lock of hair inside.',
      unlocks: [
        { person: 'tilda', line: 'Ambrose’s?', reply: 'His. Cut the morning he went out. I have had it seven years. I went out last night, Inspector. To the chapel. To write the name of the man who let my husband drown. Somebody told me he was in the water. I wrote it. I did not put him there.',
          effect: { type: 'clear', suspectId: 'tilda' } },
        { person: 'penrose', line: 'Whose hair?', reply: 'Ambrose Rask’s. She showed me once. She came to the chapel at four and chalked Bask’s name and I let her. Whoever told her he was drowned told her before the tide did.',
          effect: { type: 'lead' } },
      ] },
    { id: 'obj:salt:seal', at: 'bondstore', name: 'A customs seal, broken, no. 4471', drawing: 'button',
      desc: 'From bay four. Broken in one twist. Whoever did it had done it before.',
      spoken: 'A customs seal from bay four, broken in one twist.',
      unlocks: [
        { person: 'wren', line: 'Your seal. Your initials. Broken tonight.', reply: 'She sits down. I initial. I do not open. Salvi pays me not to open and I have never spent a dollar of it. I was at the Customs House till eleven. Aldous saw me leave.',
          effect: { type: 'clear', suspectId: 'wren' } },
        { person: 'oyelaran', line: 'Who broke it?', reply: 'Ledoux. On Salvi’s word. One twist. He has done it before, on the Corvina crates, every month for six.',
          effect: { type: 'suspectTrait', suspectId: 'salvi' } },
      ] },
    { id: 'obj:salt:button', at: 'pier9', name: 'A brass button with thread', drawing: 'button',
      desc: 'Under the tape at Pier Nine. Torn off a coat. The thread is sailcloth.',
      spoken: 'A brass button at Pier Nine, torn off with the thread still in it.',
      unlocks: [
        { person: 'vetch', line: 'Whose coat?', reply: 'A skipper’s coat. We sell those buttons. We sold a set to Ledoux in January and he lost one in February. He came back for a match. We did not have one.',
          effect: { type: 'suspectTrait', suspectId: 'ledoux' } },
        { person: 'ledoux', line: 'Yours.', reply: 'Mine. I was at Pier Nine. I brought two men in on the dinghy and I brought one back and I did not ask the one who came back what happened to the other. I was paid not to ask. I am asking now.',
          effect: { type: 'clear', suspectId: 'ledoux' } },
      ] },
    { id: 'obj:salt:watch', at: 'morgue', name: 'Bask’s watch, stopped at 11:40', drawing: 'watch',
      desc: 'From his waistcoat. Salt in the works. It stopped when he went in.',
      spoken: 'Bask’s watch, salt in the works, stopped at twenty to midnight.',
      unlocks: [
        { person: 'kite', line: 'Eleven-forty. Does that fit?', reply: 'It fits. Dr. Fenn wrote drowning at one and the truth at two. In between she went out. She came back with her hands washed. She had been somewhere with salt.',
          effect: { type: 'culpritTrait' } },
        { person: 'fenn', line: 'His watch stopped at eleven-forty.', reply: 'She does not look at it. He came to me at ten. He said somebody wanted to meet at the pier. He asked me how a man is killed with a knife under the ribs. I told him. I thought he was asking so he could avoid it.',
          effect: { type: 'suspectTrait', suspectId: 'fenn' } },
      ] },
  ],
  story: {
    backstory: [
      'Aurel Bask ran the longshoremen for twenty years. He was not liked. He was obeyed. He kept the harbour working and the union’s money where the union could see it.',
      'Six weeks ago the Corvina came in with forty crates and a manifest nobody read. Bask started counting boats. He counted the Marie-Louise going out empty and coming back heavy. He counted the crates in the bond store. He wrote it down.',
      'Thursday there is a vote. Bask was going to speak about the berths. Everyone with money in the berths knew it. On the 11th, at ten at night, he told his doctor somebody wanted to meet him at Pier Nine.',
      'They found him at low tide with his pockets sewn shut and full of rock salt. That is a message. The harbour read it. Then it stopped talking.',
    ],
    timeline: [
      { time: '8:00 PM', text: 'Okafor closes the chandlery. Forty feet of line and a needle are sold, and signed for in his book.' },
      { time: '10:00 PM', text: 'Bask visits Dr. Fenn at the Infirmary. He tells her about a meeting at the pier.' },
      { time: '11:10 PM', text: 'The Marie-Louise clears out. No cargo declared.' },
      { time: '11:40 PM', text: 'Bask’s watch stops. He is in the water.' },
      { time: '12:00 AM', text: 'A pawn ticket for a rigging knife is redeemed at Lundy’s by a hand that did not pledge it.' },
      { time: '1:04 AM', text: 'Wireless: STOP AT THE USUAL. Reply: UNDERSTOOD.' },
      { time: '1:30 AM', text: 'The keeper logs a dinghy. Two aboard going out. He crosses it out.' },
      { time: '3:05 AM', text: 'The Marie-Louise ties up, riding low. Two blocks of ice are ordered for Salvi Shipping.' },
      { time: '4:00 AM', text: 'Bask’s name is chalked on the chapel brass, under the drowned. The tide has not given him up yet.' },
    ],
    truth: [
      'Bask went to Pier Nine because Marcel Ledoux told him a friend wanted to talk about the berths before the vote. Ledoux rowed in alone from the Marie-Louise. There was never a second man in the dinghy.',
      'He killed Bask the way Dr. Fenn had once described over a dinner Bask had invited him to: under the ribs, from below, upward. Then he sewed the pockets shut with Okafor’s needle and filled them with the salt Orme was one bag short of.',
      'The salt was for the three thousand men who would hear about it by morning. It worked. Salvi paid for all of it and never held the needle. Garrow saw the dinghy and crossed it out for fifty dollars he has not touched.',
      'Ambrose Rask went into the bay in ’41 for the same reason, off the same boat, and Ledoux was the boy being sick in the bilge. Bask knew. He never said. That is the only thing about Aurel Bask nobody in this harbour has forgiven.',
    ],
  },

  epilogue: {
    win: `You make the arrest at the Hall an hour before the vote, in front of three hundred
      longshoremen who go quiet all at once. Somebody at the back starts clapping and thinks
      better of it. The tide comes in. It always does.`,
    loss: `Thursday comes. They elect a new boss. The new boss says all the right things about
      Aurel Bask. The salt goes in an evidence locker. The file goes in a drawer. The harbour
      goes back to being a place where nobody saw anything.`,
  },
};

export default def;
